### ISSUE TITLE
Programmatically create tables and insert to them

### ISSUE THREAD

**Issue by mewwts** [go-pg/pg#1004]
Hi there,

Thanks for making this lib. I'm in a situation where I want to use this library in a more dynamic way than what the docs focus on.

Assuming I have something like:

```golang
type ColumnDef struct {
    Name string
    Type reflect.Type
}

type ColumnVal struct {
    *ColumnDef
    Value interface{}
}
```

Specifically I have two things I'm struggling to do:
1. Create tables from a `[]ColumnDef` 
2. Insert into above table from a `[]ColumnVal`

If you have any pointers on how to use the library without having a static struct as the base for a model,  I'd be very grateful - thanks!

**Comment by vmihailenco** [comment]
Query to create table is generated [here](https://github.com/go-pg/pg/blob/master/orm/table_create.go#L36-L97). It is private and does not accept `*Table` so it is not usable as is. But theoretically you could manually create `orm.Table` with some `orm.Field`s in it and pass to that function. But honestly I think you will have better experience writing something similar for your use case.

**Comment by mewwts** [comment]
Thanks for the response @vmihailenco.
