### ISSUE TITLE
Full support of context 

### ISSUE THREAD

**Issue by huttarichard** [go-pg/pg#1005]
Library right now takes context which is part of `*pg.Tx` and `*pg.DB` and it is passed to `orm.DB` but none of those really takes advantage of context itself.

Example:
```go
ctx, cancel := context.WithCancel(context.Background())
go cancel()
c := db.WithContext(ctx)
_, err := c.Exec("SELECT pg_sleep(5);")
// will still need 5 secs and will not end with err
```

In library there is already support for timeout, but context solve this much better way + you always have option to cancel query when needed.

**Comment by vmihailenco** [comment]
Closed by https://github.com/go-pg/pg/commit/ad684b96035f6cff866ee7da13aedebf3d8f2b07

Following should work:

```
ctx, cancel := context.WithCancel(context.Background())
go cancel()
_, err := db.ExecContext(c, "SELECT pg_sleep(5);")
// will still need 5 secs and will not end with err
```

ORM users:

```
db.Model(....).Context(c).Select()
```

**Comment by huttarichard** [comment]
@vmihailenco great job! thanks
