### ISSUE TITLE
Encoding inconsistency when inserting [][]byte

### ISSUE THREAD

**Issue by mewwts** [go-pg/pg#1008]
Hi,

Using go-pg 6.15.0 and postgres 9.6

When inserting a `[]byte` into a column with the postgres `bytea` type, the values end up hex encoded in postgres.
However, when inserting a `[][]byte` into a column with the postgres `bytea[]` type, the values end up ESCAPE-encoded.

In order to have the values in the `bytea[]` type hex-encoded, you would need to add an additional backslash to the insert query.

Here's an example (what go-pg does today):
```
=> select '{\xdeadbeef}'::bytea[];
           bytea           
---------------------------
 {"\\x786465616462656566"}
(1 row)
```
And what I'd like it to look like
```
=> select '{\\xdeadbeef}'::bytea[];
      bytea      
-----------------
 {"\\xdeadbeef"}
(1 row)
```

The [documentation](https://www.postgresql.org/docs/9.6/static/datatype-binary.html) only states that it's needed "sometimes", but I guess this is one of those times?

If this is an easy fix I'd love to help if you point me in the right direction!

**Comment by vmihailenco** [comment]
Please try master branch.

**Comment by mewwts** [comment]
Works like a charm. Thanks!
