### ISSUE TITLE
How should I create table with pk without sequence

### ISSUE THREAD

**Issue by qianfangyuan** [go-pg/pg#1009]
type Test struct{
ID  int64`sql:"pk"`
Name string
}

table will create like this:
column id will create as primary with sequence
but some time need a primary key without sequence，how should do？

**Comment by vmihailenco** [comment]
You can manually specify type `sql:"type:bigint"`. See https://github.com/go-pg/pg/wiki/Model-Definition

**Comment by qianfangyuan** [comment]
thanks
