### ISSUE TITLE
update and returning muti rows 

### ISSUE THREAD

**Issue by qianfangyuan** [go-pg/pg#1016]
how can update and returning muti rows ?

type Test struct{
ID int
Name string
}
var test Test
test.ID=1
test.Name="aaaa"
db.Model(Test).Set("name=?name").Where("id=?id").Returning("*").Update()

Is there some way to get multi rows from returning ?

**Comment by vmihailenco** [comment]
Use `var tests []Test`

**Comment by qianfangyuan** [comment]
thanks
