### ISSUE TITLE
Many to Many query

### ISSUE THREAD

**Issue by tschellenbach** [go-pg/pg#1018]
My first day with this library, so far it's been pretty amazing. Really nice project.

I was wondering, is there a way to do a many to many select in 1 query instead of 2?

- https://godoc.org/github.com/go-pg/pg#example-DB-Model-ManyToMany
- err := db.Model(order).Relation("Items").Select() generates 2 queries

**Comment by tschellenbach** [comment]
Current behaviour

```
   // SELECT "order"."id" FROM "orders" AS "order" ORDER BY "order"."id" LIMIT 1
    //
    // SELECT order_to_items.*, "item"."id" FROM "items" AS "item"
    // JOIN order_to_items AS order_to_items ON (order_to_items."order_id") IN (1)
    // WHERE ("item"."id" = order_to_items."item_id")
```

Optimal query (simplified for readability)

```
SELECT * FROM "order" JOIN order_to_items ON (order_to_items.order_id = order.id)
```

This will allow you to read both the order and the order_to_items table in 1 query. It does get a little complex in certain cases like if you want to have a limit and offset.

Is there a way to perform raw query for this and load them into the corresponding models?

**Comment by vmihailenco** [comment]
AFAIK that query returns a duplicate if there are many rows in joined table. go-pg would need to filter out duplicates which is not easy and can be slower than issuing 2 queries.
