### ISSUE TITLE
Escaping query strings

### ISSUE THREAD

**Issue by rbatukaev** [go-pg/pg#102]
Are query strings safe or I have to escape them myself (or use prepared statements)?

```
db.QueryOne(tag, `INSERT INTo tags (name) VALUES (?name) RETURNING id, name`, tag)
```

**Comment by vmihailenco** [comment]
Your example is safe. Generally query params have 3 "modes":
- "string" - string is escaped as value, e.g. `'string'`
- pg.F("string") - string is escaped as SQL identifier (field), e.g. `"string"`
- pg.Q("string") - string is not escaped, e.g. `string`

So by default all passed params are escaped and query should be safe.

**Comment by rbatukaev** [comment]
Thanks a lot!
