### ISSUE TITLE
Compare time.Time size

### ISSUE THREAD

**Issue by iyongfei** [go-pg/pg#1027]
A field in database is time.Time. How do I query data in a certain time period? I took advantage of it

#code under
Timer:=Str2TimeTemp ("2018-11-06 16:29:04")

Order:=new (Order)

Err:=db.Model (order).Where ("time_start>?", timer).Select ()

//err:=db.Model (order).Where ("time_start>?", "2018-11-06 16:29:04").Select ()

It's all wrong.

**Comment by vmihailenco** [comment]
The code looks correct. Overall this is not a go-pg problem - you just need to construct correct SQL.
