### ISSUE TITLE
Move ErrNoRows and ErrMultiRows outside internal/errors

### ISSUE THREAD

**Issue by tbarbugli** [go-pg/pg#1029]
I want to know if the err returned by First() is of ErrMultiRows type but unfortunately this is not possible because the error is not exported.

```go
err := q.First()

if _, ok: err.(ErrNoRows); ok {
    // handle row is missing
} else {
  // handle anything else (eg. PG is dead, SQL query is not valid, ...)
}
```

**Comment by vmihailenco** [comment]
There are pg.ErrNoRows and pg.ErrMultiRows.
