### ISSUE TITLE
How can one cleanly check whether a query has no results?

### ISSUE THREAD

**Issue by tritonresearch** [go-pg/pg#103]
When a SELECT query has 0 rows, an error is returned: `pg: no rows in result set`. However, is there a clean way to separate cases of 0 results vs. errors that involve connectivity issues, etc.?

Thanks!

**Comment by vmihailenco** [comment]
`pg.ErrNoRows` is returned specifically when PostgreSQL said that query affected 0 rows. go-pg never returns `pg.ErrNoRows` on connectivity errors.

Code if you are interested:
- parsing number of affected rows https://github.com/go-pg/pg/blob/master/result.go#L19-L39
- checking number of affected rows https://github.com/go-pg/pg/blob/master/db.go#L410-L431
