### ISSUE TITLE
Array_agg and array_to_json

### ISSUE THREAD

**Issue by rbatukaev** [go-pg/pg#104]
Consider the following structs
```
type ItemWithTags struct { 
    *Item
    Tags  []Tag
}
type Tag struct {
    Id int
    Name string
}
```

Is there a way to bind the following result to ItemWithTags?:
```
SELECT i.*, array_to_json(array_remove(array_agg(t),NULL)) AS tags
FROM items i
LEFT OUTER JOIN tags t ON t.item_id=i.id
GROUP BY i.id
```

The example output from this query contains regular column values from `Items` table and the following `tags` array:

```
"tags": [
        {
            "tag_id": 304,
            "name": "Football",
        },
        {
            "tag_id": 311,
            "name": "Eurosport",
        }
    ]
```

**Comment by vmihailenco** [comment]
Did you already find a workaround?

**Comment by rbatukaev** [comment]
Yes, I found the solution in json example: ) I used a custom slice of jsonString type with Scan method on it. Thanks a lot.
