### ISSUE TITLE
Create table named user with pluralization disabled

### ISSUE THREAD

**Issue by julienkosinski** [go-pg/pg#1041]
I disabled pluralization with:
```
func init() {
	orm.SetTableNameInflector(func(s string) string {
		return s
	})
}
```

I want to create the table named `user`. I am using `pg.DB.CreateTable()`. The table created is `"user"`. It's working as expected without quotes for any other table name.

As a workaround, I can make it work without double quotes with 
```
tableName struct{} `sql:"user"`
```
as a field in User struct.

I suppose there is a problem in the process of creating the request because `user` is a reserved keyword in postgreSQL.

Thing strange here is I have done this in the past without problem, I don't know what have changed.

Thanks! :)

**Comment by vmihailenco** [comment]
I think I've fixed this in master branch - please try.

**Comment by julienkosinski** [comment]
@vmihailenco Unfortunately I can reproduce this with master.  Also, when I use the trick `tableName struct{} sql:"user"` to create the table user and then make a query with `orm.DB.QueryOne(user, sql, id)`, I get a `ERROR #42P01 relation "user" does not exist` on working query.

Do you need more code to reproduce this?

**Comment by julienkosinski** [comment]
@vmihailenco Works great! Thank you very much! :)
