### ISSUE TITLE
AddModel error does not abort transaction

### ISSUE THREAD

**Issue by betrok** [go-pg/pg#1042]
It seems that the errors returned by this method do not invalidate transactions.
```
	tx, _ := db.Begin()
	err := tx.Model().ColumnExpr(`1 AS data`).ForEach(func(struct {Data int}) error {
		return fmt.Errorf("some error")
	})
	fmt.Printf("ForEarch error: %v\n", err)
	_, err = tx.Exec("SELECT 1")
	fmt.Printf("next error: %v\n", err)
```
outputs
```
ForEarch error: some error
next error: <nil>
```

**Comment by betrok** [comment]
Well, makes sense.
But it is not obvious, mentions in the docs will be helpful.

**Comment by vmihailenco** [comment]
`ForEach` does not know anything about the transaction so it can't abort it. `ForEach` could be changed to stop iteration on first error, but still that would not close a transaction.

**Comment by betrok** [comment]
Still there should be a way to abort query/transaction from within AddModel.

Imagine a situation where you have a very slow query, the results of which are streamed to the client.
If client disconnects in halfway, there is no reason to continue fetching data.

**Comment by vmihailenco** [comment]
>If client disconnects in halfway, there is no reason to continue fetching data.

How this is related to transactions?

**Comment by betrok** [comment]
Well, it is not directly related to transactions. But will not the canceled query invalidate whole transaction?
