### ISSUE TITLE
OpenCensus support

### ISSUE THREAD

**Issue by edevil** [go-pg/pg#1043]
I'm a go-pg and OpenCensus user, and am looking for the best way to introduce tracing in go-pg queries. AFAIK, the database/sql support cannot be used with go-pg since it does not export that interface. I was looking at the hooks available, but I could only find per-model hooks.

Are there some global hooks that I can use for every query, in which I would be able to access a supplied context?

**Comment by edevil** [comment]
@vmihailenco Would you be willing to consider a `OnQueryStart` hook, dual to `OnQueryProcessed`, so that we could start the tracing span there, store it in the context, and then retrieve the span from the context and End() it at OnQueryProcessed?

**Comment by edevil** [comment]
It’s done.

**Comment by vmihailenco** [comment]
:rocket:

**Comment by giautm** [comment]
Hi, I want to intergate Opencensus with go-pg. But dont know how to deliver, can you provide an example?

**Comment by edevil** [comment]
@giautm You need to add a query hook that uses `trace.StartSpan()` in `BeforeQuery()` and then closes the span on `AfterQuery()`.

**Comment by giautm** [comment]
@edevil I don’t know how to get query (main table, fields, params) from the hook. It’s just a formatted string.

**Comment by edevil** [comment]
@giautm Yes, I think you would need to parse the query in order to separate those attributes besides the params.
