### ISSUE TITLE
how to prevent index from being created for ID field

### ISSUE THREAD

**Issue by steebchen** [go-pg/pg#1046]
I have a field `Id` in my struct, but I do not want to have a unique index on this field. How can I disable it?

I simply tagged it as `sql:"_id,notnull"` as a workaround for now.

**Comment by vmihailenco** [comment]
Why do you want to do it?

**Comment by steebchen** [comment]
I basically do not want to create an index because I except a lot of logs in there. Plus, in https://www.timescale.com/ you can't use a unique index (or rather you have to configure extra stuff).

**Comment by vmihailenco** [comment]
In master branch you should be able to use `sql:",nopk,notnull"` to make field as not a pk.
