### ISSUE TITLE
UUID issue

### ISSUE THREAD

**Issue by L11R** [go-pg/pg#1048]
Yeah, I checked all previous UUID related issues, but I didn't find similliar. So I am getting this error: `Scan: invalid UUID length: 74`. It emitted by this library: https://github.com/google/uuid
It supports scanner, `Scan()`:
https://github.com/google/uuid/blob/dec09d789f3dba190787f8b4454c7d3c936fed9e/sql.go#L15-L52

I try to debug it, but seems like `pg` is sending `src` byte array with size that equal 74, not 16.

**Comment by L11R** [comment]
I tried another package, which is considering satori/go.uuid successor: https://github.com/gofrs/uuid
Also getting error: `uuid: incorrect UUID length: \\x62366563313937632d626530312d343066362d613763302d303864633630623064386565`

My model:
```golang
type Test struct {
  UUID    uuid.UUID `sql:",pk"`
}
```
Part of code where an error is occuring:
```golang
test := &models.Test{UUID: id}
if err := h.DB.Select(test); err != nil {
  // error handler
}
```

**Comment by vmihailenco** [comment]
Looks like you are not using PostgreSQL uuid type and instead use bytea. Anyway you have to provide a reproduces if you expect help.

**Comment by L11R** [comment]
@vmihailenco lol, I didn't know, that PostgreSQL has dedicated type, thanks a lot, now all works as should. But I guess would be nice to leave mention somewhere in wiki about it.

**Comment by j796160836** [comment]
I found the answer.

Change your model into:

```
type Test struct {
  UUID    uuid.UUID `pg:"type:uuid"`
}
```
Will solve the problem.

Reference:
https://pg.uptrace.dev/uuid/
