### ISSUE TITLE
how can log query time ?

### ISSUE THREAD

**Issue by qianfangyuan** [go-pg/pg#1050]
how can log query time ?
pg.QueryEvent does not have StartTime, if have a way to log query time ?

**Comment by vmihailenco** [comment]
You are supposed to save start time in `QueryEvent.Data` map in BeforeQuery hook.

**Comment by qianfangyuan** [comment]
thanks

**Comment by qianfangyuan** [comment]
It's my falt,pool size Is too big and timeout is so little，when set pool size 10,no-concurrency is about less than 5ms,maybe first connect to pg spend more than 10ms;
