### ISSUE TITLE
Bulk UPDATE fails for jsonb fields, go-pg is trying to insert text

### ISSUE THREAD

**Issue by ernsheong** [go-pg/pg#1055]
Version: 6.15.1

This fails:
```go
db.Model(&cards).Update()
```

My card model:

```go
type Card struct {
	ID        int            `json:"id"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
        ...
	Fields    []*model.Field `json:"fields"`
}
```

model.Field:

```go
type Field struct {
	ID    string      `json:"id"`
	Value interface{} `json:"value"`
}
```

However, when doing the BULK update it appears that go-pg is trying to insert as TEXT:
`ERROR #42804 column "fields" is of type jsonb but expression is of type text`

Perhaps we need the `::jsonb` operator?

**Comment by vmihailenco** [comment]
Yes, you need to add `sql:"type:jsonb"` on the field.

**Comment by ernsheong** [comment]
Hmm, should `go-pg` automatically infer from the database? I suppose that would be inefficient. I see, thanks
