### ISSUE TITLE
JSONB Array is not working for slice type

### ISSUE THREAD

**Issue by johnwiichang** [go-pg/pg#1064]
I found there is an issue when you try to insert a value that uses a JSONB array.
The structure is defined like:

```
type A struct {
	Field []map[string]interface{} `sql:",array"`
}
```

and if I try to execute

```
a := A {
	Field: []map[string]interface{}{
		map[string]interface{}{},
	},
}
db.Insert(&a)
```

it will report an error like: `ERROR #22P02 malformed array literal: "{{}}"`

It can be solved by overriding the MarshalJSON function (two marshalling), but it can cause a lot of confusion.

I am trying to solve this problem, but because there are too many things at the moment, if I try to solve it, it may be slower than expected.

I have just checked the ORM code, it seems that tModel just transform the structure form Model without any detection that whether it might be a jsonb array or not.

Also, there is no code for jsonb array support in the db.Query implementation. To solve it temporarily, we can use reflection to detect data type and make an extra serialisation when detector says yes.

_My English is not very well, if any description is not clear, reply me without any doubt._

**Comment by vmihailenco** [comment]
`sql:",array"` says that this is a PostgresSQL array, not JSON array. Remove that tag and all should work as expected.

**Comment by johnwiichang** [comment]
> `sql:",array"` says that this is a PostgresSQL array, not JSON array. Remove that tag and all should work as expected.

Actually, the field in pq db is jsonb[], PostgreSQL JSONB array indeed.
If I remove this tag, the sql might be:
```
[{}]
```
and we will get `ERROR #22P02 malformed array literal: "[{}]"` error, and I cannot select data via db.Model(&a).Select(), program will tell me:
```
invalid character '}' after object key
```

**Comment by vmihailenco** [comment]
Okay, sounds clearer now. Please add a program that reproduces the problem - it will significantly speedup the resolution.

**Comment by johnwiichang** [comment]
```
package main

import (
	"os"

	"github.com/go-pg/pg"
)

type (
	Test struct {
		tableName struct{} `sql:"test"`
		Entities  []Entity `sql:", array"`
	}

	Entity struct {
		Key string      `json:"key"`
		Val interface{} `json:"val"`
	}
)

func main() {
	var db = pg.Connect(&pg.Options{User: "usr", Password: "psw", Addr: "localhost:5432", Database: "default"})
	db.DropTable(&Test{}, nil) //ignore error
	if err := db.CreateTable(&Test{}, nil); err != nil {
		panic("postgresql reported an error: " + err.Error() + "\r\n")
	}
	os.Stdout.WriteString("✓ table 'test' has been created.\r\n")
	t := Test{Entities: []Entity{{"Hello", "World"}, {"你好", 1}, {"こんにちは", true}}}
	if err := db.Insert(&t); err != nil {
		panic("✘ database reported an error: " + err.Error() + "\r\n")
	}
	os.Stdout.WriteString("✓ value has been inserted.\r\n")
}

/*
If you cancel the comment below, you will find that no errors will occur.
*/
// func (e Entity) MarshalJSON() (data []byte, err error) {
// 	data, err = json.Marshal(map[string]interface{}{
// 		e.Key: e.Val,
// 	})
// 	if err != nil {
// 		return
// 	}
// 	return json.Marshal(string(data))
// }
```

this is a minimal demo you can run it and reproduce the problem.
Run it directly, you will see:
```
✘ database reported an error: ERROR #22P02 malformed array literal: "{{"Name":"Hello","Value":"World"},{"Name":"你好","Value":1},{"Name":"こんにちは","Value":true}}"
```
If you cancel the comment code, you will find that no errors will occur:
```
✓ value has been inserted.
```

> ⚠️ Caution! Please notice that it will run table drop on the database which you assigned.

**Comment by vmihailenco** [comment]
Thanks for the reproduces - I think I fixed your example in the master branch. I hope to make a release by the end of the year, but don't have a date yet.
