### ISSUE TITLE
Random code

### ISSUE THREAD

**Issue by sp121933039** [go-pg/pg#1067]
Chinese garbled
![image](https://user-images.githubusercontent.com/13689466/50372569-adb15e00-060b-11e9-8ef9-dd3afba37045.png)

**Comment by vmihailenco** [comment]
Please create a reproducer.

**Comment by sp121933039** [comment]
what‘s  create a reproducer

**Comment by vmihailenco** [comment]
You need to create a small program that reproduces the problem and post it here.

**Comment by sp121933039** [comment]
The same is true of the small programs I created locally.

Is it my Windows environment?

**Comment by vmihailenco** [comment]
It definitely looks like a broken encoding somewhere:
- Shell
- Windows
- Postgres
- go-pg
- your program

**Comment by sp121933039** [comment]
Okay, confirm it.
