### ISSUE TITLE
Slice works but array of fixed length doesn't

### ISSUE THREAD

**Issue by turbobuilt** [go-pg/pg#1079]
Hello, and thanks for all the hard work!

A slight problem. I can workaround with slices.  But this code with an array of fixed length
```
type MyType struct {
	MyInfo [3]bool `sql:",array"`
}
```
complains:
2019/01/02 21:13:50 http: panic serving [::1]:64436: runtime error: invalid memory address or nil pointer dereference

net/http.(*conn).serve.func1(0xc0001523c0)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1746 +0xd0
panic(0x1495f60, 0x18e0b70)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/go-pg/pg/orm.(*Field).AppendValue(0xc0007af290, 0xc0006f9000, 0x4dd, 0x1000, 0x1514d40, 0xc000114420, 0x199, 0x1, 0xc0006f9000, 0x4db, ...)
        /Users/me/go/src/github.com/go-pg/pg/orm/field.go:82 +0x16f

Works just fine with slices.

**Comment by elliotcourant** [comment]
Would you be able to provide a code example that someone could simply run to reproduce this issue? Are you inserting, updating, selecting? Creating a table?

**Comment by turbobuilt** [comment]
```go
package main

import (
	"github.com/go-pg/pg"
	"encoding/xml"
	"github.com/go-pg/pg/orm"
)

type MyType struct {
	MyInfo [3]bool `sql:",array"`
}


func createSchema(db *pg.DB) error {
    for _, model := range []interface{}{(*MyType)(nil)} {
        err := db.CreateTable(model, &orm.CreateTableOptions{
            Temp: true,
        })
        if err != nil {
            return err
        }
    }
    return nil
}

func main() {
    db := pg.Connect(&pg.Options{
        User: "postgres",
    })
    defer db.Close()

    err := createSchema(db)
    if err != nil {
        panic(err)
    }

    thing := &MyType{
		MyInfo: [3]bool{true,true,true},
	}
    err = db.Insert(thing)
    if err != nil {
        panic(err)
    }
}
```

**Comment by vmihailenco** [comment]
Thanks for the reproducer. I think this should be fixed in master, but the code is not particularly well-tested.
