### ISSUE TITLE
Recreating tables on reconnect

### ISSUE THREAD

**Issue by tangtony** [go-pg/pg#1080]
Hi

Prior to v7, I have been using the `onConnect` function to create my tables. This ensured that even on reconnect, if the database was reset, the tables would be recreated. 

In v7 it seems that the behaviour of `onConnect` has changed and is now called before the database is connected which means I cannot create my tables in there anymore. 

I can't seem to figure out another way to do this in v7. Is there a recommended approach to create tables upon connection? 

Thanks

**Comment by vmihailenco** [comment]
AFAIK it should work the same. Please add the program the reproduces the problem.

**Comment by tangtony** [comment]
Here is a minimal example that reproduces the issue:
```go
package main

import (
	"log"

	"github.com/go-pg/pg"
	"github.com/go-pg/pg/orm"
)

type Apple struct {
	Color string
	Size  int
}

func main() {
	db := pg.Connect(&pg.Options{
		Addr:     "localhost:5432",
		User:     "postgres",
		OnConnect: onConnect,	
	})
	defer db.Close()

	if _, err := db.Exec("SELECT 1"); err != nil {
		log.Fatalf("could not connect to PostgreSQL: %s\n", err)
	}
	log.Println("connected to PostgreSQL")
}

func onConnect(conn *pg.Conn) (err error) {
	if err = conn.CreateTable((*Apple)(nil), &orm.CreateTableOptions{
		IfNotExists: true,
	}); err != nil {
		log.Println(err)
	}
	return
}
```

Without the `onConnect` function, the program connects to the database as expected.
With the `onConnect` function specified, the program never gets to `connected to PostgreSQL`. Instead you'll get the following errors:
```
2019/01/04 12:04:10 FATAL #53300 sorry, too many clients already
2019/01/04 12:04:10 FATAL #53300 sorry, too many clients already
2019/01/04 12:04:10 FATAL #53300 sorry, too many clients already
2019/01/04 12:04:10 could not connect to PostgreSQL: FATAL #53300 sorry, too many clients already
exit status 1
```
