### ISSUE TITLE
panic: invalid URL escape "%" -- Url filter

### ISSUE THREAD

**Issue by llakes** [go-pg/pg#1082]
Hello I just wanted to share this issue with you. I have worked around it, but I feel uncomfortable with my approach.

I tried making a url query with  **subject__ieq=%Lorem%** and I get the error in the title after url.ParseQuery. 
`	urlFilter, err := url.ParseQuery(`subject__ieq=%Lorem%`)
	panicIf(err) // I get panic: invalid URL escape "%Lo" here
`
After searching the internet I found out that ParseQuery does not expect to see "%" in the url value. I added the "%", because go-pg does not add it for __ieq. 

In other to work around this, I manually added "%" for every url model that has a suffix with "__ieq", and go-pg acts properly by querying "subject ILIKE %Lorem%".

Is my approach right?

**Comment by vmihailenco** [comment]
What are the alternatives? go-pg could add `%` automatically, but some people want `ILIKE %Lorem` and others `ILIKE Lorem%`. Not to say it would be backwards incompatible in an unpredictable way.

**Comment by llakes** [comment]
Okay.
