### ISSUE TITLE
WIKI needs update?

### ISSUE THREAD

**Issue by mdere-unbound** [go-pg/pg#1095]
So to view your queries realtime, we previously run this

```
db.OnQueryProcessed(func(event *pg.QueryProcessedEvent) {
	query, err := event.FormattedQuery()
	if err != nil {
		panic(err)
	}

	log.Printf("%s %s", time.Since(event.StartTime), query)
})
```

but I believe this is deprecated? What does it need to be now?

**Comment by vmihailenco** [comment]
See 2nd example in https://github.com/go-pg/pg/wiki/FAQ#how-can-i-viewlog-queries-this-library-generates

**Comment by mdere-unbound** [comment]
Thank you!
