### ISSUE TITLE
Recent changes breakes `bytea`

### ISSUE THREAD

**Issue by mewwts** [go-pg/pg#1098]
go-pg is trying to write the following `bytea` column which postgres refuses to accept:
```
pg: can't parse bytea: \"\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000\\\\001\"
```

Has anything change in how you do byte arrays?

**Comment by vmihailenco** [comment]
Please include a program that reproduces the problem.

**Comment by mewwts** [comment]
Sorry, I could not reproduce - but downgrading to v7.0.0 fixed it for me :thinking:
