### ISSUE TITLE
Has one relation does not returns related struct

### ISSUE THREAD

**Issue by falahati1987** [go-pg/pg#1101]
Hello,

I have two **structs** : 
```
type Adventures struct {
	Id          int64
	Name        string `sql:",notnull"`
	FlowsId     int64 `sql:",pk"`
	Flows       *Flows
}
type Flows struct {
       Id int64
       Name string `sql:"notnull"`
}
```
I expect when I **select**  a row from ```Adventures``` table, it'd return the corresponding object from ```Flows``` . But I always get ```nil```
To be more specific, I **select** the adventures table as below:
```
var adventures []model.Adventures
pgdb.Model(&adventures).Select()
```
Would you please help how can I get not ```nil``` object when I **select** a row from ```Adventures```?

**Comment by ribice** [comment]
https://github.com/go-pg/pg/wiki/Writing-Queries#has-one

var adventures []model.Adventures
db.Model(&adventures).Column("adventure.*", "Flows").Select()

**Comment by falahati1987** [comment]
@ribice , thank you.
