### ISSUE TITLE
Iterating through rows

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1102]
Is there a way to iterate through query results (not ORM)?

I'm migrating an app from Gorm to go-pg.

It iterates through rows like:

```
rows, err := db.Table("Select ...").Rows()

for rows.Next() {
do stuff here
}
```

I noticed that there is `forEach` but it is only for ORM?

**Comment by ericzhour** [comment]
I encountered the same problem, anyone can help reply this question?

**Comment by sunsiansong** [comment]
@ribice if you mean iterate rows of some query, i do it like this:
```go
func (r repo) iterateRow(f func(*User) error) error {
	const limit = 25

	cursorID := -1

	for {
		var list []User
		r.db.Model(&list).
			Where("id > ?", cursorID).
			Order("id asc").
			Limit(limit).
			Select()
		size := len(list)
		if size > 0 {
			for i := 0; i < size; i++ {
				cursorID = list[i].ID
				err := f(&list[i])
				if err != nil {
					return err
				}
			}
		}
		if size < limit {
			break
		}
	}
	return nil
}
```

**Comment by vmihailenco** [comment]
Without using ORM

```
var users []*User
_, err := db.Query(&uses, "SELECT * FROM users LIMIT 1000")
if err != nil {
    panic(err)
}

for _, u := range users {
    ...
}
```

**Comment by ribice** [comment]
It doesn't actually solve the problem.

When using rows.Next, you don't have to unmarshal into single struct and the result is not loaded into memory immediately. You could fill data into multiple structs and use it separated.

**Comment by betrok** [comment]
You can create custom model. See `orm/model_func.go` for reference.

**Comment by sgon00** [comment]
I am having the same problem. This is the issue https://github.com/go-pg/pg/issues/1412 I just filed. Do anyone have any ideas how to handle it? This should be a very common case and show in the wiki doc.
