### ISSUE TITLE
Fetching slice in a query

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1103]
Given the following structs:

```go
type User struct{
ID int
Name string
TimeEntries []TimeEntry
}

type TimeEntry struct{
Start time.Time
End time.Time
Type string
}
```

This is similar to HasMany relation, but I need to write a query to get data (no ORM). What do I set alias/column names in order to fetch time entries as well?

**Comment by Ryex** [comment]
I think this might be relevant to you
https://stackoverflow.com/questions/41054507/postgresql-array-of-elements-that-each-are-a-foreign-key
