### ISSUE TITLE
Connection string

### ISSUE THREAD

**Issue by HazCod** [go-pg/pg#1115]
Hi,

At the moment I am using GORM, but I'm having issues with how easily they fire multiple queries for associations.
I'd like to switch go-pg, but since I code on AppEngine Standard using Cloud SQL Proxy, I'm currently using a connection string using 'cloudsqlproxy' driver.
This allows me to connect to Cloud SQL without hassle and without specifying any host/region/project details.

Is this possible in go-pg?

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/wiki/FAQ#how-to-connect-to-google-cloud-sql-using-proxy
