### ISSUE TITLE
How to change timestamp value into null?

### ISSUE THREAD

**Issue by rogierlommers** [go-pg/pg#1116]
Given this model:
```
type Video struct {
	EAN             string    `sql:"ean,pk"`
	URLs            string    `sql:"urls"`
	LockedBy        string    `sql:"locked_by"`
	LockedTimestamp time.Time `sql:"locked_timestamp"`
	Done            bool      `sql:"done"`
}
```

I want to do the following update:
```
	v := Video{
		EAN:             ean,
		LockedBy:        "",
		LockedTimestamp: nil,
		Done:            true,
	}

	return db.Update(&v)
```

But then I get this error: `store/postgres.go:91:3: cannot use nil as type time.Time in field value`. This is not strange, but I'm now trying to figure out how to clear the timestamp field in the database. Any help is appreciated!

**Comment by vmihailenco** [comment]
Use [pg.NullTime](https://github.com/go-pg/pg/blob/master/types/null_time.go#L14) or write something similar yourself.
