### ISSUE TITLE
Prepare error message is not detailed enough

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#1125]
```go
tx, err := global.DB.Begin()
if err != nil {
	return err
}
defer fuc(){
	tx.Rollback()
}

stmt, err := tx.Prepare("INSERT INTO table_name (id, field_name) VALUES ($1, $2)")
if err != nil {
	log.Println(err.Error())
	return
}
```

My code has an error and the message is `pg: database is closed`，but this message can't let me check for errors.
I remember that the previous version is not like this. Is this a problem with the new version?

**Comment by vmihailenco** [comment]
How can I reproduce the problem?
