### ISSUE TITLE
Any doc for newbie? Regarding CreateTable, What is Temp option? What will happen if table exists? Should I run CreateTable everytime at server starts?

### ISSUE THREAD

**Issue by sgon00** [go-pg/pg#1127]
Hi, this is my first day of trying go-pg. The doc is not very clear to many things. For instance, about creating table, I have read some examples in github pages, [CreateTable api page](https://godoc.org/github.com/go-pg/pg#Conn.CreateTable) and [CreateTableOptions api page](https://godoc.org/github.com/go-pg/pg/orm#CreateTableOptions). None of them clearly explains what will happen if I run this method twice. Will it drop the table when the table already exists? Will it just simple do nothing if the table already exists? What is `Temp: true`? The api doc doesn't write a single word for it. I am just confused on how to use it. Should I run CreateTable everytime I start my server or should I put it in a standalone program and execute it only once? Thanks a lot.

**Comment by vmihailenco** [comment]
This is a PostgreSQL client - you are expected to know how `CREATE TABLE` works in PostgreSQL.

**Comment by elliotcourant** [comment]
That being said, no it should not drop the table if it already exists. There is a specific function that can be run to drop tables: https://godoc.org/github.com/go-pg/pg#Conn.DropTable
If you run create table twice, it will do one of two things. If you specify `IfNotExists` then nothing will happen if the table already exists; but if `IfNotExists` is `false` then you will receive an error just like you would running a `CREATE TABLE...` directly.

I would recommend reading this, it has all the information would would need about the behaviors you would encounter using this client.
https://www.postgresql.org/docs/11/sql-createtable.html
