### ISSUE TITLE
DB.Listen and the connection pool

### ISSUE THREAD

**Issue by bgardiner** [go-pg/pg#1128]
It appears that [`pg.DB.Listen`](https://godoc.org/github.com/go-pg/pg#DB.Listen) does not use connections from the connection pool.  That conclusion is based on [this line](https://github.com/go-pg/pg/blob/master/internal/pool/pool.go#L129) that creates a new unpooled connection for each `pg.Listener`.

Is this correct and intended?

I am currently exhausting the default connection pool (which appears to be `10 * runtime.NumCPU()`), so I am trying to figure out an appropriate value to set in the config; however, I am confused about what types of queries I should account for as utilizing the connection pool.  I use a lot of `pg.Listener`s.... should I completely ignore those from connection pool usage accounting?  If so, is there any limit on the number of connections created from `pg.Listener`s?

**Comment by vmihailenco** [comment]
Indeed `pg.Listener` does not use connections from the pool. There are no limits on number of `pg.Listener`s.

>I am currently exhausting the default connection pool

First I recommend you to check if:
- you properly close (commit or rollback) transactions so connections do not leak
- PostgreSQL is not overloaded and has resources to serve your queries fast enough

Default value `10 * runtime.NumCPU()` should be high enough.

**Comment by bgardiner** [comment]
thanks for the help  and prompt response!
