### ISSUE TITLE
`sql:",notnull"` for strings, etc.

### ISSUE THREAD

**Issue by wavded** [go-pg/pg#1131]
When defining a struct, it appears I need to default the value to `null` so it doesn't count an empty string as valid.

```
Name             string    `sql:"default:null,notnull"`
```

Without `default:null` it will insert the record with an empty string and not fail any violations.

Is this expected behavior? Should I be doing something different? I haven't tested but am guessing this the behavior for any primitive type.

**Comment by elliotcourant** [comment]
I think this would be expected, if you did not define `notnull` on a string field (say a description field or notes field for a product or an order) you might still want those fields to have a not null value (for some reason).

It might be possible though to add something eventually to models to have a `BeforeInsert` hook that you could use to validate the field. But that is something that you can achieve already by wrapping pg with your own methods and calling those instead.

You could also add a constraint to the `Name` column in PostgreSQL to check the length of the string and reject it if its 0.

**Comment by wavded** [comment]
Thanks, I can see your point and it makes sense. Was unexpected though to me. The `default:null` works. I assume required foreign keys may need the same check then to avoid `0` being inserted?

**Comment by elliotcourant** [comment]
Foreign keys on columns will reject a value that does not exist in the related table, regardless of what that value might be. If a foreign key is on a nullable column though, then the only value that would be accepted that isn't in the related table is `null`.

**Comment by elliotcourant** [comment]
@vmihailenco I think this issue is resolved.

**Comment by wavded** [comment]
I agree, explanation makes sense. Thanks @elliotcourant.
