### ISSUE TITLE
How to implement custom ScanColumn on Query type

### ISSUE THREAD

**Issue by ShellyWEI** [go-pg/pg#1137]
I read the issue #712, there is a solution based on `db.Query()`.
But I want to use `db.Apply(filter).Select()`. When I looked inside the Select() function, it uses Query.model which is TableModel type, and interesting thing is `scanColumn()` inside the interface can't be override...

My use case is I must use dynamic filters to generate sql-query to get results, but the scan seems to over-job here. I don't need to Unmarshal them to the according type in golang, so I want to override the ScanColumn.

Is there an another way to support both dynamic filter and custom scanner?

**Comment by vmihailenco** [comment]
I don't see how dynamic filters affect models, but you can model into `Select`:

```
db.Model(&tableModel).Select(&customModel)
```

**Comment by ShellyWEI** [comment]
Thanks for your response. 
Let me post my code here, because I am not sure if I understand correctly.
`type Transaction struct {
	tableName struct{} `sql:"transactions,alias:t" pg:",discard_unknown_columns"`
	...
	Data         map[string]interface{} `sql:"data,notnull" json:"data"`
}
type transactionScanner struct {
	...
	Data         byte
	cs orm.ColumnScanner
}

func NewTransactionScanner() *transactionScanner {
	t := transactionScanner{}
	t.cs = orm.Scan(&..., &t.Data)
	return &t
}

func (t *transactionScanner) Init() error {
	return nil
}

func (t *transactionScanner) NewModel() orm.ColumnScanner {
	return t
}

func (t *transactionScanner) AddModel(cs orm.ColumnScanner) error {
	return nil
}

func (t *transactionScanner) ScanColumn(colIdx int, colName string, rd types.Reader, n int) error {
	switch colName {
        ...
	case "data":
		if bytes, err := rd.ReadByte(); err != nil {
			return err
		} else {
			t.Data = bytes
		}
	}
	return nil
}`
then, like you suggested:
`db.Model(&Transactions).Apply(myFilter).Select(NewTransactionScanner())`
but I can't get what I want since `*Transaction` has nothing in there. I am not sure if it is caused by i change the `Data` type. I don't want map to be unmarshalled, I want Reader to send whatever the bytes are.
