### ISSUE TITLE
SQLBoiler comparison (performances and features).

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1143]
I'm totally newbie in Go and in ORMs.

SQLBoiler (https://github.com/volatiletech/sqlboiler) really intrigues me.

I searched a lot in issues here and there: nothing. No comparison at all.

Can I ask you to explain it better about performances and features?

**Comment by elliotcourant** [comment]
The differences are not significant at a glance and come down to personal preference. You should try them both and develop your own opinion on which is the best for your use case.

The biggest difference is pg is built specifically around the features of PostgreSQL, and that makes it much better (in my opinion) for dealing with Postgres than SQLBoiler. SQLBoiler is built to handle several different databases; each with their own nuances and advantages and disadvantages.

**Comment by frederikhors** [comment]
Ok. Thanks.

What really scares me is that `pg` is one single person contributions based (vmihailenco).

**Comment by elliotcourant** [comment]
`pg` isn't maintained by a single person. @vmihailenco created pg and contributes the most to it by far; and does an extremely good job at it. You can look at his profile and see that he is EXTREMELY active on GitHub in this project and in his other projects. I would not worry about him being the primary contributor. 

But there are other people who contribute to this project as they find things they want to see in it.
And even if others are not necessarily writing code for this project, then they are opening issues to help fix bugs or add features that people want. I'd say this project is pretty active regardless.

**Comment by frederikhors** [comment]
Ok, thanks a lot for your info. Sure amazing job go-pg.
