### ISSUE TITLE
ERROR: (gcloud.app.deploy)

### ISSUE THREAD

**Issue by hasanmumin** [go-pg/pg#1144]
ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
2019/03/23 04:55:35 go-app-builder: Failed parsing input: parser: bad import "unsafe" in mellium.im/sasl/xor_unaligned.go

Google App Engine is not allow to use "unsafe". 

```
[[constraint]]
  name = "github.com/go-pg/pg"
  version = "8.0.2"
```

Can you help me about solution ?

**Comment by vmihailenco** [comment]
You need to create this issue in github.com/mellium/sasl. The fix is trivial - xor_generic.go should be unsed on appengine instead of xor_unaligned.go.
