### ISSUE TITLE
Model field struct

### ISSUE THREAD

**Issue by khuezy** [go-pg/pg#1146]
Hi, I'm wondering if you can have a struct in a model that contains fields in a table.
I don't want to store the scores in a separate table. I just one 1 model for the code and the database.

Table:
`games`
- ID
- score_home
- score_visitor

Model:
```
type Game struct {
   ID       int
   Score *Score `sql:"???"` // somehow reference the Score struct to pull out their fields
}

type Score struct {
   Home int `sql:"score_home"`
   Visitor int `sql:"score_visitor"`
}
```

**Comment by vmihailenco** [comment]
Did you try embedding

```
type Game struct {
   ID       int
   Score
}
```

**Comment by khuezy** [comment]
Thanks @vmihailenco, I didn't know I could access parameters through the embedding type.

**Comment by khuezy** [comment]
@vmihailenco I'm getting
```
reflect: indirection through nil pointer to embedded struct
```
when using a embedded pointer.

```
type Game struct {
   ID       int
   *Score
}
```

**Comment by elliotcourant** [comment]
I don't think the `Score` should be a pointer here.

**Comment by khuezy** [comment]
Any suggestion on how to omit `Score` if it's empty?

**Comment by elliotcourant** [comment]
Make the fields on `Score` nullable. Otherwise it goes against the paradigm or golang or pg.

**Comment by khuezy** [comment]
By making it nullable, do you mean add `json:",omitempty"`?

I am getting back an empty score struct but I want to omit the Score field completely.
