### ISSUE TITLE
How to create partition table?

### ISSUE THREAD

**Issue by ShellyWEI** [go-pg/pg#1150]
Hi, I have a question about creating child table since new data comes in. Master table has been created using declarative partitioning method. 
I wonder if it can support something like:
`db.Exec("CREATE TABLE IF NOT EXISTS ?childTableName PARTITION OF masterTable FOR VALUES FROM (?fromRange) to (?toRange)", tableName, fromRange, toRange)`

**Comment by vmihailenco** [comment]
Definitely, but you did not provide much details and I doubt go-pg can help much here..
