### ISSUE TITLE
listener.go:60: pg: Listen failed: dial  tcp i/o timeout

### ISSUE THREAD

**Issue by PoslavskySV** [go-pg/pg#1155]
Hi!

I use the following code to listen pg notifications:
```go
listen := db.Listen(resourceType)
notifications := listen.Channel()
...
for {
    select {
        case event, ok := <-notifications:
              ... // logic
        ...
    }
}

```

 In some cases I see the following `go-pg` message in logs:
```
pg: 2019/03/27 10:52:05 listener.go:60: pg: Listen failed: dial tcp 10.2.65.8:5432: i/o timeout
```
My app continues to work (no any errors returned from go-pg),  but it does not receive any more new notifications from the database. 

Looking  into `db.Listen`  source code ([line 82](https://github.com/go-pg/pg/blob/a68b98d583a946f06fad4322935f83f3b0f10774/db.go#L82)), I see that the error is just ignored and that's why my app continues to work, but listen is in fact failed:

```go
// Listen listens for notifications sent with NOTIFY command.
func (db *DB) Listen(channels ...string) *Listener {
	ln := &Listener{
		db: db,
	}
	ln.init()
	_ = ln.Listen(channels...)
	return ln
}
```

Should go-pg change `db.Listen`  to 

```go
// Listen listens for notifications sent with NOTIFY command.
func (db *DB) Listen(channels ...string) (*Listener, error) {
	ln := &Listener{
		db: db,
	}
	ln.init()
	err := ln.Listen(channels...)
	return ln, err
}
```

?

**Comment by vmihailenco** [comment]
Thanks for the reporting. I think this was accidentally broken in one of the code cleanups.
