### ISSUE TITLE
Multiple WhereIn

### ISSUE THREAD

**Issue by badoet** [go-pg/pg#1158]
Tried to do 
```
query = query.WhereIn("dropoff_district IN ?", dropoffDistrict).
			WhereIn("pickup_district IN ?", pickuppDistrict) 
```
this query doesnt work
but instead need to do
```
query = query.WhereIn("dropoff_district IN ?", dropoffDistrict).
			Where("pickup_district IN (?)", pg.In(pickuppDistrict)) 
```
any idea why?
i checked the code seems like WhereIn is just a helper to Where... pg.In
how could it be behaving differently?

**Comment by vmihailenco** [comment]
You are supposed to use it like `q.WhereIn("...", 1, 2, 3)`, but you do `q.WhereIn("...", []int{1, 2, 3})` instead. See https://github.com/go-pg/pg/blob/master/orm/query.go#L439-L444

**Comment by sergolius** [comment]
@vmihailenco `WhereIn` accepts two arguments, second argument in not variadic.
https://github.com/go-pg/pg/blob/master/orm/query.go#L439-L444
