### ISSUE TITLE
Get generated query

### ISSUE THREAD

**Issue by latipovsharif** [go-pg/pg#1159]
Is there any method which will return generated query? For example I'm writing 
`q := db.Model((*SomeStruct)(nil)).Column("id").Select(&id)` and this query for some reason returning error, so I need to log why this happened. Can I get it somehow, for example like this q.GeneratedQuery?

**Comment by xakep666** [comment]
I`m using query hooks for this. Example:
```go

**Comment by vmihailenco** [comment]
https://github.com/go-pg/pg/wiki/FAQ#how-can-i-viewlog-queries-this-library-generates

**Comment by latipovsharif** [comment]
@vmihailenco but I don't need to log the query all the time I need to log it if only error occurs.

**Comment by vmihailenco** [comment]
Try `QueryEvent.Error` in https://github.com/go-pg/pg/blob/master/hook.go#L23

**Comment by latipovsharif** [comment]
@vmihailenco this is exactly what I need. Thank you very much!
