### ISSUE TITLE
DB.Model(u).First() without strings in where.

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1168]
Is there a way to use `Select` with typed fields instead of strings in `Where`?

Example:

Using this code it works:

```go
u := &User{ID: 2}
if err := DB.Model(u).First(); err != nil {
	return nil, err
}
return u // works good!
```

But when using this instead:

```go
u := &User{Email: emailAddress}
if err := DB.Model(u).First(); err != nil {
	return nil, err
}
return u // incorrect user!
```

it returns just the **first** (incorrect) user in DB.

Is this way of filtering only correct when using primary key?

Is using "strings" in `Where()` like below the only way?

```go
if err := DB.Model(u).Where("email = ?", emailAddress).First(); err != nil {
```

I'd like to use a most secure typed way.

**Comment by vmihailenco** [comment]
>Is this way of filtering only correct when using primary key?

Yes, and honestly it is confusing enough to not use it either. I always explicitly call `Where` when needed.
