### ISSUE TITLE
No automatic reconnect when using transactions

### ISSUE THREAD

**Issue by moogle19** [go-pg/pg#1169]
Hi, 
I got the following problem using go-pg:
When using normal Insert, Select... methods the reconnecting in case of a db restart is handled as it should. 

But when I use a transaction (with `db.Begin` and `tx.Insert`) I get a `write tcp [::1]:52557->[::1]:5432: write: broken pipe` error (instead of `dial tcp [::1]:5432: connect: connection refused` for an Insert without a transaction) and after the restart of the db is done, no reconnection takes place.

Tested with: 
go-pg: `v8.0.3` & `v8.0.0` & `v7.1.7`
Postgres: `10.7`

Sample code: 
```go
package main

import (
	"log"
	"time"

	"github.com/go-pg/pg"
)

type test struct {
	Test string
}

func main() {
	db := pg.Connect(&pg.Options{
		User:     "postgres",
		Database: "testing",
	})

	test := test{
		Test: "hello",
	}

	for {
		time.Sleep(time.Second)
		tx, err := db.Begin()
		if err != nil {
			log.Printf("failed to begin: %v", err)
			continue
		}
		err = tx.Insert(&test)
		if err != nil {
			continue
			log.Printf("failed to insert: %v", err)
		}
		err = tx.Commit()
		if err != nil {
			log.Printf("failed to commit: %v", err)
		}
	}
}
```

**Comment by vmihailenco** [comment]
This is expected - you need to re-run transaction on error manually (if that is what you want). Otherwise go-pg could screw data in the database.

**Comment by moogle19** [comment]
@vmihailenco 
That's what I am trying, but the `broken pipe` error is returned from `tx.Begin`, so I can't start a new transaction.
If I add a simple `db.Exec("SELECT 1")` before retrying to begin a transaction, it fixes the problem.

**Comment by moogle19** [comment]
@vmihailenco 
I think the behaviour is cause by this line:
https://github.com/go-pg/pg/blob/2025d4012ba655acfa7430308d87fb2ea2f25bb0/internal/pool/pool_single.go#L90
The channel is never read again if the connection was terminated by a db restart or connection issue so the defer function which calls `p.pool.Remove` is never called, because the channel write blocks forever.

**Comment by vmihailenco** [comment]
`tx.Begin` does not start new transaction. It is dummy function that just returns current transaction - https://github.com/go-pg/pg/blob/master/tx.go#L59-L62.

**Comment by moogle19** [comment]
@vmihailenco 
I call `db.Begin` not `tx.Begin`.

**Comment by moogle19** [comment]
@vmihailenco 
If I understand the implementation of `SingleConnPool` correctly, it currently only removes connections from the `ConnPool` when `Remove` is called and the `SingleConnPool.ch` channel is closed, because that's the only case `Remove` whould panic. But if the underlying connection in `SingleConnPool` doesn't get explicitly closed and just fails because of connectivity or db restart the connection is never remove from the pool and is used over and over again.

**Comment by moogle19** [comment]
After a bit more digging I noticed, that `SingleConnPool.Close` gets called, but it call `p.pool.Put` and adds the connection back to the pool even if the connection is terminated.
