### ISSUE TITLE
panic: ERROR #42704 type "hstore" does not exist

### ISSUE THREAD

**Issue by yxlwfds** [go-pg/pg#1173]
type Item struct {
    Id    int64
    Attrs map[string]string `sql:",hstore"` // marshalled as PostgreSQL hstore
}
when init:
func createSchema(db *pg.DB) error {
	for _, model := range []interface{}{(*Item)(nil)} {
		err := db.CreateTable(model, &orm.CreateTableOptions{
			Temp: false,
			//FKConstraints: true,
		})
		if err != nil {
			return err
		}
	}
	return nil
}

panic the error:
panic: ERROR #42704 type "hstore" does not exist

**Comment by vmihailenco** [comment]
You need to create hstore extension.

**Comment by yxlwfds** [comment]
how? thanks!

**Comment by yxlwfds** [comment]
i get it!
psql# create extension hstore;
