### ISSUE TITLE
tx|db.Update() with slice argument causes error "pg: multi rows in result set"

### ISSUE THREAD

**Issue by xakep666** [go-pg/pg#1174]
If you try to update multiple rows in one query using slice as argument for Update() method it returns error. Workaround: use tx.Model(&items).Update()
I think it should be documented

**Comment by frederikhors** [comment]
@vmihailenco I think we should document this.

**Comment by vmihailenco** [comment]
There is nothing to document - `tx|db.Update()` is gone in v10.
