### ISSUE TITLE
Add query example

### ISSUE THREAD

**Issue by j0hnwhyte** [go-pg/pg#1177]
I have been working a lot to solve a problem that apparently the documentation doesn't explain how to solve, binding to a custom model with more than one result in a query.

I'll post the code that made it work, if you think it's appropriate, it would be useful to add it to the examples.

Thanks

```go
type QueueElement struct {
	Recipients  []string  `sql:"recipients"`
	Provider    string    `sql:"provider"`
	LastTry     time.Time `sql:"updated_at"`
	MessageGuid string    `sql:"message_guid"`
}

var qr []QueueElement

res, err := max.Db.Query(&qr,
`
SELECT message.recipients, queue.provider, queue.updated_at, message.guid AS message_guid
FROM message RIGHT JOIN queue ON queue.message_id = message.id
`)

```

**Comment by vmihailenco** [comment]
Well, from go-pg POV there is nothing unusual in this query. Practically there is no difference between field `Recipients` and `Provider`. In fact go-pg does not know from which tables the data is coming.
