### ISSUE TITLE
Add "Closed" method for checking if DB is closed

### ISSUE THREAD

**Issue by jgiles** [go-pg/pg#1180]
We have some workflows where we manually close DB connections, and it would be very useful to have a `(db *pg.DB) Closed() bool` to check if a particular DB client is closed.

In particular, we have a large suite of integration tests that run against a local Postgres with isolation based on creating a separate database+connection per test, and it is important to manage connections to avoid overwhelming Postgres.

Note that this is more limited than https://github.com/go-pg/pg/issues/664 - we only care about checking whether we have manually closed the DB client.

**Comment by vmihailenco** [comment]
It is hard to tell whether this is a good idea or not. But it is definitely not a very popular request / common API. Therefore I suggest to do this in user space by creating a wrapper for `db.Close` method.

**Comment by jgiles** [comment]
I don't think a wrapper for `db.Close` is sufficient on its own to solve this problem.

The workaround I have adopted is pretty hacky:

* In a helper function we always use to call `pg.Connect`, we use `db.WithParam("very_unlikely_param_name_for_closed_marker", atomic.NewBool(false))` to attach a marker as a "parameter" so that all derived db instances (e.g. from `db.WithContext`, etc) bear that marker.
* We define a helper method `Close(db *pg.DB) error`, which extracts marker, sets its value to `true`, and calls `db.Close()`
* We define a helper `IsMarkedClosed(db *pg.DB) bool`, which extracts and checks the closed marker from the given db instance.

This seems like a hacky and brittle solution for something that could be pretty easily implemented in the library itself.

Without resorting to something like this, it is difficult do recognize the state of DB closure - the `ErrClosed` error constant is internal, so you cannot even run some query and easily determine from the error that the db instance is closed.

Identifying closure is useful: It is a permanent state where no further queries will succeed, and the application should not attempt further queries on the instance.
