### ISSUE TITLE
[][]Book directly from Postgres with (something like) SELECT ARRAY_AGG, using dataloader

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1183]
_Question for newbies like me. Eventually, if that's okay with you, I can open a wiki page to collect all these FAQs for newbies._

I'm experimenting with **gqlgen** (https://github.com/99designs/gqlgen) and **dataloader pattern** (using _dataloaden_, https://github.com/vektah/dataloaden).

These are the models:

```go
type School struct {
  ID   int
  Desc string
}

type Author struct {
  ID       int
  Name     string
  SchoolID int
}

type Book struct {
  ID       int
  Pages    int
  AuthorID int
}
```

This is the `schema.graphql`:

```graphql
type School {
  id: ID
  desc: String
  authors: [Author]
}

type Author {
  id: ID
  name: String
  books: [Book]
}

type Book {
  id: ID
  pages: Int
}
```

Using _dataloaden_ I can use **go-pg** like this:

```go
booksByAuthor = &BooksSliceLoader{
  wait:     1 * time.Millisecond,
  maxBatch: 100,
  fetch: func(keys []int) ([][]Book, []error) {
    var dbItems []Book
    if err := DB.Model(&dbItems).Where("author_id in (?)", pg.In(keys)).Select(); err != nil {
      return nil, []error{err}
    }
    items := make([][]Book, len(keys))
    for i, key := range keys {
      for _, dbItem := range dbItems {
        if dbItem.AuthorID == key {
          items[i] = append(items[i], dbItem)
        }
      }
    }
    return items, nil
  },
}
```

### QUESTION

I'm wondering if there is a way with _go-pg_ to directly retrieve from Postgresql the `[][]Book` array (also to avoid the double `range` in Go code and the two arrays every time).

I'm not an expert but I think the query below can work (or maybe with `SELECT ARRAY()`), just don't know if and how _go-pg_ can help me here:

```sql
SELECT ARRAY_AGG
	( ARRAY [ books.* ] )
FROM
	books
WHERE
	(author_id IN ( 1, 2, 3 ))
```

The query returns:

```
// id, pages, author_id
{
  {"(32,1000,1)"},
  {"(33,1000,1)"},
  {"(34,1000,1)"},
  {"(35,1000,2)"},
  {"(36,1000,2)"},
  {"(37,1000,2)"},
  {"(38,1000,2)"},
  {"(39,1000,2)"},
  {"(40,1000,3)"},
  {"(41,1000,3)"},
  {"(42,1000,3)"},
  {"(43,1000,3)"}
}
```

Am I totally wrong?

Inspiration:
- https://lerner.co.il/2014/05/23/turning-postgresql-rows-arrays-array/
- https://outcrawl.com/graphql-postgresql-window-functions
- https://gist.github.com/cpjolicoeur/3590737

**Comment by vmihailenco** [comment]
It is hard to tell for sure, but looks like you want to use array of composites which is not supported. Closing in favor of https://github.com/go-pg/pg/issues/1197
