### ISSUE TITLE
Postgres Functions Usage

### ISSUE THREAD

**Issue by ilyakaznacheev** [go-pg/pg#1186]
Is there any built-in option to use Postgres function (i.e. PL/pgSQL) as a data model for select?

I mean not just write a custom query, but proper handling of parameters, etc.?

**Comment by vmihailenco** [comment]
It is hard to understand what you mean - an example would help I guess.

**Comment by ilyakaznacheev** [comment]
@vmihailenco let's say I have some function

```sql
CREATE OR REPLACE FUNCTION get_sum(
 a NUMERIC, 
 b NUMERIC) 
RETURNS NUMERIC AS $$
BEGIN
 RETURN a + b;
END; $$
 
LANGUAGE plpgsql;
```

and I want to fetch the data using some parameters

```sql
SELECT get_sum(10,20);
```

I would like to have some shortcut for it, like that

```go
// descibe function get_sum as a model of NumberSum by means of tags
numSum := new(NumberSum)
err := db.Model(numSum).
    WithParameters(10,20).
    Select()
```

instead of manual script execution as a text.

Is something like that possible in go-pg?

**Comment by vmihailenco** [comment]
Why `db.Exec("SELECT get_sum(?, ?)", 10, 20)` does not work for you?

**Comment by ilyakaznacheev** [comment]
It will, but I was interested if there is some shortcut
