### ISSUE TITLE
support json array?

### ISSUE THREAD

**Issue by mailbaoer** [go-pg/pg#119]
I have a json array column named 'content', example value like:
`[{"time": 1458033154, "user": "baoer", "detail": "hello"}, {"time": 1458033155, "user": "beiguo", "detail": "hi"}]`
 when I find a record from my table ,It raised that "invalid character ',' after object key", how can I change it, my struct defined the content column is `Content []interface{}`

**Comment by vmihailenco** [comment]
Works just fine for me. Do you use pg.v4?

```
package main

import (
	"fmt"

	"gopkg.in/pg.v4"
)

type Test struct {
	Slice []interface{}
}

func main() {
	db := pg.Connect(&pg.Options{
		User: "postgres",
	})

	_, err := db.Exec(`create table if not exists tests (slice jsonb)`)
	if err != nil {
		panic(err)
	}

	err = db.Create(&Test{
		Slice: []interface{}{map[string]interface{}{"hello": "world"}},
	})
	if err != nil {
		panic(err)
	}

	var tests []Test
	err = db.Model(&tests).Select()
	if err != nil {
		panic(err)
	}
	fmt.Println(tests)
}
```

**Comment by mailbaoer** [comment]
I found the problem,my column type is top level json arrays, so need more work for decode
`
package main

import "fmt"
import "encoding/json"

type Server struct {
	ServerName string
	ServerIP   string
}

func main() {
	s := make([]Server, 1)
	str := `[{"serverName":"server1","serverIP":"127.0.0.1"},{"serverName":"server2","serverIP":"127.0.0.2"}]`
	json.Unmarshal([]byte(str), &s)
	fmt.Println(s)
}
`
