### ISSUE TITLE
INSERT many2many best practice?

### ISSUE THREAD

**Issue by jeffreydwalter** [go-pg/pg#1192]
Hello,

I've got a many2many relation, but my join table has a couple of extra columns that I need to set when creating the join table record.

I read through #442 and see there were 2 methods of creating the join table record, but I'm wondering if there's a preferred way 2 years later.

To borrow the example in #442, I have:
```
type User struct {
    Id    int
    Items []Item `pg:",many2many:user_to_items,joinFK:Item"`
}
type Item struct {
    Id    int
    Users []User `pg:",many2many:user_to_items,joinFK:User"`
}
type UserToItem struct {
    UserId int
    ItemId int
    ColumnThatNeedsToBeSetOnCreation string
}
```
I imagine I can do:
```
userToItem := UserToItem{userId, ItemId, "My cool value I need to store in the join table"}
tx.Model(&userToItem).Insert()
```
but, is there a better way?

**Comment by jeffreydwalter** [comment]
Also, what would you recommend I do if I wanted `UserToItem. ColumnThatNeedsToBeSetOnCreation` to be available on the User model? So I could do something like:
```
tx.Model(&user).Insert()
tx.Model(&item).Insert()
tx.Model(&userToItem).Insert()

u := new(User)
tx.Model(u).Returning("*").Select()
u.ColumnThatNeedsToBeSetOnCreation // I would like to be able to access this column from the join table on the parent User model.
```

**Comment by vmihailenco** [comment]
I can only confirm that go-pg does not offer anything special to insert data into m2m table. It is no different from inserting into any other table.
