### ISSUE TITLE
Query fails on alias

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1195]
Doing a simple Insert generates the following statement:

`db.Insert(&allEvents)`

`INSERT INTO "events" ("id", "name","url","start_date","end_date") VALUES ('1', 'Name','github.com','2019-11-02 00:00:00+00:00:00','2019-11-02 00:00:00+00:00:00') RETURNING "created_at", "updated_at"`

This works fine and a row is inserted. I tried changing this to UPSERT:

`db.Model(&allEvents).OnConflict("(events_unique_index) DO UPDATE").Set("(url, start_date, end_date) = (EXCLUDED.url, EXCLUDED.start_date, EXCLUDED.end_date)").Insert()`

`INSERT INTO "events" AS "event" ("id", "name","url", "start_date", "end_date")  VALUES ('1', 'Name','github.com',''2019-11-02 00:00:00+00:00:00'',''2019-11-02 00:00:00+00:00:00') ON CONFLICT (events_unique_index) DO UPDATE SET (url, start_date, end_date) = (EXCLUDED.url, EXCLUDED.start_date, EXCLUDED.end_date)`
2019/04/23 16:14:17 ERROR #42601 syntax error at or near "AS"`

It fails due to alias. How can I remove the alias?

**Comment by vmihailenco** [comment]
AFAIK without the alias support you also don't have upsert support. Did you try to remove alias and re-run the query without it?

**Comment by ribice** [comment]
Any clue why it fails with alias?

**Comment by vmihailenco** [comment]
The clue is that you need to upgrade Postgres.

Does it work without an alias?

**Comment by ribice** [comment]
This is related to PostgreSQL version. I remember running it just fine on different project.

For Upsert, the version has to be >= 9.5. My version is: `PostgreSQL 9.4.1`

Without alias, it prints: `[42601] ERROR: syntax error at or near "ON"`

I'll test later with updated version and probably close the issue.
