### ISSUE TITLE
Reading and writing to arbitrary columns by name

### ISSUE THREAD

**Issue by j0hnwhyte** [go-pg/pg#1200]
I'm aiming at building a system that synchronises two tables. The column names can be arbitrary, so I can't create a custom `struct` that holds the names and feed it to `Model()`.

It would be perfect to have something read the columns of a single record into a map, but despite the many tries (and the fact that how `Model` actually works is poorly documented), I've been unable to achieve such result.

How can I do this? I think it's possible with the standard go sql library.

**Comment by jos-** [comment]
To select arbitrary columns of a single row as map, you can use:

```
var result struct {
	Data map[string]interface{}
}
if err := db.Model().
	TableExpr("table_name AS t").
	ColumnExpr("row_to_json(t) AS data").
	Limit(1).
	Select(&result); err != nil && err != pg.ErrNoRows {
	return err
}
```

**Comment by j0hnwhyte** [comment]
Interesting, I used the CopyTo function as a workaround for now, I'll look into this. Thanks
