### ISSUE TITLE
Using parameter in table name

### ISSUE THREAD

**Issue by jos-** [go-pg/pg#1201]
I need to select from a table with unknown (variable) name with an alias.

`db.Model().TableExpr("? AS t", myVariable).Select(...)` encodes the value `myVariable` as a constant with single quotes around it instead of double quotes, resulting in a syntax error.

`db.Model().TableExpr(myVariable + " AS t").Select(...)` works but is vulnerable to SQL injection.

Any other way to do this? Thanks.

**Comment by jos-** [comment]
Found a workaround using an anonymous struct as model:

```
var result struct {
	tableName struct{} `sql:"alias:t"`

	...
}
db.Model(&result).Table(myVariable).Select()
```

Still, it would be nice if parameters could be used in `TableExpr` and `ColumnExpr` to define variable table or column names.

**Comment by vmihailenco** [comment]
Try `db.Model().TableExpr("? AS t", pg.F(myVariable)).Select(...)`

**Comment by jos-** [comment]
Thanks, that was the function I was looking for.

**Comment by zdraganov** [comment]
There's no such function in v10. Any replacement?
