### ISSUE TITLE
Insert without RETURNING 

### ISSUE THREAD

**Issue by mewwts** [go-pg/pg#1208]
Hey,

I'm having data races when inserting some types because the Insert is scanning the returned values. Is there a way to generate queries that do not use the `RETURNING` clause?

Thanks

**Comment by vmihailenco** [comment]
Right you can try something like `Returning("NULL AS _")` with `pg:",discard_unknown_columns"`. But go-pg should probably support special syntax like `Returning("NULL")`.

**Comment by mewwts** [comment]
Thanks, yeah!

What's the rationale behind returning by default?

**Comment by vmihailenco** [comment]
To have values for columns with `DEFAULT`.

**Comment by mewwts** [comment]
I see.

Although your fix worked, I totally agree there should be a slightly easier way of opting out of that behavior. Thanks again.

**Comment by vmihailenco** [comment]
`Returning("NULL")` is all you should need in the master branch.

**Comment by mewwts** [comment]
I have one other issue with `Returning("NULL")` and that is that I need to do a lot of checks for `pg.ErrNoRows`. My usecase is the following: I have a few different data types that I want to insert in a transaction; so after calling `Begin()` I repeatedly do
```go
_, err := tx.Model(&something).OnConflict("DO NOTHING").Returning("NULL").Insert()
if err != nil && err != pg.ErrNoRows {
    return err
}
```
Having to check for this is quite annoying, especially since it's a library-thing, not a postgresql thing. IMHO `Returning("NULL")` should not error with `pg.ErrNoRows` if the result set has no rows.

**Comment by vmihailenco** [comment]
@mewwts you are right - should be fixed with https://github.com/go-pg/pg/pull/1491

**Comment by mewwts** [comment]
Thanks @vmihailenco!
