### ISSUE TITLE
Nested structures and select columns in relation

### ISSUE THREAD

**Issue by kt75** [go-pg/pg#1211]
Suppose we have three structures as follows
```
type A struct {
	ID  uint `sql:"id,pk"`
	BID uint `sql:"b_id,fk"`
	B   *B
}

type B struct {
	ID  uint `sql:"id,pk"`
	CID uint `sql:"c_id,fk"`
	C   *C
}

type C struct {
	ID   uint   `sql:"id,pk"`
	Name string `sql:"name"`
}
```

and we want to join their tables. So I use pg as follows.
```
db.Model(&a).Relation("B").Relation("B.C").Column("a.id", "b.id", "b__c.id", "b__c.name")
```
Generated query from postgres log is:
```
SELECT 
"a"."id", 
"b"."id", b"."id" AS "b__id", "b"."c_id" AS "b__c_id", 
"b__c"."id", "b__c"."name", ""b__c"."id" AS "b__c__id", "b__c"."name" AS "b__c__name" 

FROM "as" AS "a" 
LEFT JOIN "bs" AS "b" ON "b"."id" = "a"."b_id" 
LEFT JOIN "cs" AS "b__c" ON "b__c"."id" = "b"."c_id" 
```
the `"b__c"."id","b__c"."name"` part in executed query is useless and creates bug(replace `"b__c"."id"` with `"a"."id"` value).

In this example following query is expected:
```
SELECT 
"a"."id",
"b"."id" AS "b__id",
"b__c"."id" AS "b__c__id","b__c"."name" AS "b__c__name"

FROM "as" AS "a" 
LEFT JOIN "bs" AS "b" ON "b"."id" = "a"."b_id" 
LEFT JOIN "cs" AS "b__c" ON "b__c"."id" = "b"."c_id" 
```
The sample code:
[main.txt](https://github.com/go-pg/pg/files/3182847/main.txt)

**Comment by kt75** [comment]
I think `Column` expression with such parameters is required to achieve result. So I explain what is desired result and what is my query, correct me. I need to join `A`,`B` and `C` and fetch specific columns(i.e `A.id`, `B.id`, `C.id` and `C.name` and omit others).
So I used following expression
```
db.Model(&a).Relation("B").Relation("B.C").Column("a.id", "b.id", "b__c.id", "b__c.name")
```

**Comment by vmihailenco** [comment]
In such cases you need to look at the [generated query](https://github.com/go-pg/pg/wiki/FAQ#how-to-view-queries-this-library-generates) and for from there.
