### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by tangtony** [go-pg/pg#1218]
I am trying to do some sort of health check on the database to ensure it's up and running, but the problem is that when the database is configured with `MaxRetries`, my query to check if the database is up just hangs while it constantly retries. And obviously my health check doesn't work since it never returns the status.

There is a `WithTimeout` option that lets you return a copy of the database with a timeout, but that doesn't help if the database is down. It would be nice if there was an option similar to that for enabling or disabling retry.

Or is there another way entirely to do some sort of health check?

**Comment by vmihailenco** [comment]
Just use some sensible `MaxRetries` value - there is no point in constantly retrying. `MaxRetries` usually is more than enough.

Alternatively you can create separate `pg.DB` just for the health check.

**Comment by tangtony** [comment]
I have my `MaxRetries` set to 8 with the default min and max retry backoffs which adds up to roughly 1 minute of retrying. I don't think this is unreasonable if I want it to handle the database being restarted, since PostgreSQL can take some time to recover from an unexpected shutdown.

I suppose I could use a separate `pg.DB` just for the health check if you're strongly opposed to the idea of being able to configure retry per query/connection, but it feels very hacky to create an entirely new connection pool just for health check purposes. Especially since it means you have to either have a dedicated connection for the health check or constantly create and destroy a connection as opposed to being able to reuse connections already in the pool being used by the application.
