### ISSUE TITLE
Support for non-primary key condition update?

### ISSUE THREAD

**Issue by taiyangc** [go-pg/pg#1219]
It looks like current `.Update()` is forcing a primary key condition-based update: https://github.com/go-pg/pg/blob/master/orm/update.go#L12

Even though I can prepend a `.Where("title = ?", "xxx")` before `.Update()` it still appends a primary key condition. Is there an easier way to support a non-primary key condition update or I have to write the raw statement myself? Thanks.

**Comment by vmihailenco** [comment]
Try to prepend `Where("title = ?", "xxx")` - it should work

**Comment by taiyangc** [comment]
@vmihailenco Sorry I should have made it clearer, the single update case is working as intended, however for bulk update:

```golang
import (
    "fmt"

    "github.com/go-pg/pg"
)

type Test struct {
    ID    int    `sql:"id,pk"`
    Title string `sql:"title,notnull"`
}

type dbHook struct{}

func (d dbHook) BeforeQuery(q *pg.QueryEvent) {
}

func (d dbHook) AfterQuery(q *pg.QueryEvent) {
    qs, err := q.FormattedQuery()
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println(qs)
    }
}

func main() {
    db := pg.Connect(&pg.Options{
        User:     "eric",
        Database: "eric",
    })
    defer db.Close()
    db.AddQueryHook(dbHook{})
    t := []*Test{&Test{ID: 1, Title: "hello"}}
    _, err := db.Model(&t).Where("title = ?", "xxx").Update()
    if err != nil {
        panic(err)
    }
}
```

Is forcing primary key id on where:
```sql
UPDATE "tests" AS "test" SET "title" = _data."title" FROM (VALUES (1, 'hello')) AS _data("id", "title") WHERE "test"."id" = _data."id" AND (title = 'xxx')
```

**Comment by vmihailenco** [comment]
Can you provide query that makes some sense? I don't want to change existing behavior in order to fix some non-existant use case.

**Comment by taiyangc** [comment]
Sure, I can provide one of our use cases.

Let's say we have an Objects table like this: primary id key as identifier, type to indicate object type, and some raw data in jsonb.

```golang
type Object struct {
	ID   string                 `sql:"id,pk"`
	Type int                    `sql:"type,notnull"`
	Data map[string]interface{} `sql:"data,notnull"`
}
```

When an object is first inserted, its unique id is generated, along with a fixed type, and some initial data. Afterwards, more data for specific types are collected over time, so we need to update into the data column based on type. So we really need something like

```golang
var objects []*Object
// Create an objects slice containing new data to be updated
objects = append(objects, &Object{Type: 1, Data: map[string]interface{}{...}})
objects = append(objects, &Object{Type: 2, Data: map[string]interface{}{...}})
...
db.Model(&objects).Set("data = data || ?data::jsonb").Where("type = ?type").Update()
```

This statement must not set an ID where condition because we are doing a bulk update on type, not individual unique ids.

I am not saying current behavior must be modified to support our case, but a workaround or a new function allowing override of primary id condition would be appreciated. Currently we are constructing our `UPDATE ... SET ... FROM (VALUES ...) AS ... WHERE ...` statement manually by appending types and marshaling data one by one into a buffer, which is, ugly and painful.

**Comment by vmihailenco** [comment]
Master branch should use `Where` clause you provide. It must be something like `Where("table.type = _data.type")` - see what go-pg generates by default.

**Comment by taiyangc** [comment]
@vmihailenco Works well, thank you!
