### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by santacruz123** [go-pg/pg#122]
Trying to insert 

`{{63593732575 333450581 0x67f6c0} map[fb_adset_id:6032793131234 af_c_id:3e025 af_cost_model:cpi imei:358422050231234 android_id:449021d533061234 af_sub1:<nil> media_source:Facebook Ads carrier:Vodafone os_version:4.3 device_brand:samsung af_adset:3gvow fb_campaign_id:6032793121234 af_sub4:<nil> campaign:FACEBOOK_CAMPAIGN_TEST fb_campaign_name:FACEBOOK_CAMPAIGN_TEST agency:<nil> af_sub3:<nil> customer_user_id:1234-5678 fb_adgroup_id:6032793211234 operator:Vodafone IN appsflyer_device_id:1446034686662-8619927357095541234 app_version:4.4.1 af_adset_id:3gvow device_model:GT-I9300 app_name:[App Name Comes Here] attribution_type:regular event_type:install country_code:GB af_siteid:<nil> af_cost_currency:USD af_keywords:key1 key2 key3 af_ad_id:123245353 download_time:2015-10-28 00:18:00 cost_per_install:<nil> is_retargeting:false af_sub2:<nil> fb_adgroup_name:FACEBOOK_ADGROUP_TEST event_time:2015-10-28 12:18:36 event_value:<nil> mac:<nil> http_referrer:<nil> af_channel:youtube ip:115.98.114.125 re_targeting_conversion_type:<nil> sdk_version:1.17 language:English af_sub5:<nil> wifi:true click_url:<nil> platform:android af_ad_type:Banner_210X600 event_name:<nil> af_cost_value:0.0750 advertising_id:95e55150-1111-2222-3333-3e0c8c1d9978 app_id:[App ID Comes Here] city:London fb_adset_name:FACEBOOK_ADSET_TEST currency:<nil> install_time:2015-10-28 12:18:36 click_time:2015-10-28 12:17:37 af_ad:a86721874]}`

into

`
type Postback struct {
	dt       time.Time
	postback map[string]interface{}
}
`

get

`ERROR #42601 syntax error at or near ")":`

**Comment by santacruz123** [comment]
How can I get raw query of Create?

**Comment by vmihailenco** [comment]
In postgresql.conf I have:

```
log_statement = 'all'
log_min_duration_statement = 0
```

Then I have all queries in my log at /var/log/postgresql/postgresql-9.5-main.log

Try to change your struct to

```
type Postback struct {
    Dt time.Time
    Postback map[string]interface{}
}
```

go-pg ignores unexported fields (those that start with lower case).

**Comment by santacruz123** [comment]
Works! Thanks for speed!
