### ISSUE TITLE
Is it possible to ignore on select but not insert?

### ISSUE THREAD

**Issue by mfinley3** [go-pg/pg#1220]
Similar to https://github.com/go-pg/pg/issues/770

I have a structure
```go
type myStructure struct {
	TableName        struct{} `sql:"myTable" pg:",discard_unknown_columns" json:"-"`
        ...
	NestedData
        ...
}

type NestedData struct {
	...
	Key string `json:"key,omitempty" sql:"-"`
        ...
}
```

I would like `Key` to not be ignored on insert but ignored on select.

From https://github.com/go-pg/pg/issues/770#issuecomment-364899387 - I  have tried:
```go	
_, err := dr.db.Model(&myStructure).Value("key", myStructure.NestedData.Key).Insert()
``` 
In the hopes that it would ignore the `sql:"-"` tag but that does not appear to be the case and I cannot insert using .Value() with the tag `sql:"-"`. (It's also possible I am misunderstanding how to use value, please let me know)

Is something like this possible without either having to write out the full select query, using `.Returning()`  or using a second structure to cull a single column on select?

**Comment by kramerdust** [comment]
@mfinley3, if it is still relevant. I used Value method with placeholder, like this:  
`_, err = tx.Model(&vars).Value("file_id","?", fileID).Insert()`
