### ISSUE TITLE
defining foreign keys

### ISSUE THREAD

**Issue by jedele** [go-pg/pg#1221]
I am trying to define a foreign key in a table with go-pg.

Based on this https://github.com/go-pg/pg/issues/694,
I am expecting to see FOREIGN_KEY and REFERENCES to be generated by the Create table.

I do not.  Instead I see this:

```
 CREATE TABLE CGroup ("CGUUID" uuid default uuid_generate_v4(), "ConnectionUUID" uuid, "ConnectionManagerID" bigint, "ConnectionManager" jsonb, "rpo" bigint, "snapshotduration" bigint, "state" bigint, "type" bigint, "LastReplicatedSnapshot" uuid, "expiration" timestamptz, PRIMARY KEY ("CGUUID"))
```

My table schema:

```
type CGroup struct {
        tableName struct {} `sql:"CGroup"`
        ConnectionUUID    uuid.UUID `sql:"ConnectionUUID,type:uuid" json:"ConnectionUUID"`
        ConnectionManagerID int `sql:"ConnectionManagerID"
        ConnectionManager   *ConnectionManager `sql:"ConnectionManager" pg:"fk:ConnectionManagerID"`
        ...
}
type ConnectionManager struct {
        tableName struct {} `sql:"ConnectionManager"`
        ConnectionUUID    uuid.UUID `sql:"ConnectionUUID,pk,type:uuid default uuid_generate_v4()" json:"ConnectionUUID"`
         ...
}
```

Should I see a FOREIGN_KEY in the postgresql log when I defined a foreign key
via the pg:"fk" option?
Any idea on what is wrong with my code?

Thank you  for any help you can provide. I've already spent too long trying to get this
to work.  I am new with Go, postgresql, and go-pg.

**Comment by jedele** [comment]
Attaching a better rendering of the table schema mentioned above.
 
[fkq.txt](https://github.com/go-pg/pg/files/3213599/fkq.txt)

**Comment by jedele** [comment]
I do have the FKConstraints: true as an option in the CreateTable operation:

             err = asc.DB.CreateTable(model, &orm.CreateTableOptions {
                                          Temp: false,
                                          FKConstraints: true,
                                      })

**Comment by vmihailenco** [comment]
You break several reasonable assumptions:
- you don't use snake_case naming for SQL columns
- you use `ID` and `UUID` inconsistently
- `ConnectionManagerID` has type int, but ConnectionUUID has type uuid
- overall I don't understand your schema

**Comment by jedele** [comment]
I have removed the sql: tags naming the SQL columns and call CreateTable with the FKConstraints: true
option, but I still do not see FOREIGN_KEY in the CREATE_TABLE operation logged by postgresql.

My table structs:

type CGroup struct {
        tableName struct {} `sql:"CGroup"`
        Cg_uuid    uuid.UUID `sql:",pk,type:uuid" json:"Cg_uuid"`
        Connection_manager_id int
        Connection_manager *Connection_manager `pg:",fk:Connection_manager"`
               ...
}

type Connection_manager struct {
        tableName struct {} `sql:"Connection_manager"`
        Connection_uuid    uuid.UUID `sql:",pk,type:uuid" json:"Connection_uuid"`
               ...



Here is the CREATE_TABLE entries in the postgres log:     
   
               LOG:  statement: CREATE TABLE CGroup ("cg_uuid" uuid, "connection_manager_id" bigint, "connection_manager" jsonb, "rpo" bigint, "snapshot_duration" bigint, "state" bigint, "type" bigint, "Last_replicated_snapshot" uuid, "expiration" timestamptz, PRIMARY KEY ("cg_uuid"))

2019-05-27 01:36:07.008 UTC [60] LOG:  statement: CREATE TABLE Connection_manager ("connection_uuid" uuid, "PrimaryIP" text, "PrimaryPort" bigint, "SecondaryIP" text, "SecondaryPort" bigint, "Status" boolean default false, "state" bigint, PRIMARY KEY ("connection_uuid"))

**Comment by chunariov** [comment]
@jedele Did you find how to define FKs in structs?

**Comment by jedele** [comment]
Not using go-pg.  I switched to another ORM and defined the Foreign Keys with it.
jim


________________________________

**Comment by IvanTopolcic** [comment]
@jedele which ORM did you switch to? 

I've inherited a project using go-pg and I've been struggling to get relations working after switching IDs for UUIDs (seriously, just tell me what I need to type in the tags to get this to work). Considering switching to a different library.

**Comment by jedele** [comment]
We use gorm.  Originally we were concerned that gorm  did not have a lot of adopters.
but the documentation seems to be  good enough and so far have not had any problems.


________________________________

**Comment by chk-n** [comment]
Using manual SQL queries fixes it.. 

For example in a social media app:
```
_, err := db.Model((*models.Followers)(nil)).
              Exec("INSERT INTO followers (user_id, follow_id) VALUES (?,?)", user_id, follow_id)

if err != nil {
	panic(err)
}
return true
```

and the struct

```
type Followers struct {
	Id       int
	UserId   *User `pg:"rel:belongs-to"`
	FollowId *User `pg:"rel:belongs-to"`
}
```

If this issue has been resolved already and works using the go-pg ORM, I would appreciate a heads up :)

**Comment by awsms** [comment]
How does a Postgres ORM fail to have foreign keys in struct tables definitions....
