### ISSUE TITLE
Primary key is not updated on insert.

### ISSUE THREAD

**Issue by recolic** [go-pg/pg#1223]
I have the following code:
```go
type UserInfo struct {
	Id uid_t `sql:",pk,notnull,unique"`
	Name string `sql:",notnull,unique"`
	Password string
}
```

I constructed a UserInfo and insert it. Based on Example in https://godoc.org/github.com/go-pg/pg#Conn.Insert , the `UserInfo.Id` should be updated.

However, UserInfo.Id is not updated. It just crash and saying `duplicate key value violates unique constraint...`

```go
	u := UserInfo{
		Id: -1,
		Name: name,
		Password: password,
	}

	log.Debug("%d", u.Id) // prints -1
	err := db.Insert(&u)
	log.Debug("%d", u.Id) // should print something else
```

**Comment by vmihailenco** [comment]
Remove `,notnull` from `Id` field tags and also remove `Id: -1`.
