### ISSUE TITLE
Embedded (anonymous) struct fields in arrays are always treated as structs

### ISSUE THREAD

**Issue by 3bl3gamer** [go-pg/pg#1237]
For example:
```
type MyInt struct{ int }

type MyStruct struct {
	Ints []MyInt `pg:",array"`
}

var st MyStruct
db.Query(&st, "SELECT ARRAY[1,2,3,4] AS ints")
```

`Query` here panics with `panic: reflect: NumField of non-struct type`.

Looks like it's caused by `func (t *Table) addFields` which tries to `addFields` for every anonymous field.

**Comment by vmihailenco** [comment]
I've fixed the panic but your example still does not work. Your probably want `type MyInt int` or define proper custom SQL type.

**Comment by 3bl3gamer** [comment]
Actual problem was with type from external package which needs some custom serialization logic. I can't add `Scan()` and `Value()` to it directly so there are two options:

1) `type MyType ext.ExternalType`
It works but methods are inaccessible without casts: `ext.ExternalType(myTypeVar).Method()`

2) `type MyType struct { ext.ExternalType }`
It does not work if `ext.ExternalType` is not struct (it was `[32]byte` in my case), though methods could be called without casting.

It also could be solved if go-pg supported custom type registration such as:
```go
func ScanExtType(value, dbValue interface{}) error { ... }
func ValueExtType(value interface{}) error { ... }
db.registerType(ext.ExternalType{}, ScanExtType, ValueExtType)
```

With that feature type-wrapping will not be needed at all, but I have not found such feature in docs.

> define proper custom SQL type

Did you mean `Scan()` and `Value()`?

**Comment by 3bl3gamer** [comment]
> problem was with type from external package which needs some custom serialization logic

I forgot to mention that `type MyInt struct{ int }` has `func (st *MyInt) Scan(val interface{}) error` defined. Nevertheless go-pg tried to inspect it and failed. I thought that type with Scanner interface should not be inspected at all. Or should it?

> I've fixed the panic but your example still does not work.

Now `Scan` is called on `MyInt` correctly and example actually works! So thank you! :-)
