### ISSUE TITLE
Q: How to write data-modifying CTE using With()

### ISSUE THREAD

**Issue by PeterKnego** [go-pg/pg#1242]
**Question**: how to write  a query with data-modifying CTE  using `WrapWith` or `With`? 

E.g. how to write this query with `go-pg`:

```
WITH t AS (
    UPDATE products SET price = price * 1.05
    RETURNING *
)
SELECT * FROM t;
```

**Comment by vmihailenco** [comment]
I've added `WithUpdate` to the master branch - please try.
