### ISSUE TITLE
Allow disabling table alias in update query

### ISSUE THREAD

**Issue by joedursun** [go-pg/pg#1247]
First, thanks for the great PG ORM!

I'm writing an ETL tool for PG <-> PG and PG -> Redshift and everything seems to work except update queries.

Redshift doesn't support aliases in `UPDATE` queries so something like this receives a syntax error:

```SQL
UPDATE user AS u SET "updated_at" = NULL WHERE "u"."id" = '1'
-- ERROR: syntax error at or near "AS"
```

(Redshift also doesn't support the `RETURNING` statement in `INSERT` queries but using `.Returning("NULL")` allows me to bypass that error)

I know Redshift isn't necessarily supported, but can we at least provide a struct tag or something similar to toggle using aliases in `UPDATE` queries?

This seems to be the minimum change required to make the updates work with Redshift: https://github.com/joedursun/pg/commit/87cde86ea94d1be3e1a789e5baad69235277f7b7

**Comment by vmihailenco** [comment]
Please try upgrading to master branch and set table `alias == tableName`, e.g.

```
type Article struct {
    tableName struct{} `sql:"alias:articles"` // alias is the same as autogenerated table name
}
```

For such models go-pg does not add an alias since it is the same as table name. It should hopefully fix Redshift.

**Comment by joedursun** [comment]
Thank you for the quick turn around time!

That worked perfectly for redshift and now `UPDATE`s are working.

It seems now though that on the current `master` branch I can no longer run select queries (even against postgres). For any model that defines something other than an `ID` column a select query fails with the error:

`ERROR #42703 column t.active does not exist`

Where `t.active` is any column that's not ID. The same code was working just yesterday before I pulled the latest master. Here's a minimal example to recreate:

```go
type User struct {
	tableName struct{} `sql:"users,alias:t" pg:"discard_unknown_columns"`

	ID     string  `sql:"id,pk"`
	Active bool    `sql:"active"`
}

users := []User{}
e := db.Model(&users).Where("active = true").Select()
if e != nil {
	fmt.Println(e)
	return
}
```

I get that same error unless I comment out all columns except the `ID` (primary key). It also doesn't matter if I remove/modify the alias in the struct tag.
