### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by taiyangc** [go-pg/pg#1255]
Hello, is it possible to add a new release? Since the last release 2 months ago, there has been many important fixes for us. Due to go modules always preferring explicitly tagged versions over pseudo-versions [[ref]](https://research.swtch.com/vgo-module), it makes projects harder to maintain correct minimal version selection in the case of conflicts.

Thanks for the consideration.

**Comment by tzilist** [comment]
This would be great.

**Comment by vmihailenco** [comment]
I've created `github.com/go-pg/pg/v9` that should be fully compatible with go mod. Note that it is still in beta  though.
