### ISSUE TITLE
Batch updates with WHERE clause

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1257]
When doing batch update, is there a way to specify `WHERE` clause?

Example:

```go
// Session holds session data
type Session struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt time.Time
	Data      *SessionDetails
}

var sessions []Session
for i := 1; i <= 5; i++ {
	sessions = append(sessions, Sesssion{UserID: i, Data: nil})
}

db.Model(&sessions).Where("user_id = ?", "").Column("Data").Update()
```

I want to update all Sessions where `user_id` is the one provided in sessions struct.

**Comment by taiyangc** [comment]
I've had success with something like

`db.Model(&sessions).Where("sessions.user_id = _data.user_id").Column("data").Update()`

Replace `sessions` with your actual table name or alias if it doesn't work.

**Comment by vmihailenco** [comment]
What @taiyangc said - look at generated query and write where based on that.
