### ISSUE TITLE
UpdateNotNull doesn't return the full object

### ISSUE THREAD

**Issue by Daavidaviid** [go-pg/pg#1260]
Hi,
Using this library I realized that when using UpdateNotNull with a pointer to a struct it doesn't return the whole object some fields are missing.

Is it the expected behaviour ?

**Comment by vmihailenco** [comment]
Yes, it. Add `Returning("*")` if you need those fields.

**Comment by Daavidaviid** [comment]
Perfectly what I needed, thanks.
