### ISSUE TITLE
AfterUpdate() access RowsAffected()

### ISSUE THREAD

**Issue by theromis** [go-pg/pg#1264]
I'm doing conditional notification in `AfterUpdate` stage, unfortunately I can't reach Update result from this callback.
Is it possible to access it or add this feature in future releases?

**Comment by vmihailenco** [comment]
AfterUpdate is called for each row in the query - I don't think Result makes sense there.

**Comment by theromis** [comment]
May be I'm doing something wrong, but it called on a row which was not matched in update. My situation: I'm calling update on existing message where limiting it by user to not let people modify messages not belonging to them, but it triggers AfterUpdate on every row, doesn't matter matches update conditions or not.

**Comment by vmihailenco** [comment]
The hook is called for a Go struct or all structs in a slice - it does not matter which rows were matched in PostgreSQL. Probably you want to add `Returning("*")` to your update query.
