### ISSUE TITLE
How do I get what the raw SQL query string would look like without actually running a query?

### ISSUE THREAD

**Issue by qiushihe** [go-pg/pg#1266]
Consider this query:

```
user := &User{ID: 42}
q := db.Model(user).WherePK()
```

How can I get what the raw SQL query string would be without actually running the `q.Select()`?

And reason I'm asking for this is NOT to log it. I don't want to just log the query. I want to do:

```
user := &User{ID: 42}
q := db.Model(user).WherePK()

rawSQLString := q.GetGeneratedSQLString()
... // and then do something with this `rawSQLString` that's NOT logging it.
```

Is this possible with this library?

**Comment by vmihailenco** [comment]
You can look at https://github.com/go-pg/pg/blob/master/orm/query.go#L1180-L1182 and https://github.com/go-pg/pg/blob/master/hook.go#L37-L53, but this is not something that lib officially supports.
