### ISSUE TITLE
Storing time without date

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1267]
Is there an option for storing time as Time, and not timestamptz?

**Comment by ribice** [comment]
I did manage to do this using [civil.Time](https://godoc.org/cloud.google.com/go/civil) and setting `sql:"type:date"`

It correctly inserts data into database.

But when retrieving data, it returns:

`json: cannot unmarshal number into type civil.Time` (something like that).

I assume I need to implement Scanner/Value interface?

If yes, is there an example how to do it for custom types?

**Comment by vmihailenco** [comment]
I've added an example that should give you an idea how to implement custom type - https://godoc.org/github.com/go-pg/pg#example-DB-Model-CustomType. That example uses custom go-pg interfaces, but standard sql.Scanner and driver.Valuer should work too.
