### ISSUE TITLE
UpdatedAt with Column() method doesn't get updated

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1268]
I'm using this query:

```go
_, err = db.DB.Model(&actualPlayer).Column("status").WherePK().Update()
```

and in my model `player.go` I have also:

```go
...
UpdatedAt         time.Time
...
```

Why the column `updated_at` doesn't get updated?

I think it should, right?

**Comment by vmihailenco** [comment]
If you suggest that go-pg should automatically set UpdatedAt column then no - it does not do that.

**Comment by frederikhors** [comment]
Can I ask you why? Just for `Column()` method?

**Comment by frederikhors** [comment]
> If you suggest that go-pg should automatically set UpdatedAt column then no - it does not do that.

I thought it was like Rails ActiveRecord. Isn't it?

**Comment by ernsheong** [comment]
> I thought it was like Rails ActiveRecord. Isn't it?

It isn't quite like ActiveRecord. You can instead use https://github.com/go-pg/pg/wiki/Model-Hooks to update `UpdatedAt` in a `BeforeUpdate` hook

**Comment by frederikhors** [comment]
@ernsheong thanks man.

**Comment by vmihailenco** [comment]
My advise would be to just use SQL - it is explicit, fast and concise:

```pg
db.Model(...).Set("update_at = now()").Update()

// or

item.UpdatedAt = time.Now()
db.Model(item),Column("updated_at").Update()
```

Using hooks does not buy you anything except making code harder to read and debug.
