### ISSUE TITLE
cannot use &opt (value of type *orm.CreateTableOptions) as *invalid type value in argument to db.CreateTableLSP

### ISSUE THREAD

**Issue by FlowerWrong** [go-pg/pg#1273]
Hello, I am using v9 api.

```golang
opt := orm.CreateTableOptions{
			Varchar:       255,
			Temp:          true,
			IfNotExists:   true,
			FKConstraints: true,
}
err := db.CreateTable(model, &opt)
if err != nil {
        return err
}
```

**Comment by vmihailenco** [comment]
Make sure to import v9 orm e.g. `github.com/go-pg/pg/v9/orm`. Other please provide an example that reproduces the problem.

**Comment by leoalekseyev** [comment]
I can confirm that importing `github.com/go-pg/pg/v9/orm` triggers this error. The solution for me was to change the import statement to `github.com/go-pg/pg/orm`. Perhaps this should be documented.
