### ISSUE TITLE
Consider changing wiki permissions

### ISSUE THREAD

**Issue by tbarbugli** [go-pg/pg#1274]
I just realized I was able to change the wiki docs of the project (I was expecting this to trigger the usual PR but instead a [revision](https://github.com/go-pg/pg/wiki/Model-Hooks/2ded0f1565c9ce105b2ce4e86a0c542924c46651) was added directly). 

Perhaps not a bad idea to revoke public write access to wiki? https://help.github.com/en/articles/changing-access-permissions-for-wikis

**Comment by vmihailenco** [comment]
It has been open from the very start and there were no incidents so far. Also reverting malicious change if there are any is easy. So I think we are fine.
