### ISSUE TITLE
FLOAT4 Columns are rounded to 5 decimal places during query

### ISSUE THREAD

**Issue by JesseCorrington** [go-pg/pg#1277]
I'm seeing FLOAT4/REAL columns being rounded to 5 decimal places during a query. The insert doesn't do the rounding, as I can open up the table in a postgres viewer (the goland integrated one), and the number appears with the correct number of decimal places, exactly as I inserted it.

Here's some sample code to reproduce the issue. The output printed will be 1.23457, but if you open up the table in a database viewer, you'll see the value inserted is actually 1.23456789.

```
type TestModel struct {
	Col1 float32
}

db.CreateTable(&TestModel{}, &orm.CreateTableOptions{})
db.Insert(&TestModel{1.23456789})
test := &TestModel{}
db.QueryOne(test, "select * from test_model")
fmt.Println(test.Col1)
```

If I change it to `Col1 float64` the rounding does not happen.

**Comment by vmihailenco** [comment]
My tests show that number is actually inserted as `1.23457`:

```
postgres=# INSERT INTO "test_models" ("col1") VALUES (1.2345678806304932);
INSERT 0 1
postgres=# select * from test_models;
  col1   
---------
 1.23457
(1 row)
```

Probably it is just PostgreSQL specific rounding.
