### ISSUE TITLE
Best way to handle NULL uuid types

### ISSUE THREAD

**Issue by mdere-unbound** [go-pg/pg#1285]
Any tips on how I should handle NULLABLE UUID types? Here is the reference to the UUID since I am using string, go-pg isn't identifying empty string as NULL. Do I need to configure something in my struct for that field?

ERROR #22P02 invalid input syntax for type uuid: ""

Thanks

**Comment by vmihailenco** [comment]
Please create a reproducer. Perhaps you need sql:",nopk" if column name is id or uuid and go-pg think it is a primary key.
