### ISSUE TITLE
Attempting to create trigger, desire elegant interpolation of parameter into trigger name

### ISSUE THREAD

**Issue by alecmroo** [go-pg/pg#1287]
Hi All; I'm learning go-pg, loving it, but have this edge case: I am trying to add a trigger on a model table, such that it implements a `last_modified` / `modified_at` automatic update of a timestamp, as described here:

https://www.revsys.com/tidbits/automatically-updating-a-timestamp-column-in-postgresql/

And I have tried something like:

```
var mtimeFunction = `
CREATE OR REPLACE FUNCTION bump_mtime()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modified_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';
`

var mtimeTrigger = `
CREATE TRIGGER ?TriggerName BEFORE UPDATE ON ?TableName
FOR EACH ROW EXECUTE PROCEDURE bump_mtime();
`
...<write the function>...
        _, err := pgdb.Exec(mtimeFunction)
...<iterating over several models, goes here>...
                foo = "something_distinct_per_table_from_sprintf"
                _, err = pgdb.
                        WithParam("TriggerName", foo).
                        Model(model).
                        Exec(mtimeTrigger)
...
```

Put very simply, the resulting SQL crashes because `'something_from_sprintf'` in the resulting SQL is wrapped in single quotes, which is a syntax error in this context.  If I rework the code to use double-quotes and `Sprintf()` then it works just fine.

So, my question is: is there a version of `WithParam()` which will generate a dquot, rather than an squot, string?

Or perhaps a mechanism for addressing the same kind of non-parameter string interpolation -  for instance some kind of template like `CREATE TRIGGER trigger_for_?{TableName} ...` which would permit this kind of magic string interpolation without implicit quoting, please?

Thanks!

**Comment by vmihailenco** [comment]
Please try `WithParam("TriggerName", pg.F(foo))`, but TBH this is looks a bit too complicated to create a trigger...
