### ISSUE TITLE
RunInTransaction should be part of the orm.DB interface

### ISSUE THREAD

**Issue by ericgorlin** [go-pg/pg#1289]
Both *pg.Tx and *pg.Db have access to this function, but it's not in their shared interface.
I'm using this as a workaround:

```	
var err error
switch txOrDB := db.(type) {
case *pg.Tx:
	err = txOrDB.RunInTransaction(f)
case *pg.DB:
	err = txOrDB.RunInTransaction(f)
}
if err != nil {
	return nil, err
}
```

**Comment by vmihailenco** [comment]
RunInTransaction refers to `pg.Tx` which can't be accessed in orm package because of the circular dependency. Perhaps go-pg should have separate interface like `pg.DBer`.

**Comment by ericgorlin** [comment]
I'm guessing there's a good reason, but why does orm.DB need to live in `orm` rather than `pg`?

**Comment by ericgorlin** [comment]
And why do we need separate `orm` and `pg` packages if they're going to cause circular dependencies like this?
