### ISSUE TITLE
Table Mapping Error

### ISSUE THREAD

**Issue by l0gicgate** [go-pg/pg#1293]
So I'm not sure if I'm doing something wrong or not, I was trying to look in the docs for documentation on this but I can't seem to find anything about field name length for tables.

As per the following struct, when using `db.CreateTable(model)` the field `OSID` (see struct below) which should be mapped as `os_id` but for some reason doesn't detect the relationship and maps it as `osid`. I even tried using `sql:"os_id"` but no luck. Renaming the field to `OpSysID` and everything works fine. I also tried renaming the field to `OsID` but no dice.

**This is the problematic struct**
```go
type Device struct {
    ID              uint64
    Brand           string          `json:"brand"`
    Manufacturer    string          `json:"manufacturer"`
    DisplayID       uint64          `json:"-"`
    Display         *DeviceDisplay  `json:"display"`
    OSID            uint64          `json:"-"` // using `sql:"os_id"` does not work here
    OS              *DeviceOS       `json:"os"`
}
```

**This struct with the renamed property works just fine**
```go
type Device struct {
    ID              uint64
    Brand           string          `json:"brand"`
    Manufacturer    string          `json:"manufacturer"`
    DisplayID       uint64          `json:"-"`
    Display         *DeviceDisplay  `json:"display"`
    OpSysID         uint64          `json:"-"`
    OpSys           *DeviceOS       `json:"os"`
}
```

All of the other fields get mapped and stored properly when using `db.Insert()`

**Comment by vmihailenco** [comment]
Try `OSID            uint64          `json:"-" sql:"os_id"`.

**Comment by l0gicgate** [comment]
That does not fix the problem @vmihailenco. As I said, I’ve tried that already. The only thing that fixes the issue is renaming the field to another longer name. Is the a minimum length for the field name?

**Comment by vmihailenco** [comment]
Please post a minimal example with reproduces the problem and uses `sql:"os_id"`.
