### ISSUE TITLE
Default column name inflection

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1296]
Since there is an option in ORM package to set table name inflection, can we get the same for column names?

e.g. I need column names to be camelCase instead of snakeCase. Now I'm doing this manually for every field with more than one word.

**Comment by vmihailenco** [comment]
Such flexibility comes at a cost I am not willing to pay. And https://github.com/go-pg/pg/issues/1298 suggests that you don't fully understand the consequences.

So the answer is not until there is a compelling reason. The compeling reason for table name inflection is that it allows to globally add a prefix for all your table names while keeping aliases unchanged.
