### ISSUE TITLE
How do I select from a View

### ISSUE THREAD

**Issue by atedja** [go-pg/pg#1297]
A model `User` is using the `users` table, but if I have a view `approved_users`, with the same schema. Without creating an identical but separate struct, how do I run a query against the `approved_users` view using the same `User` struct?

If I understand correctly, this will change all the select queries of that struct to use the View.

    tableName struct{} `sql:"select:view_name"`

I do not want to do that.

**Comment by vmihailenco** [comment]
This should work

```
type ApprovedUser struct {
    User
}
```

If it does not - please create a program that reproduces the problem.
