### ISSUE TITLE
Exec changes query casing

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1298]
Given the following table:

```
CREATE TABLE "role2user" (
    "id" int8 NOT NULL DEFAULT nextval('role2user_id_seq'::regclass),
    "userId" int8,
    "roleId" int8,
    PRIMARY KEY ("id")
);
```

The following fails to execute:
```
_, err := tx.Exec("INSERT INTO role2user (userId, roleId) VALUES (?, ?)", 1, 100)
```

The reason being is (I assume) that `userId` and `roleId` are converted into `userid` and `roleid` from what I can see in the logs:

```
2019/07/16 21:52:00 INSERT INTO role2user (userId, roleId) VALUES (9, 1000)%!(EXTRA <nil>)
2019/07/16 21:52:01 ROLLBACK%!(EXTRA <nil>)
2019/07/16 21:52:01 ERROR #42703 column "userid" of relation "role2user" does not exist
```

As soon as I updated role2user table to have `userid` and `roleid` column names it executed without error.

**Comment by vmihailenco** [comment]
This is PostgreSQL behavior. Use lower_case_with_underscores convention and/or read PostgreSQL docs.
