### ISSUE TITLE
foreach to stop in the first match

### ISSUE THREAD

**Issue by suren4Kites** [go-pg/pg#1301]
Hi,

I want to go through all rows with some where conditions, and run a function. Inside the function if some condition satisfies then should stop for each and return. It is like Limit 1.
Please let me know how can I achive this.

**Comment by suren4Kites** [comment]
insimple, How to stop foreach?

**Comment by vmihailenco** [comment]
There is no way to stop it now. Probably func should be changed to return bool and iteration should be stopped when false is returned.

**Comment by suren4Kites** [comment]
that works for me, are you planning to add this?

**Comment by vmihailenco** [comment]
I am not sure. The only thing go-pg can do is just close the incoming connection and hope that is better then reading all results. I guess it will be faster but I'd say this is not a behavior on which you should rely. I.e. this should not be a critical part of the contract.

**Comment by vmihailenco** [comment]
And ForEach signature will not be changed - go-pg will either stop iteration on error or it will not. Stopping looks like a safer / more conservative choice but it is backwards incompatible.

**Comment by suren4Kites** [comment]
Ok, the second approach seems good, stop iteration on error.


> I am not sure. The only thing go-pg can do is just close the connection and hope that is better then reading all results. I guess it will be faster but I'd say this is not a behavior on which you should rely. I.e. this should not be a critical part of the contract.

How do I close the connection?

**Comment by vmihailenco** [comment]
Closing since it is a tricky corner case and I don't know how to improve it.
