### ISSUE TITLE
Selecting rows searched by contents of JSON column

### ISSUE THREAD

**Issue by nghtstr** [go-pg/pg#1302]
So, here is what I am trying to do. I have a table that has a JSONB column in it. I can do the following SQL by hand, using fmt.Sprintf, and it works:

`SELECT * FROM activity WHERE "thread" @> '[{"id":"%s"}]'::JSONB`

Now, this is obviously not the most secure way of doing things. I have read the documentation over and over, and I cannot find a way to do an ORM Select using go-pg. The best I have gotten so far, and it doesn't work:

`db.Model(&a).Where(`"thread" @> '[{"id":"?"}]'::JSONB`, messageID).Select()`

It generates the following SQL (I have hidden the real table names and fields):

```sql
SELECT "activity".* FROM activity WHERE ("thread" @> '[{"id":"'48bcef44-db89-47c8-a5dc-b7f3ce6b5b78'"}]'::JSONB)
```

Any help would be greatly appreciated!!

**Comment by vmihailenco** [comment]
I think it should be:

```go
b. _ := json.Marshal(messageID)
db.Model(&a).Where("thread" @> '[{"id":?}]'::JSONB, types.Q(messageID)).Select()
```

**Comment by nghtstr** [comment]
This worked great! Just two things:

1) It is the following:
```go
err := db.Model(&a).Where(`"thread" @> '[{"id":"?"}]'::JSONB`, types.Q(messageID)).Select()
```

2) This definitely needs to be added into the documentation. With Postgres's increased power within JSON structs, this will be used more times than I care to count!
