### ISSUE TITLE
Empty Struct is Not NULL ?

### ISSUE THREAD

**Issue by awcodify** [go-pg/pg#1304]
I have struct like:

```go
type Something struct {
  ID                 string
  Name           string `sql:",notnull"`
  Description string 
}
```

Then I create a record 

```go
something := Something{
  Description: "Hello"
}

db.Insert(&something)
```

Based on this documentation: https://github.com/go-pg/pg/wiki/Model-Definition
It should be Something.Name should be NULL, but it becomes EMPTY and being inserted to db.

Am i doing something wrong?

**Comment by vmihailenco** [comment]
Remove `sql:",notnull"` - it is used so go-pg inserts empty strings, 0 etc.

**Comment by awcodify** [comment]
So how to give validation to not allow null ?

**Comment by vmihailenco** [comment]
I guess we should change `sql:",notnull"` to only mean SQL `NOT NULL` constraint. Then `pg:",nullzero"` can be used to cause go-pg to convert 0 and empty string to SQL `NULL`. That is backwards uncompatible but seems to be a right change in long term.
