### ISSUE TITLE
Question: updating only non null values. #655

### ISSUE THREAD

**Issue by lubaoyilang** [go-pg/pg#1306]
Suppose, we have a struct:

type PGBaseTable struct {
	Version	int32 `sql:",notnull"`
	CreatedAt time.Time `sql:",notnull"`
	UpdatedAt time.Time `sql:",notnull"`
	IsDeleted int8     `sql:",notnull"`
	DeletedAt time.Time `pg:",soft_delete"`

}

type UserAccount struct {
	UserId        int64 `sql:",unique,notnull"`
	BalanceCount  int64 `sql:",notnull"` 
	MoneyBuyCount int64 `sql:",notnull"` 
	PGBaseTable
}

Now, I want to update the BalanceCount and the MoneyBuyCount only if they are not null values.

If I do the following:

  db.Model(&UserAccount{BalanceCount: 222, MoneyBuyCount: 333}).UpdateNotNull() 
  sets UserId to 0  、time To zeroTime
   

why?

**Comment by lubaoyilang** [comment]
UpdateNotZero

When will it be updated?

**Comment by vmihailenco** [comment]
It is merged - please try.
