### ISSUE TITLE
i update V9 ,but hook  not work

### ISSUE THREAD

**Issue by lubaoyilang** [go-pg/pg#1308]
type PGBaseTable struct {
	CreatedAt time.Time `sql:",notnull"`
	UpdatedAt time.Time `sql:",notnull"`
	IsDeleted int8     `sql:",notnull"`
	DeletedAt time.Time `pg:",soft_delete"`
}
func (m *PGBaseTable) BeforeInsert(c context.Context, db orm.DB) (context.Context, error) {
	now := time.Now()
	m.CreatedAt = now
	m.UpdatedAt = now
	m.IsDeleted = 0
	return c,nil
}
type UserAccount struct {
	PGBaseIdTable
	UserId        int64 `sql:",unique,notnull,default:_"`
	BalanceCount  int64 `sql:",notnull"`
	MoneyBuyCount int64 `sql:",notnull"` 
	Version	int32 `sql:",notnull"`
	PGBaseTable
}

func (m *UserAccount) BeforeInsert(c context.Context, db orm.DB) (context.Context, error) {
	m.Version = 1
	return m.PGBaseTable.BeforeInsert(c,db)
}

hook fun is not work

**Comment by vmihailenco** [comment]
- Please learn how to format the code you post.
- See https://github.com/go-pg/pg/wiki/Model-Hooks for hook signature
- Make sure to use `var _ orm.BeforeInsertHook = (*Book)(nil)` so compiler can help you.
