### ISSUE TITLE
CopyTo error bufio: buffer full

### ISSUE THREAD

**Issue by shahrukh330** [go-pg/pg#1311]
I have a table with text columns containing very long json strings which i am trying to export to csv using CopyTo. But i get `bufio: buffer full`. My table structure is along the lines of 

```
   id bigint NOT NULL,
   some_field1 text,
   some_field2 character varying,
   some_field3 character varying,
   some_field4 character varying,
   some_field5 character varying,
   some_field6 text, 
```
I have tried the following in code, and both cases fail with same error.
```
file:= os.Create('/tmp/file.csv')
command := fmt.Sprintf("copy (select * from table) to stdout with csv")
_, err = db.CopyTo(file, command)

command := fmt.Sprintf("copy (select * from table) to stdout with csv")
_, err = db.CopyTo(os.Stdout, command)
```

I have diged down issue to the following line https://github.com/go-pg/pg/blob/0e50cb780a0792bc48fab1e5937f3e321a455809/internal/buf_reader.go#L13 increasing buffer size seems to fix the issue. Is there a way to handle very long text fields in without having to change this library. Is there something which i am doing wrong?

**Comment by vmihailenco** [comment]
It is likely a problem with go-pg. Please try to create small program that reproduces the problem - it will help a lot.

**Comment by shahrukh330** [comment]
@vmihailenco Thanks for your response. I have attached a small program for your reference. You will need following env variables to run this 
```
DB_USER:
DB_PWD
DB_NAME
DB_HOST
DB_PORT
```
Also I have included `create_table.sql` which creates a table with sample structure and fills it up with dummy data which causes `bufio: buffer full` error.

[export_table.zip](https://github.com/go-pg/pg/files/3436796/export_table.zip)

**Comment by vmihailenco** [comment]
Thanks for the reproducer - it should be fixed in master branch.

**Comment by shahrukh330** [comment]
Thanks @vmihailenco, Is it possible to have it merged in release?

**Comment by vmihailenco** [comment]
Sorry, but I don't resources to backport bugfixes. This fix is small so you can try to backport it yourself and send a PR against v8 branch.

**Comment by shahrukh330** [comment]
I have opened a PR, https://github.com/go-pg/pg/pull/1316. Could you create a new release tag once it is merged ?

**Comment by vmihailenco** [comment]
Tagged v8.0.5
