### ISSUE TITLE
Relation restuls in column does not exist

### ISSUE THREAD

**Issue by Slals** [go-pg/pg#1312]
Hello,

I have an issue I'm not able to solve. go-pg tries to query a Relation as a column when it should be a JOIN. I read in other issues that this case happens when go-pg doesnt find the related relation, here is the simplified code :

```go
struct A {
  ID int64
  
  B *B
  BID int64
}

struct B {
  ID int64

  C *C `pg:,joinFK:"c_name"`
  CID string `sql:"c_name"`
}

struct C {
  ID string `sql:"name"`
}

// The query
As := make([]A, 0)
db.Conn.Model(&As).Relation("B").Relation("B.C").Select()
```

The error is : `ERROR #42703 column b.C does not exist`

I'm pretty sure it has to do with the fields name of C which is not 'id' but 'name'.

Thanks a lot

**Comment by vmihailenco** [comment]
You mark `ID` as primary key:

```go
type C struct {
	ID string `sql:"name,pk"`
}
```

That is needed because you've changed SQL name.
