### ISSUE TITLE
Problem installing with `go get github.com/go-pg/pg/v9`

### ISSUE THREAD

**Issue by JakubKoralewski** [go-pg/pg#1319]
This command works for me though: `go get github.com/go-pg/pg`.

If the above is correct and the one in the title is wrong, then the README is wrong.

```
go version go1.12.7 windows/amd64
```

**Comment by vmihailenco** [comment]
You need to initialize a Go module before installing go-pg: `go mod init`. See https://github.com/golang/go/wiki/Modules#quick-start for more details.
