### ISSUE TITLE
Update with returning does not update the scan value provided.

### ISSUE THREAD

**Issue by elliotcourant** [go-pg/pg#1330]
I'm seeing an issue where the values from a returning clause are not making their way back into the object I pass to the scan of an update.

```go
func Test_UpdateSlice(t *testing.T) {
	db := modelDB()

	book := &[]*Book{
		{Id: 1, Title: "updated book 1"},
	}

	_, err := db.Model(book).Returning("*").UpdateNotZero(book)
	if err != nil {
		panic(err)
	}
}

func Test_UpdateSingle(t *testing.T) {
	db := modelDB()

	book := &Book{Id: 1, Title: "updated book 1"}

	_, err := db.Model(book).Returning("*").WherePK().UpdateNotZero(book)
	if err != nil {
		panic(err)
	}
}
```

The two tests above illustrate this and can be run from within the go-pg/pg code base directly.

The first test tries to update using a slice of books. (in this case just one book though) and if you place breakpoints before and after the update is performed, you will be able to see that the UpdateNotZero function did not update the slice or its contents at all.

But the same test run on a single object does, and the contents of the book variable will change after the update has been performed.

If you were to perform this same test with an insert the value is updated regardless of the scan value being a slice or a single variable. 

I'm having trouble finding what separates the two operations, and why specifically when updating slices it doesn't update the value in the end? But on inserts it works perfectly?

Do you have any suggestions?

**Comment by elliotcourant** [comment]
This is the query issued to PostgreSQL when updating a single value:

```sql
UPDATE "books" AS "book"
SET "title" = 'updated book 1'
WHERE "book"."id" = 1 RETURNING *;
```

This is the query issued to PostgreSQL when updating via the slice:

```sql

UPDATE "books" AS "book"
SET "title"      = COALESCE(_data."title", "book"."title"),
    "author_id"  = COALESCE(_data."author_id", "book"."author_id"),
    "editor_id"  = COALESCE(_data."editor_id", "book"."editor_id"),
    "created_at" = COALESCE(_data."created_at", "book"."created_at"),
    "updated_at" = COALESCE(_data."updated_at", "book"."updated_at")
FROM (VALUES (1::BIGINT, 'updated book 1'::text, NULL::bigint, NULL::bigint, NULL::timestamptz,
              NULL::timestamptz)) AS _data("id", "title", "author_id", "editor_id", "created_at", "updated_at")
WHERE "book"."id" IN (1) RETURNING *
```

As a side note these tests were performed on my branch for my newest additions from #1329

**Comment by vmihailenco** [comment]
Is this issue fixed by https://github.com/go-pg/pg/pull/1329 or requries more attention?

**Comment by elliotcourant** [comment]
I believe it does still require more attention. But I can write a test that you can run in a branch to make it easier to work with when it comes to reproducing the problem.

**Comment by vmihailenco** [comment]
It looks like you need to use `Returning("book.*")` when updating a slice, because `Returning("*")` return data from `book` and `_data` tables. The result looks like this:

```
postgres=# UPDATE "books" AS "book" SET "title" = COALESCE(_data."title", "book"."title"), "author_id" = COALESCE(_data."author_id", "book"."author_id"), "editor_id" = COALESCE(_data."editor_id", "book"."editor_id"), "created_at" = COALESCE(_data."created_at", "book"."created_at"), "updated_at" = COALESCE(_data."updated_at", "book"."updated_at") FROM (VALUES (100::bigint, 'updated book 100'::text, NULL::bigint, NULL::bigint, NULL::timestamptz, NULL::timestamptz)) AS _data("id", "title", "author_id", "editor_id", "created_at", "updated_at") WHERE "book"."id" = _data."id" RETURNING *;
 id  |      title       | author_id | editor_id |          created_at           | updated_at | id  |      title       | author_id | editor_id | created_at | updated_at 
-----+------------------+-----------+-----------+-------------------------------+------------+-----+------------------+-----------+-----------+------------+------------
 100 | updated book 100 |        10 |        11 | 2019-08-13 11:01:44.567676+03 |            | 100 | updated book 100 |           |           |            | 

```

**Comment by elliotcourant** [comment]
Would it make sense to preface the * in the returning clause of the generated query with the table alias of the table being updated? But only when doing a batch update? 

This way it should only return the correct columns, but also will only fix the behavior where it seems to not be working. When doing single record updates it works perfectly because there is no "second table" in the query that could also be returned.

What are your thoughts?

**Comment by vmihailenco** [comment]
As as user you've specified `*` and I think go-pg should not change that no matter what. Because who knows - perhaps there is a situation where it is desired.

But if go-pg generates `RETURNING *` then we could consider changing it to something more specific.

**Comment by vmihailenco** [comment]
Closing - I think it is working as expected.
