### ISSUE TITLE
Doc Error: hasMany example returns nil pointer dereference

### ISSUE THREAD

**Issue by sgon00** [go-pg/pg#1332]
Hi, I am trying this example https://github.com/go-pg/pg/wiki/Writing-Queries#has-many

It returns an error message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x11bd741]
```

The code which causes the error:

```go
	err := db.Model(&user).
		Column("user.*", "Profiles").
		Relation("Profiles", func(q *orm.Query) (*orm.Query, error) {
			return q.Where("active IS TRUE"), nil
		}).
		First()
```

The problem is `db.Model(&user)` should be `db.Model(user)`.

**Comment by vmihailenco** [comment]
That example is available as `go test -run=ExampleDB_Model_hasMany`. The problem is that in v9 you have to write `Column("user.*").Relation("Profiles")` - this is more reliable and returns an error when relation `Profiles` does not exist.

**Comment by sgon00** [comment]
@vmihailenco hi, Thanks a lot for the quick reply.
Maybe you checked the email content instead of reading the github page. I have updated the issue description before your post. The null pointer exception is actually caused by `db.Model(&user)`. It should be `db.Model(user)` because of `user := new(User)` in the wiki. 

Btw, how can I do this in one JOIN query in go-pg? This should be doable in one query instead of two. I do care performance a lot. Thank you very much.

**Comment by vmihailenco** [comment]
Thanks - I've updated the wiki. BTW it is publicly editable so don't hesitate to make changes if you find such bugs.

>Btw, how can I do this in one JOIN query in go-pg?

go-pg does not support this. It is probably doable but requires quite some shenanigans in Go code and SQL. And if you really care about performance - don't use joins :)

**Comment by sgon00** [comment]
Thanks for the advice. I thought JOIN was always better. I am not a true DBA. When I read this article https://thoughtbot.com/blog/postgresql-performance-considerations especially the two sections `Use more joins` and `Prefer INNER JOINs`, I thought joins were always faster than multiple select queries. Well, I haven't done any tests yet. So I don't know if it's true or not. Thanks again for your reply and valuable time.

**Comment by vmihailenco** [comment]
You can start from https://stackoverflow.com/questions/2623852/why-are-joins-bad-when-considering-scalability. But if joins are fast enough - don't bother. If left join is fast enough - don't bother with inner join.
