### ISSUE TITLE
Custom scanner and writer for a column

### ISSUE THREAD

**Issue by j0hnwhyte** [go-pg/pg#1333]
I'm trying to implement a model that uses `time.Duration` as the type for a field, but stores for convenience whole seconds in the database instead of nanoseconds. I figure the best way would be to have my own implementation of `time.Duration` or to extend it with some kind of custom scanner.

I found no documentation about this, and I'm actually wondering if it's possible at all to implement a custom writer / scanner for a user-defined type.

Again, the goal is to convert in both ways the data read and written to the database, while maintaining a specific type for the field.

Thanks

**Comment by vmihailenco** [comment]
See https://godoc.org/github.com/go-pg/pg#example-DB-Model-CustomType for an example and ask questions if you have any.

**Comment by j0hnwhyte** [comment]
That's exactly what I was looking for. The example has to be updated, but it's more than clear.
