### ISSUE TITLE
Question: Why ginkgo?

### ISSUE THREAD

**Issue by elliotcourant** [go-pg/pg#1337]
@vmihailenco This is not an issue; just a question out of curiosity.

Why ginkgo for a testing framework? What didn't you like about the normal go testing format? Or what does ginkgo offer that makes it a preferable alternative?

Also do you use any IDE tools to run ginkgo tests individually? When working on pg I find myself writing a normal go test so that I can run it easily from vim or goland using the built in tools; and only after I get it working the way I want it to do I write a ginkgo test and then run that. 

Do you have a tool or a shortcut to run tests individually easily from the development environment? Or do you just use the command line tools that ginkgo offers?

**Comment by vmihailenco** [comment]
You can use `FIt` or `FDescribe` to Focus / execute only particular test. `go test -ginkgo.f="regular expression goes here"` can be used to select test from command line.

>Or what does ginkgo offer that makes it a preferable alternative?

It helps to better structure tests and provides meaningful error message by default. I like it.
