### ISSUE TITLE
[Document] orm.Pagination Pagination not declared

### ISSUE THREAD

**Issue by sgon00** [go-pg/pg#1339]
Hi, when using https://github.com/go-pg/pg/wiki/Writing-Queries#pagination example, I found out orm.Pagination is gone. By checking the README.md, I figure out I think I should use https://godoc.org/github.com/go-pg/pg/urlvalues#NewPager instead. 

(1) The doc should be updated. 
(2) Can I have an example how to use this new Pagination way to do `?page=2&limit=50`? The old way looks pretty simple. I feel I have to create a Filter struct now. 

Thanks a lot.

**Comment by sgon00** [comment]
Anyway, I think I will simply use LIMIT and OFFSET then such as `query.Order("created_at").Limit(limit).Offset(offset).Select();`

**Comment by vmihailenco** [comment]
It is called `urlfilter.Pager` these days. I've updated the wiki.
