### ISSUE TITLE
How to get inserted auto_incremented value?

### ISSUE THREAD

**Issue by zengfenfei** [go-pg/pg#134]
The table:
```sql
create table users (
id bigserial primary key,
name varchar(512) not null)
```
I insert a user using:
```go
type User struct {
	Id       int64
	Name     string
}

var db pg.DB
var u User
db.Create(&u)
```

So how can I get the **auto_incremented** id?

**Comment by vmihailenco** [comment]
It should be automatically set in `u.Id`. Do you observe different behaviour?

Behide the scene go-pg will issue `INSERT ... RETURNING id` query and scan returned value into `User.id`.

**Comment by zengfenfei** [comment]
I check the Id of user, it's 0, but the Id in the database is not.

**Comment by zengfenfei** [comment]
The sql go-pg generated is: `INSERT INTO "users" ("name", "password") VALUES ('from Termial', '')`

**Comment by zengfenfei** [comment]
I find the problem: It's the `sql:"-"` tag after the id field.
