### ISSUE TITLE
Add orm.Query to model hooks to support user-public and internal-only data.

### ISSUE THREAD

**Issue by zanerock** [go-pg/pg#1345]
Here's the use case:

1) I have a base `Entity` type that includes internal and public IDs. Only public IDs are sent over the wire (JSON).
2) An `Entity` can be owned, by another `Entity`, so the `Entity` struct defines 'OwnerID` and `OwnerPubID`.
3) So, the struct defines fields that are present in the JSON, but no the DB table, and vice-versa.

Solving the 'SELECT' case is easy enough using views, but for 'INSERT' and 'UPDATE' ops, what I really would like (I think) is access to the query in the model hooks. For example:

```sql
CREATE TABLE entity (
  id BIGSERIAL,
  pub_id UUID NOT NULL DEFAULT uuid_generate_v4(),
  owner BIGINT
);
```

```go
type Entity struct {
  tableName struct{} `sql:"entities,alias:entity,select:entities_owner_pub_id"`
  ID int64 `json:"-"`
  PubID string `json:"pubId"`
  OwnerID int64 `json:"-"`
  OwnerPubID `json:"ownerPubId"
}

var _ orm.BeforeInsertHook = (*Entity)(nil)

func (e *Entity) BeforeInsertHook(ctx context.Context, q *orm.Query) (context.Context, *orm.Query, error) {
   q.ExcludeColumn(`owner_pub_id`)
    // handle case of external request from user, which will have OwnerPubID, but not OwnerID
    if e.OwnerPubID != `` {
      q.
        Value(`owner_id`, `(SELECT id FROM entities AS owner_e WHERE owner_e.pub_id=?)`, e.GetOwnerPubID()).
      Returning(`id, pub_id, owner_id`)
    }
    return ctx, q, nil
}
```

And would also do a similar setup for `BeforeUpdateHook`.

As a matter of interface, I don't have a strong opinion (and no internal understanding) of whether this would be combined with the existing hooks or use a new hook (for queries only and no context?).

With such a hook, I could put all my logic for this next to the `Entity` struct where (it seems to me) it belongs. It would also work cleanly with derived structs which embed `Entity` (as they do, `Entity` being a functionally abstract type).

Without the hook, the best solution I've been able to come up with (and I might be missing something) is to have a convention of `func (e *Entity) PrepInsert(q *orm.Query) *orm.Query` for the above logic, and then similar for embedding types which cascade through the embedded members, e.g.:

```go
func (c *Car) PrepInsert(q *orm.Query) *orm.Query { 
  return (&c.Entity).PrepInsert(q)
}
```

which all has to be called explicitly

**Comment by vmihailenco** [comment]
All I can tell that this is not supported at the moment and it is unlikely it will be supported in the future. Try to solve this without hooks and without creating lots of abstractions / trying to be too clever. That does not scale well.

I would just explicitly set `owner_pub_id`:

```go
owner, err := SelectOwner(ctx, e.OwnerPubID)
e.OwnerID = owner.ID
db.Insert(e)
```

**Comment by zanerock** [comment]
I agree, I don't want to be more clever than necessary. Also, query-modifying hooks seem pretty natural, both for managing data-relations and totally in-line with the idea of an ORM.

I totally get it's ultimately cost/benefit analysis. 

**Question:** 
* On the benefit side, I gather that you just don't see the use-cases for this?
* On the cost side, I'm looking at hook-based query modification as no harder than the hook-based model modification already implemented. Is that incorrect?

I've got a pretty long writeup of why this is a valuable feature, with pros and cons, but if it's more a case of you're not interested, but also not opposed, I could look into implementing myself. (And, in the meantime, I can simplify my model for the time being and work around as needed.)

**Comment by zanerock** [comment]
I think I'm understanding understand the boundaries of the project a bit better. I think what I'm trying to do is best achieved by a combination of convention+triggers+vies+go-pg rather than trying to get it all done in go-pg itself.
