### ISSUE TITLE
Include tag to always return column.

### ISSUE THREAD

**Issue by zanerock** [go-pg/pg#1348]
The use case here is a trigger-updated column. E.g., `last_updated`:

```sql
CREATE TABLE foo (
  id SERIAL PRIMARY KEY,
  val VARCHAR(64),
  last_updated TIMESTAMPZ
);

CREATE OR REPLACE FUNCTION trigger_foo_last_updated()
  RETURNS TRIGGER AS $$
    BEGIN
      NEW.last_updated := NOW();
      RETURN NEW;
    END;
  $$ LANGUAGE 'plpgsql';

CREATE TRIGGER foo_last_updated
  -- BEFORE INSERT OR UPDATE ON entities
  BEFORE UPDATE ON entities
  FOR EACH ROW
  EXECUTE PROCEDURE trigger_entities_last_updated();
```

```go
type Foo struct {
  ID int64,
  Val string,
  LastUpdated time.Time,
}

foo = &Foo{}
db.Update(foo) // reflects LastUpdated since it was DEFAULT
foo.Val = `bar`
db.Update(foo)
// LastUpdated unchanged since go-pg doesn't know it's trigger-modified
```

Would it make sense to add a field tag `return` or `volatile`? E.g.,
```go
LastUpdated time.Time, `pg:",volatile"`
```

**Comment by vmihailenco** [comment]
It makes sense, but `volatile` is a too broad term and likely you will be the only user - it is a rare and subtle feature. I suggest to use `Returning("last_updated")` if your code depends on that value - it is explicit and simple.

**Comment by zanerock** [comment]
That's what I ended up doing. Agreed, `return` would probably be the better keyword (if you ever change your mind). I'm surprised it would be perceived as rare. A "last_updated" column in particular are common enough (in my experience). It could be handled at the code level, at which point you wouldn't need to flag them, but IMO (and generally, I think) better to handle at DB level since DB is the "source of truth" for data and therefore the best source of timestamp.

Still, I appreciate you have to prioritize and I'm just providing feedback. Thanks!
