### ISSUE TITLE
`Update` generate extra comma when the updated field is not in the end

### ISSUE THREAD

**Issue by zengfenfei** [go-pg/pg#136]
The following will generate sql with syntax error:
```go
type Relationship struct {
	UserId      int64 `sql:",pk"`
	Relation    int16
	OtherUserId int64 `sql:",pk"`
}
newRelationship = Relationship{1, 1, 3}
db.Update(&newRelationship)
```
SQL generated:
```sql
UPDATE "relationships" SET "relation" = 1,  WHERE "user_id" = 1 AND "other_user_id" = 3 -- extra comma after relation field
```

If I move `Relation` to the end, it will generated the correct sql:
```go
type Relationship struct {
	UserId      int64 `sql:",pk"`
	OtherUserId int64 `sql:",pk"`
	Relation    int16
}
...
```
SQL generated:
```sql
UPDATE "relationships" SET "relation" = 1 WHERE "user_id" = 1 AND "other_user_id" = 3
```

Is this a bug?

**Comment by vmihailenco** [comment]
Yes, this is a bug. I already have a fix, but it is a part of bigger change that is still in progress...

**Comment by vmihailenco** [comment]
Should be fixed. Leaving this open as a reminder to add a test.

**Comment by vmihailenco** [comment]
Closing since the requirement this lib has for while is that primary keys should come first. So test does not looks worth it :)
