### ISSUE TITLE
Challenges with many2many query for pk's & fk's that don't use '_id' column names.

### ISSUE THREAD

**Issue by cleverartisan** [go-pg/pg#1373]
I have a historical database that has the following tables:
```
CREATE TABLE "Organization" (
  "organizationUuid" bytea NOT NULL,
  "name" varchar(255)
  "keywords" jsonb
  ...
)

CREATE TABLE "OrganizationCategory" {
  "organizationCategoryUuid" bytea,
  "organizationUuid" bytea,
  "categoryForOrganizationUuid" bytea
  ...
}

CREATE TABE "CategoryForOrganization" {
  "categoryForOrganizationUuid" bytea
  "name" varchar(255)
  ...
}
```

I defined my structs as follows:
```
type Organization struct {
  TableName struct{} `json:"-" sql:"\"Organization\"" pg:",discard_unknown_columns"`
  OrganizationUuid  []byte `json:"organizationUuid" sql:"organizationUuid,pk"`
  Name  string `json:"name" sql:"name,notnull"`
  Keywords  []string `json:"keywords" sql:"keywords,notnull"`
  ...
  Categories []*CategoryForOrganization `json:"categories" pg:",many2many:OrganizationCategory,fk:\"organizationUuid\",joinFK:categoryForOrganizationUuid"`
}

type OrganizationCategory struct {
  TableName struct{} `json:"-" pg:",discard_unknown_columns" sql:"\"OrganizationCategory\""`
  OrganizationCategoryUuid    []byte  `json:"organizationCategoryUuid" sql:"organizationCategoryUuid,pk"`
  OrganizationUuid  []byte    `json:"organizationUuid" sql:"organizationUuid,notnull"`
  CategoryForOrganizationUuid []byte `json:"categoryForOrganizationUuid" sql:"categoryForOrganizationUuid,notnull"`
 ...
}

type CategoryForOrganization struct {
  TableName struct{} `json:"-" sql:"\"CategoryForOrganization\"" pg:",discard_unknown_columns"`
  CategoryForOrganizationUuid  []byte `json:"categoryForOrganizationUuid" sql:"categoryForOrganizationUuid,pk"`
  Name string `json:"name" sql:"name,notnull"`
  ...
}
```

In practice, I used the following statement.
```
  // Register many to many model so ORM can better recognize m2m relation.
  orm.RegisterTable((*OrganizationCategory)(nil))

  var organizations []Organization = []Organization{}

  session.Schema.AddQueryHook(schema.QueryHookTarget{})
  query := session.Schema.Model(&organizations).
    Order(`organization.name ASC`).
    Relation("Categories").
    Where("keyword::text ilike '%contractors%').
    WhereGroup(func(qry *orm.Query) (*orm.Query, error) {
      qry.Where("organization.name ilike '%company name%')
      return qry, err
    }).
    Offset(int(page)).
    Limit(int(pageSize)).
    SelectAndCount()
  if err != nil {
    panic(err)
  }
```

The following SQL is generated:

```SELECT count(*) FROM "Organization" AS "organization" WHERE ((("keywords"::text ilike '%contractor%') AND ("organization"."name" ilike '%company name%'))) <nil>```

```SELECT "organization"."organizationUuid", "organization"."name", "organization"."keywords" FROM "Organization" AS "organization" WHERE ((("keywords"::text ilike '%contractor%') AND ("organization"."name" ilike '%company name%')))  <nil>```

```SELECT "OrganizationCategory".*, "category_for_organization"."categoryForOrganizationUuid", "category_for_organization"."name" FROM "CategoryForOrganization" AS "category_for_organization" JOIN "OrganizationCategory" AS "OrganizationCategory" ON ("OrganizationCategory"."organizationUuid") IN ('\x150ac27785a8466790f406f46fbc600b', '\x3c7496c2461c4d6fb901e7f3fd4b7358') WHERE (("category_for_organization"."categoryForOrganizationUuid" = "OrganizationCategory"."categoryForOrganizationUuid")) <nil>```

... along with the Error:
```
Unable to select first page of organizations: pg: relation="Categories" has no base model=Organization with id="" (check join conditions)
```
I have reworked the *sql* tag syntax on the *Organization.Categories* field several different ways and I don't quite understand the error. 

What am I missing? Please advise...

**Comment by vmihailenco** [comment]
Try to create a program that reproduces the problem. I can't guess what is wrong by looking at random bits of code...

**Comment by cleverartisan** [comment]
Here is a sample that demonstrates the situation. Let me know if you have any challenges running the sample.

go version go1.12.9 darwin/amd64
source file: sandbox.go
bash shell script file: sandbox.sh
[go-pg-issue-1373.zip](https://github.com/go-pg/pg/files/3596855/go-pg-issue-1373.zip)

**Comment by vmihailenco** [comment]
Your example should be fixed in master branch if you change `fk:\"organizationUuid\"` to `fk:organizationUuid`. Also go-pg should return a better error in such cases. Sorry for the delay.

**Comment by cleverartisan** [comment]
👍 thx
