### ISSUE TITLE
Saving queries into context

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#1380]
I want to use AfterQuery hook and save the q.FormattedQuery() result into context.

[But it seems that it only accepts context so that you can fetch values from it, not store](https://github.com/go-pg/pg/blob/master/hook.go#L110)

**Comment by vmihailenco** [comment]
To achieve that functions like `Query` and/or `Select` would have to also return `context.Context` which is not desirable or realistic regarding backwards compatibility. Otherwise you could not access the value stored in `context.Context`.
