### ISSUE TITLE
Create empty slice when records are not found

### ISSUE THREAD

**Issue by Keithwachira** [go-pg/pg#1381]
When no records are found go-pg returns nil slice.It would be nice for go-pg to return  an empty slice instead.
This would be nice since when i am sending json to the client side i end up sending nil instead of [] which forces me tho check for nulls of the client side.

**Comment by vmihailenco** [comment]
You can achieve the same by allocating an empty slice before passing it to go-pg.

**Comment by Keithwachira** [comment]
Thank you for the quick answer.That what i have been doing and it has been working great. But i have a problem when i am getting relations in a hasmany relationship
```type Business struct {
	commons.Models
	
	Services         []Services  `json:"services"`
	Title         string `json:"title"`
}```
in a situation like this when i run the query.Services returns nil.
``` go
item:=[]Business{}
s.DB.Model(&item).Where("user_id=?", id).Relation("Services").Select```

**Comment by Keithwachira** [comment]
> You can achieve the same by allocating an empty slice before passing it to go-pg.

@vmihailenco How can i use that in a a struct with Relations that at are slice

**Comment by vmihailenco** [comment]
I think your best luck is with AfterScan hook:

```go
var _ orm.AfterScanHook = (*Book)(nil)

func (*Book) AfterScan(ctx context.Context) error {
    // do it here
    return nil
}
```

Changing go-pg is complicated and breaks backwards compatibility.

**Comment by Keithwachira** [comment]
> I think your best luck is with AfterScan hook:
> 
> ```go
> var _ orm.AfterScanHook = (*Book)(nil)
> 
> func (*Book) AfterScan(ctx context.Context) error {
>     // do it here
>     return nil
> }
> ```
> 
> Changing go-pg is complicated and breaks backwards compatibility.

Thank you for your time.I think will  have to try the suggested method.Alternatively i can handle it on the front end.
