### ISSUE TITLE
TSvector insert & querying error

### ISSUE THREAD

**Issue by ToferC** [go-pg/pg#1383]
I'm having similar issues as in issue #917 while trying to implement tsvector with go-pg. I was using the same article as a base.

I'm getting the following error on queries for the model after implementing `types.ValueAppender` as a struct value: `"invalid character '\'' looking for beginning of value"`

The error also seems to be related to issue #770

I saw the suggestion in #917, but I'm not sure what type I should have for the tsvector in the regular model.

Any help would be greatly appreciated. Thanks so much for creating such an awesome package.

Code below.

Model is:
```golang
type CharacterModel struct {
	ID        int64
	Author    *User
	Random    bool
	Character *runequest.Character
	Open      bool
	Search    types.ValueAppender // tsValue
}
```

Save or update is basically the code below:

```golang
func SaveCharacterModel(db *pg.DB, cm *models.CharacterModel) error {

	cm.Character.UpdateCharacter()

	if cm.Slug == "" {
		cm.Slug = slug.Make(fmt.Sprintf("%s-%s", cm.Author.UserName, cm.Character.Name))
	}

	// Save character in Database
	_, err := db.Model(cm).
		OnConflict("(id) DO UPDATE").
		Set("character = ?character").
		Insert(cm)
	if err != nil {
		panic(err)
	}

	setTSVSearch := fmt.Sprintf(`
	UPDATE character_models SET search = 
	setweight(to_tsvector(coalesce(character ->> 'Name')), 'A') ||
	setweight(to_tsvector(coalesce(author ->> 'UserName')), 'B') ||
	setweight(to_tsvector(coalesce(character ->> 'Description')), 'C') ||

	setweight(to_tsvector(coalesce(character#> '{Homeland, Name}')), 'D') ||
	setweight(to_tsvector(coalesce(character#> '{Occupation, Name}')), 'D') ||
	setweight(to_tsvector(coalesce(character#> '{Cult, Name}')), 'D')

	WHERE
	id = %d;
	`, cm.ID)

	db.ExecOne(setTSVSearch)

	return err
}
```

Query is:

```golang
// SearchCharacterModels queries Character names and add to slice
func SearchCharacterModels(db *pg.DB, q string) ([]*models.CharacterModel, error) {
	var cms []*models.CharacterModel

	_, err := db.Query(&cms, `
				SELECT *,
				ts_rank_cd(search, q) AS RANK
				FROM character_models, plainto_tsquery(?) q
				WHERE
				search @@ q AND open = 'true'
				ORDER BY rank DESC
				LIMIT ?;`, q, 66)

	if err != nil {
		log.Println(err)
	}

	return cms, nil
}
```

**Comment by vmihailenco** [comment]
`types.ValueAppender` is an interface - you need to set a real type when using it. From the code it looks like you expect it to act like a real data type.

Usually when working with tsvector you don't need to select tsvector, but only insert/update it. With latest version that can be achieved with:

```go
type Article struct {
    ID int
    Text string
}

article := &Article{...}
db.Model(article).Value("tsv", pg.Q("to_tsvector(?)", article.Text)).Insert()
```

Here `Value("tsv", pg.Q("to_tsvector(?)", "some text"))` specifies additional "hidden" column `tsv` with some data for that column. The same trick should work with `Update` too. Try to play with it.

**Comment by ToferC** [comment]
> types.ValueAppender is an interface - you need to set a real type when using it. From the code it looks like you expect it to act like a real data type.

What is the correct data type to set for a tsvector?

In trying to reproduce your code above, I get this error: `cannot use pg.Q("to_tsvector(?)", cm.Character.Description) (type types.ValueAppender) as type string in argument to db.baseDB.Model(cm).Value`

I've added the tsv column to character_models (as a tsvector type) and updated the code to:

```golang
// Save character in Database
	_, err := db.Model(cm).
		OnConflict("(id) DO UPDATE").
		Set("character = ?character").
		Value("tsv", "to_tsvector(?)", cm.Character.Description).
		Insert()
```
I get the error: `http: panic serving 127.0.0.1:58648: model=CharacterModel does not have column="tsv"` -- Even when I know it is there.

Sorry if I seem obtuse - I'm really trying to figure this out, but something isn't fitting.

I have set the tsvectors using pure PSQL code using this:

```sql
UPDATE character_models SET search =
	
	setweight(to_tsvector(coalesce(character ->> 'Name')), 'A') ||
	setweight(to_tsvector(coalesce(author ->> 'UserName')), 'B') ||
	setweight(to_tsvector(coalesce(character ->> 'Description')), 'C') ||

	setweight(to_tsvector(coalesce(character #> '{Homeland, Name}')), 'D') ||
	setweight(to_tsvector(coalesce(character #> '{Occupation, Name}')), 'D') ||
	setweight(to_tsvector(coalesce(character #> '{Cult, Name}')), 'D')

```

I just can't get it to work on insert or update of a new model. Is there a way to make this happen OR to execute a raw psql UPDATE using pg-go?

Thank you.

**Comment by ToferC** [comment]
Figured out how to make it work with a separate function call using `db.Exec()` and the psql above. 

I'm really not sure what made it work this time, but I'm closing the issue as I'm mostly certain it's due to my own familiarity with the module. Some additional help documentation might come in handy. Happy to contribute to drafting if you'd like.

Thanks again for the great work here.
