### ISSUE TITLE
Connections Staying Active

### ISSUE THREAD

**Issue by l0gicgate** [go-pg/pg#1386]
I'm having a problem with connections staying active after a query has executed. The queries are not running in a transaction.

Just to give you a bit of insight, I have about 10 workers that share the go-pg connection. The pool size is set to `80` (total, 8 CPU x 10) and everything is fine but it seems that as the process ticks, the number of connection grows and grows over time which eventually pegs the PG instance to 100%

How can I mitigate this from happening?

**Comment by l0gicgate** [comment]
I figured out what the problem was. Connection pool size was way too high. I set it to 12 and everything is fine now!

**Comment by vmihailenco** [comment]
It is better to use connection pool like PgBouncer.
