### ISSUE TITLE
Bulk Update JSONB Column Getting Merged

### ISSUE THREAD

**Issue by l0gicgate** [go-pg/pg#1403]
I have a JSONB column that holds data in the following shape:

```
{"cookies": {
    "domain.com": [{...}, {...}],
    "domain2.com": [{...}, {...}],
}}
```

The JSONB column gets merged instead of replaced which results in duplicate objects being appended to the arrays when performing a bulk update like so:
```go
r.DB.Model(&mySlice).Update()
```

Is this normal behavior?

**Comment by vmihailenco** [comment]
That is unexpected behavior. Can you show the generated query?

**Comment by l0gicgate** [comment]
I will make a test repo as soon as possible and post it here.
