### ISSUE TITLE
Issues with WhereStruct

### ISSUE THREAD

**Issue by patrikeh** [go-pg/pg#1407]
Two things.

First, `WhereStruct` does not play well with empty structs. If no conditions are generated you end up with `SELECT * FROM something WHERE` and `ERROR #42601 syntax error at end of input`.

Second, I'm having issues when using `WhereStruct` along with `.Relation()` where there are mutual fields. For instance, with a model:

    type Human struct {
    	ID    int
    	Pet   *Pet
    }
    
    type Pet struct {
    	ID int
    	HumanID int 
    }

doing something like:

    err := db.Model(&res).WhereStruct(model.Human{ID: 1}).Relation("Pet").Select()

would result in invalid SQL:

    SELECT "human"."id",
           "pet"."id" AS "pet__id",
           "pet"."human_id" AS "pet__human_id"
    FROM "humen" AS "human"
    LEFT JOIN "pets" AS "pet" ON "pet"."human_id" = "human"."id"
    WHERE id = 1

and error with `ERROR #42702 column reference "id" is ambiguous`.

**Comment by vmihailenco** [comment]
Empty structs should be fixed in the master.

As for the second issue you can specify table name / alias via:

```pg
type Filter struct {
    tableName struct{} `urlstruct:"human"`
}
```

That assumes you are using latest v9 with https://github.com/go-pg/urlstruct
