### ISSUE TITLE
How to get Many2Many relation's column value?

### ISSUE THREAD

**Issue by sgon00** [go-pg/pg#1410]
Dear sir, if I have the following code:

```go
type Order struct {
	ID        int64
	Name     string
	Items    []Item `pg:"many2many:order_to_items"`
}

type Item struct {
	ID        int64
	Name     string
}

type OrderToItem struct {
	OrderID int64 `cpg:"index:btree"`
	ItemID  int64 `cpg:"index:btree"`
	Price   float64
}
```

How do I query an order and get all its items and their corresponding **Prices** in one command? Is that possible?
If not, what is the proper way to handle this situation to reduce database queries?

```go
order := new(Order)
err = db.Model(order).Relation("Items").First()
```

This will give everything for an order except the `Price` column. 

Thanks a lot.

**Comment by vmihailenco** [comment]
go-pg does not provide any way to get m2m relation in one query.

**Comment by sgon00** [comment]
@vmihailenco thanks a lot for the reply. Can you please show an example code how I can query the `Price` properly (and sorted by `Price` too) in go-pg? I don't find a good way to do it and there is no any example codes online too.

**Comment by sgon00** [comment]
I am getting CRAZY with this problem. It's just a common pattern used daily. I have no ideas how to query and join ItermPrice with ItermName together and then get the result rows. This is related to the new issue I just filed (https://github.com/go-pg/pg/issues/1412). I read all issues in this repo today. It seems I might need to use some kinda of custom scanner which I have no ideas how to. It looks hard and doesn't really make sense to me. Once again, this should be a common daily problem. I don't know why it's so hard to achieve. OR I am just too stupid.

**Comment by sgon00** [comment]
@vmihailenco I am very sorry to interrupt you again. After three days, I still can not figure out how to get the `Price` value properly. The code `err = db.Model(order).Relation("Items").First()` does call `SELECT "order_to_items".*`, but the return values of `Price` are just ignored. How can I use that query's result properly? Thanks a lot for your help.

**Comment by sgon00** [comment]
@vmihailenco OK, please ignore my last comment. I finally got it work by reading https://github.com/go-pg/pg/blob/c5ad18f9bf5b54792e67885ea32cac5cc62cf98f/db_test.go source code and then update my go-pg version. 

Somehow, the version I have been used v9.0.0-beta.2 doesn't work. 
After upgrading to v9.0.0-beta.14, and then modifies Item to be

```go
type Item struct {
	ID        int64
	Name     string
	Price    float64 `pg:"-"`
}
```

Now, it works as expected. I tried this Item struct two days ago. But unluckily, v9.0.0-beta.2 doesn't work with this struct. That's why it took me three days to figure out this was actually the correct way by reading db_test source code.
