### ISSUE TITLE
bulk update fails when uuid-ossp extension used

### ISSUE THREAD

**Issue by MohitKS5** [go-pg/pg#1411]
when there is a field like this :
```go
type Question struct {
  Id        string      `sql:",type:uuid default uuid_generate_v4()" json:"id"`
 SerialNo int8       
}
```
The orm generates the following query which gives syntax error.
`ERROR #42601 syntax error at or near "default"`

```sql
UPDATE "questions" 
AS "question" 
SET "serial_no" = _data."serial_no" 
FROM (VALUES (1::smallint, 'e191a00a-7917-4283-9b26-7c6dd6ece62b'::uuid default uuid_generate_v4()), (2::smallint, '2189a065-d0af-4d48-9c64-2dfb173545a8'::uuid default uuid_generate_v4())) 
AS _data("serial_no", "id") 
WHERE "question"."id" = _data."id"
```
How can I get arround this?

**Comment by MohitKS5** [comment]
This works
https://github.com/go-pg/pg/issues/1126#issuecomment-467245800
Can someone please add a small documentation in model definitions page. 
https://github.com/go-pg/pg/wiki/Model-Definition

**Comment by vmihailenco** [comment]
Done. Also wiki publicly editable - you can do such changes yourself.
