### ISSUE TITLE
Idiomatic way to update relations

### ISSUE THREAD

**Issue by mariusmagureanu** [go-pg/pg#1415]
Hi,

**Set up**

I have some types similar to the ones below:

```
type Car struct {
	ID            int           
	Name          string  
	Engine        *Engine   
        Features      []*Feature     
}

type Engine {
	ID            int           
	Name          string
        CarID         int
        Car           *Car
}

type Feature {
	ID            int           
	Name          string  
        CarID         int
        Car           *Car
}
```

**The problem**

Suppose a car object already has 2 features and I decide to add a third one (assuming the 3'rd feature is already in the database):

(sort of a pseudocode)

Would the following be a valid approach: ?

```
car.Features = append(car.Features. someFeature)
db.Update(car)
```

Or do I specifically need to do something like:

```
someFeature.CarID = car.ID
db.Update(someFeature)
```

Any pointers/suggestions would be highly appreciated.

**Comment by vmihailenco** [comment]
It is almost the same as with plain SQL - use `INSERT`. go-pg can only help you to generate insert query via `db.Model(feature).Insert()` - nothing more.
