### ISSUE TITLE
pg.DB Query execution using `where` date interval has a wrong results

### ISSUE THREAD

**Issue by muhrifqii** [go-pg/pg#1430]
I ran this syntax using postgre sql console 
```sql
select * from public.notes where (date >= ?::date and date < ?::date + interval '1 day')
```
returned 2 rows

But when I used it on go-pg
```go
var nExist = new(model.Notes)
res, err := pg.Query(nExist,
		"select * from public.notes where (date >= ?::date and date < ?::date + interval '1 day')",
		beginningOfDay, beginningOfDay)
returned := res.RowsReturned()
```
it returned 0 rows. I also tried without the where clause, and it returned all the rows normally.

Below is the structure of that object
```go
type Notes struct {
	ID       int                   `json:"id"`
	Date     time.Time             `json:"date"`
	Notes    string                `json:"notes"`
}
```

**Comment by muhrifqii** [comment]
I also tried Exec
```go
res, err := pg.Exec("select * from public.notes where (date >= ?::date and date < ?::date + interval '1 day')", beginningOfDay, beginningOfDay)
returned := res.RowsReturned()
```
I copied the value of ```beginningOfDay``` into the console, so it should have the same where clause. And still had no clue why it has different results.

**Comment by muhrifqii** [comment]
@vmihailenco could you please tell why you closed it?

**Comment by vmihailenco** [comment]
I can't tell what is going on from the information you've provided. If you need help - create a program that can be run and that reproduces the problem.

**Comment by muhrifqii** [comment]
this syntax ```date_column < ?::date + interval '1 day'``` will return a wrong result when executing on go-pg. No error returned. 

but when I changed to ```date_column < date ? + interval '1 day'```, the result returned is correct
