### ISSUE TITLE
How to perform model insertion within a transaction

### ISSUE THREAD

**Issue by mihaihuluta** [go-pg/pg#1435]
All examples provided in the existing tests and documentation show how you can perform a simple insert. My issue is that I was not able to find anything related to how one could insert a model using a transaction handled manually.

P.S: Through my quick tests I have realized that calling db.Model(...).Insert() runs in its own transaction space and if the insert is executed without any errors the transaction gets committed.

**Comment by vmihailenco** [comment]
Just use `tx.Model` instead of `db.Model` where `tx` is a `*pg.Tx`
