### ISSUE TITLE
Add support of sslmode=verify-full

### ISSUE THREAD

**Issue by semyon-dev** [go-pg/pg#1438]
Please, add support of sslmode=verify-full in ParseURL(), now just error: pg: sslmode 'verify-full' is not supported.

* verify-ca - Always SSL (verify that the certificate presented by the
  server was signed by a trusted CA)
* verify-full - Always SSL (verify that the certificate presented by
  the server was signed by a trusted CA and the server host name
  matches the one in the certificate)

**Comment by justcompile** [comment]
👍
