### ISSUE TITLE
textflag.h file not found

### ISSUE THREAD

**Issue by kalpesh-khule** [go-pg/pg#1439]
I am trying to get this 'go-pg/pg' library to my ubuntu server. I am continuously getting the below error. I also tried to remove directory and install it again but same error. It worked for me before for another server.
Can you please look into it what might have gone wrong?
```
# mellium.im/sasl
/home/ubuntu/go/src/mellium.im/sasl/xor_amd64.s:7:10: fatal error: textflag.h: No such file or directory
 #include "textflag.h"
          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by vmihailenco** [comment]
It is obvious that something is wrong with your Go installation. I would make sure to be using latest Go version and re-install it if that does not help.
