### ISSUE TITLE
Update() doesn't work

### ISSUE THREAD

**Issue by chess-equality** [go-pg/pg#1442]
Hi,

I have the following code:

```
func (myModel *MyModel) Update(db *pg.DB) (int, error) {
	res, err := db.Model(myModel).
		Where("pk = ?", myModel.Pk).
		OnConflict("DO NOTHING").
		Update()
	if err != nil {
		return -1, err
	}
	return res.RowsAffected(), nil
}
```

It returns `1` (1 row/s affected) with no errors, however the record was not updated with the new values. Any ideas?

This table has a custom primary key / id which is `pk`.

**Comment by vmihailenco** [comment]
Please create a program that reproduces the problem. Closing until then.
