### ISSUE TITLE
PG using wrong relation name

### ISSUE THREAD

**Issue by thefuga** [go-pg/pg#1448]
So, whenever i try to run any query related method with PG, it queries the wrong relation, which causes the Postgres error  `ERROR #42P01 relation "nves" does not exist`.

To put it in context:
My database only have one table (called nfes), with a `varchar` and some `jsonb` rows. 
The struct related to this table is called NFE. If i try to used `db.Select()` or `db.Insert`, the error mentioned above is returned.
The thing is, there's nothing called `nve` or `nves` or anything like it no where in the code. I'm not sure where is this coming from.

Am i missing something here?

Thank you!

**Comment by vmihailenco** [comment]
Please create a program that reproduces the problem.

**Comment by thefuga** [comment]
Sorry, I didn't post a program to reproduce because the problem seemed clear:
But anyways, the bellow code will reproduce it:

```
package main

import (
	"fmt"
	"github.com/go-pg/pg"
	"github.com/go-pg/pg/orm"
)

type Nfe struct {
	ID uint64
}

func main() {
	db := pg.Connect(&pg.Options{})

	m := &Nfe{}

	err := db.Insert(m)
	fmt.Println(err)
}
```
Will output `ERROR:  relation "nves" does not exist `.
So basically PG pluralizes `Nfe` to `nves`. 
This assumes there's already a table called `nfes` in the database.

**Comment by vmihailenco** [comment]
You can manually specify name for the table if default does not work for you

```

type Nfe struct {
    tableName struct{} `pg:"your_table_name"`

    ID uint64
}
```

**Comment by thefuga** [comment]
Just did that and it worked. At first I didn't understand that this should be used to specify the struct table name, i though it was just for relationships.
Thank you!
