### ISSUE TITLE
Improve documentation on sql tags

### ISSUE THREAD

**Issue by max-neverov** [go-pg/pg#1451]
Current [Model Definition](https://github.com/go-pg/pg/wiki/Model-Definition) describes `pg` tags with only two mentions of `sql` tags.
From the [code](https://github.com/go-pg/pg/blob/9ab62c0f9c17851e2926c019d0262f198576930e/orm/table.go#L301) I understand that they are almost identical.
What are the difference between them? Are `sql` tags hidden to be deprecated?
Please provide recommendation on what tag to use.

**Comment by vmihailenco** [comment]
I've updated the wiki - thanks.

Please use `pg` tags - it works better if you want to reuse the struct with other db clients. Using `sql` tag would only make sense if different clients support the same set of tags but that is not the case. `sql` tags are deprecated in v9.
