### ISSUE TITLE
Exclusively querying with relations

### ISSUE THREAD

**Issue by hysmio** [go-pg/pg#1457]
I have a table that has a one to many relationship.

I'm trying to write a query where the many table has a specific parameter. I want to ONLY find the items where they match and exclude all the other values where they don't.

```go
Conn.
	Model(&schedules).
	Relation("Actions", func(q *orm.Query) (*orm.Query, error) {
		return q.Where("? = column", search), nil
	})
	Select()
```
Schedule struct is below
```go
type Schedule struct {
	ID           string `json:"id"`
	CreatorID    string `json:"creatorId"`
	Active       bool   `json:"active"`
	Minutes      string `json:"minutes"`
	Hours        string `json:"hours"`
	DaysOfMonth  string `json:"daysOfMonth"`
	MonthsOfYear string `json:"monthsOfYear"`
	DaysOfWeek   string `json:"daysOfWeek"`
	Timezone     string `json:"timezone"`

	// Reference to Schedule Actions
	Actions []ScheduleAction `json:"actions"`

	// Table Name (meta)
	tableName struct{} `sql:"schedule"`
}
```

This will find ALL schedules regardless of the Relations. But I want to exclude the schedules which don't have an Action with the matching search query.

I attempted to include a `WHERE search = action_alias.column` clause in the initial query, however since go-pg handles OneToMany queries in 2 queries, I cannot use this solution.

**Comment by Dasio** [comment]
Similar issue, I ended with custom join and where.

But I'm not able to do object mapping
`can't find column=location__zip in model=Client`
```go
type Client struct {
    Locations []*Location
}
type Location struct {
    Zip string
}
```

**Comment by vmihailenco** [comment]
It looks like go-pg is working as expected. Yes, it uses 2 queries and that will remain true until someone contributes a better solution.
