### ISSUE TITLE
LastInsertId support undocumented

### ISSUE THREAD

**Issue by warent** [go-pg/pg#1459]
As mentioned in issue #42 the `LastInsertId` is not documented and it's not immediately clear how to get the ID of a newly inserted row.

That ticket was tagged with a TODO item but for some reason it seems to have been closed without ever having been addressed.

**Comment by warent** [comment]
Finally found the answer in #134

**Comment by vmihailenco** [comment]
Added https://github.com/go-pg/pg/wiki/FAQ#how-to-get-last-inserted-id

**Comment by warent** [comment]
Thank you @vmihailenco I really appreciate your work on this package, it's just great. Can you add a note to the wiki that go-pg will scan returned value into the model automagically? I love the feature, it's just not obvious that that's how it works.

**Comment by vmihailenco** [comment]
Will do, but there is nothing special about it - there is no difference between `SELECT id` and `RETURNING id`.
