### ISSUE TITLE
Please export `errTxDone` variable

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#1460]
When I call the `Rollback()` method, it returns an error:
`pg: The transaction has been committed or rolled back`.

But I can't judge whether this error will happen, I can only judge it is a string type, so please export the `errTxDone` variable in tx.go like` pg.ErrNoRows`.

Thank you!

**Comment by vmihailenco** [comment]
Closed by https://github.com/go-pg/pg/commit/6828caeb7883815a8578b9c6e5c826b34f2fbe1a

FYI there is `Tx.Close` which might do what you want.
