### ISSUE TITLE
Cannot find package go-pg/pg/urlfilter

### ISSUE THREAD

**Issue by alam157** [go-pg/pg#1461]
Dear team,

Before that, i am sorry for my bad english.
I am using go-pg since 3 months ago. and i am using urlfilter for pagination. Unfortunattely, i want to run on my server and i get this error 
`cannot load github.com/go-pg/pg/urlfilter: module github.com/go-pg/pg@latest found (v8.0.6+incompatible), but does not contain package github.com/go-pg/pg/urlfilter`
I think urlfilter is remove at latest update, but how i can get the previous version of go-pg?

Thanks for the help

**Comment by alam157** [comment]
i just read, that urlfilter no longer in v9 so i copy from v8 version in my local, and its run perfectly

**Comment by vmihailenco** [comment]
That might be the right thing to do in your case. FYI parts of urlfilter were extracted to https://github.com/go-pg/urlstruct.
