### ISSUE TITLE
pg:",required" tag doesn't work for zero values

### ISSUE THREAD

**Issue by D1353L** [go-pg/pg#1463]
I have defined Filter struct for WhereStruct and used the "required" tag as described.
```
type Filter struct {
	Status          int32 `pg:",required"`
}

...

filter = new(Filter)
db.Model(&books).WhereStruct(filter)
```
But it seems that this tag doesn't work if Status is 0. The field is missed in SQL query.
[Link to definition](https://github.com/go-pg/pg/blob/38f0d75d8fa3b1dff65a90a1641d7ea2c494b62b/orm/query.go#L591)

**Comment by derfenix** [comment]
These tags named 'urlstruct', it is orphaned info in docs. So your tag should be
```
`urlstruct:",required"`
```

**Comment by vmihailenco** [comment]
urlstruct was moved to https://github.com/go-pg/urlstruct
