### ISSUE TITLE
false =DEFAULT ???

### ISSUE THREAD

**Issue by Peng-Kun-Dai** [go-pg/pg#1466]
During use, it was found that if a field is of Boolean type, the sql statement obtained by passing 'true' is TRUE, but the sql statement obtained by passing 'false' is DEFAULT. When debug finds that false is passed in, '@ v9. 0.3 / orm / field.go line72 'execution result is true

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/wiki/FAQ#how-to-insert-zerofalse-value

**Comment by Peng-Kun-Dai** [comment]
> See https://github.com/go-pg/pg/wiki/FAQ#how-to-insert-zerofalse-value

thank you
