### ISSUE TITLE
how to map JSONB column to different structs during scanning

### ISSUE THREAD

**Issue by godfryd** [go-pg/pg#1467]
Hello,

I have structs like that:
```go
type Service struct {
	Id           int64
	Meta      interface{}
}
type Meta1 struct {
	Version string
}
type Meta2 struct {
	Uptime int
}
```

I'm adding the record to DB as follows:

```go
	s := &Service{
		Id: 0,
		Meta: Meta1{
				Version: "1.2.3",
			},
		},
	}
	db.Insert(s)
```

but when I read the record back using `Select()` then Meta column is `Meta:map[Version:1.2.3]}`, ie. default scanner returns it as `map[string]interface{}`. I would like to get Meta1 or Meta2 type respectively.

So the question is: how to read Meta column as Meta1 or Meta2 struct during scanning?

**Comment by vmihailenco** [comment]
This is not a go-pg problem - it just uses encoding/json to decode the data. If you can solve this problem with encoding/json - you can solve it with go-pg as well.

**Comment by godfryd** [comment]
Ok, but is there any way to get such result, maybe with custom scanner?

**Comment by vmihailenco** [comment]
I would consider adding `type` field:

``` go
type Service struct {
	Id           int64
	Type string // meta1 or meta2
	Meta      interface{}
}

func (s *Service) BeforeScan(ctx context.Context) error {
    switch s.Type {
    case "meta1":
        s.Meta = new(Meta1)
    case "meta2":
        s.Meta = new(Meta2)
    default:
         panic("not reached")
    }
    return nil
}
```

Or using another encoding that encodes/decodes object type for you, e.g. msgpack allows you to do that with extensions - https://godoc.org/github.com/vmihailenco/msgpack#example-RegisterExt. This way the same `type` field is encoded with the data.

**Comment by godfryd** [comment]
Thanks much. I will try it.

Is there a forum, group or mailing list for go-pg where such problems could be discussed?

**Comment by vmihailenco** [comment]
I think Stackoverflow is still the best place for such questions.
