### ISSUE TITLE
Multiple schema support

### ISSUE THREAD

**Issue by xakep666** [go-pg/pg#1468]
Currently to make a query from table located in non-default (or currently selected schema) I use this hack
```go
type queryResult struct {
		tableName struct{} `sql:"information_schema.columns,alias:columns"`
                Name string `sql:"name"`
}
```
 which generates a correct query.
I think it will be better to have posibility to set schema name using a tag in tableName (like ```sql:"columns,schema:information_schema"```) and in query builder (like ```db.Model().SchemaExpr(schema)...```.

**Comment by vmihailenco** [comment]
You may be interested in https://github.com/go-pg/sharding - specifically `tableName string \`pg:"?SHARD.users"\``.

**Comment by xakep666** [comment]
> You may be interested in https://github.com/go-pg/sharding - specifically `tableName string pg:"?SHARD.users"`.

It may work but using sharding package not for sharding (and probably also with hacks) looks strange, isn't it?

**Comment by vmihailenco** [comment]
All you need from that package is `db.WIthParam("SCHEMA", pg.Safe("myschema"))`.

>looks strange, isn't it?

If you are willing to contribute something more straightforward - please send a PR :)
