### ISSUE TITLE
Tracing support

### ISSUE THREAD

**Issue by NinaLeven** [go-pg/pg#1470]
Is there any way to shoehorn tracing with [`ocsql`](https://godoc.org/contrib.go.opencensus.io/integrations/ocsql)?

If not, do you consider implementing it?

**Comment by vmihailenco** [comment]
No, using ocsql is not viable. I plan to support https://opentelemetry.io/ once API is a little bit more stable and I have time.

**Comment by elliotcourant** [comment]
@vmihailenco what is the difference or advantage of opentelementry over something like https://opentracing.io/ ?

**Comment by vmihailenco** [comment]
My understanding is that opentemetry = opencensus + opentracing. There should be some better explanation at opentelemetry site.

**Comment by moh-abk** [comment]
otel is now in beta - https://medium.com/opentelemetry/opentelemetry-is-officially-in-beta-352fa859db10

**Comment by tankbusta** [comment]
I'd love to see some form of OTEL support in V10.

It could probably be done fairly easily (at least by not modifying library code) by expanding the use of the query hook system to provide users access to important events like Pre/Post query generation, Pre/Post scan, etc

**Comment by vmihailenco** [comment]
This should be ready for testing in v10. See https://pg.uptrace.dev/guide/tracing.html
