### ISSUE TITLE
ManyToMany empty array issues when marshaling JSON

### ISSUE THREAD

**Issue by SHT** [go-pg/pg#1471]
When there is a many2many relationship between two structs, if we query the parent and there is no children found, it returns a nil slice instead of an initialized empty one and subsequently, when marshaling to JSON, the array is returned as `null` instead of `[]`. Am I doing something wrong that causes this behavior or is it a bug?

This structure should reproduce the problem:

```
type Book struct {
    tableName  struct{}  `pg:"books"`
    ID int `json:"id"`
    Authors []*Author `pg:"many2many:book_authors" json:"authors"`
}

type Author struct {
    tableName struct{} `pg:"authors"`
    ID int `json:"id"`
}

type BookAuthor struct {
    tableName struct{} `pg:"book_authors"`
    BookID  int
    AuthorID int
}
```

For 2 books with IDs 1 and 2, and 1 author with ID 1 (and book 1 having 1 author, with book 2 having no authors), when querying all books after marshaling to JSON, this is returned:

```
[
  {
    "id": 1,
    "authors": [
      {
        "id": 1
      }
    ]
  },
  {
    "id": 2,
    "authors": null
  }
]
```
while this should be the correct output AFAIK:
```
[
  {
    "id": 1,
    "authors": [
      {
        "id": 1
      }
    ]
  },
  {
    "id": 2,
    "authors": []
  }
]
```

*Edit: Added clarification regarding existing relations
*Edit2: Added correct JSON data

**Comment by vmihailenco** [comment]
That is how it works - changing it is not trivial and is not needed in most cases.
