### ISSUE TITLE
json `@>` (contains) operator issue

### ISSUE THREAD

**Issue by pavlunya** [go-pg/pg#1474]
I have `services` attribute with jsonb type
When I'm going to filter
```
dbQuery.Where(`order.services @> '[{"serviceId": ?}]'::jsonb`, *opt.ServiceId)
``` 
query looks like
```
order.services @> '[{\"serviceId\": '2b977afb-e86a-41ce-8efb-2a81929e9c04'}]'::jsonb
```

So my question is how to deal with this single quotes marks? It should use double quotes mark instead (`"2b977afb-e86a-41ce-8efb-2a81929e9c04"`).

**Comment by vmihailenco** [comment]
Use `encoding/json` like this:

``` go
b, _ := json.Marshal(obj)
dbQuery.Where(`order.services @> ?::jsonb`, string(b))
```
