### ISSUE TITLE
Any way to "stream" a bytea column?

### ISSUE THREAD

**Issue by ORBAT** [go-pg/pg#1475]
I have a table with a `bytea` column (each with several megabytes of data) that I want to serve over HTTP. What I'd like is to be able to expose the column as an `io.Reader` / `io.WriterTo` or equivalent that I could then just `io.Copy` into the `http.ResponseWriter` instead of having to materialize the entire `[]byte` in memory and _then_ send it over. Is there any way to currently do this?

**Comment by ORBAT** [comment]
Ah, just found `CopyTo`. Haven't tested it out, but I assume it'd do what I need?

**Comment by vmihailenco** [comment]
Yes, `CopyTo` & `CopyFrom` is your best bet with Postgres.
