### ISSUE TITLE
Get connection pool and then query

### ISSUE THREAD

**Issue by KevinAnthony** [go-pg/pg#1476]
We have wrapped the go-pg lib in datadog tracing.  
However, we now find ourselves needing more granularity.  We want to split up the Query into two parts, `get-connection` and `do-query`.

We tried `pg.DB` `Conn` because the documentation says :` Conn will block until either a connection is returned or ctx is canceled` . 
This is false.  It just returns a conn object, and it's then in `Query` or `QueryContext` that it actually executes a `Get` on the pool.  This is what blocks.

I cannot find a way to actually get a connection from the connection pool. I understand this is probably to protect the connection from being checked out and never returned.  

Can you please make a recommendation?

**Comment by vmihailenco** [comment]
`Conn` is grabbed from the pool on the first usage  - I've removed misleading documentation. There are not alternatives to achieve your goal.

Our plan for tracing is to support OpenTelemetry once it is stable - see https://github.com/go-pg/pg/issues/1470. For now you can use hooks for basic perf information - https://github.com/go-pg/pg/wiki/FAQ#how-to-view-queries-this-library-generates
