### ISSUE TITLE
pg fails to connect to postgres with SASL error

### ISSUE THREAD

**Issue by logsnitch** [go-pg/pg#1483]
Hi,

I'm running postgres 11.5 (via RDS, though I don't think it matters) and when I try to connect with pg I get the following error:
```
"pg: SASL: got \"SCRAM-SHA-256-PLUS\", wanted \"SCRAM-SHA-256\""
```

Is this possibly a known issue?

Thanks,

---

**edit:** putting in my notes for anyone else who finds this later. SCRAM-SHA-256-PLUS is used when the postgres server requires TLS to connect to it (as I have configured my RDS instance to do). Since go-pg doesn't support this method yet the 2 current options are to:
- update postgres to allow plaintext connections / stop requiring TLS
- or, downgrade the role's password to MD5 instead of SCRAM

I have opted for the latter solution. This can itself be done in one of two ways:
- Update your postgres [authentication settings](https://www.postgresql.org/docs/12/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION-AUTHENTICATION) and set the inappropriately named `password_encryption` parameter to `md5` (if you're using AWS RDS this is controlled via a parameter group). Then update the role's password via psql:
    ```
    postgres=> alter role myrole with password 'password';
    ```
- or, directly update the role's password. To allow dumping/restoring backups, postgres lets you assign a raw md5/scram value to the role's password column. The md5 format postgres uses is the string "md5" followed by the md5 hash of the password concatenated with the role's name. So for a role "myrole" and password "password", you can run:
    ```
    $ echo -n "passwordmyrole" | md5sum | awk '{print "md5"$1}'
    md519488a15bff1b244feb52d621ac8b965
    ```
    Then set this as the password value via psql:
    ```
    postgres=> alter role myrole with password 'md519488a15bff1b244feb52d621ac8b965';
    ```

Hope this helps someone

**Comment by vmihailenco** [comment]
SCRAM-SHA-256 and  SCRAM-SHA-256-PLUS are 2 different SASL authentication mechanisms. Postgres only supported SCRAM-SHA-256 and that is why this package requires SCRAM-SHA-256.

**Comment by rustyx** [comment]
Any plans to support SCRAM-SHA-256-PLUS?

Can connect to PostgreSQL 10 but not to PostgreSQL 11,  PostgreSQL 12 and PostgreSQL 13 due to this limitation.

EDIT: we've since switched to GORM and `gorm.io/driver/postgres`, it's working much better.

**Comment by ernsheong** [comment]
I am facing this too

**Comment by corbkris** [comment]
I upgraded and now I get the error “pg: SASL: got ‘S’, wanted ‘\x00’”

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/go-pg/pg/commit/03ae98fca2efcb41d2ef245e3a9c4d0547b7cdca

**Comment by Neustradamus** [comment]
@vmihailenco: Good job!

SCRAM-SHA-256 has been added in PostgreSQL 10 and the SCRAM-SHA-256-PLUS variant (with TLS Binding) has been added in PostgreSQL 13 and SCRAM-SHA-256 is selected by default in PostgreSQL 14.
- https://www.postgresql.org/about/news/postgresql-10-released-1786/
- https://www.postgresql.org/about/news/postgresql-13-released-2077/
- https://www.postgresql.org/about/news/postgresql-14-released-2318/
- https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/how-to-securely-authenticate-with-scram-in-postgres-13/ba-p/1548319
