### ISSUE TITLE
Can't use pg.InMulti with structs

### ISSUE THREAD

**Issue by logsnitch** [go-pg/pg#1486]
Hi,

pg.InMulti allows you to perform a lookup on multiple keys if all the keys are the same type. However using different key types by passing in a struct doesn't appear to work:

```
str, _ := types.InMulti(struct {
	int
	string
}{1, "a"}).AppendValue(nil, 0)
fmt.Print(string(str))
```
Expected output:
```
(1, "a")
```
Actual output:
```
{}
```

**Comment by vmihailenco** [comment]
I doubt we will support structs and/or slices - you need to do some pre-processing using Go.

You your case the simplest solution seems to be `Where("(col1, col2) in (?, ?)", m.Col1, m.Col2)`
