### ISSUE TITLE
context bug?

### ISSUE THREAD

**Issue by focusonline** [go-pg/pg#1489]
```go
q := db.Model(&list)
err = q.Select()
```
Trace: runtime error: invalid memory address or nil pointer dereference

c:/go/src/runtime/panic.go:679
c:/go/src/runtime/panic.go:199
c:/go/src/runtime/signal_windows.go:233
E:/project/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.0/internal/pool/pool.go:262
E:/project/go/pkg/mod/github.com/go-pg/pg/v9@v9.1.0/internal/pool/pool.go:222

the code works fine when it replies on  v8.0.4, today, I tried to upgrade the module version to v9.1.0, it is broken with context issue.
```go
func (p *ConnPool) waitTurn(c context.Context) error {
	select {
	case <-c.Done(): // broken here
		return c.Err()
	default:
	}
```
if I crossed out the code expect it works like v8.0.4, it crashed at otherwhere with "nil context", 
seems now it is not stable for involving context supprt. should I rollback to v8.0.4 or I misused something of new version?
thanks

**Comment by vmihailenco** [comment]
Please provide full code that reproduces the problem.
