### ISSUE TITLE
Update with multiple primary keys

### ISSUE THREAD

**Issue by Kern046** [go-pg/pg#1492]
I want to update an entity which has a primary key made of two fields : 

This is my model:
```
SystemTerritory struct {
	tableName struct{} `pg:"map__system_territories"`

	TerritoryId uint16 `json:"-" pg:",pk"`
	Territory *Territory `json:"territory"`
	SystemId uint16 `json:"-", pg:",pk"`
	System *System `json:"system"`
	Status string `json:"status"`
}
```
To update I used to write:
```
func (st *SystemTerritory) update() {
	if err := Database.Update(st); err != nil {
		panic(NewException("Could not update system territory", err))
	}
}
```

The generated query is:

```
UPDATE map__system_territories AS "system_territory" SET "system_id" = 97, "status" = 'contest' WHERE "system_territory"."territory_id" = 28
```
I tried to use WherePK to see if there was any difference, but apparently not.

I specified directly the correct Where clauses and the only column I wanted updated to get the desired result, but I report this behavior as I think it would be more logic to have the two primary keys in the Where statement when using only the Update method.

Thanks for your huge work to make this library great :) !

**Comment by vmihailenco** [comment]
It is likely an unneeded comma in the tag - `json:"-",<- pg:",pk"`

**Comment by Kern046** [comment]
Gosh, I completely missed it !

So sorry for the inconvenience, It seems to have made the trick.

Thanks for your quick answer, and sorry again !
