### ISSUE TITLE
Is the character '%' in `like` condition supported to put in first parameter of 'query.Where'?

### ISSUE THREAD

**Issue by shenzhigang** [go-pg/pg#1493]
In some cases, for example ,using named placeholder. The second parameter is a struct, not a string.  So I should do like this:
`.Where("name like ?", "%" + obj.Keyword + "%")`
I think more elegant way is like this:
`.Where("name like %?keyword%", obj)`

**Comment by vmihailenco** [comment]
I don't see how that is supposed to work - the very least you are missing quotes around `%?keyword%`.

**Comment by shenzhigang** [comment]
> I don't see how that is supposed to work - the very least you are missing quotes around `%?keyword%`.

I tried with quote, but it didn't work.

 `.Where("name like '%?Keyword%'", obj)`  <=  _return empty result (Not as expected）_

 `.Where("name like '%?keyword%'", obj)`  <= _runtime error:  syntax error at or near "xxx"_

**Comment by jamesRaybould** [comment]
For those who find this in the future this is how I ended up solving it.

```
.Where("name LIKE '%' || ? || '%'", searchTerm)
```
