### ISSUE TITLE
No hooks are called on model in separate module/file

### ISSUE THREAD

**Issue by yeyep** [go-pg/pg#1494]
Hi guys,

I've already saw multiple questions regarding hooks and sadly none helped me. My model hooks are never called. I tried to implement each of the hooks, but I got none of them to work.

I have the following model (model/user.go):
```go
package model

import (
	"context"
	"fmt"
	"time"

	"github.com/go-pg/pg/v9/orm"
)

// User represents a platform user.
type User struct {
	ID             int `pg:",pk"`
	Email          string
	Password       string
	Name           string
	Timezone       string
	RoleID         int `sql:"role_id,fk:role_id"`
	Role           *Role
	Activites      []*Activity `pg:",polymorphic:trackable_"`
	LastActivityAt time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

var _ orm.AfterUpdateHook = (*User)(nil)

func (u *User) AfterUpdate(ctx context.Context) error {
	fmt.Println("After Update")
	return nil
}
```

I defined my database queries in a different file (datastore/users_store.go):
```go
func (db *Sqlstore) UpdateUser(user *model.User, columns []string) (*model.User, error) {
	logger.Debug("Update User object by PK.",
		zap.Int("id", user.ID),
	)

	_, err := db.Model(user).Column(columns...).WherePK().Returning("*").Update()
	if err != nil {
		logger.Error("Couldn't update User object by PK. SQL error occoured.", zap.Error(err))

		return nil, model.NewDatastoreError("users", "update_user", map[string]interface{}{
			"code": model.ErrCodeUnkownSQL,
		})
	}

	logger.Info("Updated User object successfully.")

	return user, nil
}
```

I've already looked in the hook_test.go, but obviously I'm missing or doing something wrong.
Maybe the problem is that I call the model in a different file?! Is my query construct wrong?

Thanks for your help :)
Greetings,
Daniel

**Comment by vmihailenco** [comment]
I don't see anything wrong in the query and it does not matter where model is defined. If this still does not work - please create a program that can be run and that reproduces the problem.
