### ISSUE TITLE
How do I join multiple tables using Relation?

### ISSUE THREAD

**Issue by suren4Kites** [go-pg/pg#1495]
select *
from test1
join test2 on test2.fk1 = test1.id
join test3 on test3.fk2 = test2.id; something like this using Relation?

**Comment by vmihailenco** [comment]
I guess something like `Relation("test2.test3")` - see https://github.com/go-pg/pg/blob/master/db_test.go#L1278-L1280

**Comment by suren4Kites** [comment]
But how can I out the conditions between` test3.fk2 = test2.id` && `test2.fk1 = test1.id`
