### ISSUE TITLE
soft delete with bigint ( unix epoch )

### ISSUE THREAD

**Issue by darioielardi** [go-pg/pg#1496]
Hello, thanks for the great work with this project.

I'm using the soft delete functionality, but I'd like to have my deleted_at column as a bigint ( set to unix epoch on deletion ), which is currently not allowed.
I can work on the implementation myself and make a PR, just let me know if you'd be willing to merge.

**Comment by vmihailenco** [comment]
I will definitely take a look - whether it will be merged or not depends on how much code such feature will require...

**Comment by darioielardi** [comment]
Should be a very simple and concise implementation, just a couple of if statements, queries handling doesn't need to be modified at all.
Seems like there are no tests for soft delete, is that correct?

**Comment by vmihailenco** [comment]
There are some tests but definitely not full coverage. Just grep for `pg:",soft_delete"` - db_test.go:2192 is the main location.
