### ISSUE TITLE
How get field when using Join()  

### ISSUE THREAD

**Issue by l0n3w0lf93** [go-pg/pg#1499]
I have 2 model
`type Book struct{
	id string
	authorID string
	Author Author
	name string
}`
`type Author struct{
	id string
	name string
}`
When i want to get book's author, i do:
`pg.Model(book).Join("LEFT JOIN author ON author.id = book.author_id").ColumnExpr("author.name").First()`
But i can't get author name becasue data return as Book ( not have author name field)
So my question is " How get author name when using JOIN()"
Thanks for watching

**Comment by vmihailenco** [comment]
It is hard to guess what you are trying to achieve - please provide full program that demonstrates the problem if you need help.

**Comment by l0n3w0lf93** [comment]
`
package main

import (
	"fmt"

	"github.com/go-pg/pg"
)

// **** Book table
// ID | Name | AuthorID
// ______________________
// 1  | Book1| 1

// **** Author Table
// ID | Name
// ________________
// 1  | Jame.B

type Book struct {
	ID     string
	Name   string
	Author Author
}

type Author struct {
	ID   string
	Name string
}

func main() {
	book := new(Book)
	err := pg.Model(book).Join("LEFT JOIN author ON author.id = book.author_id").ColumnExpr("author.name").First()
	fmt.Printf("%v", book)
}
`
I need get author info without using relation. Can you help me
