### ISSUE TITLE
Default is not working

### ISSUE THREAD

**Issue by gang018** [go-pg/pg#1500]
Hello

I have a simple model.
```go
type ChatAdmin struct {
	Id int64
	TgId int
	CreatedAt time.Time `pg:"default:now()"`
}
```

With this code I'm trying to insert an instance to the table.
```go
func (m Model) createChatAdminByTgUserID(tgUserId int) (ChatAdmin, error) {
	admin := new(ChatAdmin)
	admin.TgId = tgUserId

	_, err := db.Model(admin).SelectOrInsert(admin)
	return *admin, err
}
```

After insert, I see row in table where created_at == NULL.
Why does `default:now()` not working?

**My postgresql version is:**
PostgreSQL 11.6 (Ubuntu 11.6-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit

**Comment by vmihailenco** [comment]
`pg:"default:now()"` is for `CreateTable` to set SQL `created_at timestamptz DEFAULT now()`. You need to check how generated SQL looks like - https://github.com/go-pg/pg/wiki/FAQ#how-to-view-queries-this-library-generates

**Comment by gang018** [comment]
This is what I see in logs:

`"chat_admins" ("id" bigserial, "tg_id" bigint, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"))`

And this is what I see in heroku dataclip interface:
<img width="503" alt="Снимок экрана 2020-01-16 в 13 55 54" src="https://user-images.githubusercontent.com/2202700/72519455-6c1fd080-3868-11ea-97ac-1d36d10f47cb.png">

**Comment by vmihailenco** [comment]
`"created_at" timestamptz NOT NULL` means that column can't be null.

**Comment by gang018** [comment]
> `"created_at" timestamptz NOT NULL` means that column can't be null.

Yes, but NULL is inserted instead of the value of function `now()`

**Comment by vmihailenco** [comment]
That is impossible - NOT NULL does not allow that.

**Comment by gang018** [comment]
> That is impossible - NOT NULL does not allow that.

That's why I submitted an issue - how does it possible? Maybe there is a bug in method `SelectOrInsert` ?

**Comment by vmihailenco** [comment]
It is impossible on SQL level.

**Comment by gang018** [comment]
Looks like this is a Heroku problem. I've tested this on local database and everything is fine.

**Comment by gang018** [comment]
Thanks for your feedback.
