### ISSUE TITLE
Can not call Where with pg.In or pg.Array

### ISSUE THREAD

**Issue by vctqs1** [go-pg/pg#1501]
Error:
`message: got '(', wanted '{'`
![image](https://user-images.githubusercontent.com/30227910/72545903-618f2680-38bc-11ea-9d13-ed6f2ce57ba3.png)
![image](https://user-images.githubusercontent.com/30227910/72545911-6522ad80-38bc-11ea-85f3-520b71df283b.png)

**Comment by l0n3w0lf93** [comment]
you can try 
` .Where("school_id = (?),pg.In(schoolIDs))`
