### ISSUE TITLE
How to do UPDATE FROM SELECT, ColumnExpr ignored

### ISSUE THREAD

**Issue by theromis** [go-pg/pg#1503]
Running:

```
mymodel = &MyModel{}
db.
Model(mymodel).
                Column("last_message_created", "last_message_text", "last_message_id").
                ColumnExpr(`"new_messages" = s.new_messages`).
                TableExpr("(SELECT COUNT(id) AS new_messages FROM social_message WHERE to_id=? AND user_id=? AND deleted=false AND read=false AND chatroom_id is null) AS s", m.To.Id, m.User.Id).
                WherePK().
                Returning("s.new_messages").
                Update()
```
what gives:
`UPDATE account_connection AS "connection" SET "last_message_created" = ...', "last_message_text" = '...', "last_message_id" = ... FROM (SELECT COUNT(id) AS new_messages FROM social_message WHERE to_id=... AND user_id=... AND deleted=false AND read=false AND chatroom_id is null) AS s WHERE "connection"."id" = ... RETURNING s.new_messages`

My expectation find `"new_messages" = s.new_messages` before `FROM`

So right request should look:
UPDATE account_connection AS "connection" SET "last_message_created" = ...', "last_message_text" = '...', "last_message_id" = ..., `"new_messages" = s.new_messages` FROM (SELECT COUNT(id) AS new_messages FROM social_message WHERE to_id=... AND user_id=... AND deleted=false AND read=false AND chatroom_id is null) AS s WHERE "connection"."id" = ... RETURNING s.new_messages

using `v9.0.1`

What I'm doing wrong? Please help.

**Comment by vmihailenco** [comment]
I would try to replace `ColumnExpr` with `Set`.

**Comment by theromis** [comment]
@vmihailenco Thank you for quick reply, `Set` adding `"new_messages" = s.new_messages` but seems like it overrides `Column`, should I move everything from `Column` to `Set`?
