### ISSUE TITLE
How do I join multiple tables using Relation? 

### ISSUE THREAD

**Issue by suren4Kites** [go-pg/pg#1506]
select *
from test1
join test2 on test2.fk1 = test1.id
join test3 on test3.fk2 = test2.id; something like this using Relation?

You mentioned some thing like this : **I guess something like Relation("test2.test3") - see https://github.com/go-pg/pg/blob/master/db_test.go#L1278-L1280** 

But how can I out the conditions between test3.fk2 = test2.id && test2.fk1 = test1.id

**Comment by suren4Kites** [comment]
I can not reopen it: https://github.com/go-pg/pg/issues/1495
So I created again.

**Comment by vmihailenco** [comment]
Such requestts should come with a small program that reproduces the problem.
