### ISSUE TITLE
Column Level Database Encryption (such as hibernate jasypt)

### ISSUE THREAD

**Issue by bsakweson** [go-pg/pg#1509]
Has anyone successfully implemented column level encryption using this module? I am familiar with this use case, I implemented it  in several applications using JCE and hibernate-jasypt. It is customary now aways to encrypt some fields in their respective columns at rest. Most often, at least the way I have achieved this is by encrypting before storing and decrypting after reading. This is the right time to note that this is different from encrypting the database file system. 

I am thinking of achieving this with lifecycle events but wanted to know if the is better way using tags or annotations.

**Comment by vmihailenco** [comment]
I would create a custom type using this [example](https://github.com/go-pg/pg/blob/master/example_custom_test.go#L13-L49). Encryption should be done in `AppendValue` and decryption in `ScanValue`.

You can also use `BeforeInsert`, `BeforeUpdate`, and `AfterScan` hooks. Probably you will also need `AfterInsert` and `AfterUpdate` to immediately decrypt the fields so the model is still usable. It sounds messy.
