### ISSUE TITLE
Does use_zero work while update row?

### ISSUE THREAD

**Issue by agronomhidden** [go-pg/pg#1510]
Does use_zero work while update row?
In the order of updating row use the structure
```
type Payment struct {
        ...
	Message         string         `pg:"message,notnull,use_zero"`
        ...
}
```
Message is ""
according with https://github.com/go-pg/pg/wiki/FAQ#how-to-insert-zerofalse-value
message field must be ""

but have an error:
`ERROR #23502 null value in column "message" violates not-null constraint`

**Comment by vmihailenco** [comment]
Yes, it should work for update - please provide a program that reproduces the problem.
