### ISSUE TITLE
Simple inner join results in error

### ISSUE THREAD

**Issue by kbokarius** [go-pg/pg#1511]
I'm probably missing something simple here, but we have two tables `groups` and `organizations` Single selects, inserts, etc work just fine, but we just tried an inner join and get the following error:

invalid reference to FROM-clause entry for table "groups"
LINE 4: ON (groups.id = organization_groups.group_id) 

The code:

```
db.GetInstance().Model(&groups).
  Join("INNER JOIN organization_groups").
  JoinOn("groups.id = organization_groups.group_id").
  Where("organization_groups.organization_id = ?", 1).
  Select()
```

The query go-pg generates:

```
SELECT "group"."id", "group"."name", "group"."description", "group"."created_at", "group"."updated_at" FROM "groups" AS "group" 
INNER JOIN organization_groups 
ON (groups.id = organization_groups.group_id) 
WHERE (organization_groups.organization_id = 1)
```

As you can see, go-pg is aliasing `groups` as `group` in the query, and is thereby breaking the join code that uses `groups.id`. If we change the join code to use `"\"group\".\"id\"` instead of `groups.id` then it works, but that doesn't seem like the right solution.

What am I missing? Is there a better way write that join code, or is there a missing mapping?

**Comment by vmihailenco** [comment]
Use `"\"group\".\"id\"` or change table alias for groups table via tableName struct{} `pg:"alias:table_alias"`

**Comment by kbokarius** [comment]
Thank you @vmihailenco
