### ISSUE TITLE
no more description for errors

### ISSUE THREAD

**Issue by SavostinVladimir** [go-pg/pg#1514]
Hello! 
I try to do simple query but get error: `EOF` and no more description

There is a query, generated by pg/v9:
`INSERT INTO delays AS "exchange"
("exchange", "get_all_orderbooks", "proto", "delay")
VALUES 
('dsx', DEFAULT, 'REST', 100) 
ON CONFLICT (exchange) 
DO UPDATE 
SET 
get_all_orderbooks=EXCLUDED.get_all_orderbooks, 
delay=EXCLUDED.delay, 
proto=EXCLUDED.proto 
RETURNING "get_all_orderbooks"
`

**Comment by vmihailenco** [comment]
I admit it is strange. Not sure what you expect from me.

**Comment by ardenn** [comment]
@SavostinVladimir Did you ever figure out what caused this?
