### ISSUE TITLE
ColumnExpr for Insert

### ISSUE THREAD

**Issue by tpoxa** [go-pg/pg#1515]
I would like to do next.
I have a model like this
```
type Revision struct {
Name string
Number int 
}
```
During insert I would like override value of number by expression like nextval('sequence')
So during read number will be populated by actual integer stored in database.

Is it possible?
Thanks.

**Comment by tpoxa** [comment]
Maybe number should be some interface{} and library has special type which will suppress quotation?

**Comment by vmihailenco** [comment]
That should be possible with `Value`, e.g. `db.Model(&rev).Value("number", "nextval('seq')").Insert()`

**Comment by tpoxa** [comment]
Wow. It was so obvious. Thank you. Sorry for bothering you.

**Comment by mojtabacazi** [comment]
@vmihailenco Where can I find documentation for `Value` function? Does it work with Update? Also is it possible to add place holders instead of passing the quoted string?
