### ISSUE TITLE
Prepared statements, reconnections and Stmt.Close()

### ISSUE THREAD

**Issue by ppai-plivo** [go-pg/pg#1518]
* Are prepared statements (`*pg.Stmt`) reusable when there has been an internal network reconnection ? Or should application recreate prepared statement using `OnConnect` hook ?
* Can prepared statements share a connection pool ?

`database/sql` [defines](https://golang.org/pkg/database/sql/#Stmt) its behaviour as follows:

> Stmt is a prepared statement. A Stmt is safe for concurrent use by multiple goroutines. If a Stmt is prepared on a Tx or Conn, it will be bound to a single underlying connection forever. If the Tx or Conn closes, the Stmt will become unusable and all operations will return an error. If a Stmt is prepared on a DB, it will remain usable for the lifetime of the DB. When the Stmt needs to execute on a new underlying connection, it will prepare itself on the new connection automatically.

It'll be great if prepared statement's behaviour related to connection pooling and reconnections are documented.

And thank you for writing pg 👍

**Comment by vmihailenco** [comment]
I believe the quote is true for go-pg except `Tx` clause

>If a Stmt is prepared on a Tx or Conn, it will be bound to a single underlying connection forever. If the Tx or Conn closes, the Stmt will become unusable and all operations will return an error.

In case of Tx+Stmt go-pg behavior currently is not specified...

**Comment by ppai-plivo** [comment]
Thank you for your reply. 

I have a Go application that only runs a prepared `SELECT` statement and does not use `Tx`. Can I safely assume that I can instantiate a `*pg.Stmt` at the startup and use it through-out the lifetime of Go application, calling `pg.Stmt.Close()` at the shutdown ?

Is one instance `*pg.Stmt` of mapped to only one underlying connection ? When there's load, can `*pg.Stmt` utilise connection pool ?

**Comment by vmihailenco** [comment]
>Can I safely assume that I can instantiate a *pg.Stmt at the startup and use it through-out the lifetime of Go application, calling pg.Stmt.Close() at the shutdown ?

Yes, go-pg is supposed to re-connect on any failures.

>Is one instance *pg.Stmt of mapped to only one underlying connection ?

Yes, only one connection is used.

>When there's load, can *pg.Stmt utilise connection pool ?

`*pg.Stmt` always uses single connection no matter what the load is.

**Comment by ppai-plivo** [comment]
Thanks @vmihailenco
