### ISSUE TITLE
use_zero with null and 0 values

### ISSUE THREAD

**Issue by jeffreydwalter** [go-pg/pg#1520]
Is it possible to have a column that is null on insert/update and later is updated to take a 0 value? I haven't been able to make that work and haven't found any good examples of something like this.

**Comment by vmihailenco** [comment]
There is no such option but plenty of workarounds:
- db.Set("col = 0").Update()
- db.Value("col", 0).Update()
- or using separate model/struct for updates

**Comment by jeffreydwalter** [comment]
None of those really work for me. It would be nice to have a way to toggle that behavior with Insert() and Update(). Maybe something like:
```
db.UseZero().Insert(model) // If you didn't specify use_zero, but wanted to temporarily have that behavior.
and/or
db.UseDefaults().Insert(model) // If you specified use_zero, but wanted to insert nulls/defaults.
```
