### ISSUE TITLE
Count without a second query to DB

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1524]
I'm using this code to query for a "cursor" GraphQL pagination (https://codeburst.io/graphql-pagination-by-example-part-3-e010d9baa126).

```go
err := r.db.Model(&players).Where("id > ?", after).Limit(*first).Select()
```

Is there a way to also have `TotalCount` (total number of players) without a second query to DB?

**Comment by vmihailenco** [comment]
I am not aware of any practical way to achieve that, but you will have a better chance to get an answer at sites like stackoverflow etc.
