### ISSUE TITLE
How to quickly do First or Create?

### ISSUE THREAD

**Issue by sonhnguyen** [go-pg/pg#1525]
I need to do some kind of pattern where I query for a records using a condition, if it is not exist then I will insert it with a bunch of values or if it exists I can take the full record. How do I do this in go-pg?
I am coming up with something like this but idk if it is redundant querying
```
	exists, _ := DB.Model(&jsonResult).Where("url = ?", link).Exists()
	if exists {
		DB.Model(&jsonResult).Where("url = ?", link).Select()
	} else {
		// do a bunch of logic and finally insert the record.
		DB2.Insert(&jsonResult)
	}
```

**Comment by vmihailenco** [comment]
Please take a look at https://godoc.org/github.com/go-pg/pg#example-DB-Insert-SelectOrInsert
