### ISSUE TITLE
How to load nested associations? 

### ISSUE THREAD

**Issue by sonhnguyen** [go-pg/pg#1526]
```
type Product struct {
	Variants                  []Variant      `json:"variants"`
	Name                      string         `json:"site"`
}

// Variant Variant
type Variant struct {
	gorm.Model
	Title       string         `json:"title"`
	Options     []Option       `json:"options"`
	ProductID   uint           
}

// Option Option
type Option struct {
	gorm.Model
	Name                string    `json:"name"`
	VariantID           uint      
}
```

Say I have a Product with many Variants and each variant has many Options. Is there a way to preloads those associations for a list of products?

```
user := new(User)
err := db.Model(user).
    Column("user.*").
    Relation("Profiles", func(q *orm.Query) (*orm.Query, error) {
        return q.Where("active IS TRUE"), nil
    }).
    First()
if err != nil {
    panic(err)
}
```

I have been trying something like this but not sure how to load for a `products []Product]` and how loading all the nested associations `Options` would works

**Comment by aliereno** [comment]
I believe this will work.
` var products [ ]Product
err := db.Model(&products).
    Column("product.*").
    Relation("Variants").
    Relation("Variants.Options").
    Select()
`
