### ISSUE TITLE
discard_unknown_columns doesn't work

### ISSUE THREAD

**Issue by dink10** [go-pg/pg#1527]
I used github.com/go-pg/pg/v9 v9.1.3

And  write 
tableName struct{} `json:"-" pg:",discard_unknown_columns"`

 and after that I have error 

`{"level":"error","msg":"ERROR #42703 column \"count\" of relation \"applications\" does not exist","time":"2020-02-25T12:00:01+03:00"}`

**Comment by vmihailenco** [comment]
Please provide a program that reproduces the problem.

**Comment by dink10** [comment]
Why did you close this issue? Nice solution for resolving problem
