### ISSUE TITLE
Where for a stable sort

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1530]
I'm trying to create a

```sql
where (score, id) > (11266, 4482)
```

using a code like this:

```go
var left string
var right string
// question is e.g.: "score:11266-id:4482"
c := strings.Split(*question, "-")
for _, v := range c {
  cc := strings.Split(v, ":")
  left += cc[0] + ","
  right += cc[1] + ","
}
query.Where("( ? ) > ( ? )", left, right)
```

the result is:

```sql
WHERE (( 'amount,id,' ) > ( '11266,4482,' ))
```

which is obviously wrong because of `'`.

What do you suggest?

Is there a `.Where()` like this in go-pg?

**Comment by vmihailenco** [comment]
You are probably looking for `query.Where("( ? ) > ( ? )", pg.Ident(left), pg.Ident(right))`

**Comment by frederikhors** [comment]
Nope.

Now the query is:

```sql
( ( "score,id" ) > ( "11266,4482" ) ) 
```

Still `"` around `right`.

**Comment by frederikhors** [comment]
And is wrong the `left` side too.

It should be

```sql
where (score, id) > (11266, 4482)
```

not 

```sql
where ( ( "score,id" ) > ( "11266,4482" ) ) 
```

**Comment by frederikhors** [comment]
Is it wrong if I use this right?

```go
"(" + strings.TrimRight(left, ",") + ")>(" + strings.TrimRight(right, ",") + ")"
```

Because I'm vulnerable to sql injection, right?

**Comment by vmihailenco** [comment]
I meant `query.Where("( ? ) > ( ? )", pg.Safe(left), pg.Safe(right))`, but `left` and `right` must be safe from SQL injections.

**Comment by frederikhors** [comment]
Oh, thanks for the reply. Now works.

But I seem to be climbing an endless mountain as a blind man.

I read the docs of everything because I want to learn more and more.

For `pg.Safe` I can read:

```
type Safe string
Safe represents a safe SQL query.
```

**Why do I need it here?**

And when you say:

> but left and right must be safe from SQL injections.

how can I be sure?

I am trying to write a cursor pagination for my graphql back-end.

My client send me cursor like this:

`score:11266-id:4482`

but they can also be multiple columns (of various types of course), e.g.:

`createAt:2020-02-27 08:57:36.774147+00-value:159-score:11266-id:4482`

For sql injection prevention I need to check type of every value?

---

I would love to increase the doc of go-pg (which I love).

But first I need to understand.

Thanks for your commitment.

**Comment by frederikhors** [comment]
Ok. I'm slowly realizing that pg.Safe () isn't good in this case because it's terribly dangerous!

**Comment by frederikhors** [comment]
What do you recommend to secure those strings?

Check all types of values that arrive before stringing them?

**Comment by wwwarrior** [comment]
> Ok. I'm slowly realizing that `pg.Safe()` isn't good in this case because it's terribly dangerous!

Exactly.

@vmihailenco Can you please explicitly state the danger of SQL injections in the [documentation](https://pg.uptrace.dev/placeholders/#sql-placeholders), because currently it's not obvious. 
The same for the [bun](https://bun.uptrace.dev/guide/placeholders.html) library. As a Security Engineer, I've encountered SQLi vulnerabilities when using the `Safe()` function.
