### ISSUE TITLE
Missing documentation and/or reference for struct field tags

### ISSUE THREAD

**Issue by doppelganger113** [go-pg/pg#1531]
**Issue**
I was not able to find the **list of all tags** that can be used on the fields when constructing model. Only correlation was in the Genna library when generating models and in a couple of examples in the documentation.

**Solution**
Add documentation explaining what tags can be used or add a mention and a link to the page where the tags are defined.

**Comment by vmihailenco** [comment]
There ls list of struct fields tags at https://github.com/go-pg/pg/wiki/Model-Definition
