### ISSUE TITLE
Cursor pagination

### ISSUE THREAD

**Issue by moh-abk** [go-pg/pg#1535]
does `go-pg` support cursor pagination where a query contains `page_size` and `page_token` and a `next_page_token` is returned as described in this article - https://engineering.mixmax.com/blog/api-paging-built-the-right-way/

**Comment by tinhenouvo** [comment]
i written a util to generate page_token with default limit in config. and send limit, offset to sql. may be this one help you

**Comment by vmihailenco** [comment]
You definitely can use token/cursor based pagination with go-pg, but go-pg does not have such functionality built-in. Perhaps @tinhenouvo can share something.

My recommendation would be to not bother with "right" pagination - it is is too limited and too complicated. `LIMIT OFFSET` is slow but extremely simple and flexible. That is what I use by default.

**Comment by tinhenouvo** [comment]
ya, its OFFSET is slow, but if you already CREATE INDEX for a table you can remove OFFSET in query and change it to WHERE index < offsetParam @vmihailenco.
my function look like this : 
```tokenData := PageTokenRequest{
		Page:   page,
		Date:   date,
		Offset: int(config.Limit20 * page),
	}
	tokenString, _ := json.Marshal(tokenData)
	encodedString := base64.StdEncoding.EncodeToString(tokenString)```

**Comment by moh-abk** [comment]
I've created a util to do real cursor pagination - https://github.com/SeamPay/gopgpager
