### ISSUE TITLE
How to join table with itself?

### ISSUE THREAD

**Issue by tpoxa** [go-pg/pg#1538]
I want to simulate such join using go-pg

`SELECT child.id, child.node, child.pid, child.depth, child.lft, child.rgt FROM table1 AS child, table1 AS parent WHERE  ...`

What will be better approach? Is it possible to join table using relations by primary key?

Thanks in advance.

**Comment by vmihailenco** [comment]
TBH I think that generating query like that using go-pg query builder is the cleanest and most flexible approach.

There is an example with self relation at https://godoc.org/github.com/go-pg/pg#example-DB-Model-HasManySelf, but it is hard to tell if that is enough for your needs or not. I personally don't use ORM - building queries with `db.Model...` is enough for me.
