### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by llakes** [go-pg/pg#1542]
I cant get go-pg to connect to two databases simultaneously in two different applications. The last database to be initialized would hang and connects until I kill the other application that runs the second database. What am i doing wrong? I connect like this:
     `
       DB = pg.Connect(&pg.Options{
                        User:     DBUser,
                        Password: DBPasswordName,
                        Database: DBName,
                })
     ` 
Thank you.

**Comment by vmihailenco** [comment]
Most likely you take some global locks to initialize the app - google for "postgres lock timeout". Overall this is not a go-pg problem.
