### ISSUE TITLE
Query with relation projection only works with dummy model value

### ISSUE THREAD

**Issue by NathanBaulch** [go-pg/pg#1547]
I need to generate a list of IDs through a M:1 (belongs-to) relationship in go-pg v9.1.3. This only seems to work if I use a dummy model value instead of the normal `(*my_struct)(nil)` pattern used in the docs.

```go
var ids []uint64
// WORKS
db.ModelContext(ctx, &model.Foo{}).Column("_").Relation("BelongsTo.id").Select(&ids)
// FAILS
db.ModelContext(ctx, (*model.Foo)(nil)).Column("_").Relation("BelongsTo.id").Select(&ids)
```

For consistency sake (and the sanity of other devs that encounter this) it seems like this should be supported.

**Comment by vmihailenco** [comment]
Should be fixed in v9.1.5
