### ISSUE TITLE
DISTINCT query on jsonb array column

### ISSUE THREAD

**Issue by jdhom** [go-pg/pg#1553]
Enjoying learning this orm framework. I'm trying to represent this query in pg-orm... it returns a set of names.

```sql
SELECT DISTINCT(elements ->> 'entityName') AS unique_service_name
FROM scoring.problems
    CROSS JOIN jsonb_array_elements(ranked_impacts) AS elements
```

Output:

```
zuul-svc-training Tomcat
cust-svc-prod AuthorizedUserController
pss-ae-api-decision-tree-prod-start-user-flow
pss-ae-api-hv-session-prod-es-logs-plugin
pss-ae-hv-mixpanel-worker-prod-onSessionEvent
```

`.Distinct()` doesn't support parameters and `DistinctOn()` looks like different semantics (grouping related). I didn't have any luck finding examples. Skimmed the codebase/tests but can't _connect the dots_.

note: using the hook functionality to see the generated sql has been a big help

I thought the query would map like this, but `.Distinct()` no likey. How do I specify the mapping of the `CROSS JOIN` elements to DISTINCT? (`"elements ->> 'entityName'" AS service_name`)

```sql
	var services []string
	type ServiceResult struct {
		tableName    struct{}    `pg:"scoring.problems"`
		serviceName []string
	}
	var serviceNames ServiceResult
	err := db.Model(&serviceNames).
		Distinct("elements ->> 'entityName' AS service_name").
		Join("CROSS JOIN jsonb_array_elements(ranked_impacts) AS elements").
		Select()
	if err != nil {
		checkErr(err)
	}

```

**Comment by jdhom** [comment]
A little closer? Trying `ColumnExpression()`... think I'm getting the right result set (90 entries) but failing to map the `entity_name` back to the structure (tried adding pg metadat to entityName, no joy).

```go
	type ServiceResult struct {
		tableName      struct{} `pg:"scoring.problems"`
		entityName     string
	}
	var serviceNames []ServiceResult
	err := db.Model(&serviceNames).
		Distinct().
		ColumnExpr("elements ->> 'entityName' AS entity_name").
		Join("CROSS JOIN jsonb_array_elements(ranked_impacts) AS elements").
		Select()
```

Generated SQL...

```sql
SELECT DISTINCT elements ->> 'entityName' AS entity_name FROM scoring.problems AS "service_result" CROSS JOIN jsonb_array_elements(ranked_impacts) AS elements <nil>
```

**Comment by jdhom** [comment]
Take 3... something that works... feedback appreciated.

```sql
	type ServiceResult struct {
		tableName  struct{} `pg:"scoring.problems"`
		entityName string
	}
	var services []string
	err := db.Model((*ServiceResult)(nil)).
		Distinct().
		ColumnExpr("elements ->> 'entityName'").
		Join("CROSS JOIN jsonb_array_elements(ranked_impacts) AS elements").
		Select(&services)
```

**Comment by vmihailenco** [comment]
Are there any problems with "Take 3"? I was not aware of `DISTINCT(elements ->> 'entityName')` syntax.

**Comment by jdhom** [comment]
`Take 3` is what I ended up using. I'm new to the postgres json data type expressions, reference [json operators here](https://www.postgresql.org/docs/9.4/functions-json.html#FUNCTIONS-JSON-OP-TABLE).

`DISTINCT(elements ->> 'entityName')` is getting the text value for the key.

The ability to hook and display the generate SQL for the orm query was invaluable as a learning aid. Was a lot of _new stuff_ in this query for me.

**Comment by jdhom** [comment]
Solution working, issue solved for me. Thanks.
