### ISSUE TITLE
Explain retry logic

### ISSUE THREAD

**Issue by georgysavva** [go-pg/pg#1555]
Can you explain, what operations are subject to retry?
I can see in the code you do retries in db.Exec() and tx.Begin(). But I didn't find any retries in the tx.Commit() and tx.Exec() for example. 
As I understand we can safely retry all read queries, because they don't change anything. But for writes the operation should be idempotent to be safe to retry.

**Comment by vmihailenco** [comment]
The intention is to retry whenever possible. `Tx` are not retried because it does not seem to be 100% safe and I am not sure whether there are case where such retries would improve anything.

>As I understand we can safely retry all read queries, because they don't change anything. But for writes the operation should be idempotent to be safe to retry.

Agreed

**Comment by georgysavva** [comment]
Got it. Thanks!
