### ISSUE TITLE
Execute QueryHooks on CopyFrom/To

### ISSUE THREAD

**Issue by xakep666** [go-pg/pg#1564]
These hooks are very helpful for debugging query generation, latency measurement, etc. 
But currently it's not executed for CopyFrom/To.
If it's ok I can make PR to enable query hooks for copy commands.

**Comment by vmihailenco** [comment]
>If it's ok I can make PR to enable query hooks for copy commands.

Please do if you have time - if it fits naturally there should not be a problem merging it :)
