### ISSUE TITLE
ExcludeColumn from Relation

### ISSUE THREAD

**Issue by jarredwitt** [go-pg/pg#1566]
I'm trying to exclude certain columns from a relation and I keep getting a can't find column error. Here is my code:

```
db.Model(&session).Relation("User", func(q *orm.Query) (*orm.Query, error) {
  return q.ExcludeColumn("password"), nil
}).Where("access_token = ?", t).First()
```

I get the following when I try to execute that query - `pg: can't find column="password"`.

Is there another way to exclude columns from a relation or am I just missing something from the code above?

**Comment by jarredwitt** [comment]
Trying to debug the issue and I found that when the relation is a `HasOneRelation` the `apply` func gets a pointer to current query instead of a new query that is specific to the relation model. Here's the line I'm referencing - https://github.com/go-pg/pg/blob/7b79025886fda7dc26d6077e61a27ab8b51afefd/orm/query.go#L401

I'm new to go-pg so could be completely off. Still trying to debug but if that helps point anyone in the right direction that is willing to take a look at this issue.

**Comment by jarredwitt** [comment]
After lots of debugging (and learning more about go-pg) I figured out how to solve my issue. Ended up being able to exclude the columns that I wanted by setting up the relation as follows:
```
Relation("User", func(q *orm.Query) (*orm.Query, error) {
  join := q.TableModel().GetJoin("User")
  join.Columns = model.UserSafeColumns
  return q, nil
})
```

**Comment by kaffineaddict** [comment]
I still think this should be marked as a bug and fixed. I would expect the following to work

```
db.Model(&session).Relation("User").ExcludeColumn("users.password").Where("access_token = ?", t).First()

db.Model(&session).Relation("User").ExcludeColumn("session.value").Where("access_token = ?", t).First()
```

When ExcludeColumns is used the alias is stripped. But if you do the inverse and use .Columns() to list all of the columns the alias isn't stripped.
