### ISSUE TITLE
Define conditions in the relation

### ISSUE THREAD

**Issue by Janther** [go-pg/pg#1567]
Hi,
At the moment I'm doing this manually but I figure this could be done by the ORM.

```Golang
type User struct {
  ID       int
  Gender   string
  MotherID int
  Mother   User `pg:"where:gender = 'female'"`
  FatherID int
  Father   User `pg:"where:gender = 'male'"`
}
```

I'm new to Go so what I suggested might be impossible but it feels similar to the way polymorphic relations are defined.

**Comment by vmihailenco** [comment]
I don't think that implementing SQL on top of struct tags is a viable idea. But let me know if you have any luck :)

Please see https://github.com/uptrace/go-treemux-realworld-example-app/blob/master/blog/article_filter.go#L12-L20 for an example how to implement filters.
