### ISSUE TITLE
Ommit fields

### ISSUE THREAD

**Issue by hazcod** [go-pg/pg#1568]
Hi, i'm inserting my object with `tx.Insert(&Object)`.
However, is there a way to ommit fields from being inserted? 
In this case it's an uint32 which functions as the primary key, which I want to be autogenerated.

At the moment I am doing this:
```go
func (d *Domain) BeforeInsert(db orm.DB) error {
	if d.Id != 0 {
		return errors.New("id must be zero (null)")
	}
}
```

**Comment by vmihailenco** [comment]
You can use `Query.Column` and `Query.ExcludeColumn`

**Comment by hazcod** [comment]
Thank you @vmihailenco , exactly what I was looking for!
