### ISSUE TITLE
Pool connection issues with pg: Conn is in a bad state: EOF

### ISSUE THREAD

**Issue by d7561985** [go-pg/pg#1569]
go-pg version: v9.1.5
postgres version: 11.3
connection options:  default, no ssl

I use  persistent connection and for each db request i use such flow:

```
con := *pg.DB.Conn().WithContext(ctx)
defer con.Close()
```

After  5 min without any request to db, next request obtain error `pg: Conn is in a bad state: EOF`.

Investigation:
In`baseDB::getConn` ->   `db.pool.Get(c)` return not initiated connection that's why function `baseDB::initConn` starts connection process but inside we got `err := db.startup(c, cn, db.opt.User, db.opt.Password, db.opt.Database, db.opt.ApplicationName)` we send actually send connection request to postgres: `writeStartupMsg(wb, user, database, appName)`:

and here i have postgres.log error:
```
incomplete startup packet
```
also i observe in the log `invalid length of startup packet`

**Comment by vmihailenco** [comment]
This situation will be improved by https://github.com/go-pg/pg/pull/1574, but overall Conn does not have proper retries and generally you should not use it. It is for exceptional situations when you need to use the same connection for your requests.
