### ISSUE TITLE
AfterInsert hook is called even though record was not inserted

### ISSUE THREAD

**Issue by edalford11** [go-pg/pg#1597]
Consider the following code

```go
notification := &ChallengeNotification{
    UserID:      challenge.UserID,
    ChallengeID: challenge.ID,
    Type:        ChallengeNotificationTypeApproved,
}
ctx := context.WithValue(db.Context(), "db", db)
_, err := db.WithContext(ctx).Model(notification).
    OnConflict("(user_id,type,challenge_id) DO NOTHING").
    Insert()
```

If the insert hits the conflict and does nothing as we are instructing it to, the AfterInsert hook on ChallengeNotification is called. I currently have to work around this by doing the following

```go
func (notification *ChallengeNotification) AfterInsert(ctx context.Context) error {
    if notification.ID == 0 {
        return nil
    }

        .....
}
```

**Comment by vmihailenco** [comment]
Well, I see what you mean but I am not sure it makes sense to change current behavior. For example, in case of batch/multi insert this becomes complicated and there is no easy way to check which record was inserted and which was ignored.

**Comment by edalford11** [comment]
@vmihailenco  I see that makes sense. Can we explore potentially using something like the following for all insert queries?

```sql
RETURNING *, (xmax = 0) AS inserted;
```
If xmax is 0, that means the row was inserted and not updated, thus allowing us to call AfterInsert accordingly. Though this is subject to PG's use of xmin/xmax, I think it is unlikely to go unchanged. Thoughts?

**Comment by vmihailenco** [comment]
That is very complicated for small benefit. Right now even `RETURNING *` will not do what you expect. I prefer to leave this complexity to users :) I imagine we need better/more hooks but not something like this.
