### ISSUE TITLE
Log duplicated migration versions

### ISSUE THREAD

**Issue by Barben360** [go-pg/pg#1605]
With a large project, it sometimes happen that SQL migrations with the same number are merged altogether.

It seems that go-pg detects that there are several files X_[...].tx.up.sql with the same value of X and does not make the migrations. However, this detection is not logged.

Would it be possible to have a log entry when detected?

**Comment by vmihailenco** [comment]
This issue should be in https://github.com/go-pg/migrations

go-pg/migrations returns an error when there is a duplicate - https://github.com/go-pg/migrations/blob/master/collection.go#L383-L386. You can log it if you want to.
