### ISSUE TITLE
OnConflic Do Nothing sql print wrong

### ISSUE THREAD

**Issue by HobbyBear** [go-pg/pg#1607]
when i use OnConflict with go-pg in 7.0 this sql method return err is nil but print err msg can not bulk-insert empty slice ,this sql is realy valid .

**Comment by HobbyBear** [comment]
```go
db := connect()
	peoples := make([]*people, 0)
	peoples = append(peoples, &people{
		Id:        4,
		UpdateAt:  time.Time{},
		DeleteAt:  time.Time{},
	})
	peoples = append(peoples, &people{
		Id:        6,
		UpdateAt:  time.Now(),
		DeleteAt:  time.Now(),
	})
	_, err := db.Model(&peoples).OnConflict("do nothing").Insert()
	if err != nil{
		fmt.Println(err)
	}
```

but the consle print sql is  (the go-pg is v8)

```go
SELECT 1 <nil>
连接成功
INSERT INTO pg_test AS "people" ("id", "updated_at", "delete_at") VALUES () ON CONFLICT do nothing RETURNING "updated_at", "delete_at" <nil>

```

**Comment by vmihailenco** [comment]
pg v9 should return you an error. Overall you are supposed to check if there is anything to insert:

```go
if len(peoples) == 0 {
    return nil // nothing to insert
}
```

**Comment by invernizzie** [comment]
@vmihailenco as you can see in HobbyBear's code above, they are appending to the slice before calling `Insert`.

This is an issue with hooks or query formatting itself—I suspect that query appending is not idempotent and, in this case, it seems to break getting the formatted query after it's run.

After I run an insert with `ON CONFLICT DO NOTHING` I get the error "can't bulk-insert empty slice" from `event.FormattedQuery()`, which I run in an OnQueryProcessed hook, even though the slice I passed is not empty and the insert succeeded. I presume (I haven't read enough of the code) that the slice in the model is mutated at some point.

I'm on v6.7.2. This is what I'm doing:

```go
func logQuery(event *pg.QueryProcessedEvent) {
	if event == nil {
		return
	}
	ctx := event.DB.Context()

	query, err := event.FormattedQuery()
	if err != nil {
		clog.Info(ctx, "Cannot format Postgres query for logging", fields.Error(err))
	}

        // ...more logging
}
```

**Comment by vmihailenco** [comment]
Versions older than v10 are not updated.
