### ISSUE TITLE
AfterUpdateHook with previous values

### ISSUE THREAD

**Issue by ahan** [go-pg/pg#1610]
In `AfterUpdateHook`, I compare the current and previous field value, like `status` field.

If the `status` field value changed, I create a new log in `status watcher table` something like that.

Is there anything like this?
```
func (current *Book, previous *Book) AfterUpdate(ctx context.Context) error {
   return nil
}
```

Or what would be a better idea to achieve this?

**Comment by vmihailenco** [comment]
This would require keeping a copy of old and new values which is rather expensive. You could try to implement something yourself in user space using hooks but I don't have any details. If you need a specific hook - please let me know.
