### ISSUE TITLE
Has one relation ambigous `id` column

### ISSUE THREAD

**Issue by tommiv** [go-pg/pg#1612]
Hi! I'm struggling with has one relation definition with column names without `id` postfix.

Here is a reduced example of what I have:

```sql
CREATE TABLE posts (
    id           int   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by   int   NOT NULL REFERENCES users ON DELETE RESTRICT
);

CREATE TABLE users (
    id   int   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
```

```go
type Post struct {
    tableName struct{} `pg:"posts"`
        
    Id           uint64   `pg:"id,pk"
    CreatedByID  uint64   `pg:"created_by"`
    CreatedBy    *User    `pg:"cbid,fk:created_by"` // <== cbid column does not exist in a table, see explanation below
 // CreatedBy    *User    `pg:",fk:created_by"`  // <== this one doesn't work, see explanation below
 // ... some unrelated data fields
}

type User struct {
    tableName struct{} `pg:"users"`

    Id uint64 `pg:"id,pk"`
 // ... some unrelated data fields
}

post := Post{}

err := ormInstance.
    Model(&post).
    Where("id = ?", postID).
    Relation("CreatedBy").
    Limit(1).
    Select()
```

this code results in `ERROR #42702 column reference "id" is ambiguous` error.

Some explanations:

**I had to use a fake `cbid` column name** in `CreatedBy` field tag. Without it (`pg:",fk:created_by"`) I receive an error that relation `CreatedBy` doesn't exist on `Post` model. I assume this is because I have another field `CreatedByID` with tag `pg:"created_by"` and they conflicted.

**This approach:**
```go
CreatedBy    *User    `pg:"created_by,fk:created_by"`
// NO CreatedByID field
```
also fails with "relation doesn't exist".

**The code above with fake `cbid` column name actually half work**, but it creates slightly incorrect SQL:
```sql
SELECT 
	"post"."id", 
	"post"."created_by", 
	"cbid"."id" AS "cbid__id" 
FROM posts AS "post" 
LEFT JOIN users AS "cbid" 
	ON "cbid"."id" = "post"."created_by" 
WHERE (id = 12) -- <== There it is. The `id` column is presented in `posts` table and `users` table, both PK's
LIMIT 1;
```

**Obviously, it's fixable:**

```go
err := ormInstance.
    Model(&post).
    Where("post.id = ?", postID).
    Relation("CreatedBy").
    Limit(1).
    Select()
```
Now everything works. But I'm pretty sure I'm doing something wrong as I probably should't mention exact table name in `where` clause.

Could someone help?

**Comment by firmanalams** [comment]
yeah, i am using that way too
maybe there is another way to achieve that? 
glad to hear that

**Comment by vmihailenco** [comment]
Sorry, but it is very confusing where you have `created_by` column and where you don't. I can't wrap my head around that.

>Now everything works. But I'm pretty sure I'm doing something wrong as I probably should't mention exact table name in where clause.

You should mention exact table name - that is how SQL works. Anything else would mean that we would have to parse SQL and rewrite it replacing the names.
