### ISSUE TITLE
cannot find package "github.com/vmihailenco/msgpack/v5"

### ISSUE THREAD

**Issue by johnhill2424** [go-pg/pg#1614]
I'm running "go get ./..." to get and install the dependencies for my application but am getting this error. I see that this repo import the package "github.com/vmihailenco/msgpack/v5" in the file orm/msgpack.go. Any ideas on why it's saying it can't find the package?

**Comment by vmihailenco** [comment]
Perhaps you are no using Go Modules?

**Comment by johnhill2424** [comment]
I am using packages but not modules

**Comment by vmihailenco** [comment]
This package requires Go modules - see https://github.com/go-pg/pg#get-started
