### ISSUE TITLE
pg tag for custom table name with capitalized letter

### ISSUE THREAD

**Issue by jtai-omniex** [go-pg/pg#1620]
what's the correct way to reference a table that starts with a capitalized letter? i'm currently using:
```
type Asset struct {
	tableName struct{}  `pg:"Asset,discard_unknown_columns"
        ...
}
```
but queries to this table still try to use "asset". I've also tried using an alias like `pg:"Asset,alias:Asset"` to no avail. Is this possible?

**Comment by vmihailenco** [comment]
Try `pg:"\"Assert\""` - see https://pg.uptrace.dev/guide/models.html#naming-conventions for details.
