### ISSUE TITLE
How to get back an id returned via upsert

### ISSUE THREAD

**Issue by kozyr** [go-pg/pg#1622]
I've created an upsert like this:
`db.Model(myModel).Returning("id").
		OnConflict("(field_a) DO UPDATE set field_b=EXCLUDED.field_b").
		Insert()`

and now I'd like to read the returned id. How would I do that? All the examples I've seen ignore the result returned by the insert/update queries.

**Comment by vmihailenco** [comment]
It should work as is - returned columns are automatically scanned into the struct.

**Comment by kozyr** [comment]
Indeed it does!
