### ISSUE TITLE
Possible to only return subset of a model?

### ISSUE THREAD

**Issue by tyrong** [go-pg/pg#1625]
Hi this has probably been asked but i can't seem to find anything about it.
Im writing a rest endpoint that allows user to specify a `?field` query to only get fields that the user needs. It works fine however go-pg returns the object with falsy values.

Is it possible to omit values from the model that aren't included inside the `Column`.
Has anyone managed to implement this sort of logic?

Example:
Model:
```
type Endorsement struct {
  ID             int    'json:"id" pg:",notnull,pk"'
  title          string json:"string"'
}
```

Currently happening:
Query: `?fields=id`
Response:
```
{
  "id": "1234",
  "title": ""
}
```

Desired response:
```
{
  "id": "1234",
}
```

**Comment by vmihailenco** [comment]
It is definitely possible to return subset of model using `Query.ColumnExpr`, but that will not help with JSON serialization.

AFAIK you have following options:
- use omitempty json flag
- wait until go-pg supports scanning into `map[string]interface{}`
- use some other JSON library
