### ISSUE TITLE
What is the best parctises for go-pg in web development

### ISSUE THREAD

**Issue by ray1888** [go-pg/pg#1629]
To my confuse, i can't find any turtorial for use go-pg in web development in tdd style.  because go-pg is provide with basic function, but in application level, it is has to abstract an interface for a single table curd actions, which leeds to it is hard to inject the mock interface for db actions. so u guys has any idea of doing something for this kind of issue ?

**Comment by ray1888** [comment]
or should i use gopkg.in/DATA-DOG/go-sqlmock.v1 this module to mock go-pg to transparent the sql layer?

**Comment by vmihailenco** [comment]
I have added all I know to the FAQ - https://pg.uptrace.dev/faq.html#how-to-test-mock-database. I don't use mocks.
