### ISSUE TITLE
Array parameter in exec query

### ISSUE THREAD

**Issue by John-Hung-aimazing** [go-pg/pg#1631]
Hi guys

version in go mod
    github.com/go-pg/pg v8.0.6+incompatible
    github.com/go-pg/pg/v10 v10.0.0-beta.2 // indirect

i met the problem, i not sure it  actually an issue, it not please give me some advise, i appreciate that.

db.Exec(`select * from table where id in (?)`, pg.Array([]int{1,2,3}))

i got an error
ERROR #22P02 invalid input syntax for integer: "[1,2,3]"

in the raw query
it should be select * from table where id in (1,2,3);

Do i miss something?

 thank you guys read this issue

**Comment by vmihailenco** [comment]
It should be `pg.In`, not `pg.Array`.
