### ISSUE TITLE
How do you deal with double sided relations ?

### ISSUE THREAD

**Issue by MohitKS5** [go-pg/pg#1632]
what tags I use for this kind of relation ?
```go
type User struct {
  id string
  profile *Profile
}
type Profile struct {
  id string
  name string
  user *User
}
```
I used `fk:id` but that can be used only on one of them which is created later else while creating the table it says table profile doesn't exist. I want to know the standard way. But if I don't use it go-pg creates a jsonb object of profile in db.

**Comment by MohitKS5** [comment]
```go
type User struct {
  id string
  profile *Profile
}
type Profile struct {
  UserId string
  name string
  user *User
}
```
This worked without use of any tags. `(User{}).Relation("profile")` and `(Profile{}).Relation("user")` both are working as expected.

**Comment by Kangaroux** [comment]
@MohitKS5 If this is resolved can you mark it as closed?

**Comment by MohitKS5** [comment]
I wasn't sure that was a workaround or recommended way
