### ISSUE TITLE
UpdateNotZero does not update nullable fields by design, how to do?

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1635]
I'm having hard time trying to understand how to nullish a model field using `UpdateNotZero()`.

**Example:**

```go
type Player struct {
  ID            int
  CreatedAt     time.Time `pg:"default:now(),notnull"`
  UpdatedAt     time.Time
  AccountID     *int
}
```

Let's say I have this player now:

```
+----+------------+------------+------------+
| ID | created_at | updated_at | account_id |
+----+------------+------------+------------+
|  1 | 2020-06-16 | NULL       |         12 |
+----+------------+------------+------------+
```

in my GO code I need to "remove" `AccountID`, I need to nullish it: from `12` to `NULL`.

If I use `update()` like this: 

```go
...
player.AccountID = nil
_, err := db.Model(player).WherePK().Update()
```

it gives me the error:

```
ERROR #23502 null value in column \"created_at\" violates not-null constraint"
```

If I use `UpdateNotZero()` like this:

```go
...
player.AccountID = nil
_, err := db.Model(player).WherePK().UpdateNotZero()
```

it doesn't update `AccountID` at all.

**How to do?**

---

Related issues I think:

- https://github.com/go-pg/pg/pull/1580
- https://github.com/go-pg/pg/issues/1557

**Comment by vladimirschuka** [comment]
I might be wrong but accountID is int and default value is 0 for this type. If you need NULL maybe you should use  sql.NullInt64.

**Comment by frederikhors** [comment]
In [GORM](https://gorm.io/docs/update.html#Update-Changed-Fields) they say:

```go
// Update single attribute if it is changed
db.Model(&user).Update("name", "hello")
//// UPDATE users SET name='hello', updated_at='2013-11-17 21:34:10' WHERE id=111;

// Update single attribute with combined conditions
db.Model(&user).Where("active = ?", true).Update("name", "hello")
//// UPDATE users SET name='hello', updated_at='2013-11-17 21:34:10' WHERE id=111 AND active=true;

// Update multiple attributes with `map`, will only update those changed fields
db.Model(&user).Updates(map[string]interface{}{"name": "hello", "age": 18, "actived": false})
//// UPDATE users SET name='hello', age=18, actived=false, updated_at='2013-11-17 21:34:10' WHERE id=111;

// Update multiple attributes with `struct`, will only update those changed & non blank fields
db.Model(&user).Updates(User{Name: "hello", Age: 18})
//// UPDATE users SET name='hello', age=18, updated_at = '2013-11-17 21:34:10' WHERE id = 111;

// WARNING when update with struct, GORM will only update those fields that with non blank value
// For below Update, nothing will be updated as "", 0, false are blank values of their types
db.Model(&user).Updates(User{Name: "", Age: 0, Actived: false})
```

So I can use the `map` way to address this with GORM except I hate GORM.

**Comment by frederikhors** [comment]
> I might be wrong but accountID is int and default value is 0 for this type. If you need NULL maybe you should use sql.NullInt64.

@vladimirschuka thanks for your answer. I'm not sure this has something to do with `NullInt64`.

I think every field is `nullable` by default unless I use `notnull`.

Am I wrong?

**Comment by vladimirschuka** [comment]
If I understand correctly, when you have value of variable which is default for Go in the query to DB you have DEFAULT instead of value, and your update (when AccountID = 0 ) will be 
`update .... set account_id = DEFAULT `and of course it is `null `if there is no default value. 
Take a look on DB side what is the query go-pg does.
I had issue with boolean field, because in the DB I had default `true `and when I tried to insert false value query was exactly `= DEFAULT` which is true :)  `use_zero` tag solves the problem.

**Comment by frederikhors** [comment]
@vladimirschuka, with or without `use_zero` is the same in my case.

**Comment by vladimirschuka** [comment]
Have you tried 
`player.AccountID = 0`
`_, err := db.Model(player).WherePK().Update()` ?

**Comment by frederikhors** [comment]
@vladimirschuka the problem with `Update()` is it needs other fields too...

**Comment by mojtabacazi** [comment]
@frederikhors The problem with null-constraint on created-at is a different issue. I think you need to make sure you have a default value in the PG itself not just the struct tag.
As for AccountID shouldn't you  use a pointer  `AccountID     *int`  so you can actually set it to nil and not zero?
I would also add a hook to log queries (before they execute) to see what's actually happening.

**Comment by frederikhors** [comment]
@mojtabacazi

> As for AccountID shouldn't you use a pointer AccountID *int so you can actually set it to nil and not zero?

You're right. I was wrong to copy, but my code has `*int`. Issue updated.

> The problem with null-constraint on created-at is a different issue. I think you need to make sure you have a default value in the PG itself not just the struct tag.

Oh, but I'm **updating** the object. It's already saved in DB and I'm not retrieving it before use `UpdateNotZero()`.

I don't want (because I don't need) a previous query for `SELECT where ID = ...`. I should?

**Comment by vmihailenco** [comment]
To update single column:

```go
player.AccountID = nil
_, err := db.Model(player).Column("account_id").WherePK().Update()
```

or even simpler and more explicit

```go
db.Model(player).Set("account_id = NULL").Where("id = ?", player.ID).Update()
```

In v10 you can also use `map[string]interface{}`:

```go
values := map[string]interface{}{
    "account_id": nil,
}
db.Model(&values).TableExpr("players").Where("id = ?", id).Update()
```

**Comment by frederikhors** [comment]
@vmihailenco I don't always know exactly which columns have changed.

**Comment by vmihailenco** [comment]
https://pg.uptrace.dev/sql-null-go-zero-values/#updating-specific-columns
