### ISSUE TITLE
Feature: add WithContext to pg.TX

### ISSUE THREAD

**Issue by hazcod** [go-pg/pg#1638]
Useful in integration testing where the handler expects a `pg.DB` but we work in `pg.Tx`.
Ideally `pg.DB` should become/contain an interface to use in handler arguments.

**Comment by vmihailenco** [comment]
The problem with `WithContext` is that it returns different types - either `*pg.DB` or `*pg.Tx`. Because of that it can't be an interface.

It is better to use `ModelContext` and `QueryContext` / `ExecContext`.
