### ISSUE TITLE
model does not have relation error even though it is clearly there

### ISSUE THREAD

**Issue by kennethnym** [go-pg/pg#1646]
I have the following structs
```go
type Post struct {
  Author *user.User `pg:"fk:authorid"`
  AuthorID string `pg:authorid`
}

// in another package
type User struct {
  Username String
  Email String
}
```

When I do a query on post like `db.Model(&posts).Relation('Author')`, I am always getting the error saying `model=Post does not have relation=\"author\"`. I tried using `User`, `user` and `author` instead of `Author`, but none worked.

**Comment by AienTech** [comment]
@MrCreeper1008 please take a look at the [example](https://pg.uptrace.dev/models/#example), though I'm not sure, but I guess you must create another relation struct and migrate it to the DB. if you have used other ORMs like gorm, go-pg takes a slightly different approach to create relations as far as I understood.

**Comment by kennethnym** [comment]
Yea I already had a look at the example, but I am still not sure what went wrong. I specified the foreign key field on `Author` that is suppposedly to be filled in by `go-pg`, and I specified the field name on the foreign key field properly.

**Comment by kennethnym** [comment]
A simple workaround for this is to separate the join operations into multiple queries. It seems like the `fk` tag is completely ignored by `go-pg`, because if I don't call `.Relation("Author")` on the model, then `pg` would return an error saying `Column "Author" does not exist.`. I need to tell `pg` to ignore the field with `pg:"-"` in order to fix that.

**Comment by mhodkiewicz1** [comment]
hey, I think I have a similar Problem also with this,

I have a Money relation to User and Money to Purpose

here is mt schema struct 
```
type (

	Money struct {
		tableName       struct{}   		`pg:"money,discard_unknown_columns"`
		MoneyID         string   		`json:"loan_id" pg:",pk"`
		PurposeID   	int        		`pg:",pk"`
		Purpose   	Purpose   	        `pg:"rel:has-one"`
		TotalAmount     int        		`json:"total_amount"`
		UserID          int         	        `json:"user_id" pg:",pk"`
		User             User		        `pg:"rel:has-one"`
	}

	Purpose struct {
		tableName       	struct{}                   `pg:"money_purposes"`
		ID                      int             	   `json:"-" pg:",pk"`
		Name               	string           	   `json:"name"`
	}
       
       User struct {
                tableName       struct{}         `pg:"users"`
                ID               int             `pg:",pk"`
                Email           string 
        }
)
```

take a look at **Purpose** struct on **Money**, it worked, and on the **User** in **Money**, it doesn't work as well, when I use the tag `pg:"fk:user_id"` on the **User** it was work but it said deprecated, I don't what's wrong with it? 

when I use `rel:has-one` on User I always got 

```
pg: Loan has-one Use: Loan must have column use_user_id (use fk:custom_column tag on Use field to specify custom column)
```
and I did what the error said and I have to take a look on example documentation and test go-pg and follow like on the test and doc, but I don't know what is wrong with it, it doesn't work at all always got that above error

**Comment by vmihailenco** [comment]
@MrCreeper1008 you are missing `ID string` field in User struct. This should be handled better in v10.
