### ISSUE TITLE
No supported way and/or bug doing "update join"

### ISSUE THREAD

**Issue by bensussman** [go-pg/pg#1647]
I am attempting to write an "update join" query. See example here: https://www.postgresqltutorial.com/postgresql-update-join/

In my example I want to update rows in my table `r`, but only the rows that have a FK corresponding to rows in a different table `us`. Here is the query i want to write:

```
UPDATE r SET r.us_id = NULL
FROM us
WHERE us.id = r.us_id AND us.user_id = ?
```

There is no documentation on doing a simple query like this, i would want something like this to work:

```
db.Model(new(R)).
		Set("r.us_id = NULL").
		Join("FROM us").
		Where("us.id = r.us_id").
		Where("us.user_id = ?", u.ID).
		Update()
```

But the query it generates is simply excluding the `Join` completely:

```
UPDATE "r" SET r.us_id = NULL WHERE (us.id = r.us_id) AND (us.user_id = 1001)
```

I will write a custom query, but this is a very straightforward query I would like to see is both possible with go-pg and is documented with an example.

**Comment by vmihailenco** [comment]
Replacing `Join("FROM us")` with `TableExpr("us")` should work.

**Comment by bensussman** [comment]
Great, it looks like that will work!

I think this is something that shows how much go-pg would benefit from improved documentation, specifically more complex examples.
