### ISSUE TITLE
Generating Create Table statements from structs with relations

### ISSUE THREAD

**Issue by DuncanGener8** [go-pg/pg#1648]
Hi there,

This isn't a major issue with the project, but it had me pulling my hair out for a couple of hours so I just wanted to make sure you're aware of this behaviour.

When generating tables from structs that contain one-to-many relationships, e.g:

```
type Parent struct {
    ID `pg:"type: uuid,default:uuid_generate_v4()"`
    Children []*Child `pg:"fk:parent_id"`
}

type Child struct {
    ID `pg:"type: uuid,default:uuid_generate_v4()"`
    ParentID string `pg:"type: uuid, notnull"`
    Parent *Parent
}
```

The tags defining the ParentID in the Child struct and the ID in the Parent struct, must match exactly.

That is, if you were to define:
```
type Parent struct {
    ID `pg:"type: uuid,default:uuid_generate_v4()"`
    Children []*Child `pg:"fk:parent_id"`
}

type Child struct {
    ID `pg:"type: uuid,default:uuid_generate_v4()"`
    ParentID string `pg:"type:uuid, notnull"`
    Parent *Parent
}
```

(No space between "type:" and "uuid" in the tag for ParentID) The tables will get generated with 'jsonb' columns for `Children` and `Parent`, respectively.

I imagine that this has something to do with tokenizing the tags & performing exact matches with them somewhere in the guts of the orm.CreateTable() method.

**Comment by vmihailenco** [comment]
Thanks for the report, should be fixed by https://github.com/vmihailenco/tagparser/commit/be04d19a03d0f4739671a500012335e98ebfeb9f
