### ISSUE TITLE
AfterScanHook interface, Relation() v10 beta 5 not working as it should

### ISSUE THREAD

**Issue by burner-account** [go-pg/pg#1650]
#1352 for context, created a new issue since 1352 is closed.

Tested with **v10 beta5** and **go 1.13**:

```
var _ pg.AfterScanHook = (*A)(nil)
var _ pg.AfterScanHook = (*B)(nil)
var _ pg.AfterScanHook = (*C)(nil)

type C struct {
  // ...
}

type B struct {
   C []*C
}

type A struct {
   B  []*B
}

```
Imagine A, B, and C implementing AfterScanHook interface and having proper annotations.

```
// var dbc orm.DB

a_slice := make([]*A, 0)
count, err := dbc.Model(&a_slice).
		Relation("B").
		Relation("B.C").
		SelectAndCount()
```

This will only call the (*A).AfterScan function, but neither (*B).AfterScan or (*C).AfterScan.
The query itself (data fetching, counting) works fine.

I would require some serious guidance before i could try to write up a PR for this. So it is only a report for now.

**Comment by vmihailenco** [comment]
Please try https://github.com/go-pg/pg/pull/1653 - I did not try to run it but code looks right :)

Also it would be nice if you can turn your example into a test. That will ease & speedup development of this feature considerably.

**Comment by burner-account** [comment]
If i get a weekend, you will get the tests.

**Comment by burner-account** [comment]
I will be swamped for the next 2 weeks. But the tests are still on my todo.
