### ISSUE TITLE
UUID primary key does not save JSONB array to database (v10)

### ISSUE THREAD

**Issue by ernsheong** [go-pg/pg#1651]
Previous: My primary key is ID (integer) with UUID (non-pk field)

I switched the primary key to UUID only (no ID), but now I'm seeing that in INSERT and UPDATE, array fields (JSONB) are no longer saved to the database via PG. Before I spend more time providing example code, do you see how/why this can happen in `go-pg`? I also tried manually annotating with `pg:",pk"` but no effect. Other non-array fields get saved. When I revert to ID primary key, JSONB array gets saved

I'm on `v10.0.0-beta.5`

**Comment by ernsheong** [comment]
```go
type Source struct {
	UUID   string               `json:"uuid"`
	URL    string               `json:"url"`
	Fields []*model.SourceField `json:"fields"`
}
```

In the above, with UUID as the primary key, `Fields` is totally ignored in INSERT, SELECT, and UPDATE. When the primary key is ID, Fields works just fine.

```sql
CREATE TABLE sources (
    uuid uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    url text NOT NULL,
    fields jsonb NOT NULL DEFAULT '[]'
)
```

**Comment by vmihailenco** [comment]
I can't reproduce. `db.Model(&Source{}).Insert()` generates

```sql
INSERT INTO "sources" ("uuid", "url") VALUES (DEFAULT, DEFAULT) RETURNING "uuid", "url"
```

**Comment by ernsheong** [comment]
Ah, that is the problem right there. Where is "fields"? It is clashing with `Fields` internally? Still seeing this in 10.3.2

I am also getting:
```
DEPRECATED: pg: 2020/10/08 21:25:58 add pg:"rel:has-many" to Source.Fields field tag
```

Much appreciated if you can point out what is possibly wrong. Thanks

**Comment by ernsheong** [comment]
Issue is still present in 10.6.2

I reverted to integer `id` column, and it is working again. Something is wrong when UUID is the primary key. As you can see above, "fields" is missing from the generated SQL. Hope this can be reopened.

**Comment by vmihailenco** [comment]
Please provide minimal example that reproduces the problem. I can't fix the problem described as "Something is wrong when UUID is the primary key".
