### ISSUE TITLE
INSERT or IGNORE with NULL columns

### ISSUE THREAD

**Issue by hazcod** [go-pg/pg#1654]
Hi, is there a way for an Insert or Ignore to work when some columns are NULL?
Since in relational DBs NULL is difficult to compare.

```go
        // some variables in tech are NULL which will always result in an insert
	if _, err := db.Model(&techs).OnConflict("DO NOTHING").Insert(); err != nil {
		return errors.Wrap(err, "could not insert parameters")
	}
```

**Comment by ernsheong** [comment]
Your question is not very clear.

Does this section help you? https://pg.uptrace.dev/models/#sql-null-and-go-zero-values

> some variables in tech are NULL which will always result in an insert

If you do not want NULLs to result in an insert maybe you need to make the column `NOT NULL` in the database and have the database enforce the constraint

**Comment by hazcod** [comment]
Hi @ernsheong , the values are sometimes NULL but I still need to insert If they differ.
