### ISSUE TITLE
Loaded Relations do not have their AfterSelect hooks invoked v9.1.6

### ISSUE THREAD

**Issue by DuncanGener8** [go-pg/pg#1656]
Hi there,

I'm not sure if I'm missing something, if this has already been reported, or if this is actually a bug, but when I load an object via the 'Relation' method that has an associated AfterSelect hook - this hook does not get executed.

Please find attached, a stripped down example demonstrating the bug.

Here is the output I'm getting:

`
Loaded Parent: ccfe10c7-af38-51aa-9381-eca1ca8c1b0b :: Father
 	Child 0: &main.Child{tableName:struct {}{}, ID:"5540013b-25eb-5768-8c95-9d33eb0aa413", Description:"Son", SetWhenRead:"", Parents:[]*main.Parent(nil)}
 	Child 1: &main.Child{tableName:struct {}{}, ID:"e27a2867-3fe2-5bd1-8021-ac1bd5a60661", Description:"Daughter", SetWhenRead:"", Parents:[]*main.Parent(nil)}
`

This is the output I'd like to be getting:

`
Loaded Parent: ccfe10c7-af38-51aa-9381-eca1ca8c1b0b :: Father
 	Child 0: &main.Child{tableName:struct {}{}, ID:"5540013b-25eb-5768-8c95-9d33eb0aa413", Description:"Son", SetWhenRead:"this has been populated after select", Parents:[]*main.Parent(nil)}
 	Child 1: &main.Child{tableName:struct {}{}, ID:"e27a2867-3fe2-5bd1-8021-ac1bd5a60661", Description:"Daughter", SetWhenRead:"this has been populated after select", Parents:[]*main.Parent(nil)}
`

[relations_example.zip](https://github.com/go-pg/pg/files/4897398/relations_example.zip)

Thanks for all the awesome work on the library!

**Comment by jh125486** [comment]
Have you tried using an `AfterScan` hook instead?

**Comment by DuncanGener8** [comment]
Hi @jh125486 ,

That does the trick in the example provided. I will need to make the time to go and test it in my application to make sure that it works as expected.

Thanks very much for pointing it out - I really don't know why I didn't try that the first time around.

**Comment by DuncanGener8** [comment]
Finally got back around to this & can confirm that AfterScan works as a solution in our production system.

Apologies for keeping this ticket open for so long.

**Comment by wildan2711** [comment]
I don't know if there is a regression, but it does not seem to work using an `AfterScan` hook, using v10.

Here is my related code:
```go
type User struct {
	Id                  string    `pg:",pk" json:"id"`
	Username            string    `json:"username"`
	RatingSum           float64   `json:"rating_sum"`
	RatingNum           uint      `json:"rating_num"`
	RatingAvg           float64   `pg:"-" json:"rating_avg"`
	PhoneNumber         string    `json:"phone_number"`
	Country             string    `json:"country"`
	UpdatedAt           time.Time `json:"updated_at"`
	CreatedAt           time.Time `json:"created_at"`
}

func (u *User) AfterScan(ctx context.Context) error {
	if u.RatingNum > 0 {
		u.RatingAvg = u.RatingSum / float64(u.RatingNum)
	}
	log.Println("average", u.RatingAvg)
	return nil
}

type Review struct {
	SessionId uint      `pg:",pk" json:"-"`
	UserID    string    `pg:",pk" json:"user_id"`
	User      *User     `pg:"rel:has-one" json:"user"`
	Rating    float64   `json:"rating"`
	Note      string    `json:"note"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}

...
var reviews []Review
db.WithContext(ctx).Model(&reviews).Relation("User").Where("session_id=?", sessionID).Select()
```

**Comment by SchillingSebastian** [comment]
@wildan2711 I ran into the same issue. On v10 it seems like there is no invocation of the AfterScan hook on a relational struct. Have you found any way around this?

**Comment by SchillingSebastian** [comment]
Okay for everyone stumbling over this same issue:
Under the hood go-pg uses this [checkup](https://github.com/go-pg/pg/blob/9c3bae97abe54f184c7043c0873b1b6af1a4b495/orm/model_table_struct.go#L189) here to know whether or not to invoke a AfterScan on nested (joined) structs. Therefore invoking a AfterScan on such a joined struct requires a AfterScan Hook on the model containing the nested struct.
So in more simple terms: If you want your nested (joined) AfterScan hook to be invoked, you need an AfterScan Hook in the containing/"parent" model. In case of @wildan2711 you need a AfterScan Hook on the Review e.g:
```Go
var _ pg.AfterScanHook = (*Review)(nil)
func (r *Review) AfterScan(c context.Context) error {
	return nil
}
```
