### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by oluwandabira** [go-pg/pg#1657]
The readme links some examples which don't exist on the doc page. For instance the ForEach link goes to https://pkg.go.dev/github.com/go-pg/pg/v10?tab=doc#example-DB-Model-ForEach where there is no ForEach example.

The [doc page]( https://pkg.go.dev/github.com/go-pg/pg/v10) only has examples for Array, Connect, DB (ArrayValueScanner), DB (DiscardUnknownColumns), DB (JsonUseNumber), DB.WithTimeout, Error, Hstore, Ints, Listener, Scan and, Strings. The readme links invalid examples such for Transactions, PreparedStatements, Copying, Working with the ORM and SQL and so on (so basically, most examples).

**Comment by vmihailenco** [comment]
This is a problem with pkg.go.dev. godoc.org displays example properly - https://godoc.org/github.com/go-pg/pg?tab=doc#example-DB-Model-ForEach

**Comment by oluwandabira** [comment]
So should I close this?

**Comment by vmihailenco** [comment]
I've created https://github.com/golang/go/issues/40172 - let's see what is the feedback.
