### ISSUE TITLE
Multiple entries in slices of deeply nested relations

### ISSUE THREAD

**Issue by robinjoseph08** [go-pg/pg#1664]
### Issue

I believe I may have found a bug with how `go-pg` handles piecing together deeply nested relations. It's actually fairly complicated to explain the exact requirements that cause this to happen, so it's easier to look at the reproduction while you read the explanation.

As you can see in the output JSON both `elephants` arrays contain 2 elements where both elements are identical. However, when you look at the statements that insert into the table and the output of the `SELECT` statement, `dog_1` only has 1 copy of `elephant_1` as a child, so both `elephants` arrays should be of length 1 instead of 2.

My project that I encountered this in is using v9.1.6, but I tried it with v10.0.0-beta.6 as well, and it's still there.

### Reproduction

Here's a script to reproduce the bug. I tried to make it as minimal as possible, but it does seem to require a lot of tables/models.

To run it, you'll need a db running with a user `postgres` and a database `postgres` (like the examples in this repo). You'll also need to run `go mod init foo && go get github.com/go-pg/pg/v10` in the directory to pull in `go-pg`.

```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/go-pg/pg/v10"
)

// models

type Apple struct {
	ID    string  `json:"id"`
	Balls []*Ball `json:"balls"`
}

type Ball struct {
	ID      string `json:"id"`
	AppleID string `json:"-"`
	CatID   string `json:"-"`
	Cat     *Cat   `json:"cat"`
}

type Cat struct {
	ID   string `json:"id"`
	Dogs []*Dog `json:"dogs"`
}

type Dog struct {
	ID        string      `json:"id"`
	CatID     string      `json:"-"`
	Elephants []*Elephant `json:"elephants"`
}

type Elephant struct {
	ID    string `json:"id"`
	DogID string `json:"-"`
}

// main

func main() {
	db := pg.Connect(&pg.Options{
		User:     "postgres",
		Password: "",
		Database: "postgres",
	})
	defer db.Close()

	var n int
	_, err := db.QueryOne(pg.Scan(&n), "SELECT 1")
	panicIf(err)

	statements := []string{
		`CREATE TEMP TABLE apples (id TEXT PRIMARY KEY)`,
		`CREATE TEMP TABLE cats (id TEXT PRIMARY KEY)`,
		`CREATE TEMP TABLE balls (id TEXT PRIMARY KEY, apple_id TEXT REFERENCES apples (id), cat_id TEXT REFERENCES cats (id))`,
		`CREATE TEMP TABLE dogs (id TEXT PRIMARY KEY, cat_id TEXT REFERENCES cats (id))`,
		`CREATE TEMP TABLE elephants (id TEXT PRIMARY KEY, dog_id TEXT REFERENCES dogs (id))`,

		`INSERT INTO apples VALUES ('apple_1')`,
		`INSERT INTO cats VALUES ('cat_1')`,
		`INSERT INTO balls VALUES ('ball_1', 'apple_1', 'cat_1'), ('ball_2', 'apple_1', 'cat_1')`,
		`INSERT INTO dogs VALUES ('dog_1', 'cat_1')`,
		`INSERT INTO elephants VALUES ('elephant_1', 'dog_1')`,
	}

	for _, s := range statements {
		_, err = db.Exec(s)
		panicIf(err)
	}

	a := &Apple{}

	err = db.Model(a).Relation("Balls.Cat.Dogs.Elephants").Select()
	panicIf(err)

	printA(a)
}

// helpers

func panicIf(err error) {
	if err != nil {
		panic(err)
	}
}

func printA(a *Apple) {
	b, err := json.MarshalIndent(a, "", "  ")
	panicIf(err)
	fmt.Println(string(b))
}
```

The output of this script is included for convenience.

```json
{
  "id": "apple_1",
  "balls": [
    {
      "id": "ball_1",
      "cat": {
        "id": "cat_1",
        "dogs": [
          {
            "id": "dog_1",
            "elephants": [
              {
                "id": "elephant_1"
              },
              {
                "id": "elephant_1"
              }
            ]
          }
        ]
      }
    },
    {
      "id": "ball_2",
      "cat": {
        "id": "cat_1",
        "dogs": [
          {
            "id": "dog_1",
            "elephants": [
              {
                "id": "elephant_1"
              },
              {
                "id": "elephant_1"
              }
            ]
          }
        ]
      }
    }
  ]
}
```

And here's an output of a `SELECT` statement of the tables so it's easier to see how they're actually related.

```
postgres=# select
    a.id as apple_id,
    b.id as ball_id,
    c.id as cat_id,
    d.id as dog_id,
    e.id as elephant_id
  from apples a
  inner join balls b on a.id = b.apple_id
  inner join cats c on c.id = b.cat_id
  inner join dogs d on d.cat_id = c.id
  inner join elephants e on e.dog_id = d.id
  order by 1, 2, 3, 4, 5;

 apple_id | ball_id | cat_id | dog_id | elephant_id
----------+---------+--------+--------+-------------
 apple_1  | ball_1  | cat_1  | dog_1  | elephant_1
 apple_1  | ball_2  | cat_1  | dog_1  | elephant_1
(2 rows)
```

### Root Cause

I'm not too familiar with how `go-pg` is organized and how it works, but I spent some time trying to dig into why this was happening, and I found a few things that might be helpful.

I have query debug logging in my project, so it was easy to see if it was a problem with the queries that were being executed, and I don't believe that it is. Everything was returning the correct number of resultant rows. This makes me think it has to do with how `go-pg` is taking the rows and populating the passed in model.

I then used delve to dig into the functions that are being called and how the model gets populated, and that led me to the [`(*manyModel).AddColumnScanner` function](https://github.com/go-pg/pg/blob/cb5d6b69cdc82ba746376ff33940019f2e5d1dad/orm/model_table_many.go#L49-L67) where it iterates through the `reflect.Value`s in `dstValues` that correspond to the correct foreign key.

I _think_ the cause is because the `[]reflect.Value` slice for `dog_1` (which correctly contains 2 `reflect.Value`s, one for the model nested under `ball_1` and the other nested under `ball_2`) contains 2 _identical_ `reflect.Value`s. So the underlying `[]*Elephant` slice that the `reflect.Value` is referencing is the same for both `reflect.Value`s. So when it appends to that slice [here](https://github.com/go-pg/pg/blob/cb5d6b69cdc82ba746376ff33940019f2e5d1dad/orm/model_table_many.go#L60), it will actually append it for both slices (since it's the same slice). And then, when it goes to the next `reflect.Value` in `dstValues` (which is the still the same underlying slice), it will append it again, resulting in both elephants arrays have 2 of the same elements in it.

Thus, I _think_ the solution is to make sure each `reflect.Value` is referencing its own slice, so the fix would be related to the [`dstValues` function](https://github.com/go-pg/pg/blob/cb5d6b69cdc82ba746376ff33940019f2e5d1dad/orm/util.go#L117-L125) or a nested function. I'm not too familiar with the `reflect` package either, so that's why I opted to make this issue rather than a PR.

Hopefully all of this made sense! And if not, let me know and I'll be happy to explain more or provide more examples. And if I get confirmation that this is the issue and a nudge in the right direction, I'd be happy to put up a PR as well! Thanks!

**Comment by vmihailenco** [comment]
Sorry, I've missed this one.

You've identified the root cause correctly - go-pg shares the same value between multiple models. It works okayish if there is only only nesting level (`Balls.Cat`) but it fails on multiple levels (`Balls.Cat.Dogs.Elephants`).
