### ISSUE TITLE
Nested BeforeInsert not working as I expected

### ISSUE THREAD

**Issue by albertpurnama** [go-pg/pg#1668]
Hi all! I have the following `Base` struct that is going to be used to many other models

```
type Base struct {
	ID        uuid.UUID `pg:",pk"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt time.Time `json:"deleted_at" pg:",soft_delete"`
}

var _ pg.BeforeInsertHook = (*Base)(nil)

func (b *Base) BeforeInsert(ctx context.Context) (context.Context, error) {
	if b.CreatedAt.IsZero() {
		b.CreatedAt = time.Now()
	}
	if b.UpdatedAt.IsZero() {
		b.UpdatedAt = time.Now()
	}
	if b.ID == uuid.Nil {
		b.ID = uuid.New()
	}
	return ctx, nil
}
```

One of the other model that will use `Base` is:
```
type User struct {
	Base
	Issuer        uuid.UUID        `json:"issuer" form:"issuer"`
	ClientUserID  string           `json:"client_user_id" form:"client_user_id"`
	...
}
```

`User` model will have its own implementation of `BeforeInsert`
```
func (u *User) BeforeInsert(ctx context.Context) (context.Context, error) {
	if u.ClientUserID == "" {
		u.ClientUserID = assignedID.String()
	}
	return ctx, nil
}
```

## The problem

When I insert a `User`, it will only run `User`'s `BeforeInsert`. However, `Base`'s `BeforeInsert` will not run (I did logging to see this).

## What I did to temporarily fix the problem

I ran the `Base`'s `BeforeInsert` manually. Like the following:

```
func (u *User) BeforeInsert(ctx context.Context) (context.Context, error) {
	if u.ClientUserID == "" {
		u.ClientUserID = assignedID.String()
	}
	return u.Base.BeforeInsert(ctx)
}
```

## What I expect

I expect that `User`'s `BeforeInsert` should also run any `BeforeInsert` hooks on any of its inner fields so I don't have to manually run the hook from the parent's struct.

Please let me know if my question is unclear, I saw there is a [similar issue](https://github.com/go-pg/pg/issues/1513) but it does not provide enough evidence or explanation.

**Comment by vmihailenco** [comment]
It is not working as expected - you are expected to run `Base.BeforeInsert` manually (as you do already). The reason is that in some cases you don't want to run `Base.BeforeInsert` and we can't support both. But this way you can achieve behavior you want with some manual work.
