### ISSUE TITLE
WhereStruct generate `IS NULL` 

### ISSUE THREAD

**Issue by bitvirago** [go-pg/pg#1669]
Hi folks,

I use WhereStruct function. it's a very good feature. Can I generate somehow ` Where("foo IS NULL", strct.Foo)`?

Thanks

**Comment by vmihailenco** [comment]
Use `sql.Null*` or a pointer, e.g. `*string`. I stopped using `WhereStruct` since in most case writing a helper works much better:

```go
func (f *MyFilter) where(q *orm.Query) (*orm.Query, error) {
    if f.Foo != "" {
        q = q.Where("foo = ?", f.Foo)
    }
    return q, nil
}

q = q.Apply(f.where)
```

Perhaps it is a good idea to softly deprecate `WhereStruct`.

**Comment by vmihailenco** [comment]
Done in https://github.com/go-pg/pg/commit/7d4dffbb5f216adb0a969a9860be8166daecd25c
