### ISSUE TITLE
Issue with ILIKE %?% in WhereGroup

### ISSUE THREAD

**Issue by sgoldenb** [go-pg/pg#1677]
In v10:

I have search bar and want to do some simple sever side querying for random stuff in the table.

Code looks like:

```
	q := db.Model(&records).
		Offset(start - 1).
		Column("data.*").
		Relation("Bla").
		Limit(length).
		Order("created_at DESC")

	if query != "" {
		q = q.WhereGroup(func(q *orm.Query) (*orm.Query, error) {
			q = q.WhereOr("foo ILIKE ?", query).
				WhereOr("bar ILIKE %?%", query)
			return q, nil
		})
	}

	recordsFiltered, err = q.SelectAndCount()
	recordsTotal, err = q.Count()

```

The generated Query is quite broken and the WhereOr block looks like:

` ... WHERE ((foo ILIKE 'asdf') OR (bar ILIKE %!'(MISSING)asdf'%!)(MISSING))  ORDER...`

Why does %?% not work? 
Where does that "MISSING" come from?

EDIT:
moving the % to the query string helps with the query but the MISSING stuff still persists.

The query works but debugging this with all those "MISSING" in there is really annoying ;)

**Comment by vmihailenco** [comment]
Your example generates `SELECT "test"."id" FROM "tests" AS "test" WHERE ((foo ILIKE 'something') OR (bar ILIKE %'something'%))` for me.

`%!'(MISSING)` looks like `fmt.Sprintf` error artefact.
