### ISSUE TITLE
unclean go.sum breaks stuff for me

### ISSUE THREAD

**Issue by burner-account** [go-pg/pg#1678]
As can be seen in

https://github.com/go-pg/pg/blob/v10.0.0-beta.8/go.sum

there are many references to outdated go-pg versions, like

```
github.com/go-pg/pg/v9 v9.0.0-beta.14
github.com/go-pg/pg/v9 v9.0.3
... and so on
```

Related to my understanding are  error messages like the following:

`cannot use func literal (type func(*"github.com/go-pg/pg/v9".Tx) error) as type func(*"github.com/go-pg/pg/v10".Tx) error in argument to <...>.RunInTransaction`

These error messages are raised despite me having no direct import of v9.
This renders v10.0.0-beta.8 unusable to me.

Right now i am not 100% sure if there is a legitimate reason for those old imports. But my guess is

`go mod tidy`

should do the trick.

**Comment by vmihailenco** [comment]
>These error messages are raised despite me having no direct import of v9

I would double check. It is not a problem with go.sum

>go mod tidy

It does not remove those references. I don't know why they are present, but they don't cause any problems for me.

**Comment by burner-account** [comment]
After cleaning out go/pgk/mod an reinstalling, the error was gone.
Please excuse the disturbance.
