### ISSUE TITLE
Fine Grained Error Handling

### ISSUE THREAD

**Issue by datosh** [go-pg/pg#1679]
Is it possible to do more fine-grained error handling with go-pg?

The [example related to error handling](https://pkg.go.dev/github.com/go-pg/pg/v10?tab=doc#example-Error) allows for a check for a very broad integrity violation.

I noted that [postgres error codes](https://www.postgresql.org/docs/10/errcodes-appendix.html) are embedded in the error messages, is there a standard way to extract these codes? Or could I write my own, i.e., can I rely on the message format to be consistent?

**Comment by datosh** [comment]
I figured it out. I got confused by the documentation of `Field(byte) string`.

```
	// Field returns a string value associated with an error code.
	//
	// https://www.postgresql.org/docs/10/static/protocol-error-fields.html
	Field(byte) string
```

I would propose to change the wording here, since `Field` does not take an error code, but rather a ["Notice Message Field"](https://www.postgresql.org/docs/10/protocol-error-fields.html), and returns the associated value. So in order to get the error code one would have to something like this:

```
	err := db.Insert(&SomeModel)
	if err != nil {
		pgErr, ok := err.(pg.Error)
		if ok {
			errCode, conversionErr := strconv.Atoi(pgErr.Field('C'))
			if conversionErr == nil {
				log.Printf("%d\n", errCode)
			}
		}
	}
```

On a second note - does it make sense to include this as a helper function to ease working with errors? 
I'd be happy to put in a PR for both changes.

**Comment by vmihailenco** [comment]
I've updated the comment - thanks for the suggestion.

But I don't think we need to clutter API with `strconv` helper - you can (and should?) compare strings instead, e.g.:

```go
func (err PGError) IntegrityViolation() bool {
	switch err.Field('C') {
	case "23000", "23001", "23502", "23503", "23505", "23514", "23P01":
		return true
	default:
		return false
	}
}
```

I think what we need is a code example - it would be nice if you have time to create one.
