### ISSUE TITLE
ErrPoolTimeout & ErrClosed not exported

### ISSUE THREAD

**Issue by DuncanGener8** [go-pg/pg#1685]
Hi there,

Is there any reason why the errors from internal/pool/pool.go are not being made available externally, like ErrNoRows & ErrMultiRows are in errors.go?

**Comment by vmihailenco** [comment]
ErrClosed is not exported because you are not supposed to get into situation when client is unexpectedly closed.

ErrPoolTimeout is not exported because it is an implementation detail. It is not part of the API.
