### ISSUE TITLE
Some examples in Wiki and on pg.uptrace.dev appear to be broken

### ISSUE THREAD

**Issue by keddad** [go-pg/pg#1690]
I've tried to do the same thing as in [this](https://github.com/go-pg/pg/wiki/Writing-Queries#select) select example:
```
book := &Book{Id: 1} // example
err := db.Select(book)
```

```
func UserRegistered(db *pg.DB, chatID int64) bool {
	user := &User{ChatId: chatID} // my code
	err := db.Select(user)
}
```

Problem here is, pg.DB doesn't have Select method:
`./utils.go:49:11: db.Select undefined (type *pg.DB has no field or method Select)
`

Docs on pg.uptrace.dev are wrong as well. In the "Getting started" example, there is a db.CreateTable method being used:
```
func createSchema(db *pg.DB) error {
    models := []interface{}{
        (*User)(nil),
        (*Story)(nil),
    }

    for _, model := range models {
        err := db.CreateTable(model, &orm.CreateTableOptions{
            Temp: true, // temp table
        })
        if err != nil {
            return err
        }
    }
    return nil
}
```
but there are no CreateTable method in pg.DB. I initially thought that I might be using some kind of outdated version, but [docs](https://pkg.go.dev/github.com/go-pg/pg/v10?tab=doc#DB) on pkg.go.dev confirm that there are no such methods.

**Comment by vmihailenco** [comment]
In v10 it should be `db.Model(model).CreateTable` and `db.Model(model).Select`. pg.uptrace.dev example should be updated. Wiki is deprecated and will be shutdown soon.
