### ISSUE TITLE
How select all columns from table?

### ISSUE THREAD

**Issue by Anochin** [go-pg/pg#1693]
I want select all columns from unknown table structure. In result I want have []map[string]interface{}? Where key in map is field name.

**Comment by maxless** [comment]
Not yet possible due to #1121 
But here's a neat trick:
```
var str string
_, err := DB.Query(&str, `SELECT json_agg(t) FROM MyTable AS t`)
```

str will be a JSON array string. The caveat is that all keys will be lowercase.

**Comment by vmihailenco** [comment]
Closing as duplicate of https://github.com/go-pg/pg/issues/1121
