### ISSUE TITLE
Order by query on json field

### ISSUE THREAD

**Issue by shashank-sachan** [go-pg/pg#1694]
Hi,

I'm trying to query the table and order it using jsonb field but it's not working.

Here is the query:
_`pgConn.Model(&records).Where("id=?", id).Order("student ->> 'first_name' ASC").Select()`_

It gives the following error:
_`column "student ->> 'first_name' ASC" does not exist`_

Below is the raw query which is generated by above query:
`_SELECT "record"."id", "record"."student" FROM "record" WHERE (attendance_id='98b070cb-15b3-435d-945a-a8fa545b5d56') ORDER BY **"student ->> 'first_name' ASC"**_
`

The problem that I see here is with this ORDER BY "student ->> 'first_name' ASC". Here OrderBY is enclosed in the double quotes. If I remove then and run the query directly on the PostgresSQL then it works perfectly fine.
`_SELECT "record"."id", "record"."student" FROM "record" WHERE (attendance_id='98b070cb-15b3-435d-945a-a8fa545b5d56') ORDER BY **student ->> 'first_name' ASC**_`

But I'm not able to find any way or documentation how to handle it using go-pg.
Is it an issue with go-pg or is there any way we can do this?

Thanks,
Shashank

**Comment by vmihailenco** [comment]
You should use `OrderExpr("student ->> 'first_name' ASC")` when there are quotes in the string.
