### ISSUE TITLE
When to use sql vs pg in struct field annotation

### ISSUE THREAD

**Issue by nihiluis** [go-pg/pg#1696]
It seems that 
```
ID        uuid.UUID `sql:",pk,type:uuid,default:uuid_generate_v4()"`
```

is different than

```
ID        uuid.UUID `pg:",pk,type:uuid,default:uuid_generate_v4()"`
```

In the docs `pg` is displayed everywhere. It seems that only sql is valid. pg is ignored.

When do you use pg versus sql annotation?

This is my go mod 

```
require (
	github.com/go-pg/pg v8.0.7+incompatible
)
```

**Comment by vmihailenco** [comment]
Starting from v9 you should use only `pg` tag. v8 uses both.
