### ISSUE TITLE
Let's add name for otel span.

### ISSUE THREAD

**Issue by j2gg0s** [go-pg/pg#1699]
Thanks go-pg support [opentelemetry](https://github.com/open-telemetry/opentelemetry-go).

However, we use space as span's name. Maybe we should use special prefix and operation as span's name?

Related code: https://github.com/go-pg/pg/blob/v10/pgext/otel.go#L30

**Comment by vmihailenco** [comment]
The name is empty since Otel backend is supposed to generate readable low cardinality name from `db.statement` attribute, e.g. [Uptrace](https://uptrace.dev/1/spans/168444276395491350) generates `SELECT FROM articles`.

Using operation (SELECT/UPDATE/DELETE) is an option too. What special prefix do you have in mind?

**Comment by j2gg0s** [comment]
I use [jaeger](https://www.jaegertracing.io/docs/1.18/), it will not auto generate span name from attribute.

I'm afraid db's operation conflict with other, so one speical prefix like "postgres." or "pg." may be good?
As a refrences, mongo ext in [otel go contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) use "mongo." as prefix.

In additiion to SELECT/UPDATE/DELETE，which operation should we use to represent DB.Exec or raw sql.

**Comment by vmihailenco** [comment]
I am not sure I like using a prefix for all span names. It may work for Jaeger but may not work for other backends which may already display `db.system` to distinguish one span from another. And it does not seem to be part of the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/5c2d965108e73935b4d3dca59f2b5ca5f43b0c76/specification/trace/api.md).

Overall go-pg tries to provide all information in attributes and let backends (e.g. Jaeger) decide what to do with it.

**Comment by j2gg0s** [comment]
Sorry for my bad english.

The problem is go-pg use space as span name in [pgext/otel.go](https://github.com/go-pg/pg/blob/v10/pgext/otel.go#L30) ,
i think use operation is a better choice.
Other span's name is good, like this https://github.com/go-pg/pg/blob/v10/base.go#L243 .

Use prefix with span's name in pgext/otel.go may be a better choice, but i am not very sure.

We don't need to assume how backends display span, we only should provider span with one name.

**Comment by j2gg0s** [comment]
@vmihailenco you have done these in commit 8357062eea66f6d62d360c03505794851e42de9a ? Can we consider case for raw sql. In which, evt.Query is not queryOperation?

**Comment by vmihailenco** [comment]
>Can we consider case for raw sql. In which, evt.Query is not queryOperation?

Would a name like "query" or "pg.query" suit your needs?

**Comment by j2gg0s** [comment]
In which case, evt.Query does not support ``Operation``? Raw SQL? So name like "rawsql" maybe a good choice?

**Comment by j2gg0s** [comment]
@vmihailenco When operation is unkown, use first word as span name?
This is ok?
https://github.com/go-pg/pg/issues/1699#issuecomment-681848746

**Comment by vmihailenco** [comment]
Thanks for the fix - tagged v10.0.0-beta.11
