### ISSUE TITLE
Autoreconnect on postgresql restart

### ISSUE THREAD

**Issue by theromis** [go-pg/pg#1706]
Trying to find the way to do it and can't, if I'm eventually upgrading postgres it transparently restarts and my backend goes down, what is the right way of doing reconnect in this case.

Just have one option in mind having something like:
```go
fun checker() {
  while(true) {
    if err := db.Ping(ctx); err != nil {
        reconnectLogic(db, ctx)
    }
    sleep(1000000)
  }
}
```
but it still means backend will be inaccessible some time, what is the right way of reconnect on error?

**Comment by vmihailenco** [comment]
go-pg automatically reconnects on error.

**Comment by theromis** [comment]
@vmihailenco at list it not reconnects in my environment, can I take some sample to see autoreconnect in action?

**Comment by theromis** [comment]
@vmihailenco Thank you for clarification
this code reconnected for me during postgres reboot
```go
	ctx := context.Background()
	for i := 0; i < 10; i++ {
		fmt.Printf("%v\n", i)
		if err := db.Ping(ctx); err != nil {
			fmt.Printf("ERROR: %v\n", err)
		} else {
			fmt.Printf("OK\n")
		}
		time.Sleep(1 * time.Second)
	}
```
but my `go-chi` backend still gives `EOF` error after postgres restart

**Comment by vmihailenco** [comment]
I can't guess what happens in your app, but prepared statements and `NewConn` are not automatically reconnected. Long running transactions are re-connected when transaction is re-created.

**Comment by theromis** [comment]
@vmihailenco even basic `go-chi` backend reconnects fine
```go
                r := chi.NewRouter()
                r.Use(middleware.Logger)
                r.Get("/", func(w http.ResponseWriter, r *http.Request) {
                        db := utils.GetNextReadDb()
                        ctx := context.Background()
                        if err := db.Ping(ctx); err != nil {
                                fmt.Printf("ERROR: %v\n", err)
                        } else {
                                fmt.Printf("OK\n")
                        }
                        w.Write([]byte("welcome"))
                })
                http.ListenAndServe(":3000", r)
```
seems like my internal "soup" issue, need more time to investigate

**Comment by theromis** [comment]
@vmihailenco At list found the reason - websocket handler, still don't know how to fix it, seems like websocket handler "holds" global variable context (I'm using github.com/gorilla/websocket).
So backend reconnects but only after 1-2 minutes. Without active websocket connection it reconnects on second request.

Could you recommend something? Seems like the best is just run websocket backend as separate process but it still doing postgres requests.

**Comment by vmihailenco** [comment]
It does not sound like a problem with go-pg. I would dig further why your backend behaves like that.
