### ISSUE TITLE
Empty select for whatever reason

### ISSUE THREAD

**Issue by TheAsda** [go-pg/pg#1736]
There is a table:
```
CREATE TABLE "user" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "name" varchar(255) NOT NULL UNIQUE,
  "password" varchar(255) NOT NULL,
  CONSTRAINT "user_pk" PRIMARY KEY ("id")
)
```

I want to select all rows from it.

Code:
```
type User struct {
	tableName struct{} `pg:"user"`
	id        string   `pg:"type:uuid"`
	name      string
	password  string
}

var result []User

err := db.Model(&result).Select()
```
## Expected Behavior

It should fill result with users.

## Current Behavior

Query hook shows this query:

`SELECT  FROM "user" AS "user"`

So generated query misses '*' for some reason and it returns structures with empty fields.

## Context (Environment)

go1.15.2
go-pg v10

**Comment by vmihailenco** [comment]
It should be

```
type User struct {
	tableName struct{} `pg:"user"`
	ID        string   `pg:"type:uuid"`
	Name      string
	Password  string
}
```

In Go unexported fields are ignored.

**Comment by TheAsda** [comment]
Thanks a lot! Spent whole day figuring this out.
