### ISSUE TITLE
Warn if there is a fk without rel tag

### ISSUE THREAD

**Issue by vmihailenco** [go-pg/pg#1738]
E.g. errors like `pg:"fk:foo rel:has-one"`

**Comment by dlemel8** [comment]
Hey @vmihailenco , I want to do this.
Can you guide me a bit?
Thanks.

**Comment by vmihailenco** [comment]
@dlemel8 sure, it is about adding a check to https://github.com/go-pg/pg/blob/v10/orm/table.go#L574

```go
	if _, ok := pgTag.Options["fk"]; ok {
		internal.Warn.Printf(
			`%s.%s option "fk" requires a relation type`,
			t.TypeName, f.Name,
		)
	}
```

The similar check can be added for `join_fk` as well.

Please note that this issue is for v11 branch - not the default v10 branch.

**Comment by vmihailenco** [comment]
Fixed by @dlemel8 in v11
