### ISSUE TITLE
go-pg/pg/internal/util.go:84:18: undefined: trace.NoopSpan

### ISSUE THREAD

**Issue by rowiest** [go-pg/pg#1739]
During 'go get' process I got 'undefined: trace.NoopSpan' error.

$ go get github.com/go-pg/pg
# github.com/go-pg/pg/internal
go/src/github.com/go-pg/pg/internal/util.go:84:18: undefined: trace.NoopSpan
user@machine:~$ go version
go version go1.15.2 linux/amd64

**Comment by vmihailenco** [comment]
It should be `github.com/go-pg/pg/v10`. Please follow https://pg.uptrace.dev/ .
