### ISSUE TITLE
Many2many error when table name has a param (multi-tenant)

### ISSUE THREAD

**Issue by martoche** [go-pg/pg#1742]
In a multi-tenant application, table names are prefixed with `?tenant` — the `?tenant` param is set with the `WithParam` method.

The following reduced test case results in an error when the models are used:

```go
func init() {
	orm.RegisterTable((*IngredientRecipe)(nil))
}

type Recipe struct {
	tableName   struct{} `pg:"?tenant.recipes"`
	Id          int
	Ingredients []*Ingredient `pg:"many2many:?tenant.ingredients_recipes"`
}

type Ingredient struct {
	tableName struct{} `pg:"?tenant.ingredients"`
	Id        int
	Recipes   []*Recipe `pg:"many2many:?tenant.ingredients_recipes"`
}

type IngredientRecipe struct {
	tableName    struct{}    `pg:"?tenant.ingredients_recipes"`
	Recipe       *Recipe     `pg:"rel:has-one"`
	RecipeId     int         `pg:",pk"`
	Ingredient   *Ingredient `pg:"rel:has-one"`
	IngredientId int         `pg:",pk"`
}
```

## Expected Behavior

No error.

## Current Behavior

pg: can't find "?tenant"."ingredients_recipes" table (use orm.RegisterTable to register the model)

## Possible Solution

The issue appeared in v10, the code worked in v9.

I've narrowed the problem to https://github.com/go-pg/pg/blob/v10/orm/table.go#L810

m2mTableName is equal to `"?tenant"."ingredients_recipes"` which doesn't match the table name `?tenant.ingredients_recipes` (without the quotes).

I've fixed it and wrote a test case in this branch, please confirm that it's the correct solution:
https://github.com/go-pg/pg/compare/v10...martoche:many2many-multi-tenant-fix

Thanks!

**Comment by vmihailenco** [comment]
@martoche thanks for your contribution - it looks perfect.

**Comment by vmihailenco** [comment]
Should be in v10.3.1
