### ISSUE TITLE
Explicitly setting a `bool` column to `false` before `INSERT` always uses the default value when `use_zero` is specified.

### ISSUE THREAD

**Issue by jeffreydwalter** [go-pg/pg#1748]
@vmihailenco With the latest change made in https://github.com/go-pg/pg/issues/1747, v10 now works like v9 again, but there's still a problem with `use_zero`. Unfortunately, I think it's more of a design problem than a bug. 
Explicitly setting a `bool` column to `false` before `INSERT` always uses the default value when `use_zero` is specified. Given that, there's currently no way to set a bool column with a default value to `false` on `INSERT`.

# Suggested Solution
Maybe it would be good to create a new type based on`*bool` and implement a `Scanner/Valuer` for it. If it's `nil`, use default, if `true/false` use that value. I suppose this would require some convenience methods to make get/set more usable.

# Steps-to-reproduce
Here is a program that demonstrates the issue:
```
package main

import (
	"fmt"

	"github.com/go-pg/pg/v9"
)

func main() {
	type Test struct {
		ID      int64  `json:"id" pg:",pk"`
		Name    string `json:"name" pg:",notnull"`
		Enabled bool   `json:"enabled" pg:"default:true,notnull,use_zero"`
		Visible bool   `json:"visible" pg:"default:true,notnull,use_zero"`
	}

	t := Test{
		Name: "Test",
	}

	options := &pg.Options{
		// Your config here.
	}

	db := pg.Connect(options)
	db.Exec(`drop table if exists tests`)
	db.Exec(`create table tests ( id bigserial primary key, name text not null, visible bool not null default true, enabled bool not null default true)`)

	t.Visible = false /* Set this bool field to false explicitly before insert. */

	db.Model(&t).Returning("*").Insert()
	db.Exec(`drop table if exists tests`)
	fmt.Printf(`%+v`, t)
	/*
	   // After you run this ^ code, this is what gets inserted. :(
	   platform=# select * from tests;
	    id | name | visible | enabled
	   ----+------+---------+---------
	     1 | Test | t       | t
	   (1 row)
	*/
}
```
Expected SQL:
`INSERT INTO "tests" ("id", "name", "enabled", "visible") VALUES (DEFAULT, 'Test', DEFAULT, FALSE) RETURNING "id"`
Expected Output:
{ID:1 Name:Test Enabled:true Visible:***false***}

Actual SQL:
`INSERT INTO "tests" ("id", "name", "enabled", "visible") VALUES (DEFAULT, 'Test', DEFAULT, DEFAULT) RETURNING "id"`
Actual Output:
{ID:1 Name:Test Enabled:true Visible:***true***}

**Comment by vmihailenco** [comment]
You should already be able to use `Enable sql.NullBool`. Does it work for you?

**Comment by jeffreydwalter** [comment]
Ha, forgot you implemented those. Works perfectly! Thanks!
