### ISSUE TITLE
Use GitHub releases instead of plain git tags

### ISSUE THREAD

**Issue by ShoshinNikita** [go-pg/pg#1751]
I guess it would be a good idea to use GitHub releases instead of plain git tags. There are several advantages:

- Users can subscribe to releases

  ![image](https://user-images.githubusercontent.com/30220965/94360306-e6ba1480-00b4-11eb-8172-f8416ca5b7d4.png)

- Convenient way to compare a new release with the previous ones

  ![image](https://user-images.githubusercontent.com/30220965/94360319-fcc7d500-00b4-11eb-84d8-ab4757c988c0.png)

- Convenient way to see how many new commits there are in branch `master` since a release

  ![image](https://user-images.githubusercontent.com/30220965/94360323-05b8a680-00b5-11eb-94ab-7bd4cdbc9836.png)

**Comment by vmihailenco** [comment]
Making git tag is as simple as `git tag && git push` - very simple and fast. Is it possible to use Github releases in a similar manner?

**Comment by ShoshinNikita** [comment]
As for me, it is simple and fast enough to create a new release with web interface: just input release name and tag name and click `Publish` button (both GitHub release and git tag will be created). But if you prefer terminal to web interface, you can try new [GitHub CLI](https://cli.github.com/): something like `gh release create v1.2.3` ([docs](https://cli.github.com/manual/gh_release_create))

**Comment by vmihailenco** [comment]
I've created one release at https://github.com/go-pg/pg/releases but I've not decided yet whether I will continue to use it :) I was thinking about using Discord for announcements - seems like a more flexible and simple option...

Anyway - thanks for the suggestion.

**Comment by ShoshinNikita** [comment]
I am not sure Discord is a best option for announcements. It is a really good place for live discussions (for example, asking for an advice). But I think it's better to use a single platform for development, announcements, issues, releases and etc. Plus, I guess only small part of developers will use it:

1) some developers won't want to use an additional service
2) it has "gaming" reputation (I don't see any problems here, but some would prefer Slack)

But, of course, the decision is yours)
