### ISSUE TITLE
Passing []*Model to db.Model().Select() returns nil when no rows are found, passing *Model returns "no rows in result set"

### ISSUE THREAD

**Issue by jeffreydwalter** [go-pg/pg#1753]
Passing a slice of models to a `Select()` query that returns no rows returns `nil` instead of `no rows in result set` error. This seems wrong because running the same query with a single instance of the same model returns `no rows in result set`.

This behavior seems to be the same in both v9 and v10.

# Expected Behavior
`pg: no rows in result set` should be returned regardless of whether a `model` or `[]*model` is passed in.

# Actual Behavior
`nil` is returned when using `[]*model`.

# Steps to Reproduce
```
package main

import (
	"fmt"

	"github.com/go-pg/pg/v10"
)

func main() {
	type Test struct {
		ID      int64  `json:"id" pg:",pk"`
		Name    string `json:"name" pg:",notnull"`
		Enabled bool   `json:"enabled" pg:"default:true,notnull,use_zero"`
		Visible bool   `json:"visible" pg:"default:true,notnull,use_zero"`
	}

	t := Test{
		Name: "Test",
	}

	options := &pg.Options{
             // Your config options here.
	}

	db := pg.Connect(options)
	db.Exec(`drop table if exists tests`)
	db.Exec(`create table tests ( id bigserial primary key, name text not null, visible bool not null default true, enabled bool not null default true)`)
	db.Model(&t).Returning("*").Insert()

	ts := make([]*Test, 0)
       // QUERY RESULT ([]*Test): <nil>
	fmt.Printf("QUERY RESULT ([]*Test): %+v\n", db.Model(&ts).Where("id > 1000").Select())

       // QUERY RESULT (*Test): pg: no rows in result set
	fmt.Printf("QUERY RESULT (*Test): %+v\n", db.Model(&t).Where("id > 1000").Select())
}
```

# Output
QUERY RESULT ([]*Test): <nil>
QUERY RESULT (*Test): pg: no rows in result set

**Comment by vmihailenco** [comment]
It works like this from day 0. For `[]*Test` you should manually check `len` if you are interested in it.

**Comment by jeffreydwalter** [comment]
@vmihailenco I understand that it has worked that way since day 0, but the behavior is inconsistent at best. It bit me and I'm sure it has and will bite others. Do you sincerely think it makes sense to not return `pg.ErrNoRows` consistently when no rows are found in a `Select()` operation? If you do, what is the rationale behind your belief?

**Comment by vmihailenco** [comment]
In my practice I just don't need `pg.ErrNoRows` when slice is expected and query return no rows.

I believe this behavior is the same with database/sql but I did not use it for some time.

**Comment by jeffreydwalter** [comment]
From a user of your awesome library, I can tell you it's not obvious nor
intuitive to have `Select()`'s error return behavior change based on what
you pass in as the model. If no routes are found it would be nice to have
consistent behavior.

I realize that's a breaking change, but every major version of `go-pg` has
had some breaking API change. Is this something you would consider for v11?
🙂 Thanks!

**Comment by vmihailenco** [comment]
In this [project](https://github.com/uptrace/go-treemux-realworld-example-app) such change would not bring any benefit except that I would have to add some code to ignore `ErrNoRows`. The situation is the same in other projects I worked on.

**Comment by jeffreydwalter** [comment]
I don't think that's the point. Obviously, you built this library for you,
and I appreciate that. You've opened this library up to the world, so your
needs aside, having Select() return pg.ErrNoRows only when you pass a
non-slice is semantically incorrect and leads to people that use your
awesome library tripping over this behavior (like I did). If no rows are
found, never return pg.ErroNoRows or always, but please, please, please,
don't be inconsistent. Anyway, ultimately it's your call, but if you're not
going to fix the behavior, it would be nice to have this inconsistency
called out in the docs.
