### ISSUE TITLE
Placeholder in CREATE SEQUENCE query

### ISSUE THREAD

**Issue by vadim-dmitriev** [go-pg/pg#1765]
Hi, I trying to exec query like that - `CREATE SEQUENCE ?;`, where `?` is a placeholder for sequence`s name. Full code you could see below:
```go
func CreateSeq(name string) error {
	query := "create sequence ?;"

	if _, err := p.db.Exec(query, name); err != nil {
		return err
	}

	return nil
}
```

When you try to exec this code, could see error like this:
```
ERROR #42601: syntax error at or near: "'seq_name'"
```
In SELECT, INSERT, etc. queries placeholder '?' works nice.
What`s wrong? Where is syntax error here?

PS:
go version go1.15.3 linux/amd64
github.com/go-pg/pg v8.0.7+incompatible

Thanks!

**Comment by vmihailenco** [comment]
Should be `pg.Ident(name)`. See https://pg.uptrace.dev/placeholders/#postgresql-identifiers-and-disabling-quotation

**Comment by vadim-dmitriev** [comment]
@vmihailenco Thank you!
