### ISSUE TITLE
PK in nested struct

### ISSUE THREAD

**Issue by sintell** [go-pg/pg#177]
Hello, and thank you for your hard work.

I'd choose to change my db ms to go-pg from gorm and now I'm wondering - is it possible somehow to use nested struct field as PK.
For example:
```go
type M struct {
	ID uint `sql:",pk"`
}

type Author struct {
	M
	Name  string
	Books []Book
}

type Book struct {
	M
	Name     string
	AuthorID uint
}
```

This will loose all benefits from model binding. No relations, no `RETURNIG id` and so on.
I realise that it is not necessity but it would be very convenient to have a choise to use nested struct field as PK.

**Comment by vmihailenco** [comment]
Fixes, thanks for the bug report!

**Comment by sintell** [comment]
Cool, thank you too!
