### ISSUE TITLE
What to do in this case if I need a transaction instead of a DB connection on the same struct?

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1770]
I found [a great example of transactions between Repositories](https://github.com/agungdwiprasetyo/agungdpcms/blob/master/src/resume/usecase/usecase_impl.go#L77) using a Clean Architecture approach.

He's using Gorm.

Gorm has the same type for a DB connection and a transaction, example:

```go
var db *gorm.DB
var tx *gorm.DB
```

I'm a fan of `go-pg`. But here the types are different (maybe it's even better as is), example:

```go
var db *pg.DB
var tx *pg.Tx
```

And of course the error is: `Cannot use 'tx' (type *Tx) as type *pg.DB`

A small reproduction:

```go
package main

import (
	"github.com/go-pg/pg/v10"
)

type Player struct {
	ID   int
	Name string
}

type PlayerRepo struct {
	db       *pg.DB
	teamRepo *TeamRepo
}

type TeamRepo struct {
	db *pg.DB
}

func NewPlayerRepo(db *pg.DB) *PlayerRepo {
	return &PlayerRepo{
		db:       db,
		teamRepo: NewTeamRepo(db),
	}
}

func NewTeamRepo(db *pg.DB) *TeamRepo {
	return &TeamRepo{db: db}
}

func (r *PlayerRepo) Find(id int) (*Player, error) {
	var player Player
	err := r.db.Model(&player).Where("id = ?", id).Select()
	if err != nil {
		return nil, err
	}
	return &player, nil
}

func (r *PlayerRepo) All() ([]*Player, error) {
	// Long code
	return nil, nil
}

func (r *PlayerRepo) Insert() (*Player, error) {
	// Long code
	return nil, nil
}

func (r *PlayerRepo) Update() (*Player, error) {
	// Long code
	return nil, nil
}

func (r *PlayerRepo) Delete() (*Player, error) {
	// Long code
	return nil, nil
}

func (r *PlayerRepo) WithTransaction(txFunc func(*PlayerRepo) error) (err error) {
	tx, _ := r.db.Begin()
	manager := NewPlayerRepo(tx) // <<<--- here the problem! tx is not good here, it's `pg.Tx` not `pg.DB`
	err = txFunc(manager)
	return
}
```

What can I do?

Is there in `go-pg` an `Interface` I can use?

Something else?

Thanks in advance. ❤️

**Comment by frederikhors** [comment]
I figured I can use the `orm.DB` interface instead of `pg.DB` or `pg.Tx` types.

But now I have the problem that in some method I use a transaction with `repo.db.Begin()` that obviously interface `orm.DB` does not provide.

How can I solve?

**Comment by ganigeorgiev** [comment]
@frederikhors  I stumbled upon something similar and ended up creating a bunch of wrapper methods with type switch, eg.:

```go
func (r *PlayerRepo) Begin() (tx *pg.Tx, err error) {
    switch txOrDB := r.db.(type) { // orm.DB
    case *pg.Tx:
        tx, err = txOrDB.Begin();
    case *pg.DB:
        tx, err = txOrDB.Begin();
    }

    return;
}
```

**Comment by vmihailenco** [comment]
You can create an interface similar to `orm.DB` and add missing `Begin` method.

**Comment by frederikhors** [comment]
@ganigeorgiev thanks a lot for your answer, really. Unfortunately I don't need only `.Begin()`, I need other methods too. And I think it's too complicated to add all of them.

@vmihailenco I found the below way. **What do you think about?** Thanks in advance.

```go
package main

import (
	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

type Player struct {
	ID   int
	Name string
}

type PlayerRepo struct {
	db       orm.DB // <<<--- I'm using orm.DB interface now
	teamRepo *TeamRepo
}

type TeamRepo struct {
	db orm.DB // <<<--- I'm using orm.DB interface now
}

func NewPlayerRepo(db orm.DB) *PlayerRepo { // <<<--- I'm using orm.DB interface now
	return &PlayerRepo{
		db:       db,
		teamRepo: NewTeamRepo(db),
	}
}

func NewTeamRepo(db orm.DB) *TeamRepo { // <<<--- I'm using orm.DB interface now
	return &TeamRepo{db: db}
}

func (r *PlayerRepo) Find(id int) (*Player, error) {
	var player Player
	err := r.db.Model(&player).Where("id = ?", id).Select()
	if err != nil {
		return nil, err
	}
	return &player, nil
}

func (r *PlayerRepo) All() ([]*Player, error) {
	// Long code with no transaction
	return nil, nil
}

func (r *PlayerRepo) Update(id int) (*Player, error) {
	// Here I can use transaction like this:
	var tx *pg.Tx
	var err error

	tx, ok := r.db.(*pg.Tx)
	if !ok {
		tx, err = r.db.(*pg.DB).Begin()
	}
	if err != nil {
		return nil, err
	}
	defer func() {
		// rollback if err; commit if no err
	}()

	var player Player
	err = tx.Model(&player).Where("id = ?", id).For("UPDATE").Select()
	if err != nil {
		_ = tx.Rollback()
		return nil, err
	}

	// I do something with player here

	err = tx.Commit()
	if err != nil {
		return nil, err
	}

	return &player, nil
}

func (r *PlayerRepo) WithTransaction(txFunc func(*PlayerRepo) error) (err error) {
	tx, _ := r.db.(*pg.DB).Begin() // <<<--- Type assertion only here, because here can never come a *pg.Tx (for now)
	manager := NewPlayerRepo(tx)
	err = txFunc(manager)
	return
}
```

**Comment by frederikhors** [comment]
Instead of type assertion I can also simply define a new interface like this:

```go
type DB interface {
	Begin() (*pg.Tx, error)
	orm.DB
}
```

**Comment by frederikhors** [comment]
Now the problem is I don't know in my method if this transaction is method scoped (so I can rollback or commit it here in method) or is `WithTransaction()` usecase's scoped (and I need to return simply an error or nil).

What do you suggest to detect this?

**Comment by frederikhors** [comment]
Now the error is: `"pg: transaction has already been committed or rolled back"`.

**Comment by ganigeorgiev** [comment]
@frederikhors ~~My guess is that you are calling `pg.DB.Begin()` multiple times. I think if you use the interface (or type switch) approach this error shouldn't occur because `pg.Tx.Begin()` doesn't start a new transaction and just return the transaction instance itself.~~ The error could occur also if you call multiple times `RunInTransaction()`.

---

On second thought, the error indicates multiple `COMMIT` calls, not `BEGIN`, so maybe the issue is not from the `pg.DB.Begin()` calls.

A simplified version of what I currently do for nested transactions support:
```go
func (dao *Dao) RunInTransaction(fn func(*pg.Tx) error) error {
	var err error

	switch txOrDB := dao.db.(type) {
	case *pg.Tx:
		// for simplicity, execute the function within the current transaction
               // you could also add SAVEPOINT but that requires additional rollback handling...
		err = fn(txOrDB)
	case *pg.DB:
		err = txOrDB.RunInTransaction(dao.db.Context(), fn)
	}

	return err
}
```

**Comment by frederikhors** [comment]
Very helpful @ganigeorgiev thank you very much!

**Comment by frederikhors** [comment]
Somehow I solved it. Thank you all.

**Comment by syed-shah-zepto** [comment]
Hi @frederikhors , facing the same issue `"pg: transaction has already been committed or rolled back"`. Do you remember how you fixed this?
