### ISSUE TITLE
wrong sql code generated on inserting bytea value

### ISSUE THREAD

**Issue by bearsh** [go-pg/pg#1773]
when inserting a []byte in a bytea value, go-pg generate a query string like the following:
`INSERT INTO table (bytea_col) VALUES ('{1,2,3,4}')`

## Expected Behavior
 the bytea value should be in the escaped input or hex representation

## Current Behavior

the mentioned string `{1,2,3,4}` is inserted instead of the 4 bytes

when select that column, go-pg fails with following error message:
`got '\\', wanted '{'`

go-pg Version: 10.6.0

**Comment by vmihailenco** [comment]
Please provide a reproducer.

**Comment by bearsh** [comment]
I've created a repo demonstrating the issue: https://github.com/bearsh/gp-pg-issue-1773

Is this OK for you or do you want me to paste the code here?

**Comment by vmihailenco** [comment]
Replace `Data []byte pg:"data,array"` with `Data []byte pg:"data"` and try again.

**Comment by bearsh** [comment]
thanks @vmihailenco this works! seems I have to blame genna for generating wrong tags (or myself as genna doesn't seem to officially support go-pg/v10)
