### ISSUE TITLE
Where to set connection string paramter?

### ISSUE THREAD

**Issue by thetruechar** [go-pg/pg#1777]
Where to set the connection parameter like timezone in go-pg?
postgresql://127.0.0.1:5439/?timezone=Asia/Shanghai

**Comment by vmihailenco** [comment]
You can use `Options.OnConnect` hook to execute `SET timezone = ...` command.

**Comment by thetruechar** [comment]
Got

**Comment by nanmu42** [comment]
Just curious, does using `Options.OnConnect` hook to set session timezone bring more overhead than setting it directly in connection string?

**Comment by vmihailenco** [comment]
AFAIK connection strings are not supported by PostgreSQL itself. Libraries have to parse them and configure Postgres via usual `SET foo = bar` queries for you.
