### ISSUE TITLE
Error when selecting a model array by a composite (text, UUID) primary key

### ISSUE THREAD

**Issue by betaprior** [go-pg/pg#1778]
## Expected Behavior

Selecting a model slice by a composite PK, where one of the columns is UUID works the same way as selecting a model slice by a non-composite PK

## Current Behavior

Selecting a model slice by a composite PK throws an error: 
operator does not exist: uuid = text

## Steps to Reproduce

I am using the following model definition and query:

```
type Asset struct {
    AssetId string `pg:",pk"`
    TenantId uuid.UUID `pg:",pk,type:uuid"`
    MyField int
}

assetModels := []*Asset{
        {
            AssetId: "one",
            TenantId: uuid.FromStringOrNil("8ab47444-c81e-440a-b0b2-39366ca09bc0"),
        },
        {
            AssetId: "two",
            TenantId: uuid.FromStringOrNil("8ab47444-c81e-440a-b0b2-39366ca09bc0"),
        }
    }

db.Model(&assetModels).
        WherePK().
        Select()

```

## Detailed Description

The generated SQL creates an explicit table for the composite PK that is used in a join:

```
JOIN (VALUES ('one', '8ab47444-c81e-440a-b0b2-39366ca09bc0', 0), ('two', '8ab47444-c81e-440a-b0b2-39366ca09bc0', 1) as _pg_pk)
```

Unfortunately, this join fails because the elements are interpreted as text instead of UUID:
```
operator does not exist: uuid = text
LINE 1: ..." = "_pg_pk"."asset_id" AND "asset"."tenant_id" = "_pg_pk"... 
                                                           ^
```

Edited to add: possible workaround for this is using `pg.InMulti`. If this is the recommended approach in this case, it would be good to add an explicit example in the Query section of the docs. I literally randomly stumbled across this solution by looking at go-pg source code.

**Comment by vmihailenco** [comment]
Should be fixed in v10.7.1
