### ISSUE TITLE
v10.6.2 causes package compilation failure

### ISSUE THREAD

**Issue by morgantymartin** [go-pg/pg#1781]
Issue tracker is used for reporting bugs and discussing new features. Please use
[Discord](https://discord.gg/rWtp5Aj) or [stackoverflow](https://stackoverflow.com) for supporting
issues.

## Expected Behavior

Successful compilation using go build

## Current Behavior
failed build 
# github.com/go-pg/pgext
../../../go/pkg/mod/github.com/go-pg/pgext@v0.1.4/otel.go:106:19: undefined: codes.NotFound
../../../go/pkg/mod/github.com/go-pg/pgext@v0.1.4/otel.go:108:57: undefined: codes.Internal
note: module requires Go 1.16

## Possible Solution

Do not require go 1.16 in v10 of pg-go

## Steps to Reproduce

1. Create a package that uses github.com/go-pg/pg/v10 v10.6.2 against  go 1.1.5 in go.mod
2. run go build on that package
3. Revert to v10.3.2 = build success

## Context (Environment)

Issue prevents successful useage/compilation

postgis 12
go 1.15.5

Ahead of stable version of go (1.16) required to compile against v10 of go-pg. 
The current stable go version is 1.15.5 and the stable/release version of 10 should compile against it.

**Comment by vmihailenco** [comment]
https://github.com/go-pg/pgext says that it is deprecated. See https://pg.uptrace.dev/extra-modules/ and update import path.

**Comment by morgantymartin** [comment]
Thanks!
