### ISSUE TITLE
Latest release v10.3.2 there is no pgdebug

### ISSUE THREAD

**Issue by edieruby** [go-pg/pg#1782]
How to view queries this library generates?
Starting from v10 use:

import "github.com/go-pg/pg/extra/pgdebug"

db.AddQueryHook(pgdebug.DebugHook{
    // Print all queries.
    Verbose: true,
})

in v10.3.2 , can not find this.

**Latest release can upgrade to v10.6.2 ?**

**Comment by vmihailenco** [comment]
Yes, try to upgrade to v10.6.2
