### ISSUE TITLE
Missing join ON clause when using WherePK with slice

### ISSUE THREAD

**Issue by NathanBaulch** [go-pg/pg#1789]
All my batch select queries stopped working when I updated to latest. It looks like the ON clause for the output ordering join `_data` is being added as a WHERE clause instead. Very easy to reproduce with the code below.
Version 10.7.2.

```go
m := []struct {
	tableName struct{} `pg:"test"`
	ID        uint64
}{{ID: 111}, {ID: 222}}
panic(db.Model(&m).WherePK().Select())
```

Generated SQL:
```sql
SELECT "device"."id"
FROM "device" AS "device"
JOIN (VALUES (111, 0), (222, 1)) AS "_data" ("id", "ordering")
WHERE "device"."id" = "_data"."id"                                -- <- changing "WHERE" to "ON" here fixes the query
ORDER BY "_data"."ordering" ASC
```

**Comment by vmihailenco** [comment]
It was needed to fix batch updates and deletes. I was sure `ON` clause is optional :)

**Comment by vmihailenco** [comment]
Please try v10.7.3
