### ISSUE TITLE
About many to many relations

### ISSUE THREAD

**Issue by chris0927** [go-pg/pg#180]
I want  a table  to relates with itself,how to define Model?The struct like:

```
type   User struct{
    Id
    Name
    Users []User
}
```

**Comment by vmihailenco** [comment]
Please upgrade to latest version and try:

```
type User struct{
    Id
    Name
    Users []User `pg:",many2many:user_to_users,joinFK:Sub"`
}
```

Your `user_to_users` table should have following schema:

```
CREATE TABLE user_to_users(user_id int, sub_id int)
```

Also look at this example https://godoc.org/gopkg.in/pg.v4#example-DB-Model-ManyToMany

PS This is new functionality so I reserve right to change it in near days :)
