### ISSUE TITLE
`Relation` breaks in M2M when `Column` is used

### ISSUE THREAD

**Issue by kudrykv** [go-pg/pg#1801]
The `Relation` fails to retrieve nested data on many2many connection when explicit fields are specified using the `Column` query.

## Expected Behavior

The query should execute with no complaints whatsoever.

## Current Behavior

go-pg fails to build the query.

```go
// this works
err := db.Model(&actual).Relation("Books", func(q *orm.Query) (*orm.Query, error) {
	return q.Order("name asc"), nil
}).Select()

// this doesn't
err = db.Model(&actual).Relation("Books", func(q *orm.Query) (*orm.Query, error) {
	return q.Column("id").Order("name asc"), nil
	//     ^^^^^^^^^^^^^^
}).Select()

// panic: pg: model=Book does not have column="author_id"
```

Gist: https://gist.github.com/kudrykv/38426eaf2efe4e7c6617e21e1b8c3274

## Steps to Reproduce

https://gist.github.com/kudrykv/38426eaf2efe4e7c6617e21e1b8c3274

## Context (Environment)

I need to select the nested model, but I need to select only some fields for the nested model.
I'm using v10.7.3

**Comment by kudrykv** [comment]
Solution: insead of `Column`, use `Relation` on the top level:
```go
db.Model(&some).Relation("Books.id").Relation("Books.name").Select()
```

The lib will create only the needed queries.

**Comment by ghost** [comment]
I had this problem today and I fixed it by including the columns from the intermediary table in the query. If you select specific columns without including these, you are excluding the columns required for the join.

So with the following models:

```go
type Alpha struct {
	Id     int
	Name   string
	Age    int
	Height int
	Weight int
	Betas  []Beta
}

type Beta struct {
	Id     int
	Name   string
	Age    int
	Height int
	Weight int
	Alphas []Alpha
}

type AlphatoBeta struct {
	AlphaId int
	BetaId  int
}
```

You can run the following to get only the id and name columns:

```go
alpha := Alpha{}
err := db.Model(&alpha).
        Relation("Betas", func(q *orm.Query) (*orm.Query, error) {
	        q.Column(
		        "beta.id",
		        "beta.name",
		        "alpha_to_beta.alpha_id",
		        "alpha_to_beta.beta_id").
		        Order("name asc")
	        return q, nil
        }).
        Select()
```
