### ISSUE TITLE
Value always zero

### ISSUE THREAD

**Issue by reggieoswald-ads** [go-pg/pg#1804]
When i'm using `pg:",use_zero"` with my struct field "Amount" and trying to write decimal not zero value (48900, for example), it writes 0 in db

Struct field
<img width="403" alt="Снимок экрана 2020-12-24 в 19 05 03" src="https://user-images.githubusercontent.com/76565028/103098215-fa750880-461a-11eb-8681-77d6cfc17044.png">

While debugging 
<img width="460" alt="Снимок экрана 2020-12-24 в 19 02 29" src="https://user-images.githubusercontent.com/76565028/103098156-cac60080-461a-11eb-834c-355c406c0c18.png">

In db 
<img width="414" alt="Снимок экрана 2020-12-24 в 19 03 31" src="https://user-images.githubusercontent.com/76565028/103098169-d1ed0e80-461a-11eb-9c8f-8a2cf774f140.png">

**Comment by vmihailenco** [comment]
How can I reproduce this problem?
