### ISSUE TITLE
I cant use "join_fk" with "has-one" Relation

### ISSUE THREAD

**Issue by KMACEL** [go-pg/pg#1812]
I want to use "has-one" relation. Example;

```
type UserDB struct {
	ID int `json:"-" 
	UserID      string    `json:"userID" pg:",unique"`
	 // Other user fields
}

type UserDetailDB struct {
	ID int `json:"-" `
	UserID      string    `json:"userID" pg:",unique"`
	UserDB      *UserDB `json:"user,omitempty" pg:"rel:has-one,fk:user_id,join_fk:user_id"`
      // Other User Detail fields
}

var userDetailDB []UserDetailDB
db.Model(&userDetailDB).Column("user_detail_db.*").Relation("UserDB") ....
```

When I do this, it creates a query like 

LEFT JOIN" user_dbs "AS" user_db "ON" user_db "." Id "=" user_detail_db "." User_id "

While "user_detail_db" gets "user_id" as I want, "user_db" gets "id". I want "user_id" in both tables. 

What can I do ?

**Comment by vmihailenco** [comment]
@KMACEL no, go-pg does not support `user_id` for has-one (but perhaps it should). It uses primary key which is `UserDB.ID` in your case.

**Comment by mojtabacazi** [comment]
@vmihailenco Any ETA on supporting fk and join fk for has-one queries ?
