### ISSUE TITLE
Current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by Barben360** [go-pg/pg#1813]
## Expected Behavior

Error in the transaction but client remains stable

## Current Behavior

When the context of a transaction gets cancelled, the following errors happen:

### Client-side error:
 
These errors occur:

```
tx.Rollback failed: ERROR #57014 canceling statement due to user request
```

```
ERROR #57014 canceling statement due to user request
```

Then during at least one minute, all transactions fail with:

```
ERROR #25P02 current transaction is aborted, commands ignored until end of transaction block
```

![image](https://user-images.githubusercontent.com/25642495/105964778-f6596200-6082-11eb-91e5-057e07f8a9cb.png)

### Server-side error

In a loop:

```
user=user,db=db,app=[unknown],client=xx.xxx.xx.xx LOG:  08006: could not receive data from client: Connection reset by peer
```

## Possible Solution

Perhaps when a transaction context gets cancelled (e.g, timeout), rollback of a transaction should be run anyway?

If you have any clue about what can be done in go-pg, we'd be pleased to help implement it.

## Steps to Reproduce

This error is quite random. At first it used to happen because too many connections were opened on the server. Now this problem is fixed (I am far under the client connections limit) but now it's fixed, but this still happens sometimes.

**Comment by vmihailenco** [comment]
I guess you should not pass such context to Rollback function. Perhaps go-pg should not accept one too, but I am not sure.

**Comment by Barben360** [comment]
Thank you for your quick answer. However I'm using `Rollback` through `RunInTransaction` so I don't have the control over having a different context for `Begin` and `Commit`/`Rollback`, so maybe indeed `Rollback` should use an independent context when the cause of transaction abortion is context cancellation?

**Comment by vmihailenco** [comment]
>so maybe indeed Rollback should use an independent context when the cause of transaction abortion is context cancellation

Sounds good.

But It does not explain why client becomes unstable. `RunInTransaction` always closes the transaction...

**Comment by Barben360** [comment]
What it seems anyway is that the "ROLLBACK" command is never called on the server so the transaction remains hanging until the transaction timeout deadline is reached, blocking everything on the server. This line of log:

```
tx.Rollback failed: ERROR #57014 canceling statement due to user request
```

makes me think that the rollback is attempted by go-pg, but something lower level does not even make the call attempt to the DB because of the cancelled context.

[This (solved) issue](https://github.com/lib/pq/issues/577) on (deprecated) `pq` project seems to talk about the same problem, maybe they are related?

**Comment by vmihailenco** [comment]
>the transaction remains hanging until the transaction timeout deadline is reached

Okay, this makes sense.

I think that go-pg should just ignore the context in `Rollback`, `Commit`, and `Close`. Because it seems impossible to use context cancellation correctly with those commands. In v11 context can be removed from accepted args. Does that sound good?

**Comment by Barben360** [comment]
I think it is ok to have an input context for these atomic commands because you may always need to avoid being indefinitely stuck, that would leave freedom to people who want to use these commands manually, they know the risk.

However I think that in `RunInTransaction`, a new context shall be created inside the function with a fixed timeout to process the final `Rollback`. I think that `Commit` should still use the context, because if the context is ending before the commit, `RunInTransaction` will return an error anyway, so we don't expect the commit to have worked but the transaction to have rolled back.

For `Close`, I'm not sure as I'm not familiar with it, what is the server doing if it receives a `Close` during a transaction?

**Comment by vmihailenco** [comment]
`Close` just calls `Rollback` if it was not already called.

>they know the risk

I doubt that. I did not know. And now when I know my immediate reaction is to not use context with those functions.

`context.Context` is just passed everywhere without much thinking. And deadline can be added to a context much later. So it is a ticking bomb that can be triggered by an innocent change.

**Comment by Barben360** [comment]
Indeed if there is no more information than context cancellation that is passed in the context then maybe it should not be passed. I think I'd still keep it for the commit for the reason explained above, however I think you may drop it for `Close` and `Rollback`, but the risk is then to hang somewhere, which may sometimes be worse than having a stalled transaction which will unlock by itself later.

**Comment by vmihailenco** [comment]
It looks like in v10 we have Rollback/RollbackContext so you can already fix this on your side by picking method without a context. I guess it is not worth it to change anything for v10.

~~In v11 I am going to remove context support from those 3 functions.~~

>but the risk is then to hang somewhere

You should use Read/WriteTimeout to prevent this. It is way cheaper and reliable then `context.Context`. And it will be set by default in v11.

**Comment by vmihailenco** [comment]
Scratch that. I've sent https://github.com/go-pg/pg/pull/1814 with your suggestion regarding run in transaction. Context will stay since it is used for other things as well (like tracing).

**Comment by Barben360** [comment]
I've sent #1815 based on the remarks I made in the comments of #1814. I've applied the copy of span for tracing, but if there are more things to carry in the context perhaps that's not the best solution.
