### ISSUE TITLE
Any way for to force an index in CockroachDB?

### ISSUE THREAD

**Issue by CyborgMaster** [go-pg/pg#1817]
We are using go-pg to connect to CockroachDB and need to force an index.  In CockroachDB, you can force an index using the syntax `SELECT * FROM table@my_idx;` (see: https://www.cockroachlabs.com/docs/v20.2/table-expressions#force-index-selection).  

I haven't come up with a solution yet.  Based on your suggestion in #1810.  I'm using a wrapper struct like this 

```go
type Wrapper struct {
    tableName struct{} `pg:"table@my_idx"`
    *SomeModel
}
```

However this generates a query like 
```sql
SELECT * FROM "table@my_idx";`
```

with quotes around the table name, which makes CockroachDB search for a table with that exact name instead of treating it like an index hint.  

Is there any way to append something to the table name outside the quotes?

**Comment by CyborgMaster** [comment]
I was able to work around this by having my wrapper have an empty table name:

``` go
type Wrapper struct {
    tableName struct{} `pg:"_"`
    *SomeModel
}
```

and using `TableExpr`
```go
db.Model(&wrapper).TableExpr("table@my_idx").Select()
```

This generated the query with a table name with no quotes, so it worked needed.  

I'm not going to immediately close this issue as I would love to see a cleaner API for accomplishing this, but the problem is no longer blocking.

**Comment by vmihailenco** [comment]
As #1817 suggests the cleaner solution will be `q.ModelTableExpr("table@my_idx")` in v11

**Comment by CyborgMaster** [comment]
Got it.  Of course.  The original request was because I couldn't figure it out in v10, but then after I figured it out, I forgot that you had already explained the cleaner API for v11.  My apologies.  

Is there a changelog for v11 where I can look at the upcoming additions for things like this?  `CHANGELOG.md` only links to  https://pg.uptrace.dev/changelog/, which doesn't have the upcoming changes yet.  In other places I've sometimes seen upcoming changes in an "unreleased" section of the changelog.

Thanks for your help.  Closing as resolved.

**Comment by CyborgMaster** [comment]
Any place I can look at that upcoming v11 changelog?

**Comment by vmihailenco** [comment]
@CyborgMaster I've added https://github.com/go-pg/pg/blob/v11/CHANGELOG.md , but v11 is far from done.

**Comment by CyborgMaster** [comment]
Awesome thanks!  I have no expectations on the timeline for v11.  Take your time.  I just wanted a place to look if the future so if I have an issue / suggestion I can check if you've already solved it before bugging you.
