### ISSUE TITLE
pg: unknown startup message response: 'N'

### ISSUE THREAD

**Issue by elliotcourant** [go-pg/pg#1830]
Issue tracker is used for reporting bugs and discussing new features. Please use
[Discord](https://discord.gg/rWtp5Aj) or [stackoverflow](https://stackoverflow.com) for supporting
issues.

## Expected Behavior

go-pg would do nothing or would not return an error.

## Current Behavior

go-pg returns an error `pg: unknown startup message response: 'N'`

## Possible Solution

Handle `N` messages during startup when the `Code:` is `42622`.

## Steps to Reproduce

```
	options := &pg.Options{
		Network:         "tcp",
		Addr:            os.Getenv("POSTGRES_HOST") + ":5432",
		User:            os.Getenv("POSTGRES_USER"),
		Password:        os.Getenv("POSTGRES_PASSWORD"),
		Database:        os.Getenv("POSTGRES_DB"),
		ApplicationName: "i am just a really really super long application name so that i make a notice during startup",
	}
	db := pg.Connect(options)

	require.NoError(t, db.Ping(context.Background()), "must ping database") // Error occurs here.
```

## Context (Environment)

When running tests in CI against a database I will append `t.Name()` to my application name to see what each test is doing. If a test name is too long this error occurs when connecting to the database.

![image](https://user-images.githubusercontent.com/37967690/107127892-ec9fdd80-687e-11eb-92d4-72a2d4eb61e1.png)

## Possible Implementation

I'm happy to make a PR for this and resolve it but wanted to open an issue for visibility until then. 
- Could simply truncate the application name in go-pg.
- Add handling of notices during startup for that particular code.

**Comment by vmihailenco** [comment]
>Could simply truncate the application name in go-pg.
>Add handling of notices during startup for that particular code.

Both suggestions sound reasonable and a PR is most welcome :)
