### ISSUE TITLE
ERROR #42P01 missing FROM-clause entry for table "_data"

### ISSUE THREAD

**Issue by ferhatelmas** [go-pg/pg#1836]
A simple test case to reproduce the error:
```go
m := []struct {
	tableName struct{} `pg:"test"`
	ID        uint64 `pg:"id,pk"`
	Name      string `pg:"name"`
}{{ID: 111}, {ID: 222}}

var names []string
_, err := db.Model(&m).WherePK().Returning("name").Delete(&names)
```

## Expected Behavior

Should work.

## Current Behavior

Returns error with the message in title.

## Context (Environment)

go-pg v10.7.7, pg v11.7

**Comment by siampudan** [comment]
I've the same issue while working on many2many relation.

**Comment by carameleon** [comment]
same error 
go-pg : 9.2, 10.8,  
pg : 12.4

account table have columns(id(pk), address(not null, unique)
```
tx.Model(&accounts).Where("address = ?address").OnConflict("DO NOTHING").SelectOrInsert()
```
results 
```
SELECT "account"."id", "account"."address" FROM "refine"."account" AS "account" WHERE (address = _data."address")
```

solution
deliver single data works fine. but slow.
```golang
for i := range e.SourceAccounts {
	accounts[i].Address = e.SourceAccounts[i].AccountAddress
	res, err := tx.Model(&accounts[i]).Where("address = ?address").OnConflict("DO NOTHING").Returning("id").SelectOrInsert()
	fmt.Println(res)
	fmt.Println(err)
}
```

deliver []data will be error
```golang
// ERROR #42P01 missing FROM-clause entry for table "_data"
//res, err := tx.Model(accounts).Where("address = ?address").OnConflict("DO NOTHING").Returning("id").SelectOrInsert()

```

**Comment by AnatolyRugalev** [comment]
It seems that the problem was introduced in https://github.com/go-pg/pg/commit/1b376451c961b8eb0ba9b604643d50a1e83e7039

`WherePK` now appends into `where` which makes [this code path](https://github.com/go-pg/pg/blob/c9ee578a38d6866649072df18a3dbb36ff369747/orm/delete.go#L90) unreachable. As a result we get incorrect SQL

**Comment by vmihailenco** [comment]
This is fixed in v11 branch but it requires rather big refactoring so it is unlikely to be backported to v10. Use v11 if this functionality is critical for you.

**Comment by ferhatelmas** [comment]
@vmihailenco thanks for your reply. We realized the scope and since we run a production workload, we can't go to v11 yet. We are keeping a fork for now and when v11 is ready, we will move to it then.

**Comment by vmihailenco** [comment]
I forgot to mention that removing `WherePK` should fix the query in v10. In v11 WherePK is required.
