### ISSUE TITLE
Support Multiple columns on relation.

### ISSUE THREAD

**Issue by debendraoli** [go-pg/pg#1839]
Issue tracker is used for reporting bugs and discussing new features. Please use
[Discord](https://discord.gg/rWtp5Aj) or [stackoverflow](https://stackoverflow.com) for supporting
issues.

## Expected Behavior

Support for selecting multiple columns when using Relation.

## Current Behavior

Currently It just selects one column only no matter how many columns you specify.

## Possible Solution

    db.Relation("User.id").ComunExpr(`"user"."name" as "user__name"`)

## Context (Environment)

In many cases we have to select multiple columns which is not possible without use of `ColumnExpr()`, supporting  within a relation would greatly facilitate.

## Possible Implementation

`db.Relation("User,id,name")`

**Comment by TDiazT** [comment]
I've used the following and it's worked, but idk if it's the intended way of using it:
```go
db.Relation("User.id").Relation("User.name")
```
I agree though that it'd be simpler if it were just a simple `Relation` call.
