### ISSUE TITLE
Bulk update errors with ERROR #42804 on custom type

### ISSUE THREAD

**Issue by masterentropy** [go-pg/pg#1841]
I am using the bulk update feature, by passing in an array of values into the library. My tables and types look like:

```go
type Shape struct {
	tableName models.TableName `pg:"shapes"`
	ID               string          `pg:"id,pk"`
        UserID           string          `pg:"user_id,notnull"`
	Type             ShapeType  `pg:"shape_type,notnull"`
}

type ShapeType string

const (
	ShapeTypeCircle ShapeType = "Circle"
	ShapeTypeSquare ShapeType = "Square"
)
```

And my SQL migration file:

```sql
CREATE TYPE shape_type AS ENUM ('Circle', 'Square');
ALTER TABLE shapes
    ADD COLUMN shape_type shape_type NOT NULL DEFAULT 'Circle';
```

## Expected Behavior

Should update the table with the new values with no errors. The query for bulk updates under the hood should look very similar to singular updates, with no COALESCE.

## Current Behavior

I get `ERROR #42804 COALESCE types text and shape_type cannot be matched`

## Steps to Reproduce

For example, I am using:

```go
shapes *[]*Shape
db.Model(shapes).WherePK().UpdateNotZero()
```

When I turn on additional Postgres query logging, I notice that go-pg tries to COALESCE every value:

```
UPDATE shapes AS "shape" SET "user_id" = COALESCE(_data."user_id", "shape"."user_id"), "shape_type" = COALESCE(_data."shape_type", "shape"."shape_type") FROM (VALUES ('22539aac-a97e-4d7c-a637-7837570bd229'::text, '5da66f29-d994-4a01-8e30-6d44038261d0'::text, 'Circle'::text), ('b13c7b7d-8085-4612-b951-8d353fe3b2d3'::text, '5fbf96c8-837c-4a08-aa3b-a292c9d65fa9'::text, 'Square'::text)) AS _data("id", "user_id", "shape_type") WHERE "shape"."id" IN ('22539aac-a97e-4d7c-a637-7837570bd229', 'b13c7b7d-8085-4612-b951-8d353fe3b2d3')
```

In comparison, when I do an update of a single object, ie. `*Shape`, the query under the hood looks normal:

```
UPDATE shapes AS "shape" SET "user_id" = '2283e6ba-1d01-424f-aa7b-7f5a2575a00e', "shape_type" = 'Circle' WHERE "shape"."id" = 'edf8eae7-5c25-4147-b456-0da2fdacebb5'
```

## Context (Environment)

I am using `go-pg v9.1.6`

**Comment by dsonck92** [comment]
You could try specifically indicating the type on the struct:

```go
type Shape struct {
    tableName models.TableName `pg:"shapes"`
    ID               string          `pg:"id,pk"`
    UserID           string          `pg:"user_id,notnull"`
    Type             ShapeType  `pg:"shape_type,notnull,type:shape_type"`
}
```

as found in #993

**Comment by masterentropy** [comment]
Thanks, that worked. What's odd is this was never a problem on singular inserts, nor did the ORM try to cast or COALESCE under the hood. I was able to insert records with custom types just fine without `type:the_type`. Another thing I noticed is that if I declared a column as type `UUID`, I also had to set `type:uuid` on the object field for bulk inserts. This was also not needed on singular inserts.

**Comment by vmihailenco** [comment]
@masterentropy that is how PostgreSQL works.

>When I turn on additional Postgres query logging, I notice that go-pg tries to COALESCE every value:

COALESCE has nothing to do with this behavior. You can manually remove COALESCE and you get the same error.

**Comment by masterentropy** [comment]
So it's a casting problem then, not a COALESCE problem.
> that is how PostgreSQL works.
Can you explain by what you mean by this? As I mentioned, on singular updates, this casting issue does not happen. It only happens on bulk updates. Can you explain why?

**Comment by masterentropy** [comment]
So it's a casting problem then, not a COALESCE problem.
> that is how PostgreSQL works.

Can you explain what you mean by this?

As I mentioned, on singular updates, this casting issue does not happen. It only happens on bulk updates. Can you explain why?

**Comment by vmihailenco** [comment]
>As I mentioned, on singular updates, this casting issue does not happen. It only happens on bulk updates. Can you explain why?

I don't know enough about PostgreSQL internals to explain this. go-pg is only responsible for generating SQL and scanning the data into Go models. We can change the generated SQL, not how Postgres handles it.

**Comment by masterentropy** [comment]
So my question was regarding why the SQL is being generated as such. If you look at my initial post, when I am inserting a single record, the generated SQL looks just fine, but when trying to insert a bulk amount of records, the SQL being generated is incorrect, and this is fixed by adding the `type` tag to my field, which tells `go-pg` the type of the field and no casts are in the generated SQL statement. So my question is why does `go-pg` function this way. I never asked anything about Postgres.

I expect both singular and bulk inserts/updates to work without any issues, with the above setup, but I do need to add `type` for bulk inserts to work correctly.
