### ISSUE TITLE
Order() doesn't support `COLLATE <name> ASC|DESC` syntax.

### ISSUE THREAD

**Issue by jeffreydwalter** [go-pg/pg#1845]
Issue tracker is used for reporting bugs and discussing new features. Please use
[Discord](https://discord.gg/rWtp5Aj) or [stackoverflow](https://stackoverflow.com) for supporting
issues.

PostgreSQL supports icu collation, but the go-pg library's Order() method does not have support for it and so does the wrong thing.

## Expected Behavior
```
If I have the following: 
q.Order(`product.name COLLATE icu_natural DESC`)

it should produce: 
ORDER BY "product"."name" COLLATE icu_natural DESC
```

## Current Behavior
```
If I have the following: 
q.Order(`product.name COLLATE icu_natural DESC`)

it produces: 
ORDER BY "product"."name COLLATE icu_natural DESC"
```

## Possible Implementation

PR: https://github.com/go-pg/pg/pull/1846

**Comment by vmihailenco** [comment]
`Order` is meant to accept data from end users (e.g. via URL query) and automatically quotes it against SQL injections. In all other cases `OrderExpr` should be used.

Could you confirm that you really want to accept variable `COLLATE` from users? It is a bit unusual...

**Comment by dsonck92** [comment]
@vmihailenco Hmm, I can see that viewpoint now. Perhaps update the docs on the Order function to highlight this usage as it's currently not that obvious. I mean, it's an Order function that quotes the column name, that much is clear. But perhaps adding "Which means userdata can be passed directly which is useful for handling sorting payloads from requests" or something in that line.

On the other hand, it may be useful for frontends to specify the collation as users may expect a different sorting based on their locale as deduced by the frontend whereby this feature results in less code between the frontend and go-pg layer as it could send a request including the COLLATE bit.

When I look at `NULLS FIRST/LAST`, while this is perfectly valid sent by the frontend, I expect this API not being directly exposed to users by the frontend but wrapped around some "unassigned first/last" checkbox. This could be the same for `COLLATE` where the frontend may send this, but also not directly expose it similar to NULLS. However, if this is properly handled and quoted, then the effort in the frontend would be very minimal:

```typescript
const sorting = [`${column} COLLATE ${user.locale} ${direction}`]
```
where `user.locale` would be some local state specifying whichever locale information is normal for the user. That's just my 2cts

**Comment by jeffreydwalter** [comment]
@vmihailenco why make a distinction for `Order()` like that? I don't know about you, but I would never take user input for ordering and pass it directly to a function like `Order()`. How would one guard against users creating invalid order by clauses with tables/columns that don't exist? Why would you expose implementation details to the client in that way? I would wager the more typical usecase is to parse the query string and build up a url.Values{} to pass to `Order()` which does the right thing. Either way, getting quoting for free is compelling enough for me to use `Order()` over `OrderExpr()` in the general case. Why not just make `Order()` support the full syntax of the `order by` clause?

**Comment by vmihailenco** [comment]
>why make a distinction for Order() like that?

Not sure what you mean, but go-pg has `Table/TableExpr` and `Column/ColumnExpr` with same distinction.

>How would one guard against users creating invalid order by clauses with tables/columns that don't exist?

Nothing bad happens AFAIK so why bother with validation.

>Why not just make Order() support the full syntax of the order by clause?

Because it is too complicated. E.g. `ORDER BY lower(something)` or `ORDER BY a + b`.

**Comment by vmihailenco** [comment]
@jeffreydwalter it sounds like you already have column and collate in separate vars. Then you can do

```go
q.OrderExpr(`? COLLATE ? DESC`, types.Ident("product.name"), types.Ident("icu_natural"))
```

>On the other hand, it may be useful for frontends to specify the collation as users may expect a different sorting based on their locale as deduced by the frontend whereby this feature results in less code between the frontend and go-pg layer as it could send a request including the COLLATE bit.

@dsonck92 yes, that is why I ask if you actually send order with collate from a frontend or this is just a mis-understanding.

**Comment by vmihailenco** [comment]
I assume that this was a misunderstanding and OrderExpr works for you.

I've tried to improve documentation in https://github.com/go-pg/pg/commit/60841bb785e27df2a3d0fd8e18eca9605ea7d88e
