### ISSUE TITLE
v3 multiple inserts returning values

### ISSUE THREAD

**Issue by rbatukaev** [go-pg/pg#185]
I have written query that insert multiple rows using the following construct:

`db.Query(hold, "INSERT INTO table (id, name, url) VALUES (?, ?, ?), (?, ?, ?), ... returning id, url", args...)
`

Is it possible to load returned `id` and `url` values to a slice `hold` ? Is there a way to access the result directly?

**Comment by vmihailenco** [comment]
Sure, if you define hold as:

```
type A struct {
    Id int64
    URL string
}
var hold []A
db.Query(&hold, ...)
```

**Comment by vmihailenco** [comment]
If you are interested I can also improve https://godoc.org/gopkg.in/pg.v4#DB.Create to accept several arguments, .e.g. `db.Create(item1, item2).Returning("id", "url")`.

**Comment by rbatukaev** [comment]
Thanks a lot!
