### ISSUE TITLE
Timestamps and model definitions tags

### ISSUE THREAD

**Issue by silasb** [go-pg/pg#186]
I have a SQL table like so:

```SQL
CREATE TABLE IF NOT EXISTS users (
	id SERIAL,
	uuid UUID, -- default gen_random_uuid(),
	name TEXT,
	email TEXT UNIQUE,
	created_at TIMESTAMP DEFAULT NOW(),
	updated_at TIMESTAMP
);
```

My model definition is:

```Go
type User struct {
	TableName struct{} `sql:"users"`
	Id        int64
	UUID      uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time `sql:",null"`
	UpdatedAt time.Time `sql:",null"`
}
```

When I try to create a new user via:

```Go
	uuid, _ := uuid.V4()

	user := &User{
		Email: to,
		UUID:  uuid,
	}
	err := db.Create(user)
	if err != nil {
		panic(err)
	}
```

I panic with `ERROR #22008 date/time field value out of range: "0000-12-31 19:00:00-05:00":`

It looks like I initialize the struct with default time stamp, which I'm not sure how to avoid.  I was hoping that the `sql:",null"` would stop that, but it doesn't appear to help.

In my case, I'd like to have the DB handle creating the date.

It's also be nice to understand what the struct tags actually do without reading the code.

**Comment by vmihailenco** [comment]
Thanks for the report. I fixed `sql:",null"` to do the right thing. Please try latest version.
