### ISSUE TITLE
Possible to periodically update passwords? 

### ISSUE THREAD

**Issue by nick567187** [go-pg/pg#1864]
This is a replication of an issue posted in PGX which has more fine-grained control over connection pooling.

https://github.com/jackc/pgx/issues/676

I am working with Hashicorp Vault in Kubernetes which can dynamically generate database roles for short-lived sessions. Would be nice if go-pg supported a way to instrument the new configs on new connections to the pool or if a new pool can be created while allowing the old one to finish queries and garbage collect

**Comment by vmihailenco** [comment]
Let's keep this discussion in https://github.com/go-pg/pg/discussions/1848

Changing password for new connections is not hard, but properly closing existing connections is. As I understand https://github.com/jackc/pgx/issues/676 is only about the former.
