### ISSUE TITLE
Connection pool timeout

### ISSUE THREAD

**Issue by rbatukaev** [go-pg/pg#188]
I am constantly getting "pg: connection pool timeout" using api v3. However, at the same time I still can connect to the same database using PgAdmin and another go application. The only workaround is to restart the API application completely. 

To connect to the database I do the following:
```
options := pg.Options{
	User:     postgres.User,
	Password: postgres.Password,
	Database: postgres.Database,
	Host:     postgres.Host,
	Port:     postgres.Port,
}
db = pg.Connect(&options)
db = db.WithTimeout(30 * time.Second)
```

And when the API accepts incoming requests, it queries the database. 
I never had this issue when connecting to the local database, but now I need to use the database that is in the cloud through public IP address.

What could it be? Thanks.

**Comment by vmihailenco** [comment]
Could be:
- long running queries so there are no free connections in the pool
- Tx/Stmt/Listener is not closed properly so connections are not freed
- https://github.com/go-pg/pg/issues/137

**Comment by rbatukaev** [comment]
1. The queries are fairly simple and take 1-40ms. 
2. I do not use any transactions and listeners, and query the database using DB struct

**Comment by vmihailenco** [comment]
What about panics? Do you use recover?

Overall I use both pg.v3 and pg.v4 in production so there should not be stupid/obvious bugs...

**Comment by rbatukaev** [comment]
Yes, I have recover middleware implemented in the application. In case of panics, it recovers and sends me full stack trace to my email address (I have not received any these days).

**Comment by rbatukaev** [comment]
I am sorry, it was an issue on my side. I am going to close the issue. Thanks again!

**Comment by zdebeer99** [comment]
@rbatukaev can you please explain what the issue on your side was as I am getting the same behaviour.

**Comment by zdebeer99** [comment]
I am using Stmt created by prepare and was not closing them, after I added defer stmt.Close() to all my stmt after using them, the connection pool error went away. Thanks.

**Comment by rbatukaev** [comment]
My issue was related to Azure Load Balancer.
