### ISSUE TITLE
?TableAlias with TableExpr

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1891]
Is it possible that using `TableExpr` with `?TableAlias.?` doesn't replace `?TableAlias`?

I'm using this code:

```go
Model().TableExpr("(?) as a", myQuery).Select(&output)

...

q.Where("?TableAlias.? > ?", pg.Ident(value), cursors[index])
```

and it gives me:

```
ERROR #42P01 missing FROM-clause entry for table \"tablealias\""
```

but without `TableExpr` it works!

**Comment by vmihailenco** [comment]
What query go-pg generates?

You can try `q.Where("?(TableAlias).? > ?", pg.Ident(value), cursors[index])`
