### ISSUE TITLE
db.Update is returning an error

### ISSUE THREAD

**Issue by yawhide** [go-pg/pg#192]
On the latest version of this repo.

Here is my error:

`ERROR #42601 syntax error at end of input: `

this is what I am doing:
```
var s Summoner
err = db.Model(&s).Where("summoner_id = ?", summonerId).Select()
s.MasteriesUpdatedAt = time.Now().UTC()
fmt.Println(s) // things looking good!

err = db.Update(&s)
if err != nil {
    fmt.Println(err) // error is `ERROR #42601 syntax error at end of input: `
}
```

doesn't seem like I am doing anything wrong?

**Comment by vmihailenco** [comment]
You probably need to mark `summoner_id` as primary key, e.g.

```
type Summoner struct {
    SummonerId int `sql:",pk"`
}
```

or rewrite update as

```
db.Model(&s).Where("summoner_id = ?summoner_id").Update()
```

or even better

```
db.Model(&s).Set("updated_at = ?updated_at").Where("summoner_id = ?summoner_id").Update()
```

PS I will also make sure that go-pg returns better error in such case.

**Comment by yawhide** [comment]
thanks for the very fast reply!

SO i added the `sql:",pk"` to my Summoner struct, then proceeded to use the same code in the OP, and I still got the same error ` ERROR #42601 syntax error at end of input: `.

I then tried one of the other examples you posted and this one worked:
`db.Model(&s).Set("masteries_updated_at = ?masteries_updated_at").Where("summoner_id = ?summoner_id").Update()` but I still needed to do the `SELECT` before hand and change `s` (the instances of the Summoner class).

2 questions, 
1. is there a way to print out the sql this library generates?
2. I know in sql, you can call `UPDATE` without having to do a `SELECT` first as long as you have enough info for the `WHERE` clause. How can I do that in your library?
I tried the following but to no avail:
```
var s Summoner
db.Model(&s).Set("masteries_updated_at = ?", time.Now().UTC()).Where("summoner_id = ?summoner_id").Update()
```

thanks again!

**Comment by vmihailenco** [comment]
>is there a way to print out the sql this library generates?

Please see https://github.com/go-pg/pg#how-can-i-view-queries-this-library-generates. Then please paste here queries that library generates, because I don't see anything wrong in examples you provided.

>db.Model(&s).Set("masteries_updated_at = ?", time.Now().UTC()).Where("summoner_id = ?summoner_id").Update()

This should generate something like:

```
UPDATE table_name
SET masteries_updated_at = 'time here'
WHERE summoner_id = 'id here'
```

So it should work fine...

**Comment by vmihailenco** [comment]
I also added new section to the readme, which should give you good overview of queries https://github.com/go-pg/pg#writing-queries

**Comment by yawhide** [comment]
hello, so I am having a weird issue where I am getting a error:
```
2016/05/07 19:20:07 http: panic serving [::1]:56384: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc82007d900)
	/usr/local/opt/go/libexec/src/net/http/server.go:1389 +0xc1
panic(0x5a8440, 0xc82000a100)
	/usr/local/opt/go/libexec/src/runtime/panic.go:426 +0x4e9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x290a588, 0xc8201dc1a0, 0x5e5c20, 0xc82005e2a0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/html/template/template.go:101 +0x34
main.GetMatchup(0xabac50, 0xc8201dc1a0, 0xc8201127e0)
	/Users/yawhide/golang/src/github.com/yawhide/lol-counter/main.go:193 +0x1202
net/http.HandlerFunc.ServeHTTP(0x7603f0, 0xabac50, 0xc8201dc1a0, 0xc8201127e0)
	/usr/local/opt/go/libexec/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82000eb40, 0xabac50, 0xc8201dc1a0, 0xc8201127e0)
	/usr/local/opt/go/libexec/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82007d880, 0xabac50, 0xc8201dc1a0, 0xc8201127e0)
	/usr/local/opt/go/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82007d900)
	/usr/local/opt/go/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/opt/go/libexec/src/net/http/server.go:2137 +0x44e
2016/05/07 19:20:07 http: proxy error: EOF
```
using the following:
```
var matchups []ChampionMatchup
err = db.Model(&matchups).Order("win_rate desc").Select()
```
