### ISSUE TITLE
Postgres Array in datamodel

### ISSUE THREAD

**Issue by ly-william** [go-pg/pg#206]
Hey, didn't know where else I could post the question so there it is.

How can I represent an array type in the model ?
I have a table that has a field of type `double precision[]` and I want to represent it in my go code.

Neither
```
type MyTable struct {
    MyField []float64
}
```
Nor
```
type MyTable struct {
    MyField types.Array
}
```
seems to do the trick.

For now I retrieve it as a string and parse it afterwards. Is there another way ?

One more quick question there doesn't seem to be an UUID type, I'll just have to use a string here as well ?

**Comment by vmihailenco** [comment]
Hey, can you try:

```
type MyTable struct {
    MyField []float64 `pg:",array"`
}
```

There is an example https://godoc.org/gopkg.in/pg.v4#example-DB-Model-PostgresArrayStructTag

**Comment by vmihailenco** [comment]
>One more quick question there doesn't seem to be an UUID type

I did not try, but this package can help: https://github.com/m4rw3r/uuid. Basically any type that implement sql.Scanner can be used with go-pg.

**Comment by ly-william** [comment]
Oh I wasn't aware of those, didn't see that example in the doc. My mistake :)
It works like a charm. Thanks for your help.
