### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by yawhide** [go-pg/pg#218]
Hello,

I cant find any examples of bulk inserting: `insert into ____ values (...), (...), ...`

Am I blind? Or has this just not been implemented? I tried calling `db.Create()` with a slice of instances of my struct (instead of just a single instance of a struct) and the lib throws a panic:
```
2016/05/13 10:58:25 http: panic serving [::1]:53762: reflect: call of reflect.Value.Field on slice Value
```

**Comment by vmihailenco** [comment]
It is not implemented yet. I will try to look at this over weekend... or you can give it a try yourself :) https://github.com/go-pg/pg/blob/v4/orm/insert.go

**Comment by yawhide** [comment]
thanks!
