### ISSUE TITLE
Create generates an erroneous query with 'AS'

### ISSUE THREAD

**Issue by farnzworld** [go-pg/pg#220]
My Simple Tryouts:
`var modelTables = [...]string{
	`CREATE TABLE IF NOT EXISTS accounts (
		id       serial      PRIMARY KEY,
		username varchar(64) UNIQUE NOT NULL,
		password varchar(64) NOT NULL,
		forename varchar(64) NOT NULL,
		surname  varchar(64) NOT NULL
	);`,
}

type Account struct {
	Id       int64  `json:"-" xml:"-" sql:"id"`
	Username string `json:"-" xml:"-" sql:"username"`
	Password string `json:"-" xml:"-" sql:"password"`
	Forename string `json:"forename" xml:"forename" sql:"forename"`
	Surname  string `json:"surname" xml:"surname" sql:"surname"`
}

var Db *pg.DB

func init() {
	options := pg.Options{
		User:     "postgres",
		Password: "postgres",
		Database: "dat_test",
		SSL:      false,
	}
	Db = pg.Connect(&options)

	for _, createTableIfNotExists := range modelTables {
		result, err := Db.Exec(createTableIfNotExists)
		if err != nil {
			panic(err)
		} else {
			fmt.Println(result.Affected(), result)
		}
	}

	account := &Account{
		Username:"gordon",
		Password:"secret!",
		Forename:"Gordon",
		Surname:"Shamway",
	}
	err := Db.Create(account)
	if err != nil {
		panic(err)
	}
}`

Result:
ERROR:  syntax error at or near "AS" at character 24
STATEMENT:  INSERT INTO "accounts" AS "account" ("username", "password", "forename", "surname") VALUES ('gordon', 'secret!', 'Gordon', 'Shamway') RETURNING "id"

**Comment by vmihailenco** [comment]
Are you on latest version? It was fixed some time ago in https://github.com/go-pg/pg/issues/210:

```
go get -u gopkg.in/pg.v4
```

**Comment by farnzworld** [comment]
That did the trick - thanks!
