### ISSUE TITLE
Erroneous 'AS' with ...OnConflict()...Create()

### ISSUE THREAD

**Issue by farnzworld** [go-pg/pg#221]
Modeling of:
```golang
var modelTables = [...]string{
	`CREATE TABLE IF NOT EXISTS accounts (
		id       	serial      	PRIMARY KEY,
		username 	varchar(64) 	UNIQUE NOT NULL,
		password_hash 	text 		NOT NULL,
		forename 	varchar(64) 	NOT NULL,
		surname  	varchar(64) 	NOT NULL
	);`,
}

type Account struct {
	Id       int64  `json:"-" xml:"-" sql:"id"`
	Username string `json:"-" xml:"-" sql:"username"`
	PasswordHash string `json:"-" xml:"-" sql:"password_hash"`
	Forename string `json:"forename" xml:"forename" sql:"forename"`
	Surname  string `json:"surname" xml:"surname" sql:"surname"`
}

...
_, err = Db.Model(&account).OnConflict("(username) DO UPDATE").Set("password_hash = ?password_hash").Create()
...
```

Results in:
ERROR:  syntax error at or near "AS" at character 24
STATEMENT:  INSERT INTO "accounts" AS "account" ("id", "username", "password_hash", "forename", "surname") VALUES (DEFAULT, 'gordon', '$2a$10$PDevC/oUEdRVFLEiIkj.Zu6v9DmTRNuIiMIhqOmec8C8Z2XYQmfQm', 'Gordon', 'Shamway') ON CONFLICT (username) DO UPDATE SET password_hash = '$2a$10$PDevC/oUEdRVFLEiIkj.Zu6v9DmTRNuIiMIhqOmec8C8Z2XYQmfQm' RETURNING "id"

last 'go get -u gopkg.in/pg.v4' today

**Comment by vmihailenco** [comment]
Generated query looks good. My guess is that you need to update your PostgreSQL to version 9.5, because earlier versions don't support `ON CONFLICT` and table alias in `INSERT`.

**Comment by farnzworld** [comment]
Thanks very much! Now it works - Maybe you should point that out in your README...

Good job btw, I really like working with pg!
