### ISSUE TITLE
Error retrieving 'bytea' to type []byte

### ISSUE THREAD

**Issue by farnzworld** [go-pg/pg#223]
I'm using bcrypt for password hashing and want to save it as bytea in the db-column. 
My struct User has a field passwordhash with type []byte.

Saving to db works fine, but retrieving it just won't!

```golang
var passwordHash []byte
err = Db.Model(&User{}).Column("password_hash").Where("username = ?", username).Select(&passwordHash)
```

> Error: strconv.ParseUint: parsing "\\x2432612431302459627548334171664647364b6c616b5955776f6d384f68317a62317a6c446d56586e70505655677272515a324a7374646e78676553": invalid syntax

I know, it works with string, but due to performance in a webservice I would prefer to not convert from/to string

**Comment by vmihailenco** [comment]
TLDR: update go-pg and change code to `Select(pg.Scan(&bytes))`

Overall there are 2 possibilities here:
1. you want to scan bytea - use `Select(pg.Scan(&bytes))`
2. you want to scan N rows that have 1 column containing uint8 into []uint8, i.e. array of numbers - use `Select(&bytes)`

**Comment by farnzworld** [comment]
Thanks - works!
