### ISSUE TITLE
Schemas?

### ISSUE THREAD

**Issue by fgblomqvist** [go-pg/pg#229]
I'm a little confused about how go-pg deals with schemas. It is not mentioned anywhere in the documentation/readme. To me it seems like go-pg just works with 'public'. I'm guessing you encourage your users to use the multiple db's -- one schema approach?

Also, a side question: when you say that go-pg generates table names, identifies primary keys etc, I'm guessing this is just for access? Because it cannot generate (aka. init the db) the schema itself, can it?

**Comment by vmihailenco** [comment]
>I'm guessing you encourage your users to use the multiple db's -- one schema approach?

I am not sure what you mean, but you can specify custom table name containing schema, e.g.

```
type Article struct {
    TableName `sql:"my_schema.articles"`
}
```

https://github.com/go-pg/sharding/ uses such approach to shard data in multiple schemas.

>Because it cannot generate (aka. init the db) the schema itself, can it?

No, it can't but I would like to add such ability at some point.

**Comment by fgblomqvist** [comment]
Okay, thanks!

**Comment by smahalingam** [comment]
Following works in public schema 
type Applications struct {
	AppId   int    `sql:"app_id"`
	AppName string `sql:"app_name"`
	AppCode string `sql:"app_code"`
	AppDesc string `sql:"app_desc"`
	Url     string `sql:"url"`
	Status  int    `sql:"status"`
}

What should i do to make it work in 'xxx' schema ?.

Thanks in advance

**Comment by vmihailenco** [comment]
Try

```
type Applications struct {
tableName struct{} `sql:"xxx.applications"`
}
```

**Comment by smahalingam** [comment]
Works like a charm. Thanks for your help
