### ISSUE TITLE
pg.scan function uses Boolean variable

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#231]
First I'm sure this record exists,because this code works fine:
``` go
	var id string
	result, err := db.QueryOne(pg.Scan(&id), "select id from users where id=?", "test")
	if err != nil {
		log.Fatalln(err.Error())
	}
	if result.Affected() == 0 {
		log.Fatalln("do not exist")
	}
	log.Println(id)	//Print "test"
```
Now I only judge whether the record exists, use a Boolean variable:
``` go
	var exist bool
	result, err := db.QueryOne(pg.Scan(&exist), "select 1 from users where id=?", "test")
	if err != nil {
		log.Fatalln(err.Error())
	}
	if result.Affected() == 0 {
		log.Fatalln("do not exist")
	} else {
		log.Println(result.Affected()) //Here returns a value greater than 0
	}
	if exist == true {
		log.Println("Record exists")
	} else {
		log.Println("do not exist")
	}
```
The err variable value is nil and result.Affected () returns a value greater than 0, but exist variable value is always FALSE, I try to use the lib/pq package is normal, I think this is a bug.

**Comment by vmihailenco** [comment]
Please try to replace `select 1` with `select 't'` or `select 1::bool`. Currently go-pg is not smart enough to scan 1 as boolean true - https://github.com/go-pg/pg/blob/v4/types/scan_value.go#L141-L151

**Comment by dxvgef** [comment]
OK, I try to use `select 1::bool` now everything is normal, thank you!
