### ISSUE TITLE
Map struct field to PostgreSQL time column

### ISSUE THREAD

**Issue by fgblomqvist** [go-pg/pg#233]
According to the docs, you can store time information using the time.Time type, which has to map to a timestamp column. Is it possible to map some datatype to a time column? The postgres time datatype only stores time of day. Maybe add a field tag to a time.Time type where you specify the column data type you will be mapping to? Or is there already another data type in go which maps to the time data type?

**Comment by vmihailenco** [comment]
I don't have anything working at the moment. But you can create such type yourself (not tested).

```
type PGTime time.Time

func (tm PGTime) Value(driver.Value, error) {
    return tm.Format("15:04:05"), nil
}
```

Probably go-pg should support custom time format via field tag:

```
type Item struct {
    CreatedAt time.Time `sql:",type:time"`
}
```

But this requires some investigation and coding...

**Comment by fgblomqvist** [comment]
Thank you, was not aware that I could do that. I implemented the following type:

```
type TimeOfDay struct {
	time.Time
}

func (tod TimeOfDay) Value() (driver.Value, error) {
	return tod.Format("15:04:05"), nil
}

func (tod TimeOfDay) Parse(value string) (TimeOfDay, error) {
	var err error
	tod.Time, err = time.Parse("3:04 PM", value)

	return tod, err
}
```

Also, the suggestion you made sounds good. Maybe in the future this could be implemented.
