### ISSUE TITLE
Postgres Log "incomplete message from client" when closing connection

### ISSUE THREAD

**Issue by Matt3o12** [go-pg/pg#238]
I don't know if this is really a bug but I notice a lot of `incomplete message from client` log entries from Postgres when calling db.Close().

I have a lot of new connections during the unit tests and thus the logs get floated with those messages. 

Here is a testcase:

	func main() {
		db := pg.Connect(&pg.Options{User: "postgres"})
		fmt.Println(db.Exec("CREATE TEMP TABLE test();"))
		fmt.Println(db.Exec("SELECT * FROM test;"))
		fmt.Println(db.Close())
	}

No errors are reported except those log messages in the postgres server log.

I'm using postgres PostgreSQL 9.5.3 on x86_64-pc-linux-gnu using the docker image and no custom configurations. If my server is misconfigured, please let me know as well.

**Comment by vmihailenco** [comment]
It is already fixed it latest version - please try to upgrade. AFAIK this bug should not cause any problems.

**Comment by vmihailenco** [comment]
Thanks for reporting this anyway!

**Comment by jerrytgill** [comment]
This is not fixed in v9.6.2.

**Comment by vmihailenco** [comment]
Do you close database with `db.Close`? If not then you will get `incomplete message from client`.

**Comment by jerrytgill** [comment]
Unfortunately, I cannot tell the origin of the issue; I have tracked it back to IBM's Infosphere Data Stage set of jobs. We are still researching the message, but at this point, it is a low priority. I will update here if we find any useful information. Thanks for the feedback.
