### ISSUE TITLE
some update case primary key may be empty

### ISSUE THREAD

**Issue by kongfei605** [go-pg/pg#243]
type Test struct {
TableName string `sql:”test”`
Id int64 `sql:”id,pk”`
UserId int64 `sql:”user_id”`
Info string `sql:”info, type:json”`
}

CREATE SEQUENCE test_id_seq;
CREATE TABLE IF NOT EXISTS test (
id bigint DEFAULT nextval('test_id_seq'),
user_id bigint,
info json,
PRIMARY KEY(id)
) WITH (OIDS=FALSE); 
CREATE UNIQUE INDEX idx_uid on test(user_id)

when I use 
 err = db.Model(&this).Column(“info”).Where(“user_id = ?”, this.UserId).Update(),
it shows 
**pg: primary key is empty**

so I have to use : 
_, err = db.Exec(“UPDATE test SET info= ? WHERE user_id= ?”, this.Info, this.UserId)

It seems the Column method does not work.

**Comment by vmihailenco** [comment]
Looks like you are using old version. Please upgrade:

```
go get -u gopkg.in/pg.v4
```

Also your struct can be simplified to:

```
type Test struct {
    TableName struct{} `sql:”test”`
    Id int64
    UserId int64
    Info map[string]interface{} // or any other type supported by encoding/json
}
```

**Comment by vmihailenco** [comment]
@kongfei605 I assume this is fixed by upgrading to latest version. Closing.

**Comment by kongfei605** [comment]
This problem is truely caused by the old version, and solved with command "go get -u" .
sorry so late to feedback. these two days i am away from my desk .
 thanks a lot
