### ISSUE TITLE
Question - Support for Raw SQL

### ISSUE THREAD

**Issue by allochi** [go-pg/pg#244]
Hi, I'm new to go-pg, thanks for the good work, I was wondering am I missing something, is there a raw sql query? like

```go
err = db.Model(&items).Select(`select * from items where order > $1;`, somevalue)
```

I want to port an application and I already have all the `sql`, I just need to use it instead of chain of functions.

Thanks!

**Comment by vmihailenco** [comment]
Yes, see https://godoc.org/gopkg.in/pg.v4#example-DB-Query:

```
db.Query(&items, `select * from items where order > ?`, somevalue)
```

**Comment by allochi** [comment]
Many thanks! I was checking the github page only, this is going to be really useful.

**Comment by andreleoni** [comment]
This not worked for me.

I'm getting the follow error  `multiple-value postgres.Client.baseDB.Query() in single-value contextgo`

I'm trying to perform a query one `err := postgres.Client.QueryOne(&user, query, "1")` from a instantiated client in another package like this

```
package postgres

import (
	"github.com/go-pg/pg"
)

var Client *pg.DB

func SetupClient() {
	Client = pg.Connect(&pg.Options{
		Addr:     "localhost:5432",
		Database: "website_development",
		User:     "postgres",
		Password: "postgres"})
}
```
