### ISSUE TITLE
getting a lot of `pg: connection pool timeout` and don't know how to solve it

### ISSUE THREAD

**Issue by yawhide** [go-pg/pg#249]
So I am doing a lot of writes (100-1000 writes per second) on a single local postgres instance and after a few hours of doing this, I start constantly getting `pg:connection pool timeout` as the error from doing an insert. I tried setting 
```
PoolSize:    20,
PoolTimeout: time.Second * 30,
```
and halving the number of writes (used to be twice as much) but I am still getting this error. 

Can you shed some light why this is happening?

**Comment by vmihailenco** [comment]
There can be 2 reasons:
1. connection leaking, e.g. you don't close `Tx` or `Stmt` (`defer tx.Close()`). So after some time go-pg does not have free connections to use.
2. postgres is slow - enable Postgres logging to check this

I bet on 1). To check my apps for connection leaking I run tests with PoolSize=1 (or 2 if you use transactions).

**Comment by yawhide** [comment]
I dont use tx or stmt. I only ever use db.Model.Create/Select or db.Create

but I shall take a look at PoolSize=1

thanks

**Comment by yawhide** [comment]
yeah I just had to use more pools. I was using them all up

**Comment by yawhide** [comment]
I think the docs say 10? I changed to 40 (doing about 40 inserts
concurrently at a given time)

**Comment by MohitKS5** [comment]
@vmihailenco The `db.RunInTransaction` handles `tx.close()` itself right ?

**Comment by wgeorgecook** [comment]
@MohitKS5 I know this is an old comment but for posterity yes, `db.RunInTransaction` does close the transaction. 

`RunInTransaction` will invoke the provided function and on either error or panic call `tx.RollbackContext`. If no error it will run `tx.CommitContext`. Both of which will call `tx.Close`.
