### ISSUE TITLE
Id key with a different name

### ISSUE THREAD

**Issue by ly-william** [go-pg/pg#251]
I have a table:
```
type MyTable struct {
  TableName struct{} `sql:"my_table"`

  Uuid string `sql:"pk"`
  ... // some other fields
}
```

My table is configured to generated automatically a new UUID when none is given. I want to create a new model easily using the orm by filling all the fields, calling `Create` and then retrieving the new Uuid.
I have a problem with the generated sql when inserting a new element. It tries to insert with an empty UUID which cause uuid format exception.

How to indicate to the framework than my Uuid is the primary key ? Kinda new to this, I tried to add `pg:"pk:"` without success. Is there an easy way to find the tag arguments available and what they do ?

**Comment by vmihailenco** [comment]
It should be sql:",pk" - note the comma before pk. Probably Uuid should be detected as primary key automatically.

**Comment by ly-william** [comment]
Even with the extra comma I still got the same problem, the generated creation request gives an empty string value for the uuid field.

**Comment by ly-william** [comment]
Ops nop I made a mistake, now I have the error: `pg: Scan(nonsettable string)`

**Comment by vmihailenco** [comment]
Please show the code. `nonsettable string` means that you need to pass pointer to string or struct.

**Comment by ly-william** [comment]
Oh indeed, I gave the struct to create instead of a pointer, my bad. It now works, thanks again for your help.
