### ISSUE TITLE
segfault when using uuid

### ISSUE THREAD

**Issue by rodriguise** [go-pg/pg#256]
If I add a uuid to my structure using the	"github.com/m4rw3r/uuid" package, go segfaults.

I have the table set to auto generate the uuid, I have tried setting sql:",null"` on the uuid field with no success.

CREATE TABLE IF NOT EXISTS mojo.members 
	                    (id serial, 
	                     uuid UUID DEFAULT uuid_generate_v4() NOT NULL,
	                     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(), 
	                     updated_at TIMESTAMP WITH TIME ZONE, 
	                     user_data jsonb, 
	                     meta_data jsonb,
	                     full_name varchar(256),
	                     display_name varchar(256),
	                     dob date,
	                     phones jsonb,
	                     addresses jsonb,
	                     emails jsonb
	                    )

-----
Program received signal SIGSEGV, Segmentation fault.
0x0000000000581a7f in gopkg.in/pg.v4/orm.(*Field).AppendValue (f=0xc820211ab0, b=..., strct=..., quote=1, ~r3=...) at /usr/local/go/src/gopkg.in/pg.v4/orm/field.go:57
57              return f.append(b, fv, quote)

**Comment by rodriguise** [comment]
I solved this by defining my model using a pointer

```

Member struct {
		*base.Record

		TableName struct{} `sql:"mojo.members"`

		// UUID is the member's uuid
		UUID *uuid.UUID `json:"uuid" sql:",null"`

		// FullName is the member's fullname
		FullName string `json:"full_name"`

		// DisplayName is the member's display name
		DisplayName string `json:"display_name"`

		// Dob is the member's date of birth
		Dob time.Time `json:"dob" sql:",null"`

		// Phones is an array of phone numbers for the member
		Phones []PhoneNumber `json:"phones"`

		// Addresses is an array of street addresses for the member
		Addresses []StreetAddress `json:"addresses"`

		// Emails represents the users known email addresses
		Emails []EmailAddress `json:"emails"`
	}
```

Perhaps the docs should be updated.

**Comment by vmihailenco** [comment]
Do you mean that `UUID uuid.UUID` does not work? It is not clear which pointer you have in mind.

**Comment by vmihailenco** [comment]
Closing since I can't do anything without more info.
