### ISSUE TITLE
inserting arrays is broken

### ISSUE THREAD

**Issue by yawhide** [go-pg/pg#260]
Hello,

So I am trying to insert an array of uint64s into my postgres table and I am getting the following error:
```
ERROR #22P02 malformed array literal: "[28621476,23789923,35389760,21420602,34360010,32624658,73510474,36811901,62282190,20007678]": Missing "]" after array dimensions.
```
I checked the postgres logs and this is how its making the insert call

```
LOG:  statement: INSERT INTO "match_stores" AS "match_store" ("match_id", "region", "queue_type", "timestamp", "summoner_id", "game") VALUES (2124282787, 'NA', 'TEAM_BUILDER_DRAFT_RANKED_5x5', 1457917349491, '[43181889,19868733,54699819,26385095,39595778,20007678,66231754,19173646,21543823,22251662]', ...
```

changing the log to the following successfully inserts the the row
```
LOG:  statement: INSERT INTO "match_stores" AS "match_store" ("match_id", "region", "queue_type", "timestamp", "summoner_id", "game") VALUES (2124282787, 'NA', 'TEAM_BUILDER_DRAFT_RANKED_5x5', 1457917349491, '{43181889,19868733,54699819,26385095,39595778,20007678,66231754,19173646,21543823,22251662}',
```

thanks

ps. how do I make code segments word wrap?

**Comment by vmihailenco** [comment]
My guess is that you need need to add `pg:,array` tag to `[]uint64` field - https://godoc.org/gopkg.in/pg.v4#example-DB-Model-PostgresArrayStructTag. By default structs and slices are marshaled as JSON, because jsonb data type is much more flexible.

**Comment by yawhide** [comment]
sorry thanks

**Comment by narrowizard** [comment]
> My guess is that you need need to add `pg:,array` tag to `[]uint64` field - https://godoc.org/gopkg.in/pg.v4#example-DB-Model-PostgresArrayStructTag. By default structs and slices are marshaled as JSON, because jsonb data type is much more flexible.
> 
> > ps. how do I make code segments word wrap?
> 
> No ideas :)

`pg:,array` not works for me but `pg:",array"` works. (notice the quote.)
