### ISSUE TITLE
whereOr cancels out hasMany

### ISSUE THREAD

**Issue by LennartOlsen** [go-pg/pg#266]
Hi.

Ive been using the belongs with a where statement like so :
```go
e := []models.Company
s.conn.Model(&e).
Column("company.*", "CompanyPerson").
WhereOr(
	pg.SQL("contact_person.entity_type = ?", new(models.ContactPerson).GetType()),
	pg.SQL("contact_person IS NULL"),
).
Select(); 
```
And it works beautifully creates the following sql

```sql
SELECT 	"company".*, 
		"contact_person"."entity_type" AS "contact_person__entity_type", 
		"contact_person"."company_id" AS "contact_person__company_id"  
FROM 	"companies" AS "company" 
LEFT JOIN 
	"company_persons" AS "contact_person" ON "contact_person"."company_id" = "company"."id" 
	WHERE (
		contact_person.entity_type = 'Contact Person' OR 
		contact_person IS NULL
	)
```

If i am were to create a similar query where I am using multiple persons :

```go
e := []models.Company
s.conn.Model(&e).
Column("company.*", "IndividualsInvolved").
WhereOr(
	pg.SQL("individual_involved.entity_type = ?", new(models.IndividualInvolved).GetType()),
	pg.SQL("individual_involved IS NULL"),
).
Select();
```
It just produces :
```sql
SELECT "company".*, "IndividualInvolved" 
	FROM "companies" AS "company" 
WHERE (
	individual_involved.entity_type = 'Individual Involved' OR 
	individual_involved IS NULL
	)
```

I have tested .where as well with the same result, without .whereOr the hasMany works nicely

**Comment by vmihailenco** [comment]
If the relation is `Company` has many `IndividualInvolved` then go-pg will produce 2 queries:
1. select companies
2. select inviduals for selected companies

So it looks like you are trying to add where clause to the 2nd query (`WHERE individual_involved.entity_type = 'Individual Involved'`). Currently this is not supported mainly because I am not sure about the syntax. So far the best idea I have is:

```go
companies := []models.Company
err := s.conn.Model(&companies).
    Column("company.*").
    Relation("IndividualsInvolved", func(q *orm.Query) *orm.Query {
        return q.WhereOr(
            pg.SQL("individual_involved.entity_type = ?", new(models.IndividualInvolved).GetType()),
            pg.SQL("individual_involved IS NULL"),
        )
    }).
    Select()
```

But that is relatively verbose...

**Comment by vmihailenco** [comment]
P.S. `pg.SQL("individual_involved IS NULL")` condition does not make any sense...

**Comment by LennartOlsen** [comment]
@vmihailenco i like your proposal, i like verbose 👍  (its kinda one of the key things about go?)

In regards to `pg.SQL("individual_involved IS NULL")` i added so that i would get my companies without any individuals involved as well

**Comment by vmihailenco** [comment]
Done in v4.7.3. See https://godoc.org/gopkg.in/pg.v4#example-DB-Model-HasMany for example.

>In regards to pg.SQL("individual_involved IS NULL") i added so that i would get my companies without any individuals involved as well

AFAIK that is not valid SQL. But anyway you will all companies by default.
