### ISSUE TITLE
BelongsTo relation with custom field name

### ISSUE THREAD

**Issue by roobre** [go-pg/pg#274]
I'm having a bit of trouble with 1:1 relationships. I have:

    type Entity struct {
		TableName struct{} `sql:"entities"`
	
		Id           int64
		Name         string
		Type         int16
		CreationDate time.Time `sql:"creation_date"`
	
		Address *Address `sql:"address_id"`
	}

And `Address` is a plain struct, of course also mapped to its table

However, the relation is not being detected, as I get: `panic: json: cannot unmarshal number into Go value of type servin.Address` when I try to `err := db.Model(&entity).First()`

How can I tell pg this filed is part of a relation?

Also, slightly unrelated, is there a list with all the available annotations? I'm having some other small problems, and it would be nice to have them, examples aren't always sufficient.

Regards.

**Comment by roobre** [comment]
Ok, I got around it, I was looking at "BelongsTo", but the right example was "HasOne".

Entity should look like:

	type Entity struct {
		TableName struct{} `sql:"entities"`
	
		Id           int64
		Name         string
		Type         int16
		CreationDate time.Time `sql:"creation_date"`
	
		Address   *Address
		AddressId int64
	}

And the correct instruction is: `err := db.Model(&entity).Column("entity.*", "Address").First()`, the second parameter to "Column" is the name of the field you want to fill, I suspect (it is not documented anywhere).

**Comment by vmihailenco** [comment]
`Model.Column` accepts a list of columns. It check each column and if there is a relation with same name go-pg selects data for that relation. If relation does not exist then column name is treated as SQL column name, i.e. it is escaped according to Postgres rules. So:
- "Address" is the relation name
- "entity.*" is SQL expression that selects all columns on table with alias `entity`

>I have no idea what the first parameter stands for, as nothing is named entity in lowercase neither in my DB nor in my object model.

go-pg will generate following query:

```
SELECT entity.* FROM entities AS entity
```

So:
- entities - table name
- entity - table alias
- entity.* - column name

**Comment by roobre** [comment]
Ok, it's pretty clear now. Thanks!
