### ISSUE TITLE
Specify field names in many2many relation

### ISSUE THREAD

**Issue by roobre** [go-pg/pg#275]
I have these two structures:

	type User struct {
		TableName struct{} `sql:"users"`
	
		Id           int64
		Login        string
		Password     string
		Email        string
		FirstName    string `sql:"first_name"`
		LastName     string `sql:"last_name"`
		LastLogin    string `sql:"last_login_date"`
		CreationDate string `sql:"creation_date"`
	
		Entities []Entity `pg:",many2many:_user_entities,joinFK:Sub"`
	}
	
	type Entity struct {
		TableName struct{} `sql:"entities"`
	
		Id           int64
		Name         string
		Type         int16
		CreationDate time.Time `sql:"creation_date"`
	
		Address   *Address
		AddressId int64
	}

Both are related using the `_user_entities` table.
This table has the following fields:

    CREATE TABLE _user_entities
    (
      user_id bigint NOT NULL,
      entity_id bigint NOT NULL,
      permissions smallint,
      -- constraints, etc

However, when querying the data using `db.Model(&user).Column("user.*", "Entities").First()`, it seems to be looking for `_user_entities.sub_id`:

    ERROR #42703 column _user_entities.sub_id does not exist:

Is there a way to specify these field name?

Again, a list with all the possible tags woudl be **greatly** appreaciated.

Regards

**Comment by vmihailenco** [comment]
I think you need to remove `,joinFK:Sub` from the tag.

>Again, a list with all the possible tags woudl be greatly appreaciated.

Okay, will try to do something about it.
