### ISSUE TITLE
HSTORE Support for structs?

### ISSUE THREAD

**Issue by jraede** [go-pg/pg#277]
Have you considered this? It would have to have only string keys of course, but it would save a few steps and would help with autocompletion, etc to have hstore values as structs vs map[string]strings.

**Comment by vmihailenco** [comment]
Hstore is a flat key/value structure that is useful when you need dynamic/unspecified number of keys. But structs have fixed/predefined number of fields. So I don't really understand why you want to use hstore with structs...

**Comment by vmihailenco** [comment]
Closing since there is no much interest in this and I still don't understand the big picture...
