### ISSUE TITLE
Question about date and time types

### ISSUE THREAD

**Issue by Bondza** [go-pg/pg#279]
Hello and thanks for an awesome package! I have a question about date and time types and how they are handled.

I was playing around with the nullable types from the `sql` package, but since I wanted to serialize the output from `pg` into JSON they did not really work that well for me. So I tried the [null package](https://github.com/guregu/null) which works as I'd like it to, i.e. missing columns are serialized as `null`. This works for all types except `null.Time`.  Which gives me an error:
```
null: cannot scan type []uint8 into null.Time: [50 48 49 54 45 48 55 45 50 49 32 49 56 58 48 55 58 48 57 46 53 54 50 51 48 52]
```
And the bytes are just the string returned from Postgresql, convert the bytes to a string and it reads `2016-07-21 18:52:02.425869` which is correct.

So I am wondering what's your thoughts about handling date and time types so that it would be compatible with the `null` package? I guess it would require parsing date and time columns to the appropriate type from the `time` package.
Or maybe there is an easier way to do this?

**Comment by vmihailenco** [comment]
Hi,

The preferred solution is to modify null package around https://github.com/guregu/null/blob/master/time.go#L19-L32 to accept `[]byte`. But that can be complicated since null package can't assume that time comes in Postgres format. So the practical solution would be to provide `NullTime` in go-pg...

**Comment by vmihailenco** [comment]
Added `pg.NullTime` and released v4.7.8. Hope it will work for you.

**Comment by Bondza** [comment]
Cool, Thanks! I looked around a bit further. So I tried using `NullTime` and then pointers like 

```go
type Data struct {
    ID int64
    CreatedAt *time.Time
}
```

Both ways should allow you get null when serializing it to JSON. I guess using `NullTime` looks a bit nicer than using pointers if you want this behaviour for all fields of a struct.

**Comment by vmihailenco** [comment]
Interesting! So probably I should remove NullTime and recommend everyone to use `*time.Time`...

**Comment by vmihailenco** [comment]
I think NullTime is still useful, because it handles `tm.IsZero()` case correctly. So I am going to keep it.

**Comment by Bondza** [comment]
It probably is nice to have. And maybe it's better to have these types so that you do not need use pointers for types like integers and floating point numbers?

**Comment by vmihailenco** [comment]
Probably, though `sql.Null*` are already fully supported.
