### ISSUE TITLE
Support TLS Client Certificates

### ISSUE THREAD

**Issue by flowhamster** [go-pg/pg#283]
Postgres allows clients to authenticate using TLS client certificates. The db.Options object should contain properties to specify a clients certificate and private key to use in the TLS handshake.

The TLS configuration should also not not skip verification (tls.InsecureSkipVerify = false).

**Comment by vmihailenco** [comment]
Hi,

What do you think about https://github.com/go-pg/pg/pull/284 ?

**Comment by flowhamster** [comment]
I was working on a similar PR. Yours looks great! Thank you.

**Comment by flowhamster** [comment]
Closing in favor of #284

**Comment by flowhamster** [comment]
I thought #284 was a ticket. Leaving this open until it is merged in.

**Comment by vmihailenco** [comment]
Released v4.7.7
