### ISSUE TITLE
Mapping fields

### ISSUE THREAD

**Issue by njspok** [go-pg/pg#304]
I use go-pg library and specify row in table "unit"

	type UnitModel struct {
		Id int
		Name string

		TableName struct{} `sql:"unit"`
	}

but table "unit" contains more then 2 fields and when i call

	var unit UnitModel
	err := db.Model(&unit).Where("id = ?", id).Select()

get error "pg: can't find column alter_name in model".
How specify ignore other fields in table "unit"? Call Column() method every time no good.

**Comment by vmihailenco** [comment]
Why not to define those columns in struct? Ignoring unknown columns can lead to subtle bugs because of typos in column names...

>Call Column() method every time no good.

Yeah, but selecting all columns when you need only one or two is not good practice too...

**Comment by njspok** [comment]
I do not need other fields and i want select only fields specified in struct. I have tables more than 80 fields and specify all them in struct very hard.

**Comment by vmihailenco** [comment]
Okay, I see. So you want to change generated query from

```
SELECT * FROM ...
```

to

```
SELECT id, name FROM ...
```

**Comment by njspok** [comment]
Yes. If model can contain `tableName` attribute, maybe she have opportunity mapping? Or by default if model not specify table field do nothing?

**Comment by vmihailenco** [comment]
Sorry, I don't understand the question. Feel free to post it in Russian.

>Or by default if model not specify table field do nothing?

By default table name is generated from struct name, e.g. `UnitModel` struct will have table name `unit_models`.

**Comment by njspok** [comment]
Maybe ignore situation when in db table has some filed but struct this field not specified?

**Comment by vmihailenco** [comment]
Please try v4.8.10. I think I fixed this issue.

**Comment by njspok** [comment]
Thanks!
