### ISSUE TITLE
pg: no rows in result

### ISSUE THREAD

**Issue by njspok** [go-pg/pg#310]
Table "units" contains only 100 records with id from 1 to 100.

``` go
    // case 1
    var unit Unit
    err := db.Model(&unit).Where("id = ?", 200).Select()
    // In this var err = "pg: no rows in result" and unit is {0  {}}
```

But if condition like this

``` go
    // case 2
    var unit []Unit
    err := db.Model(&unit).Where("id > 200").Select()
    // In this var err is "nil" and unit is []
```

Its normal? Maybe "case 2" err must be a "pg: no rows in result"?

``` go
    // case 3
    unit := []Unit{
        Unit{
            Id: 999,
        },
    }
    err := db.Model(&unit).Where("id > 200").Select()
    // err is "nil" and unit is [{999  {}}]
```

In "case 3" i can't understand what happens - no errors and unit var not rewrite. Maybe if unit var rewrite to empty []Unit or nil would be better (or err return "pg: no rows in result")?

P.S.

``` go
type Unit struct {
    Id int
    Name string
}
```

**Comment by vmihailenco** [comment]
The 1st and 2nd case work as intended. `pg.ErrNoRows` is needed to distinguish between no rows and row with zero/null values. Also it is usually very handy to return an error when you select 1 row.

3rd case requires fixing so after query slice has 0 elements.

**Comment by amonaco** [comment]
This would be nice if added to the documentation, since most developers will not expect "no rows" to be an error.
