### ISSUE TITLE
Auto creating tables for structures

### ISSUE THREAD

**Issue by aliksend** [go-pg/pg#313]
Can you implement a method to auto-create tables for structures? Something like that

``` go
type User struct {
    Id     int64
    Name   string
    Emails []string
}


func createSchema(db *pg.DB) error {
    err := db.CheckTable(&User{})
    return err
}
```

This method will look for table in database and will create it when didn't exists.
Also it can check every field: if field exist in struct but not exist in table – create it. 
For situation when field exists but has different type (or `null`/`not null`) it can just raise error to avoid data loss: for this migration recommend to use [go-pg/migrations](https://github.com/go-pg/migrations)

I think it will be very useful improvement: changes in struct will directly affect to database – changing name of struct, adding fields or changing it types will not go unnoticed.
Also it will help avoid redundancy: now we need to declare struct twice: when we directly declared it and when we created table – it may contribute to errors

**Comment by vmihailenco** [comment]
I've added basic functionality for creating tables in v5. It is only about creating tables from Go structs - I don't have plans to support migrations generation from structs diff, because it is very ambitions task :)

**Comment by aliksend** [comment]
Auto migrations implemented in [https://github.com/jinzhu/gorm](gorm), you can look how it done there. I would like do it myself, but I need help to understand codebase properly.

**Comment by vmihailenco** [comment]
You can start from https://github.com/go-pg/pg/blob/v5/orm/create_table.go#L21-L52 to see how to work with tables on go-pg side. But there is no any support to inspect tables in PostgreSQL.

Overall there are multiple ways to achieve what you want and gorm's way is not ideal, which is explained in docs

```
AutoMigrate will ONLY create tables, missing columns and missing indexes, and WON'T change existing column's type or delete unused columns to protect your data.
```

Obviously even with such restrictrion it is useful for you, but I would expect something more sophisticated :) For example, Django/Rails has different approach and it is more flexible. But it also requires more work...

**Comment by aliksend** [comment]
Rails approach is very good, but it is really big work. 
I've seen your merge and have some ideas. From your profile I know that you from Moldova. I'm from Ukraine. If you know Russian and can give your contacts, we can communicate in a more convenient form and post on github just most important things.

**Comment by vmihailenco** [comment]
Yeah, Russian is my native language. I guess we can try Slack? I am not sure what is the best way to use it, but you can PM me at https://gophers.slack.com. I also can join any other Slack channel if that makes more sense.

**Comment by aliksend** [comment]
Can you invite me to this channel? aliknoname@gmail.com

**Comment by vmihailenco** [comment]
It is open - just fill the form to get invite https://invite.slack.golangbridge.org/
