### ISSUE TITLE
Why can't use pg.Scan() in Model() inside?

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#316]
`pg.Scan()` now can only be used in the `Query()` and `QueryOne()` function, why can not use `pg.Scan()` in the `Model()`?

**Comment by vmihailenco** [comment]
AFAIK it was always like that, because `Select` accepts the same args as `Scan`:

```
var id int
db.Model(&Entry{}).Column("'1'").Select(&id)
fmt.Println(id) // 1
```

**Comment by dxvgef** [comment]
Thank you!
