### ISSUE TITLE
Model().Create() problem

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#317]
`&struct{}` has three fields, using `Model(&struct).Create()` to insert only two of the field, how to do?
I don't want to use ``sql:"-"``

**Comment by vmihailenco** [comment]
You can try `Model(&struct).Column("column1", "column2").Create()`

**Comment by vmihailenco** [comment]
Actually no, specifying columns to use in `INSERT` query is not supported. And adding support for `Column("column1", "column2")` is not possible, because it is used in `SelectOrCreate`:

```
_, err := db.Model(a).
	Column("id").
	Where("name = ?name").
	Returning("id").
	SelectOrCreate(&a.ID)
```

**Comment by dxvgef** [comment]
This feature will consider supporting it? About the same time `Model().Create()` and `Column()`.

**Comment by vmihailenco** [comment]
I can only think about adding `InsertColumn`, e.g. `db.Model(...).InsertColumn("col1". "col2").Insert()`. But that is kinda ugly...

Can you describe your use case in more details? I guess you don't have control of the structure you want to insert...

**Comment by dxvgef** [comment]
Field has been defined default value, and I hope these fields insert records ignored.
There are three solutions:
1. Use the `Exec()`
2. The default value is defined in the code, ignoring the default values defined by the table field
3. Make `Column()` on the `Insert()` Effective
But I am inclined to the third approach.

**Comment by vmihailenco** [comment]
Got you. The solution is to add `sql:",null"` flag on the field so insert query will generate `DEFAULT` value for such field. I am preparing pg.v5 that will have all field nullable by default.

**Comment by dxvgef** [comment]
You have the final say
