### ISSUE TITLE
error from pg.Options Addr

### ISSUE THREAD

**Issue by xpopit** [go-pg/pg#318]
error from pg.Options Addr

ash-3.2$ go run main.go                                                                                               
panic: runtime error: invalid memory address or nil pointer dereference                                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x219c]                                                   
                                                                                                                       
goroutine 1 [running]:                                                                                                 
panic(0x250560, 0xc42000c0e0)                                                                                          
        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1                                               
main.main()                                                                                                            
        /Users/xpop.it/gowork/work3/main.go:31 +0x15c                                                                  
exit status 2

**Comment by vmihailenco** [comment]
Can you provide full backtrace? That is not enough to figure out where panic occurres.
