### ISSUE TITLE
Feature Proposal: ORM PATCH support

### ISSUE THREAD

**Issue by chrisaxiom** [go-pg/pg#319]
@vmihailenco 

We are looking at adding support for partially updating a table (via the ORM) and returning the newly updated model (via `Returning("*")`)  Our goal is to utilize the ORM so that we do not have to write SQL to update the fields we want; this we feel will greatly speed up development and and iteration.

Example:

```
type Car struct {
    Id int
    TableName struct{} `sql:",alias:cars"`
    Make string
    Model string
    Doors int
}

type MakeModel struct {
    Id int
    TableName struct{} `sql:",alias:cars"` // same table as cars
    Make string
    Model string
}

// Doors will not be updated
res, err := db.Model(&makeModel).Returning("*", &car).Update()
```

or perhaps

`res, err := db.Model(&makeModel).Returning("*").Update(&car)`

Do you have any thoughts or suggestions before we implement this?

**Comment by vmihailenco** [comment]
I guess you know that following is already possible:

```
res, err := db.Model(&makeModel).Returning("*").Update()
```

or 

```
res, err := db.Model(&makeModel).Set("make = ?make").Returning("*").Update()
```

or

```
res, err := db.Model(&makeModel).Column("make").Returning("*").Update()
```

You can also prebuild queries if it makes sense

```
q = pg.Model().Column("make", "model")
res, err := q.Model(&car).Update()
```

If you are asking specifically for `Update(&car)` then I think it makes sense and should be relatively straighforward to implement.
