### ISSUE TITLE
Call to use $1, $2, $3... instead of ?

### ISSUE THREAD

**Issue by allochi** [go-pg/pg#333]
Hi,

This is just a question/suggestion, I hope it find its way in.

In my project I find myself many times use a `switch` to select a specific sql statement and then issue a db query using that command, the `where` conditions varies based on the user input, for example:

```go
switch {
	case params.ISO3 != "" && params.Year != 0:
		stmt = `SELECT * FROM records WHERE iso3=? and year=?`
	case params.ISO3 != "" && params.Year == 0:
		stmt = `SELECT * FROM records WHERE iso3=?`
	case params.ISO3 == "" && params.Year != 0:
		stmt = `SELECT * FROM records WHERE year=?`
	case params.ISO3 == "" && params.Year == 0:
		stmt = `SELECT * FROM records`
}

stmt += ` ORDER BY iso3, year;`

var data []models.Record
_, err = db.Query(&data, stmt, params.ISO3, params.Year)
if err != nil {
	log.Println(err)
}
```

The problem here is that `?` doesn't identify which variable I want to use in the `Query` like `$1, $2, $3...`, is this something that is already included in the library? going to?

Thanks a lot!

**Comment by vmihailenco** [comment]
Hi,

Did you consider using ORM? It could look like this:

```
var data []models.Record
q := db.Model(data).Order("iso3, year")
switch {
    case params.ISO3 != "" && params.Year != 0:
        q = q.Where("iso3=? and year=?", params.ISO3, params.Year)
    ...
}
err := q.Select()
```

**Comment by allochi** [comment]
Hi,

Thanks for your reply, this is what I'm doing now when there is a model-table relation, some queries are just too complicated for that. an example from today's work:

```sql
WITH _conflict AS(
	SELECT iso3 as c_iso3, geo_name as c_geo_name, total_displacement as c_total_displacement, new_displacement as c_new_displacement
	FROM data_platform.conflict
	WHERE year = ?
),
_disaster AS (
	SELECT iso3 as d_iso3, geo_name as d_geo_name, SUM(new_displacement) AS d_new_displacement
	FROM data_platform.disaster
	WHERE year = ?
	GROUP BY iso3, geo_name
),
_both AS (
	select * from _conflict as c
	FULL OUTER JOIN
	_disaster as d
	ON c_iso3 = d_iso3
)

SELECT
	COALESCE(c_iso3, d_iso3) AS iso3,
	COALESCE(c_geo_name, d_geo_name) AS geo_name,
	? as "year",
	c_total_displacement as conflict_total_displacement,
	c_new_displacement as conflict_new_displacement,
	d_new_displacement AS disaster_new_displacement
FROM _both;
```

This needs

```go
_, err = db.Query(&data, stmt, params.Year, params.Year, params.Year)
```

The query above is too complicated to be created in `ORM`, and If we used `$1` instead of `?`, we could in this case pass `params.Year` only once.

This is not stopping us from using your excellent package, and it's saving us a lot of time, this is just some feedback and a suggestion that comes from work.

Thanks again.

**Comment by vmihailenco** [comment]
Okay, I will see what I can do.

BTW you can write `WITH` queries with ORM:

```
subq := db.Model().Table("foo").Column("one", "two")
db.Model(&data).With("subq_name", subq).Select()
```

**Comment by allochi** [comment]
Cool, I will try that. Thanks!

**Comment by vmihailenco** [comment]
Oh, I forgot that go-pg supports named params! For example:

```
type Params struct {
    Foo string
    Bar int
}

func (p *Params) Rand() int {
    return rand.Int()
}

db.Query(..., "SELECT ?foo, ?bar, ?Rand", &Params{Foo: "hello", Bar: 42})
```

will produce query `SELECT 'hello', 42, 12345`. But the struct with named parameters should be the very last in params list.

**Comment by vmihailenco** [comment]
@allochi I've added support for indexed placeholders `?0, ?1, ?2` to v5 with example https://godoc.org/gopkg.in/pg.v5. Let me know if anything else is missing.

**Comment by allochi** [comment]
This is great, Thanks! I didn't know about named params, I changed my code to use it. Also excited about having indexed placeholders. Any estimated time for v5?

**Comment by vmihailenco** [comment]
I plan to release v5 in 1-2 weeks.
