### ISSUE TITLE
Is there a way to turn on tcpKeepAlive=true for long-running queries?

### ISSUE THREAD

**Issue by jbeemster** [go-pg/pg#342]

**Comment by vmihailenco** [comment]
I think I can add something to pg.v5 depending on how important this is. Did you consider closing idle connections with `IdleTimeout=5*time.Minute`?

**Comment by jbeemster** [comment]
Hi @vmihailenco it is quite important as we see quite a few queries fail if they run for too long, these queries are normally being run through a NAT instance also which might contribute to the issue.

I had not considered that no as we only open up the connection (and the application) when we need it so there should never be any dangling connections lying around.

**Comment by vmihailenco** [comment]
@jbeemster do you know any reasons to not enable keep alive on all TCP connections? I.e. why go-pg user can decide to disable keep alive...

**Comment by jbeemster** [comment]
I cannot see why you would want to disable, as soon as you are finished the connection ends anyway so it seems like the safest option.  However having the choice over a feature is something that people tend to like, and while I might not be able to come up with a use case I am sure one must exist!

**Comment by vmihailenco** [comment]
Also did you consider setting keep alive on server side? http://stackoverflow.com/questions/2166872/how-to-use-tcp-keepalives-settings-in-postgresql

**Comment by vmihailenco** [comment]
Or that will only close server-side connection I guess? :)

**Comment by vmihailenco** [comment]
I think I addressed this in v5 via `Dialer`:

```
pg.Connect(&pg.Options{
    Network: "tcp",
    Addr: "1.1.1.1:5432",
    Dialer: func(network, addr string) (net.Conn, error) {
        cn, err := net.DialTimeout(network, addr, 5*time.Second)
        if err != nil {
            return nil, err
        }
        return cn, cn.(*net.TCPConn).SetKeepAlive(true)
    },
})
```

Let me know if that is not enough.

**Comment by jbeemster** [comment]
Hey @vmihailenco, thanks for adding that!  Will get it implemented and see if it resolves the issues we were seeing.  Thanks again!
