### ISSUE TITLE
hasMany with inner join?

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#343]
Following up https://github.com/go-pg/pg/issues/266#issuecomment-228323717
> In regards to pg.SQL("individual_involved IS NULL") i added so that i would get my companies without any individuals involved as well

As far as I can tell there is currently no way to do relations in such a way that only rows which have relations are returned. I believe I am left to do post-processing in Go to achieve this. Is this correct?

**Comment by vmihailenco** [comment]
Well, you can add some relativately complex SQL to achieve this, e.g.

```
db.Where("EXISTS (SELECT 1 FROM subtable WHERE subtable.id = table.id)")
```

to filter such items at SQL level. So far I don't see what go-pg should do here.

**Comment by matthewvalimaki** [comment]
@vmihailenco this works. Thank you.
