### ISSUE TITLE
Upgrading from v3 to v5: how to mimic `SSL: true` behaviour with TLSConfig

### ISSUE THREAD

**Issue by jbeemster** [go-pg/pg#349]
During the upgrade I noticed that the SSL option has been deprecated in favour of the TLSConfig, I was wondering if you had a sample config that would mimic the now removed feature.

**Comment by vmihailenco** [comment]
Previous code used following config:

```
&tls.Config{
	InsecureSkipVerify: true,
}
```

See https://github.com/go-pg/pg/pull/284/files and linked issue
