### ISSUE TITLE
Ability to insert/update with DEFAULT instead of NULL

### ISSUE THREAD

**Issue by ababo** [go-pg/pg#350]
If I have a table with `created TIMESTAMP WITH TIMEZONE DEFAULT current_timestamp` I would like just not to fill `Created` field with `time.Now()` when creating a new object.

**Comment by vmihailenco** [comment]
In pg.v4 you need to add `,null` tag:

```
    Created time.Time `sql:",null"`
```

In pg.v5 this is default behaviour. But this only works for insert. I don't see how it could work with update.

**Comment by ababo** [comment]
You're right, thanks.

**Comment by ababo** [comment]
Should I use v5 for a new project, or it isn't mature enough?

**Comment by vmihailenco** [comment]
I think you should use pg.v5. It will be released soon and I don't plan to break APIs.

**Comment by ababo** [comment]
Thank you.
