### ISSUE TITLE
How specify schema in queries?

### ISSUE THREAD

**Issue by njspok** [go-pg/pg#351]
I may specify db schema in `TableName` (example, `TableName struct{} 'sql:web.user'`) field model, but this case not convenient. Im use same models for different schemes. Solve - when create connection make query `db.Exec("SET SCHEMA web")`, but... application lost connection to db and you library reconnect? If so, query `SET SCHEMA` not execute again.
How i can specify schema for connection?

**Comment by vmihailenco** [comment]
I think the easiest way for you is to define separate struct for each schema. If number of schemas is not big that may work for you. E.g.

```
type User struct {}

type WebUser struct {
    TableName struct{} 'sql:web.user'
    Base
}
```

For https://github.com/go-pg/sharding I wrote a wrapper for DB that adds some named placeholders that can be used in queries and/or table name - https://github.com/go-pg/sharding/blob/v4/shard.go#L29-L30. You could do something like that too.

**Comment by njspok** [comment]
Sorry, i find how specify schema when connection create. Work if reconnect.
```go
	params := make(map[string]interface{})
	params["search_path"] = "myschema"

	return pg.Connect(&pg.Options{
		User:     // user
		Database: // db
		Password: // pass
		Addr:     //addr
		SSL:      false,
		Params:   params, // this!
	})
```

**Comment by vmihailenco** [comment]
I would not recommend you to go that way, because you will need separate *DB and pool of connections for each schema. That is not practical.

**Comment by mkozjak** [comment]
@vmihailenco: what if the number of schemas is huge? ie., in huge multitenancy systems..

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/sharding

**Comment by mdere** [comment]
@vmihailenco - so following your example (While I am learning golang)

How does

```
type User struct {}

type WebUser struct {
    TableName struct{} 'sql:web.user'
    Base
}
```

Fit into a query example?

**Comment by vmihailenco** [comment]
This is closed and I can't guess what do you mean.

**Comment by vmihailenco** [comment]
I am using https://github.com/go-pg/sharding/blob/master/cluster.go#L70-L75.

There is also `OnConnect` hook that allows to execute arbitrary queries.

**Comment by j0hnwhyte** [comment]
Ah yes, that's what I was looking for. I was using `_, _ = b.Db.Exec(`set search_path=?`, ctx.SchemaName)` right now as a workaround. I saw a previous version of the code that mentioned the `Param` attribute, this must be its substitute.

Thanks

**Comment by j0hnwhyte** [comment]
After some testing it seems that it's not working properly. Maybe we're talking about different things?

I tried using this code to setup the database:
```go
	b.Db = pg.Connect(pgopt).
		WithParam("search_path", ctx.SchemaName)
```

and queries seemed to ignore the schema prefix. Using my workaround turned out to be good:
```go
	_, _ = b.Db.Exec("set search_path=?", ctx.SchemaName)
```

I'll just continue using it. Hope this is useful

**Comment by j0hnwhyte** [comment]
Testing found out that this works initially and then it forgets it's working in a separate schema. Maybe it's due to connection pooling. None of the mentioned solutions work, should I open a new issue?

**Comment by j0hnwhyte** [comment]
For future readers (like myself clicking the same links), the problem is solved by putting the `set search_path` in the `OnConnect` method, like this:

```go
pgopt := &pg.Options{
		Addr:     fmt.Sprintf("%s:%d", b.Config.Host, b.Config.Port),
		User:     b.Config.User,
		Password: b.Config.Pass,
		Database: b.Config.Database,
		OnConnect: func(conn *pg.Conn) error {
			_, err := conn.Exec("set search_path=?", ctx.MaxSchemaName)
			if err != nil {
				b.log.Error(err.Error())
			}
			return nil
		},
	}
```

**Comment by bmulder-innoseis** [comment]
> For future readers (like myself clicking the same links), the problem is solved by putting the `set search_path` in the `OnConnect` method, like this:

@john8329 so it is not possible to switch schemas during program execution unless you reconnect? In a connection pooled application, this would pose a problem, since all connections would need to be closed and opened again.

**Comment by john8329** [comment]
@bmulder-innoseis I guess you could just execute the `SET search_path` command again, but then you have to be really careful about reverting it back to the original schema, since the connection (with that contextual schema) might be reused. In my use case it's for dedicating separate schemas to application modules, if you need to switch them frequently I'd suggest explicitly declaring them in your queries.

**Comment by bmulder-innoseis** [comment]
@john8329 all right, but how do you specify them in the queries without having to write raw manual SQL queries?

**Comment by john8329** [comment]
@bmulder-innoseis Ah, you mean the query builder? I rarely use it, it's so confusing. I think you can specify names that include the schema or use something like `ColumnExpr` to get closer to SQL. I haven't tested it much unfortunately.

**Comment by bmulder-innoseis** [comment]
in the example on the front page:
```go
    // Select all users.
    var users []User
    err = db.Model(&users).Select()
    if err != nil {
        panic(err)
    }
```
for instance, how can I now select all users from the "Foo" schema?

**Comment by john8329** [comment]
_maybe_ you can specify the schema in the table name you have in your model, but no idea if it works. The ORM is limited here.

**Comment by bmulder-innoseis** [comment]
it seems to me that this table name is either deduced from the class name using reflection and therefore hardcoded
or using struct tags (e.g. ``TableName struct{} `sql:"custom_table_name"` ``), which is also hard-coded.

So this means multi-tenant systems will need to write all SQL queries manually and the ORM is useless there.

**Comment by john8329** [comment]
...or use multiple ORM instances by creating more than one connection.
```go
db1 := pg.Connect(pgopt1) // Set schema in OnConnect
db2 := pg.Connect(pgopt2) // Same with different schema
```
