### ISSUE TITLE
Problem with recognizing joins

### ISSUE THREAD

**Issue by ababo** [go-pg/pg#352]
I try to get collect all nodes which have access records with a given UserID and compatible permission mask.

This is my data schema:

```go
type node struct {
	ID     string
	Users  []userNodeAccess
}

type userNodeAccess struct {
	UserID      string
	NodeID      string
	Node        *node
	Permissions uint
}

func (s *server) findAccessibleNodes(
	userID string, permissions uint) ([]node, error) {
	nodes := []node{}
	err := s.db.Model(&[]node{}).
		Column("node.*", "Users").
		Where("user_id = ?", userID).
		Where("permissions & ? = ?", permissions, permissions).
		Select(&nodes)
	return nodes, err
}
```
As result `pg` generates the following joinless  query:

```sql
 SELECT "node".*, "Users" FROM "nodes" AS "node" WHERE (user_id = '94787eb0-e32c-4b7d-b88c-b231247178e8') AND (permissions & 1 = 1)
```
Why the join recognition is so unreliable? Or maybe I got it wrong?

**Comment by ababo** [comment]
Updated as following:
```go
type user struct {
	ID          string
	Nodes       []userNodeAccess `sql:"-"`
}

type userNodeAccess struct {
	UserID      string
	User        *user
	NodeID      string
	Permissions uint
}

func (s *server) findAccessibleNodes(
	userID string, permissions uint) ([]node, error) {
	users := []user{}
	err := s.db.Model(&[]user{}).
		Column("user.*", "Nodes").
		Where("id = ?", userID).
		Where("permissions & ? = ?", permissions, permissions).
		Select(&users)
	return nil, err
}
```
As result `pg` generates the following joinless  query:

```sql
SELECT "user".*, "Nodes" FROM "users" AS "user" WHERE (id = '94787eb0-e32c-4b7d-b88c-b231247178e8') AND (permissions & 1 = 1)
level=error msg=aaaaa err="ERROR #42703 column \"Nodes\" does not exist (addr=\"[::1]:5432\")"
```

Why the join recognition is so unreliable? Or maybe I got it wrong?

**Comment by vmihailenco** [comment]
My first guess is that you need to export your structs:

```
type Node struct {
    ID     string
    Users  []UserNodeAccess
}

type UserNodeAccess struct {
    UserID      string
    NodeID      string
    Node        *Node
    Permissions uint
}
```

Can you try it?

**Comment by ababo** [comment]
Still doesn't join.
```sql
SELECT "node".* FROM "nodes" AS "node" WHERE (user_id = '94787eb0-e32c-4b7d-b88c-b231247178e8') AND (permissions & 1 = 1)
```
It seems to be a bad practice trying to guess what kind of query ORM will generate in every non-trivial case...

**Comment by vmihailenco** [comment]
Are you sure that there is no 2nd query that selects `UserNodeAccess`?

**Comment by ababo** [comment]
Yes.

**Comment by vmihailenco** [comment]
go-pg here generates 2 queries that
1. select all nodes
2. select all users for every node selected at step 1)

But apparently you expect a `JOIN` so you can filter nodes by user_id and permissions. You can do it manually:

```
db.Column(...).Join("JOIN user_node_accesses ON ...").Where(...)
```

Probably at some point go-pg will support something like this `db.Column(...).JoinRelation("Users").Column(...)`

**Comment by ababo** [comment]
After using `gorm` and trying `pg` I think I've realised that SQL are unavoidable, otherwise I need to guess what SQL will be generated for every non-trivial query (so I'll be obliged to know two languages instead of one: (DSL of the chosen ORM, i.e. how does it map to SQL + SQL itself). Therefore I'd rather use `reform` which doesn't support joins by design. Anyway, thanks for your help.
