### ISSUE TITLE
save struct to type hstore / json

### ISSUE THREAD

**Issue by dieuit07** [go-pg/pg#354]
Hi everyone, I stuck with save type hstore with struct

```
type Event struct {
	TableName struct{} `sql:"events,alias:event"`
	Id        int64
	Rawdata   json.RawMessage `json:"rawdata"`   // hstore type in pg
}

type ModelB struct {
      FieldA   string     `json:"fieldA"`
      FieldB   int64     `json:"fieldB"`
}

type ModelA struct {
      ModelBs   []ModelB     `json:"model_bs"`
}

newEvent := Event{Rawdata:   ModelA}
```

=> ERROR: %!(EXTRA internal.PGError=ERROR #XX000 Unexpected end of string (addr="127.0.0.1:5432")

**Comment by vmihailenco** [comment]
Hi,

go-pg only supports mapping hstore to map[string]string. Can you use json/jsonb instead of hstore?

**Comment by dieuit07** [comment]
It work now. Thanks so much @vmihailenco  ;)
