### ISSUE TITLE
ST_GeomFromGeoJSON create parse error (postgis)

### ISSUE THREAD

**Issue by g3gurung** [go-pg/pg#355]
`building.Geom = "ST_GeomFromGeoJSON('{"type":"Point","coordinates":[25.467152,65.0135608]}')"`

`err := db.Create(&building)`

`if err != nil { panic(err)}`

this throws the error 

>  ERROR #XX000 parse error - invalid geometry 

---------------------------------------

but this plain sql query works fine

```
INSERT INTO building(geom) VALUES (ST_GeomFromGeoJSON('{"type":"Point","coordinates":[25.467152,65.0
135608]}'));
```

Help please!!

**Comment by vmihailenco** [comment]
go-pg escapes your query like this:

```
INSERT INTO building(geom) VALUES ('ST_GeomFromGeoJSON(''{"type":"Point","coordinates":[25.467152,65.0
135608]}'')');
```

Can you try to change `Geom` field type from string to types.Q:

```
type Building struct {
    Geom types.Q
}
```

?

**Comment by g3gurung** [comment]
yes that did the trick thanks....

also this doc helped too [https://godoc.org/gopkg.in/pg.v4#example-Q]

Thanks again!

**Comment by vmihailenco** [comment]
You are welcome.
