### ISSUE TITLE
There is a problem with the group() function

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#361]
I have three fields **`"id, item_name, user_id"`** in the **`"t"`** table, I want to get the result of **`"group by user_id"`**, I try to use **`"Model().Group("user_id")"`**, But the automatically generated SQL string is wrong:
**`SELECT "t"."id", "t"."item_name", "t"."user_id" FROM "t" AS "t" GROUP BY user_id`**

The correct should be like this:
**`SELECT DISTINCT ON (user_id) * from t`**

I used the `Query()` function to temporarily work around this problem, but I wanted to fix the problem with the `Model().Group()` function.
Thank you for developing this package! I really like it!

**Comment by vmihailenco** [comment]
Did you try:

```
Model().ColumnExpr("DISTINCT ON (user_id) *").Group("user_id")
```

? I don't think go-pg should do that automagically :)

**Comment by dxvgef** [comment]
The problem is solved, thank you!
