### ISSUE TITLE
Delete with Returning

### ISSUE THREAD

**Issue by Kay-Zee** [go-pg/pg#366]
I've noticed that the `ORM` does not support `Returning()` with `Delete()`, at least that's my assumption looking [here](https://github.com/go-pg/pg/blob/v4/orm/delete.go#L19-L21) would it be possible to add Returning for Delete queries?

**Comment by vmihailenco** [comment]
Sure, fixed in v4.9.5

**Comment by Kay-Zee** [comment]
The Debug query now shows `Returning *`, but the model never receives the data. I've changed the `Delete` function @ https://github.com/go-pg/pg/blob/v4/orm/query.go#L495 locally to resemble the Update function:

```
func (q *Query) Delete(values ...interface{}) (*types.Result, error) {
	if q.err != nil {
		return nil, q.err
	}

	model, err := q.newModel(values)
	if err != nil {
		return nil, err
	}

	return q.db.Query(model, deleteQuery{q}, q.model)
}
```

and now it works for my use-case.

**Comment by jack-chung** [comment]
What is the right way to use Returning with Delete?
I'm trying to retrieve the list of deleted IDs into an int slice.
```
var deletedIDs []int64
result, err = tx.Model(&MyTable{}).Where("col1 = ?", col1Val).Returning("id", deletedIDs).Delete()
```
The query was generated correctly with RETURNING id, but the slice was not populated. I have checked that RowsAffected() is > 0.

**Comment by vmihailenco** [comment]
I guess what @Kay-Zee [wrote](https://github.com/go-pg/pg/issues/366#issuecomment-254272801) is right and this needs to be fixed. You will need to upgrade to master though :)

**Comment by jack-chung** [comment]
I think I used it wrong even if the fix is there.
Looking at it closer now, I believe the second parameter to Returning() is for input not output, right?
The output should be a parameter to Delete(), which isn't supported in the version I have. Did I get that right?

I'm not quite ready to move to master yet. I think I'm going to use raw sql for now.

**Comment by vmihailenco** [comment]
Yeah, query should be following:

```
var deletedIDs []int64
result, err = tx.Model(&MyTable{}).Where("col1 = ?", col1Val).Returning("id").Delete(&deletedIDs)
```
