### ISSUE TITLE
About the pg.v5

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#370]
Hello! May I ask pg.v5 is now a stable version? Can it be used in a production environment? Compared to the v4 version of what features and performance improvements?

**Comment by vmihailenco** [comment]
Hello,

I hope to release it this week so I hope it is stable :) I tried to document important changes in https://github.com/go-pg/pg/blob/v5/CHANGELOG.md .

**Comment by dxvgef** [comment]
Thank you for your work!
