### ISSUE TITLE
Master/Slave queries

### ISSUE THREAD

**Issue by njspok** [go-pg/pg#372]
Will there be the opportunity specify master-slave server and read from slave, write - only master?

**Comment by vmihailenco** [comment]
If you know how to automatically detect read only queries - yes. Simply checking for `SELECT` is not enough, because `SELECT custom_function()` can do writes.

In my projects I just have 2 database instances which I use accordingly

```
db.Query() - for write
readonlyDB.Query() - for read-only queries
```

**Comment by joeky888** [comment]
In the real-life use cases, I use `gorm` on Master, and `go-pg` on read-only Slave replications. Both are great. Note that `gorm` has some handy functions like `Automigrate()` and automatically updates the `updated_at` column while `go-pg` can do some complex SQL selections.

So basically the code looks like this:

```go
type Orm struct {
	MasterGorm *gorm.DB
	SlavePg    *pg.DB
}

type BaseModel struct {
	ID        int64          `pg:",pk" gorm:"primarykey"`
	CreatedAt time.Time      `pg:"default:now()" gorm:"default:now()"`
	UpdatedAt time.Time      `pg:"default:now()" gorm:"default:now()"`
	DeletedAt gorm.DeletedAt `pg:",soft_delete" gorm:"index"`
}

type User struct {
	BaseModel
	Name  string `pg:"type:varchar(50),notnull" gorm:"type:varchar(50);not null"`
	Trees string `pg:"type:ltree,unique,notnull" gorm:"type:ltree;uniqueIndex;not null"`
}

// In case I need to use go-pg on Master, I will need to export go-pg orm to raw SQL query then use gorm.Exec() to use it
// See https://stackoverflow.com/questions/57973171
func (o *Orm) pgQueryString(query *orm.Query) (string, error) {
	queryString, err := query.AppendQuery(orm.NewFormatter(), nil)
	return string(queryString), err
}
```
