### ISSUE TITLE
Why not join the awesome-go list?

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#373]
go-pg is a great PostgreSQL driver, but why not add it to the [awesome-go](https://github.com/avelino/awesome-go) list?

**Comment by vmihailenco** [comment]
We should (I think) but the reason is that awesome-go is just a list that does not help you to chose a package by describing strong and weak points of the library. So TBH I don't see how it is better than similar list provided by your favorite search engine...

**Comment by dxvgef** [comment]
But add to this list will increase the go - pg number of users, there will be more people to help improve it.

**Comment by vmihailenco** [comment]
Done.
