### ISSUE TITLE
Support for setting model's table dynamically

### ISSUE THREAD

**Issue by serg472** [go-pg/pg#377]
Currently it's not possible change a table name of a model dynamically, it is either autoguessed from the model name or defined inside `model.TableName`. This makes it impossible to work with multiple temporary tables of the same structure through ORM.

```
type MyModel struct {
    TableName struct{} `sql:"temp_table1"`
    Id              int64
    Name            string  
}

var mymodels []MyModel
err := db.Model(&mymodels).Column("mymodel.id", "mymodel.name").Select()
```

Now if those temp tables are dynamically created the only choice seems to be using raw queries to query them.

Thanks.

**Comment by vmihailenco** [comment]
Did you try:

```
err := db.Model(&mymodels).Table("temp_table_999").Alias("mymodel").Column("mymodel.id", "mymodel.name").Select()
```

**Comment by serg472** [comment]
Thanks for the quick response, this generates the following sql (not what I need):

	SELECT "mymodel"."id", "mymodel"."name" FROM "mymodels" AS "mymodel", temp_table_999 AS mymodel

**Comment by vmihailenco** [comment]
This should work I think:

```
err := db.Model().TableExpr("temp_table_999 AS mymodel").Column("mymodel.id", "mymodel.name").Select(&mymodels)
```

But yeah, we need a better solution...

**Comment by serg472** [comment]
Thanks, this worked.

**Comment by themrxcm** [comment]
How do I write data into a table, the name of which I do not know in advance? The table is created on the server node j, after I transfer the name of the table to the server GO and there it is necessary to write the data into the already created table. How to do it? Why can not you simply transfer the name of the table and the necessary data for the record to here http://docs.sequelizejs.com/manual/tutorial/instances.html#working-in-bulk-creating-updating-and-destroying-multiple-rows-at-once-
