### ISSUE TITLE
v5 WhereOr and SQL missing

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#379]
Where did `Query.WhereOr` and `pg.SQL` go? They're still both mentioned in the readme.

**Comment by vmihailenco** [comment]
Both gone since API was too specialized and code was not much cleaner. I recommend to use:

```go
db.Where(
    "foo = ? OR"+
    "hello = ?",
    "bar", "world",
)
```

in those rare cases you need it.

PS Readme updated - thanks.
