### ISSUE TITLE
BeforeSelectQuery hook

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#380]
Continuing related discussion https://github.com/go-pg/pg/issues/276#issuecomment-244544789 I would propose `BeforeSelectQuery` to be implemented. If implemented perhaps the other verbs should be implemented as well, but for those I do not have strong opinion right now.

Sub selects is an example of a use case for `BeforeSelectQuery`. For example if you have relational tables from which you want to select, say count of rows, this feature would be extremely beneficial. While one can certainly just do those sub selects when the model is instantiated it does not quite work if instantiation happens in multiple locations or if the sub selects should be in Relation query.

**Comment by vmihailenco** [comment]
Sorry, I don't follow. Can you provide some example how this is supposed to work?

**Comment by matthewvalimaki** [comment]
First let me correct myself and I say that instead of Relation I meant Column with relations. For example Column("a.*", "b", "a.b").

Example schema and manual query:
```
CREATE TABLE a (
  id SERIAL PRIMARY KEY
);

CREATE TABLE b (
  id SERIAL PRIMARY KEY,
  a_id INTEGER REFERENCES a,
  status BOOLEAN DEFAULT FALSE
);

SELECT a.id, (SELECT COUNT(*) FROM b WHERE b.a_id = a.id AND status = true) AS status_true_count
FROM a;
```
I am proposing that with `BeforeSelectQuery` I would be able to make that sub select possible without having to do `ColumnExpr` and more importantly if table a is part of a more complex setup where I use Column(...,"d.a.b.c") it would really be helpful.

**Comment by vmihailenco** [comment]
But why you want to do that with `BeforeSelectQuery`? That will add `Count` query to every query on model `A` which I think is not what most users want. Much more flexible solution is to write small helper function:

```
func countQuery(q *orm.Query) (*orm.Query, error) {
    q = q.columnExpr(`(SELECT COUNT(*) FROM b WHERE b.a_id = a.id AND status = true) AS status_true_count`)
    return q, nil
}

db.Model(a).Apply(countQuery).Select()
```

What do you think?

**Comment by matthewvalimaki** [comment]
@vmihailenco thank you for the thoughtful comment.
> But why you want to do that with BeforeSelectQuery?

I have a use case where relations are dynamically assigned. At the time of query other than doing string matching I do not know if table `A` is involved or not. Also the real table `A` has multiple foreign keys therefore complicating my challenge to always provide `Count`. In my use case `Count` serves as metadata that has to be always present.

> Much more flexible solution is to write small helper function:

I looked at using `Apply` but I did not see a way for me to do if-clause to check if my table `A` is there.

**Comment by matthewvalimaki** [comment]
@vmihailenco I'll close this issue if you are not going to implement requested BeforeSelectQuery.
Could you consider implementing it regardless of my use case?

**Comment by vmihailenco** [comment]
It is possible, though it would be a big change that requires some thinking/planning and working. So far I don't see a big potential in this feature...

**Comment by matthewvalimaki** [comment]
Understood. I shall close this issue.
