### ISSUE TITLE
Foreign table and non-existing columns

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#381]
It would be nice to have a tag or some other way to control if column is to be included into query based on database. For example with foreign table one might want to drop irrelevant columns but still use the same model. Of course model can always be copied with unnecessary columns removed.

**Comment by vmihailenco** [comment]
If you want to select only existing columns you can use `db.Model(&Model{}).Column("model.*")`. It is also possible to add something like `SkipField("Foo")` which will skip struct field, but I am reluctant to add new API for such rare case.

**Comment by matthewvalimaki** [comment]
@vmihailenco thank you for the comments. I have overcome my challenge by simply creating a new reduced version of the model.

The two options you mentioned would not have worked for me as what I was going after was more automatic way of knowing when not to use certain columns. For example:
Following table exists in database A and B as foreign table.
```
type TableA struct {
TableName struct{} `sql:"table_a"`
ID int
Name string
Email string `pg:",db:a"`
}
```
When building query pq would have checked against current database and if they did not match then automatically exclude the column.
