### ISSUE TITLE
Doc: name conventions for default table names, aliases, snake_cased column names, etc

### ISSUE THREAD

**Issue by jeromenerf** [go-pg/pg#393]
I could not find in the documentation the default naming conventions for the table and column names.

IIUC, for a given `User{ID int64, FirstName string}` model, the expected table name should be `users` with `id` and `user_name`. 

However, `go-pg` use singular (vs. plural) aliases, so adding a WHERE clause on User.UserName and SomeJoinedTable.SomeProperty requires us to write `"user".user_name` and `"somejoinedtables".some_property`. 

There is no bug there but maybe a need for documentation to clarify the rationale?

**Comment by vmihailenco** [comment]
I think I addressed this in https://github.com/go-pg/pg/pull/411/files. Sorry for late response.
