### ISSUE TITLE
Rotate connection in connection pool

### ISSUE THREAD

**Issue by viblo** [go-pg/pg#397]
I want to rotate the connection in the connection pool. Now its handled in a first in - last out order, so that the first connection created will almost never be recycled, while some that are only used to handle peak requests can be closed fairly quickly. I think it would make sense to make this first in - first out order instead.

(The downside as I see it is a little bit more complicated code, and a little performance cost. But I definitely think its worth it. This is how auto-scaling in AWS works for example)

The reason why this could help is that we have a HA Proxy between our go code and a pg bouncer instance. Sometimes we want to update some setting in this HA Proxy. HAProxy will then keep connections that are alive running in its old "instance/config", while any new connections are handled by the new config. If some connections are never unused they will use the old settings forever, which instead requite restart of our go code which we want to avoid, both for uptime but also for easier management, we have 100+ go instances talking to the database.

**Comment by vmihailenco** [comment]
It is first in - first out:
- https://github.com/go-pg/pg/blob/v5/internal/pool/pool.go#L199 - Put appends free conn to the list
- https://github.com/go-pg/pg/blob/v5/internal/pool/pool.go#L134-L135 - Get takes last connection from the list

You can also set `Options.IdleTimeout = 15*time.Minute` so unused connections are closed if they were not used for 15 minutes.

**Comment by viblo** [comment]
Ah, I see. Thanks! (We currently use v3, but it seems to have the same behavior.)
Then it must be something else in our setup that create the issues we have, we should have IdleTimeout set as well...
I will just close this issue.
