### ISSUE TITLE
I can't get models & associations to work.

### ISSUE THREAD

**Issue by macnibblet** [go-pg/pg#398]
I'm trying to query recordings and eager load all the images (e.g left join)

Model definitions 
```go
type RecordingEntity struct {

	TableName struct{} `sql:"recordings,alias:recording"`

	Uuid        uuid.UUID `sql:",pk" json:"uuid"`
	ExternalId  uint64    `sql:",notnull" json:"externalId"`
	//PerformerId uuid.UUID `sql:",notnull" json:"performerId"`

	StageName string `json:"stageName"`

	StorageServer string `json:"storageServer"`
	StoragePath   string `json:"storagePath"`

	ViewCount uint `json:"viewCount"`
	LikeCount uint `json:"likeCount"`

	BitRate  uint16 `json:"bitRate"`
	Duration uint16 `json:"duration"`

	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`

	Images []*RecordingImage `json:"images"`
	Performer *PerformerEntity
}

type RecordingImage struct {
	TableName struct{} `sql:"recording_images,alias:images"`

	Uuid        uuid.UUID `sql:",pk" json:"uuid"`
	ExternalId  uint64    `json:"externalId"`
	RecordingId uuid.UUID `json:"recordingId"`

	MainImage bool `json:"mainImage"`

	StorageServer string `json:"storageServer"`
	StoragePath   string `json:"storagePath"`

	CreatedAt time.Time `json:"createdAt"`
}
```

The Query
```go
recording := new(entities.RecordingEntity)

err := r.DB.Model(recording).Column("recording.*", "Images").Where("recording.uuid = ?", id).Select()
```

The SQL generated
```sql
SELECT "recording".*, "Images" FROM recordings AS recording WHERE (recording.uuid = '313843ba-efc9-4797-acc9-c2e52b67a126')
```

So as you can see, it's thinking `Images` is a column and not loading the actual association.

**Comment by vmihailenco** [comment]
This is has-many relation: RecordingEntity has-many RecordingImage. For has-many relation go-pg generates 2 SQL queries:
- first loads RecordingEntity
- second loads RecordingImage

But to make it work you need to rename `RecordingId` to `RecordingEntityUuid` so field name consists of model name + pk name. Otherwise go-pg has no chances to guess foreign key in RecordingImage.

**Comment by macnibblet** [comment]
I see, but that makes for some extremely unwieldy column names, any chance it would be possible to configure the column names used ?

**Comment by vmihailenco** [comment]
You can also try rename `RecordingId` to `RecordingUuid` and add `foreignKey` tag:

```
Images []*RecordingImage `json:"images" pg:",fk:Recording"`
```

**Comment by macnibblet** [comment]
I removed all the `entity` suffixes I had and renamed all `id` suffixes to `uuid` so it almost works now, I can query all the images, but trying to add a `belongsTo` seams to cause it to crash.

```SQL
SELECT
  "recording".*,
  performer."uuid"            AS "performer__uuid",
  performer."external_id"     AS "performer__external_id",
  performer."origin_service"  AS "performer__origin_service",
  performer."origin_section"  AS "performer__origin_section",
  performer."stage_name"      AS "performer__stage_name",
  performer."aliases"         AS "performer__aliases",
  performer."recording_count" AS "performer__recording_count",
  performer."updated_at"      AS "performer__updated_at",
  performer."created_at"      AS "performer__created_at"
FROM
  recordings AS recording
LEFT JOIN
  performers AS performer ON performer."uuid" = recording."performer_uuid"

```

Models
type Recording struct {
	TableName struct{} `sql:"recordings,alias:recording"`

	Uuid          uuid.UUID `sql:",pk" json:"uuid"`
	ExternalId    uint64    `sql:",notnull" json:"externalId"`
	PerformerUuid uuid.UUID `sql:",notnull" json:"performerId"`

	StageName string `json:"stageName"`

	StorageServer string `json:"storageServer"`
	StoragePath   string `json:"storagePath"`

	ViewCount uint `json:"viewCount"`
	LikeCount uint `json:"likeCount"`

	BitRate  uint16 `json:"bitRate"`
	Duration uint16 `json:"duration"`

	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`

	Images    []*RecordingImage `json:"images"`
	Performer *Performer
}

type RecordingImage struct {
	TableName struct{} `sql:"recording_images,alias:images"`

	Uuid          uuid.UUID `sql:",pk" json:"uuid"`
	ExternalId    uint64    `json:"externalId"`
	RecordingUuid uuid.UUID `json:"recordingId"`

	IsMainImage bool `json:"mainImage"`

	StorageServer string `json:"storageServer"`
	StoragePath   string `json:"storagePath"`

	CreatedAt time.Time `json:"createdAt"`

	Recording *Recording
}


type Performer struct {
	TableName struct{} `sql:"performers,alias:performer"`

	Uuid       uuid.UUID `sql:",pk" json:"uuid"`
	ExternalId uint64    `sql:",notnull" json:"externalId"`

	OriginService string         `sql:",notnull" json:"originService"`
	OriginSection sql.NullString `json:"originSection"`

	StageName string           `sql:",notnull" json:"stageName"`
	Aliases   db.PGStringArray `sql:",notnull" json:"aliases"`

	RecordingCount uint16 `sql:",notnull" json:"recordingCount"`

	UpdatedAt time.Time `sql:",notnull" json:"updatedAt"`
	CreatedAt time.Time `sql:",notnull" json:"createdAt"`
}

```

```go
count, err := r.DB.Model(&recordings).Column("recording.*", "Images", "Performer").SelectAndCount()
```

Error
```
panic: reflect: call of reflect.Value.Field on ptr Value

goroutine 66 [running]:
panic(0xc1f840, 0xc42035b0a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
reflect.Value.Field(0xbc8100, 0xc42035ab78, 0x196, 0xe, 0xc42035b040, 0xc420055430, 0x4e33a1)
	/usr/local/go/src/reflect/value.go:741 +0x1e8
reflect.Value.FieldByIndex(0xbc8100, 0xc42035ab78, 0x196, 0xc4203b79c8, 0x1, 0x1, 0xbc8100, 0xc42035ab78, 0x196)
	/usr/local/go/src/reflect/value.go:773 +0x280
gopkg.in/pg.v5/orm.(*structTableModel).Bind(0xc4203aa0e0, 0xbc8100, 0xc42035ab78, 0x196)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/orm/model_table_struct.go:92 +0x6b
gopkg.in/pg.v5/orm.(*structTableModel).bindChildren(0xc42026e0b0)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/orm/model_table_struct.go:104 +0xaa
gopkg.in/pg.v5/orm.(*structTableModel).NewModel(0xc42026e0b0, 0xbc8100, 0xc42035ab78)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/orm/model_table_struct.go:114 +0x2b
gopkg.in/pg.v5/orm.(*sliceTableModel).NewModel(0xc42026e0b0, 0x12d7c44, 0x188)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/orm/model_table_slice.go:48 +0x67
gopkg.in/pg%2ev5.readSimpleQueryData(0xc42027c000, 0xce6140, 0xc42026e0b0, 0xc420324880, 0x1, 0x1, 0x0, 0x0)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/messages.go:678 +0x290
gopkg.in/pg%2ev5.simpleQueryData(0xc42027c000, 0xce6140, 0xc42026e0b0, 0xcfa1e0, 0xc42041c420, 0xc420324880, 0x1, 0x1, 0xc42025c400, 0x7fb950095960, ...)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/db.go:350 +0xc1
gopkg.in/pg%2ev5.(*DB).Query(0xc4203b6fc0, 0xce6140, 0xc42026e0b0, 0xcfa1e0, 0xc42041c420, 0xc420324880, 0x1, 0x1, 0xc94a20, 0x12e6460, ...)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/db.go:179 +0xe2
gopkg.in/pg.v5/orm.(*Query).query(0xc42041c420, 0x12e50c0, 0xc42026e0b0, 0xcfa1e0, 0xc42041c420, 0xc42026e0b0, 0x0, 0x0)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/orm/query.go:313 +0x296
gopkg.in/pg.v5/orm.(*Query).Select(0xc42041c420, 0x0, 0x0, 0x0, 0xc42041c580, 0x5)
	/home/antoine/Workspace/golang/src/gopkg.in/pg.v5/orm/query.go:327 +0xae

```

**Comment by macnibblet** [comment]
Okej

So I resolved the latest problem, it was with the declaration of the slice I was using.

The following only worked if it was not using the performer association ?
```go
var recordings []*Recording
```

The following works for both.
```go
var recordings []Recording
```

**Comment by vmihailenco** [comment]
Thanks for the report - I am going to fix it.
