### ISSUE TITLE
MaxAge on connections

### ISSUE THREAD

**Issue by viblo** [go-pg/pg#401]
Would it be possible to add a MaxAge on connections. So that if a connection is older than Max age when its retrieved from the Pool its closed, and a new one is opened. 

The reasoning behind this is the same as in my issue #397 . It turns out that some of the services we run are using connections slowly so only 1 connection is active at any time, but still enough traffic that it never times out. In this case a connection can live forever.

**Comment by vmihailenco** [comment]
That sounds like a small addition. I can add it to the master, but it will require upgrading to v5. Does that work for you?

**Comment by viblo** [comment]
That would be great. We have plans to upgrade to v5, we just havent come around to do it yet.

**Comment by vmihailenco** [comment]
Added `MaxAge` option in v5.2.0 - https://godoc.org/gopkg.in/pg.v5#Options
