### ISSUE TITLE
pg struct error

### ISSUE THREAD

**Issue by tommoholmes10** [go-pg/pg#408]
here my code

```
type Owner struct {
    Ownername  string
}
type Shop struct {
    Shopname  string
}
owner_put := &Owner{ Ownername:  "lorem",}
if err := db.Insert(owner_put); err != nil {
      log.Println(err)
    }
```
when I run this code,I get error like this
`2016/11/18 07:21:56 ERROR #42P01 relation "owners" does not exist (addr="127.0.0.1:5432")`
why my table transform to owners with s
my table owner without s

**Comment by vmihailenco** [comment]
You need to specify `TableName`:

```
type Owner struct {
    TableName struct{} `sql:"owner"`
    Ownername  string
}
```
