### ISSUE TITLE
model Post does not have primary keys

### ISSUE THREAD

**Issue by LevonXXL** [go-pg/pg#414]
Hi, I'm newbie in go and go-pg.

When I'm try use existing tables I've receive exception

model Post does not have primary keys

My model

Post struct {
		TableName struct{} `sql:"post"`
		id int `sql:",pk"`
		content string
		url_slug string
		user_id int
	}

exception with query

post := Post{
    id: 1,
}
err := db.Select(&post)
if err != nil {
    panic(err)
}

So, is it possible to use go-pk for exists tables?

**Comment by LevonXXL** [comment]
sorry, there was column names in lower case instead capitalize

**Comment by wildattire** [comment]
Any chance of re-opening this? We are experiencing the same behavior, except on Update(), not Select():

create table foos ( username varchar(64) primary key, bar_id int references bars(id) );

type Foo struct {
Username string `db:"username",sql:",pk"` 
BarID int32 `db:"bar_id"`
}
