### ISSUE TITLE
SelectAndCount does not work with joins

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#415]
```
var a []*TableA
m := db.Model(&a)
m.Column("a.*", "TableB")
m.SelectAndCount()
```
Correctly throws `ERROR #42803 column "table_b.id" must appear in the GROUP BY clause or be used in an aggregate function`. So then I modified it to this:

```
var a []*TableA
m := db.Model(&a)
m.Column("a.*", "TableB")
m.Group("table_a.id")
m.Group("table_b.id")
m.SelectAndCount()
```
But now it throws `pg: no Scan value for column index=1 name=table_b__id`.

The query for `count` seems to be the problem:
`SELECT count(*), table_b."id" AS "table_b__id" FROM table_a AS "table_a" LEFT JOIN table_b AS table_b ON table_b."id" = "table_a"."table_b_id" GROUP BY table_a.id, table_b.id`

Right now my workaround is to do `m.Count()` with the first example and then `m.Select()` with the second example:
```
var a []*TableA
m := db.Model(&a)
	count, err := m.Count()
	if err != nil {
		log.Println(err)
		return
	}
m.Column("a.*", "TableB")
err = m.Select()
	if err != nil {
		log.Println(err)
		return
	}
```

So is it by design that `SelectAndCount` cannot be used with joins?

**Comment by vmihailenco** [comment]
It's not by design, but it is broken. I will try to fix it tomorrow.
