### ISSUE TITLE
instrumentation hooks

### ISSUE THREAD

**Issue by aep** [go-pg/pg#416]
A generic hook to time queries would be great, so we can feed them to newrelic with https://github.com/yvasiyarov/gorelic
Is there any consent on how to do that?
something like (bad pseudcode ahead)

````go
type Instrumentation interface {
    start(*orm.Query) interface{}
    end(interface{}, orm.Query)
}

func (a *gorelic.Agent, query *orm.Query ) start() interface{} {
   return a.Tracer.BeginTrace(query.something)
}

db.Connect{Instrumentation: theGoRelicAgent....

````

**Comment by macnibblet** [comment]
Did you ever solve this, i'm also looking into this problem, but the author doesn't seam to interested.

**Comment by aep** [comment]
@macnibblet nope. we wrap all pg calls instead.
@haikoschol since there's an interest, maybe we can contribute something to pg that is similar to https://github.com/go-redis/redis/issues/424

**Comment by vmihailenco** [comment]
I am not ignoring this but this issue requires fair amount of work and it is not even clear what is the best or decent way to address it. Some notes:
- orm.Query is not available in raw mode like `db.Exec("TRUNCATE accounts")`
- At the moment you can't even extract query and params from orm.Query
- `Instrumentation` interface requires some context so you can match corresponding `End` and `Start`
- Instrumentation interface looks cool, but it is hard to imagine how you can use it except for logging query and time
- So it probably can be replaced with some hook like

```
type Event struct {
    StartTime time.Time
    State string // start, end?
    Query string
}

func myHook(db *pg.DB, event *Event) {}

db.RegisterHook(myHook)
```

Overall would be nice to research how other libraries (database/sql? gorm?) address this.

**Comment by macnibblet** [comment]
A quick google showed allowing callbacks to be registered https://github.com/smacker/newrelic-context/blob/master/gorm.go

**Comment by vmihailenco** [comment]
There is an example https://github.com/go-pg/pg/wiki/FAQ#how-can-i-view-queries-this-library-generates

**Comment by aep** [comment]
@vmihailenco this won't work with newrelic. it requires passing down a context which contains its own timer in addition to information about  the callstack. 
All this does is give us the query time outside the callstack. there's no way to implement proper segmentation.

**Comment by vmihailenco** [comment]
@aep if I understand correctly the only thing that is missing is context support. If so I created https://github.com/go-pg/pg/issues/528 and will add it soon

>there's no way to implement proper segmentation.

I don't use newrelic so I can misunderstand, but you can segment/group queries by `event.File:event.Line` and `event.UnformattedQuery`.
