### ISSUE TITLE
Is pg support the LastInsertId() method of the Result type in database/sql ?

### ISSUE THREAD

**Issue by hebl** [go-pg/pg#42]
Is pg support the LastInsertId() method of the Result type in database/sql ? Or when insert a row into table, how to get the `LastInsertId`?

In [https://github.com/lib/pq/blob/master/doc.go](https://github.com/lib/pq/blob/master/doc.go), There is another solution.

**Comment by vmihailenco** [comment]
TODO: add this to the faq
