### ISSUE TITLE
null value in column "id" violates not-null constraint 

### ISSUE THREAD

**Issue by aep** [go-pg/pg#421]
````
type Device struct {
     Id   string  //uuid
     Name string
}

err := db.Insert(Device{Name:"foo"});
````
[psql] 2016/11/26 19:02:19 config_test.go:20: INSERT INTO "foo" ("id", "name") VALUES (DEFAULT, 'foo') RETURNING "id", "name"

#23502 null value in column "id" violates not-null constraint (addr="[::1]:5432")

**Comment by vmihailenco** [comment]
It is not obvious what you are expecting here...

**Comment by aep** [comment]
right. I was thinking 'id' being part of the query is simply wrong because i've never seen "DEFAULT".   On the other hand, is setting default supposed to be identical to skipping the field? If yes there must be something wrong with my postgres setup instead.

**Comment by aep** [comment]
yep, definitely something with my setup. DEFAULT works fine in a clean testcase, sorry for the noise.
