### ISSUE TITLE
Query.Relation not applied

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#439]
I'm trying the following:
```
q.Relation("TestCaseTestSteps.TestStep",  func(q *orm.Query) (*orm.Query, error) {
  log.Println("order test")
  return q.OrderExpr("some_column NULLS FIRST"), nil
})

q.Column("TestCase.*", "TestCaseTestSteps", "TestCaseTestSteps.TestStep")
```
But the `apply` of `Relation` does not seem to execute. Neither the log message or the `OrderExpr` itself are present. I also tried breaking "TestCaseTestSteps.TestStep" to their individual `Relation` calls but it too seems not to work, I do not see the log or the order by.

Things do work if I have just one level in the `Relation`, for example: `q.Relation("Execution", ...)` with same `OrderExpr` and log works.

**Comment by vmihailenco** [comment]
Can you please write an example that reproduces the issue?

If the relation between TestCaseTestSteps and TestStep is has one then you should change your code to:

```
q.Relation("TestCaseTestSteps",  func(q *orm.Query) (*orm.Query, error) {
  log.Println("order test")
  return q.OrderExpr("some_column NULLS FIRST"), nil
})
```

because has one / belongs to relations are inlined in the main/host `TestCaseTestSteps` query.

**Comment by matthewvalimaki** [comment]
@vmihailenco the relation indeed was type of has one and your suggestion did fix it for me. Thank you for helping me.
