### ISSUE TITLE
Formatting a WHERE field IN (array) query

### ISSUE THREAD

**Issue by geoffgarside** [go-pg/pg#44]
How would you send a query with a `WHERE field IN ('a', 'b', 'c')` clause in it? Passing the string slice to FormatQ wraps the slice up as `{"a","b","c"}` if I use `WHERE field IN (?)`.

I think I'm going to end up having to use AppendQ and looping over the members of the array. Is there a better way?

Having only really been exposed to Arel in recent years I don't know if I've ended up with any Arel specific expectations about how interpolation would happen.

**Comment by Babazka** [comment]
You can rewrite the query as `WHERE field = ANY(?)`, it will work with slices / Postgres arrays:

```
da=# SELECT * FROM test;
 x |  y   
---+------
 a |   42
 b |   66
 c | 1138
(3 rows)
da=# SELECT * FROM test WHERE x = ANY('{"a", "c"}'::text[]);
 x |  y   
---+------
 a |   42
 c | 1138
(2 rows)
```

**Comment by vmihailenco** [comment]
There is also pg.Strings/pg.Ints structs that implement `pg.Appender` interface, e.g.:

```
ids := []string{"id1", "id2"}
db.Query(&articles, `SELECT * FROM articles WHERE id IN (?)`, pg.Strings(ids))
```

**Comment by geoffgarside** [comment]
Ahh, cool, thank you very much :) :+1:

**Comment by vmihailenco** [comment]
TODO: provide an example
