### ISSUE TITLE
Casting type money to numeric

### ISSUE THREAD

**Issue by matthewvalimaki** [go-pg/pg#441]
What would be the best way to do database side cast to numeric with the money type? Per https://www.postgresql.org/docs/current/static/datatype-money.html `SELECT '52093.89'::money::numeric::float8;` would (and does) work.

Right now with `sql.NullFloat64` I get `converting driver.Value type []uint8 ("$0.00") to a float64: invalid syntax`.

**Comment by matthewvalimaki** [comment]
This is how it works for me right now:
```
	PerUser          string
	PerUserConverted sql.NullFloat64 `sql:"-,per_user_converted,null"`

ColumnExpr("level.per_user::money::numeric::float8 AS level__per_user_converted")
```
While this does work challenge going forward is that I need to somehow inject that `ColumnExpr` whenever I want to use said table.

**Comment by vmihailenco** [comment]
I think this is not a go-pg issue - it is just that `sql.NullFloat64` does not accept `$0.00`. Probably you can store `0.00` instead of `$0.00`? If not the only way I see it to enhance `sql.NullFloat64` so it accepts the format you need.

**Comment by matthewvalimaki** [comment]
@vmihailenco thank you for the quick response. I will close. While I wanted to use `money` type I've chosen to go with `numeric`. Interestingly enough I did not find any mention anywhere for support for the `money` type, so like you said probably `sql` library would be the place for this.
