### ISSUE TITLE
How to insert a many2many?

### ISSUE THREAD

**Issue by acroca** [go-pg/pg#442]
Let's say I have this two models:
```go
type User struct {
    Id    int
    Items []Item `pg:",many2many:user_to_items,joinFK:Item"`
}
type Item struct {
    Id    int
    Users []User `pg:",many2many:user_to_items,joinFK:User"`
}
```
How can I add entries to the many2many table? I can always write the SQL query, but I'm wondering if there's a better way.

**Comment by vmihailenco** [comment]
There should be a better I believe, but we don't have it yet. For now I would define helper struct:

```
type UserToItem struct {
    UserId int
    ItemId int
}
db.Insert(&UserToItem{1, 2})
```

**Comment by acroca** [comment]
Yup, that's what I ended up doing. Was just wondering if there's a better way to do it from either a `User` or an `Item`.

**Comment by vmihailenco** [comment]
I can only think of something like `db.Model(&user).Relation("Items").Add(&item)`, but it does not look much (any?) better or shorter.

**Comment by acroca** [comment]
I didn't know that was a way to insert items into the relation. That works for me. I'll give it a try, Thanks!

**Comment by HazCod** [comment]
How can I write a migration script (raw sql) for creating this mapping table?
