### ISSUE TITLE
built in OR method

### ISSUE THREAD

**Issue by rodzzlessa24** [go-pg/pg#447]
First thank you for the library I've recently switched over from `gorm` and I'm enjoying it a lot more. I have a query that requires and `or` statement. I've searched the docs and the `Query` methods but I couldn't seem to find it. I know I can just simply use a custom query but I just wanted to first verify there was no `Or` method similar to `gorm` (https://godoc.org/github.com/jinzhu/gorm#DB.Or).

**Comment by vmihailenco** [comment]
There is nothing like that, but it is probably a good idea to add one :)

**Comment by vmihailenco** [comment]
Added `WhereOr` in v5.2.2
