### ISSUE TITLE
RunInTransaction Panic Recovery

### ISSUE THREAD

**Issue by AndrewBurian** [go-pg/pg#468]
I've had an issue where some bad code inside a `RunInTransaction` function panicked. The panic was recovered further up the stack but the panic prevented the transaction from being automatically rolled back. We ended up with connections that were stuck idle in transaction and eventually brought the database down when we exhausted the connection pool.

The fix (other than preventing panics) was to start every function like this

```go
err := db.RunInTransaction(func(tx *pg.Tx) error {
   defer func(t *pg.Tx) {
      if err := recover(); err != nil {
         t.Rollback()
         // rethrow the panic once the database is safe
         panic(err)
      }
   }(tx)
   // . . .
})
```

I was wondering if this would be a good thing to move into the `RunInTransaction` implementation itself. Allow the rollback to be done automatically, but then rethrow the panic so it's not hidden.

**Comment by vmihailenco** [comment]
This is related to https://github.com/go-pg/pg/issues/137

database/sql started to use [withLock](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L427-L433) recently to solve the same issue. Probably go-pg should do the same even though it adds some performance penalty.

**Comment by vmihailenco** [comment]
@AndrewBurian overall suggested fix looks good. Do you want to send a PR? If not I will apply fix myself.
