### ISSUE TITLE
Calling Insert multiple times with pointers to data structure without explicit Ids fails due to language behavior

### ISSUE THREAD

**Issue by TheChuckster** [go-pg/pg#473]
Adding two records in succession with a unique Id field (without specifying a value for it) fails, as in the following common use case (from your readme):

```
   user1 := &User{
      Name:   "admin",
   }
   err = db.Insert(user1)
   if err != nil {
      panic(err)
   }

   user2 := &User{
      Name:   "admin2",
   }
   err = db.Insert(user2)
   if err != nil {
      panic(err)
   }
```

Returns the error `ERROR #23505 duplicate key value violates unique constraint \"users_pkey\"` of course because the Id field in both User structs is the same (auto-initialized to 0 for both).

This is not the programmer's intended behavior, though; the programmer wanted user2 to be a successfully-inserted unique record with an auto-incremented Id of 1 (assuming user1 has Id 0, which will succeed when the table is empty).

How do you insert multiple records with an auto-incrementing Id without specifying an explicit non-colliding Id value in the struct?

**Comment by vmihailenco** [comment]
This should already work as expected if:
- field is called `Id` then go-pg automatically recognizes it as primary key
- field has tag `sql:",pk"`
- column is defined as serial or has some default value

Can you show struct and table definition?

**Comment by TheChuckster** [comment]
Hm, interesting -- so what about `ID` (the definitive naming convention for "ID" instead of `Id` per `golint` in VSCode)? Although, those guys are considering relaxing that requirement (thank God):
https://github.com/golang/lint/issues/89

The table itself is pretty non-interesting -- one thing to note is that I'm trying to take advantage of pg's new ORM features by using `CreateTable` instead of `Exec` with hand-coded `CREATE TABLE` SQL queries, which results in `id` being a `bigint` instead of a `serial`.

So, this table definition was autogenerated by pg's `CreateTable`:
```
db=> \d+ users;
                                                             Table "public.users"
        Column         |           Type           |                     Modifiers                      | Storage  | Stats target | Description
-----------------------+--------------------------+----------------------------------------------------+----------+--------------+-------------
 id                    | bigint                   | not null default nextval('users_id_seq'::regclass) | plain    |              |
 email                 | text                     | not null                                           | extended |              |
 name                  | text                     |                                                    | extended |              |

...

Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "users_email_key" UNIQUE CONSTRAINT, btree (email)
```

from this struct:
```
type User struct {
	Id    int64  `sql:",pk,unique,notnull"`
	Email string `sql:",unique,notnull"`
	Name  string
}
```

At least it looks like it auto-increments (per the table definition)!

I was missing `pk` on my `Id` field in my struct, but interestingly enough, it looks like even without that "tag" the primary key was being made (you mentioned that if the "field is called `Id` then go-pg automatically recognizes it as primary key" which after my own verification, does seem to be the case).

I tested it again, and with this struct+table, I still get the same error upon second `INSERT`:
`ERROR #23505 duplicate key value violates unique constraint \"users_pkey\"`

**Comment by vmihailenco** [comment]
You need to remove `,notnull` from the primary key tag.

**Comment by TheChuckster** [comment]
Thanks, seems like something worth mentioning in the documentation?

**Comment by rtanx** [comment]
it's still happended
