### ISSUE TITLE
Function "CreateTable" get error when struct contains array field

### ISSUE THREAD

**Issue by yobyzal** [go-pg/pg#474]
Golang version: go1.7 windows/amd64

The following code comes from file `exampledb_model_test.go`, and I made some changes. I got an #42702 error: `Error #42704 type "slice" not exist (addr="[::1]:5432")`

```
package main

import (
	"fmt"

	"gopkg.in/pg.v5"
	"gopkg.in/pg.v5/orm"
)

type User struct {
	Id     int64
	Name   string
	Emails []string
}

func (u User) String() string {
	return fmt.Sprintf("User<%d %s %v>", u.Id, u.Name, u.Emails)
}

func main() {
	db := pg.Connect(&pg.Options{
		Addr:     "localhost:5432",
		User:     "******",
		Password: "******",
		Database: "******",
	})

	err := db.CreateTable(&User{}, &orm.CreateTableOptions{
		Temp: true,
	})
	if err != nil {
		panic(err)
	}
}
```

**Comment by vmihailenco** [comment]
Should be fixed if you upgrade to v5.2.10. Overall CreateTable is in beta state and does not support some corner cases yet.

**Comment by yobyzal** [comment]
@vmihailenco Thinks for your time. I have tested the latest version, and got no error. However field type of `[]string` stored in postgresql is wrong that expect `text[]` but get `jsonb`.

**Comment by vmihailenco** [comment]
Well, go-pg by default treats slices as jsonb. You need to add `pg:",array"` tag to get desired behaviour, but `CreateTable` currently does not support it. You can workaround this

```
type User struct {
    Emails []string `sql:",type:text[]" pg:",array"`
}
```

**Comment by yobyzal** [comment]
@vmihailenco It works, thinks a lot.

**Comment by vmihailenco** [comment]
Lets keep this open since CreateTable can be improved to work without `,type:text[]` tag.

**Comment by jmheidly** [comment]
Am not sure if i should create another issue or if this is related but CreateTable fails to create when a map[string]string is supplied to a property of a struct.

**Comment by yobyzal** [comment]
Better to paste your code here because I get no error with `map[string]string`.
```
type County struct {
	Id         int64
	ProvinceId int64
	Name       map[string]string
}
```
Field `Name` will be store as `jsonb` type in postgresql.

**Comment by jmheidly** [comment]
Hey guys,

Is this issue resolved or do I still have to go through the workaround?
