### ISSUE TITLE
WhereIn orm method

### ISSUE THREAD

**Issue by rodzzlessa24** [go-pg/pg#479]
Hey man so I was thinking adding a WhereIn method would be helpful. I've played around implementing it and here is somewhat of a working rough draft:

```go
func (q *Query) WhereIn(where string, params ...interface{}) *Query {
	query := where + " IN ("
	for range params {
		query += "?,"
	}
	query = strings.TrimSuffix(query, ",")
	query += ")"

	q.where = append(q.where, &whereAppender{"AND", query, params})
	return q
}
```

And using it looks something like this:

```go
var ids = []interface{}{}
for _, other := range others {
	ids = append(ids, other.ID)
}

var demo []Demo
if err := DB.Model(&demo).WhereIn("other_id", ids...).Select(); err != nil {
	return nil, err
}
```

**Comment by vmihailenco** [comment]
Hi,

I like the idea, but `WhereIn` should use existing [In](https://github.com/go-pg/pg/blob/v5.3.2/pg.go#L37-L43). Probably following should work:

```
func (q *Query) WhereIn(where string, params ...interface{}) *Query {
    return q.Where(where, types.In(params))
}
```

Do you want to tryit and submit PR?

**Comment by rodzzlessa24** [comment]
Submitted the PR. https://github.com/go-pg/pg/pull/481.

**Comment by rodzzlessa24** [comment]
As just a side note probably making the function call `WhereIn(where string, params interface{})` will make it a bit easier for the end user. I'm trying to dive in and understand why the query is not being build as expected.

**Comment by vmihailenco** [comment]
Most likely you need to add support for `reflect.Interface` in https://github.com/go-pg/pg/blob/v5/types/append_value.go#L67.

**Comment by rodzzlessa24** [comment]
If we change the method call to `WhereIn(where string, params interface{})` Then I don't think we need to add `reflect.Interface` since the `typ` would just be string which is already supported. What is throwing me off is since type string is already supported and the `appender` func gets called for every type in a struct why is it throwing an error only for the `WhereIn` method. I've realized I should probably take at least a day or 2 to jump into the code base to understand it a bit more which I can't during the week but this weekend I should have the time to do it.

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/pull/482 - it seems to work without any additions.
