### ISSUE TITLE
Batching CopyTo

### ISSUE THREAD

**Issue by poopoothegorilla** [go-pg/pg#485]
It might be nice to add the ability to batch read from `CopyTo`. Unless there is already a possibility to do this that I am unaware of. What do people think?

**Comment by vmihailenco** [comment]
AFAIK Postgres already returns data in batches and go-pg immediately writes it to provided `io.Writer`. So you should be able to concurrently read that data from `io.Writer` without wating for `CopyTo` to finish. Just make sure your `io.Writer` supports concurrent read/write operations.

**Comment by poopoothegorilla** [comment]
I meant batching in terms of smaller buffer sizes. one scenario is a table with 100,000 rows... wouldn't this create a very large buffer in memory?

**Comment by vmihailenco** [comment]
go-pg does not create any buffers - it just reads data from PostgreSQL server to user's `io.Writer`. `io.Writer` decides what to do with the data - write it to disk, buffer in memory or block `Write` operation. I don't see any way to improve current behavior.

**Comment by poopoothegorilla** [comment]
I think i have a misunderstanding sorry
