### ISSUE TITLE
insert OnConflict error

### ISSUE THREAD

**Issue by xtreeio** [go-pg/pg#488]
this is my model

type Item struct {
	Id   int
	Name string
	Bank string
	In1  float64
	Out1 float64
	In2  float64
	Out2 float64
	Date int
}

then 

                       in1 = 1.1
			in2 = 0
			out1 = 2
			out2 = 0`

                    

			item := &Item{
				Name: coinName,
				Bank: bankName,
				In1: in1,
				Out1: out1,
				In2: in2,
				Out2: out2,
				Date: int(time.Now().Unix()),
			}

			_, err := rateDb.Model(item).
				OnConflict("(name, bank) DO UPDATE").
				Set("in1 = ?in1").
				Set("out1 = ?out1").
				Set("in2 = ?in2").
				Set("out2 = ?out2").
				Set("date= ?date").
				Insert()`

it has an error 
`ERROR #23502 null value in column "in2" violates not-null constraint (addr="127.0.0.1:5432")`

my column `in2` is float and I update value for this column as 0, but it'll set this column to 0.
can anyone help me ? thanks so much!

**Comment by vmihailenco** [comment]
Add `,notnull` tag:

```
    In2 float64 `sql:,notnull`
```
