### ISSUE TITLE
Magic 3 number in retries context

### ISSUE THREAD

**Issue by gazoon** [go-pg/pg#493]
I am trying to figure out how pg works with the retries. And I found the magic 3 number in some places.

For example db.Query method:
[https://github.com/go-pg/pg/blob/7c2d9d39a5cfc18a422c88a9f5f39d8d2cd10030/db.go#L193-L227](url)
[https://github.com/go-pg/pg/blob/7c2d9d39a5cfc18a422c88a9f5f39d8d2cd10030/stmt.go#L63-L82](url)

But in simular db.Exes method the magic 3 number doesn't appear: 
[https://github.com/go-pg/pg/blob/7c2d9d39a5cfc18a422c88a9f5f39d8d2cd10030/db.go#L150-L174](url)

Why do we need this number, if we have MaxRetries option? 

I also inspected redis library from the same author [https://github.com/go-redis/redis](url)
And found only one occurrence of this number:
[https://github.com/go-redis/redis/blob/f33571c93c72d3c4717a7b3c0bce95136496f772/pubsub.go#L230-L270](url)

**Comment by vmihailenco** [comment]
It just an overlook - 3 must be replaced with `MaxRetries` just like you suggested.

**Comment by gazoon** [comment]
I can try to fix it, or would it be better if you do this?

**Comment by vmihailenco** [comment]
I already fixed it in master but you can try to backport it to v5 if you want. Thanks for the report.
