### ISSUE TITLE
Custom table name not quoted in queries

### ISSUE THREAD

**Issue by jack-chung** [go-pg/pg#496]
Hello everyone,

I have a model like this:
```go
type User struct {
	tableName          struct{} `sql:"user"`
	ID                 int64
}
```
and db.Insert(&user) is generating queries without quoting the table name, resulting in an error due to reserved keyword. Surprisingly, if I don't define a table name override, by default it quotes the table name. It only skips the quotes when it's an override.

Is there any way to force the quotes?

**Comment by jack-chung** [comment]
Ah, I figured out a workaround, by adding quotes into the tag like this: `sql:"\"user\""`.
The current behavior should probably still be considered a bug?

**Comment by vmihailenco** [comment]
I think this is a bug, but I need to test that it does not break placeholders in case like `sql:"?shard.user"`. In case it works I will fix this in master (not v5).

**Comment by vmihailenco** [comment]
But it definitely will break cases like:

```
type AdminUser struct {
    tableName struct{} `sql:"(select * from users where admin) as users"`
}
```

Not that I am using something like that, but...
