### ISSUE TITLE
Use of internal package not allowed

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [go-pg/pg#502]
Hi, 

Using the latest version of Go, and given the following code: 
```
package main

import (
	"encoding/json"
	"net/http"
	"os"

	"github.com/go-pg/pg"
	"github.com/gorilla/mux"
)

func homeHandler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	rv := struct{ OK bool }{OK: true}
	json.NewEncoder(w).Encode(rv)
}

func main() {
	db := pg.Connect(&pg.Options{
		User:     os.Getenv("DATABASE_USER"),
		Password: os.Getenv("DATABASE_PASS"),
		Database: os.Getenv("DATABASE_DATABASE"),
	})

	router := mux.NewRouter()
	router.HandleFunc("/", homeHandler)
	http.Handle("/", router)
	http.ListenAndServe(":8080", nil)
}
```

and installing `pg` with Glide:
```
package: github.com/verygoodsoftwarenotvirus/blahblah
import:
- package: github.com/go-pg/pg
  version: ^5.3.3
- package: github.com/gorilla/mux
  version: ^1.3.0
```

This code fails to build with the following error:
```
package github.com/verygoodsoftwarenotvirus/blahblah
	imports github.com/go-pg/pg
	imports gopkg.in/pg.v5/internal: use of internal package not allowed
package github.com/verygoodsoftwarenotvirus/blahblah
	imports github.com/go-pg/pg
	imports gopkg.in/pg.v5/internal/pool: use of internal package not allowed
```

I'm developing in my GOPATH, as is advised, and had no issues compiling when I was just using mux. I really hate to file an issue, but I couldn't find any reference to my problem in any closed issues. 

From what I can see, it seems that the latest published version of `go-pg` references itself, which causes Go 1.7.4 to barf all over itself. Deleting my vendored version of `go-pg` and cloning master in its place seems to have fixed the issue. Perhaps the solution is to simply publish a release?

**Comment by vmihailenco** [comment]
I think you are right - I need to tag v6.0.0

**Comment by vmihailenco** [comment]
Please use https://github.com/go-pg/pg/tree/v6.0.0

**Comment by martoche** [comment]
The problem persists:

    $ go get gopkg.in/pg.v6
    go/src/gopkg.in/pg.v6/db.go:8:2: use of internal package not allowed
    go/src/gopkg.in/pg.v6/db.go:9:2: use of internal package not allowed

`db.go:8` imports `github.com/go-pg/pg/internal`. From what I understand, you're not allowed to import internal packages outside the repo which is `gopkg.in/pg.v6` in this case. My guess is that commit c23ec76 introduced the error.

`go get github.com/go-pg/pg` works though.

**Comment by vmihailenco** [comment]
I can confirm that gopkg.in and v6 don't work any more.
