### ISSUE TITLE
IF NOT EXISTS Option for Create Table

### ISSUE THREAD

**Issue by NickPancakes** [go-pg/pg#509]
I would like to suggest a new option for orm.CreateTableOptions that will use "IF NOT EXISTS" syntax when creating tables. This is useful in my application as I attempt to initialize all tables using CreateTable on application start. I can only assume it would be equally as useful for others.

**Comment by NickPancakes** [comment]
Added PR of my own implementation. I hope it's an acceptable request and solution!

**Comment by fangker** [comment]
think it's  useful advice
