### ISSUE TITLE
Support for CIDR/INET Values

### ISSUE THREAD

**Issue by dimitertodorov** [go-pg/pg#519]
Hey,

Before I dig in, do you guys support mapping inet/cidr columns to the corresponding go types.

https://github.com/jackc/pgx seems to do this fine.

I am open to assisting with implementing this feature if it does not already exist.

**Comment by vmihailenco** [comment]
No, currently there is no any special support for `net.IP`. Do you want to try to add it?

**Comment by dimitertodorov** [comment]
Yes. Ill try and do a PR if I have the time.
D

**Comment by vmihailenco** [comment]
Let's keep the issue open
