### ISSUE TITLE
Unmarshall json from jsonb fields with UseNumber() option

### ISSUE THREAD

**Issue by drblez** [go-pg/pg#524]

**Comment by vmihailenco** [comment]
I will get to this eventually, but at the moment JSON decoder does not have access to any flags/info set on the `DB` or models so it is not a trivial change. See https://github.com/go-pg/pg/blob/master/types/scan_value.go#L209-L218 if you are interested.

**Comment by vmihailenco** [comment]
See https://godoc.org/github.com/go-pg/pg#example-DB--JsonUseNumber
