### ISSUE TITLE
Select fails when no results are found

### ISSUE THREAD

**Issue by goncalo-msrt** [go-pg/pg#529]
Hi there,
first of all great library but I have an "issue".

Basically I want to check in the DB if there's already a relation before inserting a new one.

The problem is that when I Select it, if it does not find it it returns an error. But in a query there could be many errors and I want to proceed even if the result is not found.

At the moment I solved this way checking that the error is different than what it is returned by go-pg:
```
	var relationOutgoing models.Relation
	err = srv.Psql.Conn.Model(&relationOutgoing).
		Column("relation_status", "relation_uuid").
		Where("user_uuid = ? AND other_user_uuid = ?", request.UserUuid, request.OtherUserUuid).
		Limit(1).
		Select()
	if err != nil && err.Error() != "pg: no rows in result set" {
		return mrerrors.FormedError(err, mrerrors.ServiceSocialGetRelations)
	}
```

Is there another way to do this kind of checks?

**Comment by vmihailenco** [comment]
There is `pg.ErrNoRows` and `pg.ErrMultiRows` vars for this.

But you better use `INSERT ... ON CONFLICT DO NOTHING`:

```
db.Model(&mod).OnConflict("(user_uuid) DO NOTHING").Insert()
```

There is also `SelectOrInsert` helper if you need to select the record - https://godoc.org/github.com/go-pg/pg#example-DB-Insert-SelectOrInsert. Code is [here](https://github.com/go-pg/pg/blob/master/orm/query.go#L481-L517)

**Comment by goncalo-msrt** [comment]
But for example, if I find a row, I have to run an update depending on the value in it, So an insert (on conflict) will not really help I guess.

I guess I'll use the pg.ErrNoRows then

**Comment by vmihailenco** [comment]
See [this](https://godoc.org/github.com/go-pg/pg#example-DB-Insert-OnConflictDoUpdate) for version with update. Overall I recommend to look at all examples - https://godoc.org/github.com/go-pg/pg#pkg-examples
