### ISSUE TITLE
Incorrect format of the string for channels

### ISSUE THREAD

**Issue by Krule** [go-pg/pg#532]
Hi!

***Disclamer*: I am super new to golang so this might be a non issue or me implementing it incorrectly.**

While trying to use this library in order to listen for `NOTIFY`, I have encountered a weird issue. Namely, I have channels in Postgres which follow the pattern: `context.event`. When I defined my listener as:

```go
channels := []string{"user.loggedIn", "user.loggedOut"}
listener := db.Listen(channels...)
defer listener.Close()

notification := <-channel
fmt.Println(notification)
```

... nothing happened, but I've got an error logged in Postgres:

```log
db_1      | ERROR:  syntax error at or near "." at character 14
db_1      | STATEMENT:  LISTEN "user"."loggedIn"
db_1      | ERROR:  syntax error at or near "." at character 14
db_1      | STATEMENT:  LISTEN "user"."loggedOut"
```

So, it appears like strings with dot are automatically (and possibly incorrectly) formatted?

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed in v6.1.3
