### ISSUE TITLE
Potential Bug: Selecting fields that contain substring `id` produces incorrect query

### ISSUE THREAD

**Issue by Krule** [go-pg/pg#536]
Hello again, looks like I have found another potential bug:

Provided I have model:

```golang
type Foo struct {
	Id     int    `db:"id"`
	UUIDv4 string `db:"uuidv4"`
}
```

and I execute query like:

```golang
var foo []Foo
_, err := es.Model(&foo).Select()
```

I expect query produced to be:

```sql
SELECT "foo"."id", "foo"."uuidv4" FROM "foos" AS "foo" 
```

Instead query produced is: 
```sql
SELECT "foo"."id", "foo"."uui_dv4" FROM "foos" AS "foo" 
```

It appears as if any string containing substring `id` is parsed to have `_` inserted between `i` and `d`.

**Comment by vmihailenco** [comment]
Hello,

AFAIK you need to change `UUIDv4` to `UUIDV4`.

**Comment by Krule** [comment]
@vmihailenco I did now and it changed to:

```sql
SELECT "foo"."id", "foo"."uuid_v4" FROM "foos" AS "foo"
```

**Comment by Krule** [comment]
NVM, used `sql` tag and corrected it.

**Comment by vmihailenco** [comment]
Then Go name should be `UUIDV4` :) I did not notice you had `db` tag in your example...
