### ISSUE TITLE
UUID as default value

### ISSUE THREAD

**Issue by gaghan430** [go-pg/pg#537]
I don't know if this is an issue or not, but I have question
I was trying to insert data without `id` being set, but I got this result
```json
{
    "Id": "00000000-0000-0000-0000-000000000000",
    "Name": "root",
    "Emails": [
        "root1@root",
        "root2@root"
    ]
}
```

My table:
```
type User struct {
	Id     uuid.UUID `sql:",notnull,type:uuid default uuid_generate_v4()"`
	Name   string
	Emails []string
}
```

so, how do I set the uuid as a default value when there is no value for id?

**Comment by macnibblet** [comment]
It's pretty simple
```go
struct MyStruct {
	Uuid     uuid.UUID `sql:",pk"json:"uuid"`
}
```

Notice the `,pk` ?

**Comment by gaghan430** [comment]
@macnibblet thanks for answering
I tried this, but got the same result
```go
type Profile struct {
	Id     uuid.UUID `sql:",pk,notnull,type:uuid default uuid_generate_v4()"`
	Lang   string
	UserId uuid.UUID `sql:",type:uuid"`
}
```

**Comment by vmihailenco** [comment]
My guess is that you need to remove `notnull`. That makes go-pg to generate `NULL` value and let's PostgreSQL to set default value. I will see how current behavior can be improved.

**Comment by macnibblet** [comment]
@gaghan430 I have never tried it will postgres generating the UUID for me, I always found that to be extremely annoying, everything needs to be pointers and stuff.

**Comment by gaghan430** [comment]
@macnibblet I was wondering, if there is another way store the data without `id` being set?

@vmihailenco I've tried it, but still no luck

**Comment by macnibblet** [comment]
@gaghan430 you would need to use `Returning("Id")` on the insert and `uuid.UUID` would need to be a pointer. Given that the `id` column is created with the `default uuid_generate_v4()` but honestly, I don't see *any* benefits of using that.

**Comment by vmihailenco** [comment]
The problem is that you are using custom `uuid.UUID` type and go-pg have no idea if `00000000-0000-0000-0000-000000000000` is null/zero value or not. https://github.com/satori/go.uuid/issues/49 should fix this.

For now workaround is to upgrade to latest go-pg version and use `uuid.NullUUID`:

```
package main

import (
	"github.com/go-pg/pg"
	"github.com/satori/go.uuid"
)

type Profile struct {
	Id     uuid.NullUUID `sql:",pk,type:uuid default uuid_generate_v4()"`
	Lang   string
	UserId uuid.NullUUID `sql:",type:uuid"`
}

func main() {
	db := pg.Connect(&pg.Options{
		User: "postgres",
	})
	err := db.Insert(&Profile{})
	if err != nil {
		panic(err)
	}
}
```

**Comment by gaghan430** [comment]
@macnibblet @vmihailenco thank you so much for helping me! keep rocking guys!

**Comment by vmihailenco** [comment]
I also fixed `uuid.UUID` since it is implemented as `[16]byte` and go-pg can be smart enough to check if array contains only zeroes. You will need to upgrade go-pg to use it.
