### ISSUE TITLE
How to get table name from model?

### ISSUE THREAD

**Issue by dudochkin-victor** [go-pg/pg#542]
I have that piece of code. It's possible to drop table if exists or know table name form model?
```
for _, value := range []interface{}{&Product{}, &Color{}, &Category{}, &Language{}, &Book{}, &Publisher{}, &Comment{}, &Author{}} {
		//pbprod.Exec("drop table product_tags;") // value
}
```

**Comment by vmihailenco** [comment]
Please upgrade to latest version and try https://godoc.org/github.com/go-pg/pg#DB.DropTable

**Comment by dudochkin-victor** [comment]
Anyway it will usable to iterate all database fields for model. Please add this feature coz it's very important for development. In my code i reimplement methods to generate table and field name. Also is necessary to know keys, primary key and other metadata. Tnx.

**Comment by dudochkin-victor** [comment]
Another question:  How to store model with submodels?
In my case i trying to insert User model with nested Address model. Are go-pg will store address with user? or i should to store address and then store user?

**Comment by MrBadge** [comment]
Just in case it will help somebody:

```
type Example struct {
	TableName struct{} `sql:"games" json:"-"`
}

model := Example{}
tags, ok := reflect.TypeOf(model).FieldByName("TableName")
if !ok {
	return errors.New("failed to get model tags")
}
tableName, ok := tags.Tag.Lookup("sql")
if !ok {
	return errors.New("failed to get table name from sql tag")
}
fmt.Println(tableName)
```
