### ISSUE TITLE
Zero values transforms into NULL values if the field has no flag NOT NULL

### ISSUE THREAD

**Issue by diztex** [go-pg/pg#548]
The AppendValue method in field.go transforms zero values into NULL in case if the field type does not have NOT NULL flag. It is not a correct behaviour because the zero value is not equal to NULL.

**Comment by vmihailenco** [comment]
You are supposed to add `sql:",notnull"` flag if you don't need this behavior.

**Comment by diztex** [comment]
Thanks! I apologize for inattention
