### ISSUE TITLE
Is it possible to do a multiple row update with ORM?

### ISSUE THREAD

**Issue by tapir** [go-pg/pg#554]
I'm wondering if it's possible to update multiple rows at the same time. I've tried something like

```Go
books = append(books, SomeBook())
books = append(books, AnotherBook())
db.Model(&books).Set("title = ?title").Update()
```

but unfortunately it didn't work. I could always use a query but I would rather do it with the ORM.

Thanks

**Comment by tapir** [comment]
Is it maybe possible to create a query like this when model receives a slice and the method called is update:
```sql
UPDATE conf_currencies AS t 
SET price = c.price
FROM (
VALUES
(2, $1),
(3, $2),
(4, $3),
(5, $4),
(6, $5)
) AS c(id, price)
WHERE c.id = t.id
```

**Comment by vmihailenco** [comment]
No, that currently only works for inserts.

**Comment by vmihailenco** [comment]
See https://godoc.org/github.com/go-pg/pg#example-DB-Update-BulkUpdate

**Comment by tapir** [comment]
Does it also work with slices line in insert? If so maybe it would be good to add another example like that

**Comment by vmihailenco** [comment]
Yes, it works - added another example

**Comment by tapir** [comment]
Thank you very much

**Comment by latipovsharif** [comment]
How can I cast primary key? for example in my database tables the primary keys of type `uuid` so if I use bulk update it throws the following exception `SQL Error [42883]: ERROR: operator does not exist: uuid = text
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 586`

**Comment by vmihailenco** [comment]
Add `sql:"type:uuid"` tag on the column.
