### ISSUE TITLE
Seems to parse arrays incorrectly

### ISSUE THREAD

**Issue by Krognol** [go-pg/pg#559]
Whenever a row has an array column and I try to do anything with that row i get an error.

In this case the column is a `BIGINT[]` and contains `{127317863}`.
The error: `invalid character '1' looking for beginning of object key`.

**Comment by vmihailenco** [comment]
I guess that go-pg thinks the type of column is jsonb, not array. You need to add `pg:",array"` tag or specify type `sql:",type:bigint[]"`.

**Comment by vmihailenco** [comment]
Added some docs about types to https://github.com/go-pg/pg/wiki/Model-Definition
