### ISSUE TITLE
Support connection via postgre url string

### ISSUE THREAD

**Issue by nihiluis** [go-pg/pg#564]
(Feature request)

like this:  "postgres://postgres:leonardodicaprio71@localhost/gojim"

```go
orm := pg.Connect(&pg.Options{
    URL:  "postgres://postgres:leonardodicaprio71@localhost/gojim"
}
```

**Comment by vmihailenco** [comment]
See http://godoc.org/github.com/go-pg/pg#ParseURL that parses an URL into `pg.Options`. I guess we need an example somewhere.
