### ISSUE TITLE
How to use intersect?

### ISSUE THREAD

**Issue by Pcummings** [go-pg/pg#567]
Hey Guys,

How would you write queries with subqueries and intersects? If e.g. I have a query looking like this
```
select u.* from schma.table u where u.id in (
select user_id from schema.users where lx=42 and y>=(select something from table where lx=42) 
INTERSECT select user_id from schema.users where lx=123 and y>=(select something from table where lx=123) 
);
```
Any help is greately appreciated.

**Comment by vmihailenco** [comment]
Currently there is no special support for UNION/INTERSECT in the ORM. If query is complex it is often simpler to use SQL directly:

```
var users []User
res, err := db.Query(&users, `
    SELECT
    UNION
    ANOTHER SELECT
`)
```

You could also try to rewrite your query with common table expressions and `WITH`, but it is not obvious that result will be better.
