### ISSUE TITLE
orm: better support for subqueries

### ISSUE THREAD

**Issue by vmihailenco** [go-pg/pg#569]
E.g.

```
subq := db.Model(&Author{}).Column("id").Where("admin")
q := db.Model(&books).Where("author_id IN (?)", q)
```

should generate

```
SELECT * FROM books
WHERE author_id IN (
  SELECT id FROM authors WHERE admin
)
```

**Comment by MohitKS5** [comment]
@vmihailenco Can this be used in Insert statements ? Can you provide any way to use subqueries in Insert statement (replacing values) ?

**Comment by psaikiran2890** [comment]
Hi @vmihailenco, I have the same question as above.

I'm trying to do a SELECT into INSERT but the SELECT query on a different table needs to be have the WHERE clause with the values passed to the insert.

I have two tables (table1 & table2) which have a common column. When trying to insert into table1, if one of the columns is empty/null, I want to SELECT that column from table2 and then insert.

Something like: 
```
query2 := db.Model((*table2)(nil)).Column(id).Where("column1 = ?")
db.Model(&table1).Value(column1, query2)
```

Trying to understand how to do this. Any help here would be great.

Thanks.

**Comment by vmihailenco** [comment]
@GMac2890 see https://pg.uptrace.dev/queries/#insert-from-select
