### ISSUE TITLE
pg: unsupported dst: []float64

### ISSUE THREAD

**Issue by owentran** [go-pg/pg#57]
I noticed there's support for []int64 but []float64  are missing from the decoder. Do you plan on adding support or is there some technical reason this can't be handled? Thanks!

**Comment by vmihailenco** [comment]
Do you mean decoding PostgreSQL `double precision[]` into Go `[]float64`? That can be added fairly easy. Let me know if you are interested.

**Comment by owentran** [comment]
Yes. That's exactly what I'm looking for. Please add and I'll test it out.

**Comment by vmihailenco** [comment]
Done. Please test.

**Comment by owentran** [comment]
Confirmed, works great! Thanks.
