### ISSUE TITLE
SelectOrInsert

### ISSUE THREAD

**Issue by 5k3105** [go-pg/pg#573]
Hi!

I have a table with two unique fields. `pffo_id` and `path`.

Since the id is autogenerated, I would expect every time I change the path, I can get a new record. Running SelectOrInsert, it will insert one record with path but when I change the path, it will not insert a new record.

So on first insert with path at "x/y", returns true and inserts. On second insert with path at "x/y/z" it returns false.

Also noticed, if the table is completely empty and I attempt SelectOrInsert or just Insert using the '.Model' notation, I get this error:

```panic: ERROR #42601 syntax error at or near "AS" (addr="10.205.77.25:5432")```

Using the db.Insert(&folder) notation works on an empty table though.

```go
package main

import (
	"fmt"
	"github.com/go-pg/pg"
	"time"
)

type FullsiteFolder struct {
	Pffo_id    uint64
	Uploadtime time.Time
	Path       string
	Year       string
}

var dbhost = `dev-postgres-1:5432`

func main() {

	db := pg.Connect(&pg.Options{
		User:     "postgres",
		Password: "postgres",
		Database: "products",
		Addr:     dbhost,
	})

	//createtable(db)

	createrecord1(db)
	createrecord2(db)

}

func createtable(db *pg.DB) {

	r, err := db.Exec(ctFolders)

	check(err)
	println(r)

}

func createrecord1(db *pg.DB) {

	var folder = FullsiteFolder{
		Uploadtime: time.Now(),
		Path:       "x/y",
		Year:       "2016",
	}

	res, err := db.Model(&folder).OnConflict("DO NOTHING").SelectOrInsert()

	if err != nil {
		panic(err)
	}

	fmt.Println(res, folder)

}

func createrecord2(db *pg.DB) {

	var folder = FullsiteFolder{
		Uploadtime: time.Now(),
		Path:       "x/y/z",
		Year:       "2016",
	}

	res, err := db.Model(&folder).OnConflict("DO NOTHING").SelectOrInsert()

	if err != nil {
		panic(err)
	}

	fmt.Println(res, folder)

}

var ctFolders = `CREATE TABLE fullsite_folders(
 pffo_id 		serial UNIQUE NOT NULL,
 uploadtime		timestamp, 
 path 			varchar (20) UNIQUE NOT NULL,
 year			char(4)

);`

func check(e error) {
	if e != nil {
		panic(e)
	}
}
```

**Comment by 5k3105** [comment]
This works as well with the correct pg version ;( 
Sorry!

**Comment by 5k3105** [comment]
On second look, this is still misbehaving. It consistently worked on a test table but now:

This always works:
```go
		res, err := db.Model(&folders).OnConflict("DO NOTHING").Insert()
```

This 
```go
		res, err := db.Model(&folders).OnConflict("DO NOTHING").SelectOrInsert()
```

Always returns false except if it's a single insert on an empty table.

**Comment by vmihailenco** [comment]
I think the query should be:

```
	res, err := db.Model(&folder).
		Where("path = ?path").
		OnConflict("DO NOTHING").
		SelectOrInsert()
```

But overall you should start debugging with viewing at generated queries - https://github.com/go-pg/pg/wiki/FAQ#how-can-i-viewlog-queries-this-library-generates.

**Comment by 5k3105** [comment]
Yes, this worked. Thank you for the feedback.
