### ISSUE TITLE
Can I do class table inheritance?

### ISSUE THREAD

**Issue by timopick** [go-pg/pg#581]
Hi everyone, 

I'm connecting with go-pg to a legacy database (hibernate on postgres) thats using class table inheritance. I thought about using polymorphic joins but these require a "type" field in the parent table. Is there some other way to make it work?

Example:
```
TABLE "address"
- id: primary_key
- zip: varchar
- city: varchar

TABLE "invoice_address"
- id: foreign_key -> address.id
- company: varchar

type Address struct {
  Id int
  Zip, City string 
}

type InvoiceAddress struct {
  Id int
  Company string
  Address <-- Some way to reference the content of Address
}
```

Best regards,
Timo

**Comment by vmihailenco** [comment]
Hi,

Do you mean

```
type Address struct {
  Id int
  Zip, City string 
}

type InvoiceAddress struct {
  Id int
  Company string
  Address <-- Some way to reference the content of Address
}
```

?

**Comment by timopick** [comment]
Oops, yes.

**Comment by vmihailenco** [comment]
Please upgrade to v6.4.5 and try following:

```
type Address struct {
	Id        int
	Zip, City string
}

type InvoiceAddress struct {
	Id      int
	Company string
	Address Address `pg:",fk:"`
}
```

`fk:` specifies empty foreign key prefix, e.g. "" + "Id" = "Id". Usually fk prefix is type name, e.g. "Address" + "Id" = "AddressId".

**Comment by vmihailenco** [comment]
@timopick please let me know if that code is working so I can add it to the wiki / package examples. Thanks.

**Comment by timopick** [comment]
@vmihailenco Thanks for the answer. Will try it now and report!

**Comment by nihiluis** [comment]
@timopick so you got report now?
