### ISSUE TITLE
escape ? question mark

### ISSUE THREAD

**Issue by goncalo-msrt** [go-pg/pg#585]
Hi guys, I have to query in a jsonb field and the where clause looks like this: `attributes ? 'value'`

So when using `.Where()` I should escape the first question mark like `.Where("attributes \? ?, "value")`.

Is there any way of doing this? I tried to search but I could not find anything.

**Comment by vmihailenco** [comment]
`.Where("attributes \? ?, "value")` should work. Did you try it?

**Comment by goncalo-msrt** [comment]
I got `unknown escape sequence`

The solution is actually like that but using the backticks (string literals) ``.Where(`attribuets \? ?`, "value")``

**Comment by vmihailenco** [comment]
Added a hint in https://github.com/go-pg/pg/wiki/Writing-Queries#placeholders

**Comment by Obayanju** [comment]
I know this has been closed for a while, but  I wanted to understand what difference the backticks make?
I tried googling but didn't find anything.

**Comment by vmihailenco** [comment]
Backtricks allow writing ``attribuets \? ?`` instead of `"attribuets \\? ?"`

**Comment by wangmengyu** [comment]
I got "pq: syntax error at or near "\"" 

	has, err := session.Where(`attributes \? value`).Get(&mateInfo)

**Comment by elliotcourant** [comment]
I'd try turning on query logging on the PostgreSQL server and grabbing the query it's generating so we can more easily debug it.

**Comment by louisheath** [comment]
I'm also struggling here. gORM leans on `go-pg` and [suggests](https://github.com/go-pg/pg/blob/v10/example_placeholders_test.go#L19) a backslash. I've also heard `??` should do the trick. Neither seem to work

`Where("categories \\? ?", "cat")` -> `syntax error at or near "\" (SQLSTATE 42601)`

`Where("categories ?? ?", "cat")` -> `syntax error at or near "$2" (SQLSTATE 42601)`

`Where("categories ?? @name", sql.Named("name", "cat"))` -> `operator does not exist: @ text (SQLSTATE 42883)`

I'm moving on with a hacky `like '%"cat"%'`

```
		gorm.io/gorm v1.24.1
		github.com/go-pg/pg/v10 v10.11.1 // indirect
```

**Comment by vivere-dally** [comment]
I'm facing the same issue, trying to use the jsonb operator `?|` as such `my_jsonb_col ?| ?`. I tried all escape variations, none seem to work, GORM replaces the first `?` no matter what I do

**Comment by solidiquis** [comment]
Same issue as @vivere-dally .. did you figure it out? Why is this issue closed?

**Comment by vivere-dally** [comment]
> Same issue as @vivere-dally .. did you figure it out? Why is this issue closed?

Yes, I remember using `gorm.Expr`
