### ISSUE TITLE
Is it possible to get sql table name by model?

### ISSUE THREAD

**Issue by Labutin** [go-pg/pg#586]
I know, it is possible to set custom table name for model.
But is it possible to get default sql table name by model?

**Comment by madhukar93** [comment]
custom table name is set using field `tableName` in your struct
```
type MyModel struct {
tableName        struct{} `sql:"actual_table_name"`
}
```
and
```
type MyModel struct { 
// fields 
}
```
translates to table `my_model` in sql 
does that answer your question ?

**Comment by Labutin** [comment]
Thank you madhukar93, but not.
I am asking  how to get table name in runtime.
Something like this, db.Model(&object).TableName

**Comment by Labutin** [comment]
I want to explain why I am asking this question.
Look at this example: https://godoc.org/github.com/go-pg/pg#example-DB-Model
`err := db.CreateTable(model, &orm.CreateTableOptions{
            Temp: true,
        })`
And then I want to create additional indexes for tables.
https://github.com/go-pg/pg/issues/125
To create index I have to know table name. But I don't want to use filed:
tableName        struct{} `sql:"actual_table_name"`

**Comment by Labutin** [comment]
And one correction.
@madhukar93 in your example table in sql will have name `my_models` (plural form).

**Comment by vmihailenco** [comment]
Thanks for describing your use case. I've added an example to the [wiki](https://github.com/go-pg/pg/wiki/Writing-Queries#executing-custom-queries) (you will need latest version)
