### ISSUE TITLE
example code doesnt change localhost postgres dabase

### ISSUE THREAD

**Issue by jaroslaw-weber** [go-pg/pg#587]
i checked an example code and it was working without errors but localost database stays untouched. i set up adress and user etc but not working. how to check if db.Connect failed? it doesnt returns error nor throwing panic

**Comment by vmihailenco** [comment]
Execute some query, e.g. `_, err := db.Exec("SELECT 1")`

**Comment by sj14** [comment]
Hi, 
I had the same problem.
If you are using the example from the README.md you have to set "Temp: false" in the createSchema function.

**Comment by jaroslaw-weber** [comment]
@sj14 thx it worked! it would be nice to add some comment in readme because it was confusing when started!

**Comment by vmihailenco** [comment]
Oh, I misunderstood the quertion... I fixed example in readme to not create temp table.
