### ISSUE TITLE
problem with providing relation with custom name

### ISSUE THREAD

**Issue by madhukar93** [go-pg/pg#588]
is the following model
```
type GrProduct struct {
	tableName        struct{} `sql:"gr_product"`
	ID               int64
	Name             string
	RelatedBrand     int
	RelatedBrandObj  *GrBrand `pg:",fk:RelatedBrand"`
}
```
On making queries, where `RelatedBrand` isn't even a part of `Columns`, the generated query tries to select `"product"."related_brand_obj"`. It doesn't seem to recognize `RelatedBrandObj` as a relation.
I'm having this problem due to badly named column as the foreign key from `gr_brand` to `gr_product` is called `related_brand` instead of `related_brand_id`

edit: I tried a couple of things hoping to get lucky by trial and error like providing ````sql:"related_brand"```` on RelatedBrandObj, but it didn't work.
Issue might be similar to https://github.com/go-pg/pg/pull/584 ? where `ModelName` is being used instead of the provided `fk`

**Comment by vmihailenco** [comment]
`fk` is actually a prefix for the key, i.e. the field name will be `fk + pk.Name = RelatedBrandId` (if your primary key is named `id`). It is done that way to support multi-column primary keys. I guess go-pg can be improved to also try just `fk`, but it will not support multi-column primary keys... Are you still interested?

**Comment by madhukar93** [comment]
Yes, although I don't understand how multi column pks are implemented, I believe that use cases such as mine shouldn't be all that uncommon (IMO it should be possible to explicitly define these parameters, although the framework magic is very nice and convenient). The only significant experience I've had with ORMs is Python's Django's where giving the sql names for entities is always possible (I don't think it supports multi column pks even after the level of maturity it is at now). I think I have been able to make my problem clear ? Is there any workaround possible at the moment ? I am definitely interested in a solution.
Thanks for your time.

**Comment by vmihailenco** [comment]
Please try v6.4.8 - I think your original example should be fixed.

**Comment by madhukar93** [comment]
thanks so much ! 
hoping to contribute back to your project some day.
