### ISSUE TITLE
Missing auto quote

### ISSUE THREAD

**Issue by devmarwen** [go-pg/pg#592]
Trying to get a user with its associations with a `where` condition on the `user`:
```go
	err = db.
		Model(&user).
		Column("user.*", "Company", "PendingOperations").
		Where("id = ?id").
		First()
```
The problem: 
```go
Where("id = ?id")   #=> Fail: ambiguous
```
```go
Where("user.id = ?id")   #=> Fail: Syntax error
```
```go
Where("\"user\".\"id\" = ?id")   #=> Works but ugly
```

Any insights on this?

**Comment by vmihailenco** [comment]
user is a keyword in Postgres so you should escape it via `Where(`"user".id = ?id`)`

**Comment by gmolveau** [comment]
Thank you so much, been having trouble with it for a longtime !
