### ISSUE TITLE
how to order by joined tables

### ISSUE THREAD

**Issue by madhukar93** [go-pg/pg#595]
```
type Product struct {
	ID               int64
	Name             string
        Tags             []GrTag             `pg:",many2many:product_tags"`
}
/*
Tables are
products (id, name), product_tags(id, product_id, tag_id), tags(id, name)
*/
```
in the following model, while selecting products with their tags, how can I order by tag names, I tried something like
```
DB.Model(&p).Column("product.id", "Tags").Where("id = ?", 1).Order("tags.name ASC").Select()
```

(PS: Also, I guess I'll file a separate issue for this but `Relation` example in the wiki seems broken, as the `apply` function argument is supposed to return `(*orm.Query, error)` now, instead of just `*orm.Query`, also it didn't seem apply when I returned `q.Where(...), nil` in the `apply` function.There was no error but the query didn't have the condition on the join. I'll file an issue after verifying further.)

**Comment by vmihailenco** [comment]
AFAIK you can order tags by the name, but not products by the tag name. First because products and tags are selected with 2 different queries. Second because product can have multiple tags and it is not clear how order should work (anyway I don't know query).

So to sort tags by the name:

```
DB.Model(&p).
    Column("product.id", "Tags").
    Where("id = ?", 1).
    Relation("Tags", q *orm.Query) (*orm.Query, error) {
        return Order("tags.name ASC"), nil
    }).
    Select()
```

>I'll file a separate issue for this but Relation example in the wiki seems broken

Thanks, I fixed the example.

**Comment by madhukar93** [comment]
thank you for your quick response as always, this was  what I was looking for, sorry my language was unclear.
