### ISSUE TITLE
Set or update TIMESTAMP WITHOUT TIMEZONE fails because of wrong value formating.

### ISSUE THREAD

**Issue by RepentantGopher** [go-pg/pg#608]
Hi.
I have model with field type of time.Time which refers to column in postgres database type of  TIMESTAMP WITHOUT TIMEZONE.
While reading value from this field works fine, insert or update operations fails with error like:
```
ERROR #42804 column \"created_at\" is of type timestamp without time zone but expression is of type text
```

On model bulk update library generates following sql query:
```
UPDATE 
	sms_recipient AS "sms_recipient_model"
SET 
	"created_at" = _data."created_at", 
	"processed_at" = _data."processed_at"
FROM (
	VALUES (
		20, 
		'2017-08-07 14:37:57.375559663+00:00:00',
		'2017-08-07 14:37:57.375559663+00:00:00'
	)	
) AS _data(
	"id", 
	"created_at", 
	"processed_at"
) WHERE 
	"sms_recipient_model"."id" = _data."id";
```
which definitely broken, but can be simply fixed by adding convertion to timestamp.
Working sql query looking like this:
```
UPDATE 
	sms_recipient AS "sms_recipient_model"
SET 
	"created_at" = _data."created_at", 
	"processed_at" = _data."processed_at"
FROM (
	VALUES (
		20, 
		'2017-08-07 14:37:57.375559663+00:00:00'::timestamp, 
		'2017-08-07 14:37:57.375559663+00:00:00'::timestamp
	)	
) AS _data(
	"id", 
	"created_at", 
	"processed_at"
) WHERE 
	"sms_recipient_model"."id" = _data."id";
```
In source code this bug could be simply fixed by adding this convertion to AppendTime function
https://github.com/go-pg/pg/blob/master/types/time.go#L34
like this

```
func AppendTime(b []byte, tm time.Time, quote int) []byte {
	if quote == 1 {
		b = append(b, '\'')
	}
	b = tm.AppendFormat(b, timestamptzFormat)
	if quote == 1 {
		b = append(b, '\'')
	}
	b = append(b, []byte("::timestamp")...)
	return b
}
```

Should i make pull request with these changes or i don't understand it right?

**Comment by vmihailenco** [comment]
I wonder if it works if you change type from `timestamp` to `timestamptz`?

**Comment by RepentantGopher** [comment]
Yes it works.

**Comment by vmihailenco** [comment]
I am tempted to say that it is working as intented and you should use `timestamptz`, because it is better in every aspect.

Changing `AppendTime` to use `timestamp` will break all the code that uses `timestamptz`.

**Comment by RepentantGopher** [comment]
> I am tempted to say that it is working as intented and you should use timestamptz, because it is better in every aspect.

I can't agree with you because in last few years timezones in my country was changed very often, so in my opinion it's better to store time in UTC without tz to avoid headache in future:)

I'll test my changes with columns of different time types and if it will be ok ill create pull request.

**Comment by vmihailenco** [comment]
See http://justatheory.com/computers/databases/postgresql/use-timestamptz.html . It is not obvious from the name, but timestamptz is what most users want.

**Comment by iqbalaydrus** [comment]
To anyone coming across to this from google, you can create your own type to support timestamp without timezone if changing your column type to timestamptz isn't an option.

```
const pgTimeFormat = "2006-01-02 15:04:05.999999999"

type TimeNoTz struct {
	time.Time
}

var _ types.ValueAppender = (*TimeNoTz)(nil)

func (tm TimeNoTz) AppendValue(b []byte, flags int) ([]byte, error) {
	if flags == 1 {
		b = append(b, '\'')
	}
	b = tm.AppendFormat(b, pgTimeFormat)
	if flags == 1 {
		b = append(b, '\'')
	}
	return b, nil
}

var _ types.ValueScanner = (*TimeNoTz)(nil)

func (tm *TimeNoTz) ScanValue(rd types.Reader, n int) error {
	if n <= 0 {
		tm.Time = time.Time{}
		return nil
	}

	tmp, err := rd.ReadFullTemp()
	if err != nil {
		return err
	}

	tm.Time, err = time.ParseInLocation(pgTimeFormat, string(tmp), time.Local)
	if err != nil {
		return err
	}

	return nil
}
```

Then you can use the type for the struct as usual

```
type PerformanceLog struct {
	tableName  struct{} `pg:"performance_log"`
	DateTime   TimeNoTz
	ModuleName string
	Kwargs     map[string]interface{}
	Duration   float64
	TaskId     uuid.UUID `pg:"type:uuid"`
	TimeRange  string
}
```
