### ISSUE TITLE
How can I response a custom error message

### ISSUE THREAD

**Issue by kieusonlam** [go-pg/pg#610]
Hi all,

I'm new to Go, how can I response a custom error message. 

For example I want to get a Post info by post_id, but the post_id doesn't exist. I want to response with the message like "Post does not found". I just don't know how to do it :(

**Comment by vmihailenco** [comment]
Something like:

```
post := new(Post)
err := db.Model(post).Where("id = ?", 123).Select()
if err == pg.ErrNoRows {
    fmt.Println("post not found")
} else if err != nil {
    panic(err)
}
```

**Comment by kieusonlam** [comment]
Cool, that what I'm looking for. Thanks @vmihailenco
