### ISSUE TITLE
Feature request: support default value

### ISSUE THREAD

**Issue by siteshen** [go-pg/pg#611]
It will be convenient if we can set default value when define model, like SQLAlchmey's `server_default=10` and `default=20`.

```go
type DemoTable struct {
	SqlDefault  int8 `sql:"default=10"`
	CodeDefault int8 `pg:"default=20"`
}
```

`sql_default` is a field with default value 10 in sql, and `code_default` is set to 20 before insert into database.

1. add field `orm.Field.DefaultValue reflect.Value`
2. set `append(b, ENCODE(f.DefaultValue)...)`  instead of `append(b, "DEFAULT"...)` `in insertQuery.appendValues()`

**Comment by vmihailenco** [comment]
Looks reasonable except that AFAIK tags use slightly different format: `sql:"default:10"` instead of `sql:"default=10"`.

Do you want to give it a try yourself?

**Comment by vmihailenco** [comment]
I've added support for `sql:"default:10"`. For code default please use https://www.postgresql.org/docs/9.6/static/ddl-default.html or 

```
func (b *Book) BeforeInsert(db orm.DB) error {
    if b.CreatedAt.IsZero() {
        b.CreatedAt = time.Now()
    }
    return nil
}
```
