### ISSUE TITLE
Calling `First` does not load related models through a many2many relation

### ISSUE THREAD

**Issue by alexbrand** [go-pg/pg#614]
I was using the following to load my model and it's relations:
```
tx.Model(&modelA).
		Column("modelA.*", "modelB").
		Where("modelA.id = ?", ID).
		First()
```
This was loading `modelA` just fine, but was not loading the related `modelB`.

Switching to using `Select` instead of `First` fixed it.
```
tx.Model(&modelA).
		Column("modelA.*", "modelB").
		Where("modelA.id = ?", ID).
		Select()
```

**Comment by vmihailenco** [comment]
`First` adds order and limit and calls `Select` and it is well-tested to load relations so I need more info to fix this. Can you try to record queries executed by go-pg?

**Comment by alexbrand** [comment]
Definitely. I'll get them ASAP.
