### ISSUE TITLE
Question: I cannot get ManytoMany to work

### ISSUE THREAD

**Issue by kieusonlam** [go-pg/pg#620]
Hi,

I trying to do a REST API server using aah framework and go-pg. I have 2 models `post` and `category`
Post model: https://github.com/kieusonlam/golamapi/blob/master/app/models/post.go
```
type (
	// Post struct hold the post details
	Post struct {
		ID         int        `json:"id"`
		Title      string     `json:"title"`
		Content    string     `json:"content"`
		Categories []Category `json:"categories" pg:",many_to_many:posts_categories,fk:Post,joinFK:Category"`
		CreatedAt  time.Time  `json:"created_at"`
		UpdatedAt  time.Time  `json:"updated_at"`
	}
)
// CreatePost use to create new post.
func CreatePost(title string, content string) *Post {
	post := &Post{
		Title:   title,
		Content: content,
	}
	err := db.Insert(post)
	if err != nil {
		log.Error(err)
	}
	return post
}
// GetPost use to get single post.
func GetPost(id int) Post {
	var post Post
	err := db.Model(&post).Column("post.*", "categories").Where("id = ?", id).Select()
	if err != nil {
		log.Error(err)
	}
	return post
}
```
Category model: https://github.com/kieusonlam/golamapi/blob/master/app/models/category.go
```
type (
	// Category hold post category details
	Category struct {
		ID          int    `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description"`
		Posts       []Post `json:"posts" pg:"many_to_many:posts_categories,,fk:Category,joinFK:Post"`
	}
)
```
Relation model: https://github.com/kieusonlam/golamapi/blob/master/app/models/posts_categories.go
```
type (
	// PostsCategories Post Category relation
	PostsCategories struct {
		ID         int `json:"id"`
		PostID     int `json:"post_id"`
		CategoryID int `json:"category_id"`
	}
)
```
I created new post, new category and add relation but it's not work.
![image](https://user-images.githubusercontent.com/13093313/29449306-60e40858-8424-11e7-90ed-1b23f101bdb3.png)
--------------------------------
![image](https://user-images.githubusercontent.com/13093313/29449325-7023553a-8424-11e7-927c-37bd9d2b0995.png)
--------------------------------
![image](https://user-images.githubusercontent.com/13093313/29449382-b2d03c68-8424-11e7-8030-f949a1aef31c.png)
console log didnt have join table
![image](https://user-images.githubusercontent.com/13093313/29449561-6c724b70-8425-11e7-9233-0c68e03fbaca.png)

Am I missing something :(

**Comment by vmihailenco** [comment]
Try `Column("post.*", "categories")` -> `Column("post.*", "Categories")`

**Comment by kieusonlam** [comment]
@vmihailenco Thank for reply.

I did try that before

![image](https://user-images.githubusercontent.com/13093313/29456740-60df8504-8441-11e7-8a26-492d688399b5.png)

**Comment by vmihailenco** [comment]
Following seems to work:

```
type Post struct {
	ID         int        `json:"id"`
	Title      string     `json:"title"`
	Content    string     `json:"content"`
	Categories []Category `json:"categories" pg:"many2many:posts_categories"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type Category struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Posts       []Post `json:"posts"  pg:"many2many:posts_categories"`
}

type PostCategory struct {
	ID         int `json:"id"`
	PostID     int `json:"post_id"`
	CategoryID int `json:"category_id"`
}
```

Specifically `many_to_many` is called `many2many` in go-pg.

**Comment by kieusonlam** [comment]
Thank for helping me.
