### ISSUE TITLE
Singular table names not documented?

### ISSUE THREAD

**Issue by robvdl** [go-pg/pg#623]
How do I tell go-pg that I want a struct User to use table "user" not "users"?

I can't find it anywhere in the docs

Is there a way to tell go-pg that all table names should be singular? or does it need to be defined on each struct?

**Comment by robvdl** [comment]
Also would that mean that currently for a struct called Staff it would use a table name "staffs" which isn't even proper English :)

**Comment by vmihailenco** [comment]
As for now there is no way to globally table name generation rules. You need to define name on each struct.

**Comment by robvdl** [comment]
What do you mean name, a Name() method?

**Comment by robvdl** [comment]
This is going a little OT and I am not trying to come across as rude but I personally think plural table names is wrong (and so do most devs at work I talk to) + it can lead to funny names like staffs or addresss.  Most (possibly even all) Python ORMs I know don't do this and use singular table names: Django, SQLAlchemy, they all default to singular table names.  Same goes with rest endpoints, most Python rest frameworks, TastyPie, Django Rest Framework all default to singular names.  For example you would use /api/v1/user not /api/v1/users though I realise this is an age old debate and people have different point of views towards this.

Back to Go, I remember GORM defaulted to plural table names too and I found it annoying, but they had a setting if you wanted to use singular table names globally.

**Comment by vmihailenco** [comment]
I've added `orm.SetTableNameInflector` which changes inflection func for the whole library. You are supposed to use it like this to disable pluralization:

```
func init() {
    orm.SetTableNameInflector(func(s string) string {
        return s
    })
}
```

>What do you mean name, a Name() method?

I mean `tableName struct{} `sql:"genres,alias:genre"`` field on the struct.
