### ISSUE TITLE
Changing column names not documented?

### ISSUE THREAD

**Issue by robvdl** [go-pg/pg#624]
Mostly this is needed for ID columns, at work we are not allowed to call a pk column "id", it must be called "user_id" for example.  Mostly because we are dealing with old school DBAs.

Why doesn't this work:

    type User struct {
        ID         int     `db:"user_id"`
        Active   bool  `db:"is_active"`
    }

It still thinks the column is called "id" when querying, rather than "user_id"

Same with is_active, it's trying to use active, but I want the db column to be is_active.

**Comment by vmihailenco** [comment]
When did you get `db:"user_id"`? All examples use `sql:"user_id"`.

**Comment by robvdl** [comment]
Thanks heaps for that, I was not able to find this anywhere in the examples or docs.  Every single example I saw specified simple models without field renames.
