### ISSUE TITLE
Does this support dynamically switching schemas at runtime?

### ISSUE THREAD

**Issue by damitchem** [go-pg/pg#627]
To support a multi-tenant requirement for data isolation each tenant has a schema created that contains its copy of the data structure. We need the ability to change which schema that is accessed based on API call that provides a schema identifier.

Is this possible with the current implementations in pg? If not, is a future implementation planned?

**Comment by vmihailenco** [comment]
See [global params](https://github.com/go-pg/pg/wiki/Writing-Queries#placeholders). E.g.

```
tenant1 := db.WithParam("tenant", types.F("tenant1"))
tenant2 := db.WithParam("tenant", types.F("tenant2"))

tenant1.Query("SELECT * FROM ?tenant.table_name")
```

https://github.com/go-pg/sharding uses that to [shard](https://github.com/go-pg/sharding/blob/master/cluster.go#L60-L65) Postgres.
