### ISSUE TITLE
Can we add fk constraint 

### ISSUE THREAD

**Issue by mayur-tolexo** [go-pg/pg#628]
Didn't found any settings for
on delete restrict on update cascade.
Does it support adding constraints like gorm

**Comment by vmihailenco** [comment]
go-pg does not create any constraints. For now you should be able to manually add constraints you need via https://github.com/go-pg/pg/wiki/Writing-Queries#executing-custom-queries

**Comment by damitchem** [comment]
@vmihailenco 

According to your [model definition page](https://github.com/go-pg/pg/wiki/Model-Definition) FK is a valid constraint that go-pg incorporates. Although the usage and how it handles it is a little fuzzy.

**Comment by vmihailenco** [comment]
In model definition fk specifies field/column that is used to detect relation between tables. go-pg can use that info to create foreign keys constraints, but it is not done yet.

**Comment by vmihailenco** [comment]
I've added basic support for foreign key constraints that are enabled via `CreateTableOptions.FKConstraints` option. Please try it out and let me know what is missing.

**Comment by julienkosinski** [comment]
@vmihailenco Could you please help me on the way to create foreign constraints? What does it supports now? How to use this basic support between two models structs to add foreign keys constraints automatically?
Thanks :)

**Comment by vmihailenco** [comment]
Try following

```
db.CreateTable(&YourStruct{}, &orm.CreateTableOptions{
  FKConstraints: true,
})
```

and check which constraints library generates. There are some chances it already does what you expect, but it is unlikely - it was added recently and I doubt it has many users. If the latter is the case - please open an issue with concrete example.

**Comment by julienkosinski** [comment]
@vmihailenco Thank you for your response.
Of course, if it doesn't work I'm gonna open an issue.
If I have something like "user_role has many user" then I'm supposed to do things like that?

``
db.CreateTable(&User{}, &orm.CreateTableOptions{
  FKConstraints: true,
})

db.CreateTable(&UserRole{})

type User struct {
	ID                  int
	UserRoleID    int
}

type UserRole struct {
	ID       int
	Users []*User
}
``

**Comment by vmihailenco** [comment]
Better try:

```
models := []interface{}{&User{}, &UserRole{}}
for _, model := range models {
  _, err := db.CreateTable(model, &orm.CreateTableOptions{
    FKConstraints: true,
  })
}
```

**Comment by julienkosinski** [comment]
@vmihailenco Thank you for your response. I have opened an issue. https://github.com/go-pg/pg/issues/694
