### ISSUE TITLE
How can I  create a sequence

### ISSUE THREAD

**Issue by fangker** [go-pg/pg#629]
I just use 

> 	Db.Exec(`CREATE SEQUENCE   test_id_seq;`) 

 But it does not work

**Comment by vmihailenco** [comment]
Any errors returned by `db.Exec`?

**Comment by fangker** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x132623c]

goroutine 1 [running]:
github.com/go-pg/pg.(*DB).Exec(0x0, 0x15f6e80, 0xc42015b3d0, 0x0, 0x0, 0x0, 0x16, 0x0, 0x0, 0x0)
        /Users/renge/go/src/github.com/go-pg/pg/db.go:139 +0x5c
_/Users/renge/Desktop/cardtoon/cardtoon-backend/model.NewUserSchema(0xc42004ff01, 0x12af828)
        /Users/renge/Desktop/cardtoon/cardtoon-backend/model/user_model.go:25 +0xbc
_/Users/renge/Desktop/cardtoon/cardtoon-backend/model.init()
        /Users/renge/Desktop/cardtoon/cardtoon-backend/model/db_model.go:13 +0x5e
main.init()
        /Users/renge/Desktop/cardtoon/cardtoon-backend/main.go:62 +0x6e
exit status 2

**Comment by vmihailenco** [comment]
Looks like you did not connect to data via `pg.Connect`. Does this query work:

```
_, err := db.Exec("SELECT 1")
```

?

**Comment by fangker** [comment]
Thank  you for your patience,I  found  it  not connect to database。
