### ISSUE TITLE
What is the parameter of Select() and Insert()?

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#641]
`var users []User`
//That's right
`Mode(&users).Select()`
//That's wrong
`Mode(&User{}).Select(&users)`

What is the parameter of Select () and Insert ()?

**Comment by vmihailenco** [comment]
Both variants look right to me. Can you expand on what is wrong and right about them?

**Comment by dxvgef** [comment]
The second method cannot pass in values, all values become `DEFAULT`, the first method is normal,
But I can do this in Insert(), it feels a little confusing
`Mode(&User{}).Insert(&users)`

**Comment by vmihailenco** [comment]
`Insert(&users)` or `Insert(&col1, &col2, &col3)` is used with `RETURNING col1, col2, col3`. So:
- `Model(&user)` - `user` is used to insert the data
- `Insert(&users)` - `users` are used to scan returned data via `RETURNING *`

**Comment by dxvgef** [comment]
I see. Thank you!

**Comment by vmihailenco** [comment]
Note that you can call Model multiple time, e.g. `db.Model(&User{})...Model(&users).Insert()`.
