### ISSUE TITLE
Question: Default value for "text" fields

### ISSUE THREAD

**Issue by kaustavdm** [go-pg/pg#645]
How would you add default value for "text" fields using the `default` syntax introduced for #611?

I tried `sql:",default:baz"` and `sql:",default:'baz'"` (single quote around `baz`). These produce sql as `"fieldname" text DEFAULT baz` without quotes, thus, resulting in an error.

The only way I got this to work is by adding extra content to the `type` option in `sql`, like this: 

```go
type Foo struct {
	Bar string `sql:",type:text default 'baz'"`
}
```

Is there a better way?

**Comment by vmihailenco** [comment]
Please try to escape single quotes as in `sql:"default:\'baz\'"`

**Comment by kaustavdm** [comment]
I'm using golang 1.9 (forgot to mention that before). I had already tried escaping single quotes. This results in a `go vet` error:

```
struct field tag `sql:",notnull,default:\'bar\'"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```

Also, the SQL output for `CreateTable()` does not contain any `DEFAULT` statement in this case. So, this outputs:

```
CREATE TABLE "foo" ("bar" text)
```

**Comment by vmihailenco** [comment]
Please upgrade go-pg and try `sql:"default:'baz'"`. Overall you need to double escape quotes `sql:"default:'baz \\' bar'"`.

**Comment by kaustavdm** [comment]
@vmihailenco It works! Thanks!
