### ISSUE TITLE
How to define varchar, char length?

### ISSUE THREAD

**Issue by julienkosinski** [go-pg/pg#650]
Hello,

If I'd like to handle varchar and char is there something implemented in the ORM?
Also, how should I proceed to define a length to it?

Thanks! :)

**Comment by vmihailenco** [comment]
You specify field type using `sql:"type:varchar(255)"`. Or use [CreateTableOptions.Varchar](https://godoc.org/github.com/go-pg/pg/orm#CreateTableOptions) option if all strings should have same length. Note that go-pg only uses that type to create table, i.e. it does not not truncate data to specified length.

**Comment by julienkosinski** [comment]
Thank you very much for your response @vmihailenco! Then about length I need validators!
