### ISSUE TITLE
Does it support Debug mode as in gorm

### ISSUE THREAD

**Issue by mayur-tolexo** [go-pg/pg#651]
Can we print the query after binding the value to it as it is supported in gorm. In gorm if we add Debug() in the model then it will print the query after execution. Is it anyhow possible to check what actual query executed after binding the values to model?

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/wiki/FAQ#how-can-i-viewlog-queries-this-library-generates

**Comment by mayur-tolexo** [comment]
Thanks for the quick response.

**Comment by dxps** [comment]
Updated ref: https://pg.uptrace.dev/faq/#how-to-view-queries-this-library-generates

And to see all queries (not just erroneus ones), use `db.AddQueryHook(pgext.DebugHook{Verbose: true})`.
