### ISSUE TITLE
About the ID field of the struct

### ISSUE THREAD

**Issue by dxvgef** [go-pg/pg#653]
Why Update() automatically gets the ID field value of the struct to do the where condition, while Select() and Delete() do not?
And the Column() function is valid for Update() and Select() and is only invalid for Insert(), which makes people feel that the package's planning is a bit confusing.

**Comment by vmihailenco** [comment]
`db.Select(&model)` adds `WHERE` too, but you can't customize the query.

Delete and Update require `WHERE` clause so you don't accidentally delete or update whole table (and it is also handy in most cases). By adding `Where("true")` you can easily bypass that restriction.
