### ISSUE TITLE
ERROR #42P01 relation "[pluralized table name]" does not exist

### ISSUE THREAD

**Issue by JoelTrottier** [go-pg/pg#654]
What is causing go-pg to always attempt finding the pluralized name of my table?

PostgreSQL Table:
```
public.employeesalary (
    employeeid varchar(50),
    badgeid varchar(50),
    salary bigint
)
```
GO Model:
```
type EmployeeSalary struct {
        tableName struct{} `sql:",employeesalary"`
        EmployeeId string `sql:",pk"`
        BadgeId string
        Salary int
}
```

Query:
```
var salary int
db.Model(&EmployeeSalary{}).Column("salary").Where("badgeid = ?", emp.BadgeId[0]).Limit(1).Select(&salary)
```

Error:
`ERROR #42P01 relation "employee_salaries" does not exist`

What have I missed?

**Comment by vmihailenco** [comment]
Try to replace `tableName struct{} `sql:",employeesalary"` with `tableName struct{} `sql:"employeesalary"`

**Comment by JoelTrottier** [comment]
That did the trick!

For my own understanding, could you explain why adding the `tableName` was necessary in the first place?

If the table name was the same as the struct, shouldn't it have found it on it's own?

**Comment by vmihailenco** [comment]
It is not the same, for `EmployeeSalary` go-pg auto-generates table name `employee_salaries`.

**Comment by JoelTrottier** [comment]
Gotcha!

Well thanks for this great library.

**Comment by Aegon95** [comment]
@vmihailenco doesn't work for uppercase table name

**Comment by j796160836** [comment]
Watch out the `s` and **snake_case**. ⚠️
By default, `EmployeeSalary` struct will create `employee_salarys` table.
(Camel case will be transfer to snake case and add `s`.)

Be careful for the coding. 😮
