### ISSUE TITLE
Failed to compile 5.3.3

### ISSUE THREAD

**Issue by jack-chung** [go-pg/pg#656]
Hi,

I'm unable to compile 5.3.3 if I import from github.com/go-pg/pg. It only works when I import from gopkg.in. It is because the code itself imports from gopkg.in, specifically the internal packages caused the errors below:

vendor/github.com/go-pg/pg/db.go:8:2: use of internal package not allowed
vendor/github.com/go-pg/pg/orm/format.go:10:2: use of internal package not allowed
vendor/github.com/go-pg/pg/db.go:9:2: use of internal package not allowed

Is gopkg.in still the proper way to use v5?
Thanks!

**Comment by vmihailenco** [comment]
Hi,

Yes, v5 is the last version that works with gopkg.in.
