### ISSUE TITLE
Sanitize Parameter for JSONB Query

### ISSUE THREAD

**Issue by dc0d** [go-pg/pg#663]
How can a parameter be sanitized for a JSONB query?

For example in a query (where clause) like:

```go
`(json_data @> '{"group_id": ?, "sent_to_group": false}'::jsonb)`
```

If a string parameter is provided, it will be sanitized using single quotes, like `'GROUP_123'`. While as a JSON value it should be `"GROUP_123"`, with double quotes.

BTW currently a query object is being used by first converting it to JSON and then providing the whole _JSON string_ as a parameter and the where clause looks like:

```go
`(json_data @> ?0::jsonb)`
```

**Comment by vmihailenco** [comment]
I think `(json_data @> ?0::jsonb)` is the correct way to do it. I could create some special wrapper for JSON value like `Where("...", pg.JSONValue("group_123"))`, but that looks like overkill.

**Comment by dc0d** [comment]
I agree. Thanks for the response. It would help if this be added to documentation as a practice or reference since it's not an obvious way for doing this.

**Comment by nihiluis** [comment]
```
Where(`some_column @> '[?]'`)
```

where do I put the 0::jsonb here?

**Comment by vmihailenco** [comment]
I don't understand what is the problem. Please open new issue with more details - what you try, what is the result and what do you expect.
