### ISSUE TITLE
Timeouts?

### ISSUE THREAD

**Issue by nihiluis** [go-pg/pg#667]
I'm using this options

```go
	orm := pg.Connect(&pg.Options{
		User:     config.Instance.PostgresUser,
		Password: config.Instance.PostgresPass,
		Database: config.Instance.PostgresDatabase,
    Addr:     config.Instance.PostgresAddress,
    MaxRetries: 5,
    DialTimeout: 30 * time.Second,
	})

  orm = orm.WithTimeout(30 * time.Second)
```

When I use this to test if the connection is alive:

```go
func CheckPg() bool {
  _, err := ORM.Exec(`SELECT * FROM pg_catalog.pg_tables`)
  if err != nil {
    return false
  }

  return true
}
```

the timeout stuff doesnt seem to have any effect, as it immediately returns false in docker. how do I make it take effect here? basicaly I want the ORM to retry to get an appropriate connection for a specified time.

**Comment by vmihailenco** [comment]
Timeout is the max amount of time to wait. It does not mean "retry 30 seconds no matter what happens".

>basicaly I want the ORM to retry to get an appropriate connection for a specified time.

Try higher `MaxRetries = 30`

**Comment by mwmahlberg** [comment]
However, DialTimeout seems to be ignored:

```
opts.User = mustHaveEnv("POSTGRES_USER")
opts.Password = mustHaveEnv("POSTGRES_PASSWORD")
opts.Addr = fmt.Sprintf("%s:%s", mustHaveEnv("POSTGRES_HOST"), mustHaveEnv("POSTGRES_PORT"))
opts.Database = mustHaveEnv("POSTGRES_DB")
opts.DialTimeout = 5 * time.Second

[...]

db := pg.Connect(&opts)
```

Above code blocks forever.

**Comment by vmihailenco** [comment]
Code above does not open any connections and therefore can't block.
