### ISSUE TITLE
Don't use DELETE CASCADE by default

### ISSUE THREAD

**Issue by roobre** [go-pg/pg#669]
I think this is a very dangerous default, which also is not clearly stated anywere. `ON DELETE SET NULL` or `ON DELETE SET DEFAULT` would be better options.

I can write a pull request changing this, and even adding another options field to choose between the allowed options, if you are interested.

**Comment by vmihailenco** [comment]
I think it would be better to add an option like:

```
&CreateTableOptions{
    FKConstraints: true,
    OnDelete: "SET NULL",
}
```

Can you create a PR?

**Comment by roobre** [comment]
Sure, expect it this afternoon or tomorrow morning.

**Comment by roobre** [comment]
Okay, I just made the changes on my own branch, but I think it would need some tests. However, I can't find any instructions on how to run those. What kind of test environment does pg expect?

**Comment by vmihailenco** [comment]
I think you are looking for https://github.com/go-pg/pg/blob/master/orm/create_table_test.go.

As for the environment it expects Linux with fresh Postgres 9.6 running on standard 5432 port. It requires almost no setup - see https://github.com/go-pg/pg/blob/master/.travis.yml

**Comment by jmheidly** [comment]
Any luck with the PR guys?

**Comment by vmihailenco** [comment]
See https://godoc.org/github.com/go-pg/pg#example-DB-CreateTable
