### ISSUE TITLE
pg: cannot map timestamp with time zone/time.Time field

### ISSUE THREAD

**Issue by AustinDizzy** [go-pg/pg#67]
So I'm trying to run a simple SELECT query and get the resulting rows in a slice of their respective struct. This includes a `time.Time` value that is stored in postgres as a timestamp with time zone.

Here's the postgres result running the query:
````
testdb=# SELECT * FROM users WHERE device = 'android';
registrationid | tokens | device  |       registrationdate
---------------+--------+---------+-------------------------------
    foobar     |        | android | 2015-08-20 23:12:24.593388-04
(1 row)
````

And here's the relevant Go code:

````
type User struct {
     RegistrationID string
     Tokens *oauth2.Token
     Device string
     RegistrationDate time.Time
}

type Users struct {
     C []User
}

var _ pg.Collection = &Users{}

func (users *Users) NewRecord() interface{} {
     users.C = append(users.C, User{})
     return &users.C[len(users.C)-1]
}

func getUsers(device string) ([]User, error) {
     var users Users
     //DB is my active postgres DB connection
     _, err := DB.Query(&users, `SELECT * FROM users WHERE device = ?`, device)
     return users.C, err
}
````

The exact error I'm getting is `pg: cannot map field "registrationdate"` without a whole lot of other explanation or documentation on what that means.

There is one record retrieved, but RegistrationID is blank (not nil, just an empty string) and the RegistrationDate is "0001-01-01 00:00:00 +0000 UTC".

So far, everything I've done or tried seems to be exactly how it is in the documentation/examples so I'm assuming either the documentation is wrong/scare for time-based values or there's a bug mapping go's time.Time to and from timestamp with time zone. I've also tried switching the column to timestamp without time zone, date, and bigint with no avail.

Sorry if this doesn't really constitute a GitHub issue, but I could've find anywhere else to get specialized help related to this library like a mailing list or Slack channel. Any ideas what it could be?

**Comment by vmihailenco** [comment]
The go-pg mapper maps Go field `RegistrationID` to PostgreSQL column `registration_id`, but your table uses `registrationid` column name. So you either have to:
- rename column `registrationid` to `registration_id` (recommended)
- or add field tag to Go struct ```RegistrationID string `pg:"registrationid"````

Same for other columns.

PS Also Go naming convention is to use `RegistrationId`, not `RegistrationID`.

**Comment by AustinDizzy** [comment]
Yup, that's gotta be it. Sorry, I guess I was prototyping too fast and didn't notice my variable and column names didn't meet proper specification.

Thanks.
