### ISSUE TITLE
Query.First() does not add WHERE clause if model has non-zero ID

### ISSUE THREAD

**Issue by roobre** [go-pg/pg#670]
I assume from the examples and own experience that a query like:

```go
myModel := MyModel{ID: 5, Changed: true}
pg.Model(&myModel).Columns("changed").Update()
```

does parse the `ID` field, and only the row with ID 5 is updated.

However, `.Select()` and `.First()` do not add this clause. I think pg should add them automatically if the supplied model has at least one index set to non-zero, and it is not a slice, just like it is done with `db.Select(&myModel)`.

**Comment by vmihailenco** [comment]
First is a shortcut for `OrderExpr("id ASC").Limit(1)` and it is not designed to add any wheres. `Query.Select` could do what you suggest, but
- there is already `db.Select(&model)` that does that (don't confuse it with `db.Model(&model).Select()`)
- it is too late for such change

**Comment by roobre** [comment]
Understood. I just commented it because mixing `db.Model()` and `db.{Select,Update,Insert...}()` feels a little weird to me. But I understand it is a desing decision made long ago that can't be changed easily. Thanks for explaining it.
