### ISSUE TITLE
db.CreateTable is erroring with reflect: NumField of non-struct type 

### ISSUE THREAD

**Issue by jmheidly** [go-pg/pg#677]
my models table creation suddenly stopped working giving the following error:
what do you think could have gone wrong?

panic: reflect: NumField of non-struct type

goroutine 1 [running]:
reflect.(*rtype).NumField(0x47ede40, 0x0)
	/usr/local/go/src/reflect/type.go:1016 +0x5e
github.com/go-pg/pg/orm.newTable(0x4d24160, 0x47ede40, 0x4d24160)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:124 +0x26a
github.com/go-pg/pg/orm.(*Table).addFields(0xc420306270, 0x4d24160, 0x47fbc80, 0x0, 0x0, 0x0)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:194 +0x169
github.com/go-pg/pg/orm.newTable(0x4d24160, 0x47fbc80, 0x4d24160)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:129 +0x585
github.com/go-pg/pg/orm.(*Table).newField(0xc420085450, 0x477bef6, 0xe, 0x0, 0x0, 0x4d24160, 0x4729820, 0x477bf06, 0x4a, 0x1a0, ...)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:334 +0x110e
github.com/go-pg/pg/orm.(*Table).addFields(0xc420085450, 0x4d24160, 0x48496e0, 0x0, 0x0, 0x0)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:208 +0x4e7
github.com/go-pg/pg/orm.newTable(0x4d24160, 0x48496e0, 0x4d24160)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:129 +0x585
github.com/go-pg/pg/orm.(*Table).newField(0xc4200852b0, 0x4700199, 0x5, 0x0, 0x0, 0x4d24160, 0x47299a0, 0x47001a0, 0x1f, 0xc0, ...)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:334 +0x110e
github.com/go-pg/pg/orm.(*Table).addFields(0xc4200852b0, 0x4d24160, 0x4836b80, 0x0, 0x0, 0x0)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:208 +0x4e7
github.com/go-pg/pg/orm.newTable(0x4d24160, 0x4836b80, 0x4905100)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:129 +0x585
github.com/go-pg/pg/orm.(*Table).newField(0xc4200851e0, 0x4703cf3, 0x9, 0x0, 0x0, 0x4d24160, 0x4717300, 0x4703cfe, 0x20, 0x20, ...)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:382 +0xab4
github.com/go-pg/pg/orm.(*Table).addFields(0xc4200851e0, 0x4d24160, 0x48438c0, 0x0, 0x0, 0x0)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:208 +0x4e7
github.com/go-pg/pg/orm.newTable(0x4d24160, 0x48438c0, 0x4905100)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:129 +0x585
github.com/go-pg/pg/orm.(*Table).newField(0xc4200841a0, 0x46f5c76, 0x5, 0x0, 0x0, 0x4d24160, 0x48438c0, 0x46f5c7d, 0x15, 0xb0, ...)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:382 +0xab4
github.com/go-pg/pg/orm.(*Table).addFields(0xc4200841a0, 0x4d24160, 0x482b480, 0x0, 0x0, 0x0)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:208 +0x4e7
github.com/go-pg/pg/orm.newTable(0x4d24160, 0x482b480, 0xc4201a7a38)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/table.go:129 +0x585
github.com/go-pg/pg/orm.(*tables).Get(0xc420281be0, 0x4d24160, 0x482b480, 0x4d24160)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/tables.go:35 +0x12f
github.com/go-pg/pg/orm.newStructTableModelValue(0x482b480, 0xc4200938c0, 0x199, 0x4810260)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/model_table_struct.go:25 +0x67
github.com/go-pg/pg/orm.newTableModelValue(0x482b480, 0xc4200938c0, 0x199, 0x482b480, 0xc4200938c0, 0x199, 0x2a00201a7cb0)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/model_table.go:57 +0x13e
github.com/go-pg/pg/orm.newTableModel(0x476bd60, 0xc4200938c0, 0x15, 0xc4201a7ca8, 0x4012ef8, 0x180)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/model_table.go:51 +0x26c
github.com/go-pg/pg/orm.(*Query).Model(0xc420242600, 0xc42031a670, 0x1, 0x1, 0xc42031a670)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/query.go:114 +0x1a8
github.com/go-pg/pg/orm.NewQuery(0x4d20c60, 0xc4202a4eb0, 0xc42031a670, 0x1, 0x1, 0x4d95580)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/query.go:48 +0x7f
github.com/go-pg/pg/orm.CreateTable(0x4d20c60, 0xc4202a4eb0, 0x476bd60, 0xc4200938c0, 0xc4202e3500, 0x20, 0x47e58c0, 0x1, 0xc4202e3500)
	/Users/Hack/gocode/src/github.com/go-pg/pg/orm/create_table.go:16 +0x8a
github.com/go-pg/pg.(*DB).CreateTable(0xc4202a4eb0, 0x476bd60, 0xc4200938c0, 0xc4202e3500, 0x0, 0x0)
	/Users/Hack/gocode/src/github.com/go-pg/pg/db.go:363 +0x55

**Comment by vmihailenco** [comment]
Probably you are passing pointer to the pointer, not pointer to the struct.
