### ISSUE TITLE
Insert model with extra fields not in struct

### ISSUE THREAD

**Issue by RangelReale** [go-pg/pg#678]
Assuming this database tables

```
project (project_id int, name string)
playlist (playlist_id int, project_id int, name string)
```

In my REST api, the project_id come via a nested URL, so it is not returned in any query, and the "Playlist" struct doesn't have it.

```go
type Playlist struct {
    PlaylistId int
    Name string
}
```

When inserting this model, I want to set the project_id field manually, but calling ".Set" doesn't work. Is there any way to do this?

```go
ret := &Playlist{}
_, err = db.Model(&ret).
	Set("project_id = ?", project_id).
	Insert()
```

As I see ".Set" is already used for OnConflict, maybe creating a ".Values" method to do this?

**Comment by vmihailenco** [comment]
`Set` is only supported for UPDATE, because that is what SQL uses. For inserts use:

```
ret := &Playlist{}
_, err = db.Model(ret).
	Column("project_id").
	Insert()
```

**Comment by RangelReale** [comment]
This is not what I need, I need to set some internal fields that are not on the model, like "deleted", "modified" or "type", control fields that I don't want exposed to the end user.

**Comment by vmihailenco** [comment]
Just create new struct with your secret fields.

**Comment by RangelReale** [comment]
Yes I can do that, but the point is, why on Update I can set any field I want, even if it is not on the model, but on Insert I can't? I think it is a useful thing to have.

**Comment by vmihailenco** [comment]
Since what you are asking for is already possible by creating additional struct I prefer to not complicate API  and code with `Value` method. Especially because this is not a very popular/widely used feature.
