### ISSUE TITLE
Opening a connection with a URL

### ISSUE THREAD

**Issue by rodzzlessa24** [go-pg/pg#685]
What do you think about being able to open a connection using a url? This is primarily handy for setting up SSL connections. Currently having to create a tls config from scratch and pass that in seems very cumbersome even if only have to write that code one time per project. Perhaps allowing the url connection doesn't fix the root issue I'm having which is setting up SSL connections.

**Comment by vmihailenco** [comment]
See https://godoc.org/github.com/go-pg/pg#ParseURL, but it does not configure TLS for you.

**Comment by rodzzlessa24** [comment]
Would adding an automatic TLS config be a feature to consider? Or is there a specific reason why this is not a feature?

**Comment by vmihailenco** [comment]
Turns out there is some support for TLS - https://github.com/go-pg/pg/blob/master/options.go#L174-L187
