### ISSUE TITLE
Create foreign key constraints

### ISSUE THREAD

**Issue by julienkosinski** [go-pg/pg#694]
Hello,

So I'd like to use brand new foreign key creation handler but no constraints are created.
Let's see an example here.

I have "user_role has many users".

Strucs:
```
type User struct {
	ID            int
	UserRoleID    int
}

type UserRole struct {
	ID    int
	Users []*User
}
```

I am creating tables as follows:
```
models := []interface{}{&User{}, &UserRole{}}
	for _, model := range models {
		err := db.CreateTable(model, &orm.CreateTableOptions{
			FKConstraints: true,
		})
		if err != nil {
			return err
		}
	}
```

Result is does not create any foreign key constraints.

Thanks! :)

**Comment by vmihailenco** [comment]
Hi,

go-pg expects that your model defines has-one relation:

```
type User struct {
	ID         int
	UserRoleID int
	UserRole   *UserRole
}
```

and then it generates

```
CREATE TABLE IF NOT EXISTS "users" ("id" bigserial, "user_role_id" bigint, PRIMARY KEY ("id"), FOREIGN KEY ("user_role_id") REFERENCES "user_roles" ("id") ON DELETE CASCADE)
CREATE TABLE IF NOT EXISTS "user_roles" ("id" bigserial, PRIMARY KEY ("id"))
```

Which is less or more what I would expect in this case. What behavior do you expect?

PS Right now fk contraints are only defined for has one relation - see https://github.com/go-pg/pg/blob/master/orm/create_table.go#L104-L122
PPS Sorry for late response

**Comment by andrewdbase** [comment]
I can't seem to get this to work, using a very similar data model:

```
type User struct {
    Id             int
    UserTypeId     int
    UserType       *UserType
   ...
}

type UserType struct {
    Id     int
    Name   string
    Desc   string
}
```

No foreign key constraint gets created.  I've tried changing "Id" to "ID" thinking maybe it was a case-sensitivity issue.  No dice.  Any help would be greatly appreciated.
