### ISSUE TITLE
Choose the name/pattern of a foreign key

### ISSUE THREAD

**Issue by julienkosinski** [go-pg/pg#697]
Hello,

I have "user_role has many users".

As follows:
```
type User struct {
	ID            int
	UserRoleID    int
}

type UserRole struct {
	ID    int
	Users []*User
}
```

I need in `User` to have `UserRoleID` as foreign key because of the way it is parsed.
I'd like to define the name I want for this foreign key and describe in tag the relation.
Because of the case of HasManySelf we can define a name in the pattern `something + ID`.

I propose to add a new tag (to avoid changing API).

I could imagine something like that:
```
type User struct {
	ID            int
	IDUserRole    int
}

type UserRole struct {
	ID    int
	Users []*User `pg:",fk-custom:IDUserRole"`
}
```

(For this example, having also a global configuration setting would be the best, it could tell `ID` is before the name of the struct and not after.)

Thanks :)

**Comment by vmihailenco** [comment]
Did you try `pg:"fk:IDUserRole"`?
