### ISSUE TITLE
Invalid array syntax in WHERE

### ISSUE THREAD

**Issue by szechyjs** [go-pg/pg#699]
I have the following code:

```go
names := []string{"a", "b", "c", "d"}
.Where("n.name IN ?", names).Select(&ret)
```

Which results in the following in the sql query:

```sql
WHERE (n.name IN '["a","b","c","d"]')
```

This obviously is not correct syntax, I would expect it do to the following:

```sql
WHERE n.name IN ('a','b','c','d')
```

I also tried using:
```go
.Where("n.name IN ?", pg.Array(names)).Select(&ret)
```

and it resulted in the following invalid query as well.

```sql
WHERE (n.name IN '{"a","b","c","d"}')
```

**Comment by szechyjs** [comment]
I found the following solution, I'm not sure if its correct, but it works.

```go
.Where("n.name IN (?)", pg.In(names))
```

It would be nice if the IN functionality was documented in the Wiki.

**Comment by siteshen** [comment]
@szechyjs Yes, it's correct. Another solution is  using `WhereIn`:

> // WhereIn is a shortcut for Where and pg.In to work with IN operator:
> //
> //    WhereIn("id IN (?)", 1, 2, 3)


```go
names := []string{"a", "b"}
.WhereIn("name IN (?)", StringSliceToInterfaceSlice(names)...)
```

Note: `WhereIn` accept argument `interface{}...`, so you need to write a helper function `StringSliceToInterfaceSlice([]string) -> []interface{}`:

**Comment by vmihailenco** [comment]
Please use `WhereIn("n.name IN ?", "a", "b", "c", "d")` or `Where("n.name IN ?", pg.Where(slice))` if you already have a slice.
