### ISSUE TITLE
Issue with uuid

### ISSUE THREAD

**Issue by yashsriv** [go-pg/pg#700]
Hi,

I am trying to use UUID like this:
``` go
import 	uuid "github.com/satori/go.uuid"
type Test uuid.UUID
// Item represents an element in the db
type Item struct {
	Foo Test `sql:",pk,type:uuid"`
}
```

Somehow this causes something like:
```
panic: ERROR #22P02 invalid input syntax for type uuid: "\x430c94b1cf154e9fb692a8c9537f81d9" (addr="[::1]:5432")
```

I have tried implementing the `String` method for my `Test` type and still it doesn;t work.

I know that if I use just `uuid.UUID`, it will work but I can;t figure out why this isn't working. Even in the code, I see no hardcoding for uuid.

**Comment by vmihailenco** [comment]
go-pg uses following methods to marshal/unmarshal UUID:

```
Scan(src interface{}) error
Value() (driver.Value, error)
```

`type Test uuid.UUID` erases all the methods for the type.

**Comment by yashsriv** [comment]
Got it. Thanks a lot :smile:
