### ISSUE TITLE
Perform db.Select() FOR UPDATE

### ISSUE THREAD

**Issue by yashsriv** [go-pg/pg#703]
Hi,

I wanted to perform the equivalent of `db.Select() FOR UPDATE` where the `WHERE` clause for the select is autofilled with PKs. I ended up creating a wrapper function which used a lot of reflection to obtain PKs and automatically add them to the where clause. Is there a better way to do this?

**Comment by vmihailenco** [comment]
Hi,

Latest version should support `db.Model(...).WherePK().Select()` - please try it.
