### ISSUE TITLE
Error handling when try connect

### ISSUE THREAD

**Issue by oceanicdev** [go-pg/pg#710]
Hello! Thanks for an awesome package. I will use it for my new project. I have one question.
Is there is a way to handle the error when I try to connect to the database? I see it does not return any error. 
Example:
gorm:
```
db, err := gorm.Open("postgres", "postgres://postgres:@postgres/postgres")
if err != nil {
    log.Fatal(err)
}
```
go-pg
```
options, err := pg.ParseURL("postgres://postgres:@postgres/postgres")
if err != nil {
   log.Fatal(err)
}
db := pg.Connect(options)
```

**Comment by vmihailenco** [comment]
Try to execute some queries:

```
_, err := db.Exec("SELECT 1")
```

**Comment by oceanicdev** [comment]
@vmihailenco thanks!
