### ISSUE TITLE
Relation WhereOr somehow behave weirdly

### ISSUE THREAD

**Issue by badoet** [go-pg/pg#711]
i have simple has many relationships that look like this
```
type Order struct {
	TableName struct{} `sql:"orders"`
	ID                    eh.UUID
	Trips []*Trip
}
```
```
type Trip struct {
	TableName struct{} `sql:"trips"`
	ID                    eh.UUID    `sql:"id"`
	OrderID               eh.UUID    `sql:"order_id"`
	Order  *Order
}
```

and i tried to run this:
```
query := db.Model(&orders).
		Column("order.*", "Trips").
		Relation("Trips", func(q *orm.Query) (*orm.Query, error) {
			return q.
				Where("\"trip\".status=?", TRIP_CONTACTING_AGENT).
				WhereOr("\"trip\".status=?", TRIP_IN_BUNDLE), nil
		}).
		Where("\"order\".status = ?", ORDER_CONTACTING_AGENT)
```

and this will give me error like this:
`pg: can't find dst value for model id="aaaa-bbb-ccc," `

Upon inspection, i found that the error was due to the `Order` returned
includes those with other status (not ORDER_CONTACTING_AGENT)

the solution is to do something like this:
```
query := db.Model(&orders).
		Column("order.*", "Trips").
		Relation("Trips", func(q *orm.Query) (*orm.Query, error) {
			return q.WhereOr(
                                fmt.Sprintf("\"trip\".status='%s'", TRIP_CONTACTING_AGENT),
                                fmt.Sprintf("\"trip\".status='%s'", TRIP_IN_BUNDLE),
			), nil
		}).
		Where("\"order\".status = ?", ORDER_CONTACTING_AGENT)
```
any idea why, this is so?

**Comment by vmihailenco** [comment]
Just check generated query - it will look like `WHERE id IN (1, 2, 3) AND status = 1 OR status = 2`. You need `WHERE id IN (1, 2, 3) AND (status = 1 OR status = 2)`. You should use `status IN (1, 2)` or `WhereGroup` to wrap conditions in parentheses.
