### ISSUE TITLE
Soft deletion

### ISSUE THREAD

**Issue by willsr** [go-pg/pg#723]
Soft deletion was mentioned in #276. 
Paranoid queries would be a really useful addition. Wondering whether someone is already working on a pull request.

**Comment by siteshen** [comment]
IMO go-pg should not couple with specific field of client code, eg. deleted_at or is_deleted.

And it's easy to implement it in client code:
```go
type Base struct {
	DeletedAt *time.Time
}

func (b *Base) SoftDelete() {
	now := time.Now()
	b.DeletedAt = &now
}

func (b *Base) Undelete() {
	b.DeletedAt = nil
}

type User struct {
	Base
	ID       int
	Username string
}
```

**Comment by willsr** [comment]
![tenor](https://user-images.githubusercontent.com/1422761/35425041-ddd1bc46-02a7-11e8-9f20-35b62381ebf4.gif)

**Comment by Fyb3roptik** [comment]
I actually built this into my wrapper for pg-go since GORM had this. Put this into your model.go and just call it for deleting

```golang
func Delete(m Model, id int64) error {
	Read(m, id)
	deleted_at := time.Now()
	_, err := dbwrapper.DB().Model(m).Set("deleted_at = ?", deleted_at).Where("id = ?", id).Update(&deleted_at)
	return err
}
```

**Comment by Fyb3roptik** [comment]
Also I should mention GORM checks to see if you have a deleted_at column. If not then it does a hard delete. So we could have both here.

**Comment by vmihailenco** [comment]
https://godoc.org/github.com/go-pg/pg#example-DB-Model-SoftDelete
