### ISSUE TITLE
error with false boolean

### ISSUE THREAD

**Issue by xperiafan13-rom** [go-pg/pg#727]
I try to insert a false value but this take a value with DEFAULT, with true all is ok
`PhysicalLocation            bool                      `json:"physical_location,omitempty"``
```
if err := dao.db.Insert(&configuration); err != nil {
		return "", database.BaseErrors(err.Error())
	}
```
Response sql:
'1', 1, 1, DEFAULT, TRUE, 'ctl'
with true all is ok, but with false ...

**Comment by vmihailenco** [comment]
For future references - use `sql:",notnull"` tag
