### ISSUE TITLE
Support Connecting using URI parameters: host=,user=,password=

### ISSUE THREAD

**Issue by danielbprice** [go-pg/pg#730]
It's very convenient to be able to pass the entire connection parameter set as a single URI; it allows me to store the connection information to the database (including the password) as a secret and just pass it through to from the frontend of my application to the database part.   I can also target my application at a hostname, or through a proxy, without having to modify the application code itself.

I found similar code in `pq`: https://github.com/lib/pq/blob/master/url.go

In my example, I want to use a string like this:
```
connStr := "postgres:///mydatabase?host=/var/tmp/cloud-sql-sock/foo-bar-baz:us-west1:scratch0&user=postgres&password=12345"
```

I can use this with the `psql` command.

With go-pg this seems to result in:
```
pg: options other than 'sslmode' are not supported
```

Apologies if I'm _Doing It Wrong_ but I didn't see a way to get this to work as I had hoped.

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/blob/master/options_test.go#L20-L135 for example how to set username & password.

**Comment by danielbprice** [comment]
For me the issue is two-fold: One is that it seems convenient-- and expected-- that this tool would accept the same `postgres:` scheme URLs as the official tools, creating interoperability. 
 Two is that, with `pqsl`, `host=` allows me to specify either a hostname, or a unix domain socket.  When working with Google Cloud Postgres I have occasion to use both.

Would you accept a patch which adds this functionality?

I can write my own wrapper for now.

**Comment by vmihailenco** [comment]
Yes, such patch would be appreciated, but please add some comments explaining what format you are trying to support. Thanks in advance.

**Comment by dhax** [comment]
Any progress on this? For unix socket connection this format would be handy:
postgresql:///dbname?host=/var/run/postgresql
