### ISSUE TITLE
bug: reflect.Value.IsNil

### ISSUE THREAD

**Issue by superwy** [go-pg/pg#732]
use 'override' will be  crash

goroutine 1 [running]:
reflect.Value.IsNil(0x12b9740, 0xc4203bc360, 0x199, 0x0)
        /usr/local/Cellar/go/1.9.1/libexec/src/reflect/value.go:995 +0x12e
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.visitField(0x12b9740, 0xc4203bc360, 0x199, 0xc42026b000, 0x2, 0x4, 0xc42004d9d8)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/util.go:89 +0xb1
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.walk(0x12a8d00, 0xc4203bc360, 0x199, 0xc42026b000, 0x2, 0x4, 0xc42004d9d8)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/util.go:81 +0x189
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.dstValues(0x1438460, 0xc4202430e0, 0xc42000e928, 0x1, 0x1, 0x100622b)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/util.go:126 +0x1af
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.newM2MModel(0xc4200e3f90, 0xc42004db18)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/model_table_m2m.go:23 +0xa2
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.(*join).m2mQuery(0xc4200e3f90, 0x1437600, 0xc4200e3ea0, 0xc42010cbc0, 0x1, 0x1)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/join.go:89 +0x43
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.(*join).selectM2M(0xc4200e3f90, 0x1437600, 0xc4200e3ea0, 0xc42012c960, 0xc42004dd28)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/join.go:78 +0x43
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.(*join).Select(0xc4200e3f90, 0x1437600, 0xc4200e3ea0, 0xc42012c940, 0xc42010cbc0)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/join.go:23 +0x56
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.(*Query).selectJoins(0xc420209200, 0xc4200e3f90, 0x1, 0x1, 0x12d2000, 0xc42011f280)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/query.go:571 +0xcd
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.(*Query).selectJoins(0xc420209200, 0xc4200e3f40, 0x1, 0x1, 0xc42012c940, 0x14347c0)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/query.go:569 +0x85
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.(*Query).Select(0xc420209200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/query.go:485 +0x1d7
github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm.(*Query).First(0xc420209200, 0x12df0b6, 0xf)
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/vendor/github.com/go-pg/pg/orm/query.go:449 +0x200
main.main()
        /Users/Yang/Documents/GoWorkSpace/src/github.com/superwy/pg_demo/main.go:74 +0x470

simple program:
https://github.com/superwy/pg_demo

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed in master.
