### ISSUE TITLE
Updating some columns with a model fails for JSONB columns?

### ISSUE THREAD

**Issue by ivoras** [go-pg/pg#735]
Hello,

I have a model which contains these fields:

```
	TableName  struct{}          `sql:"user,alias:users" json:"-"`
	ID         int               `sql:"id" json:"id"`
	Password   string            `sql:"password" json:"password"`
	Email      string            `sql:"email" json:"email"`
	PermLevel  int               `sql:"perm_level" json:"perm_level"`
	Metadata   map[string]string `sql:"metadata" json:"metadata"`
```

In the database, the "metadata" field is defined as `JSONB NOT NULL`, and when I try to update the record like this:

```
_, err = db.Model(&uu).Column("email", "password", "metadata").Update()
```

I get the error "ERROR #23502 null value in column "metadata" violates not-null constraint".

uu.Metadata is an empty `map[string]string`, it is definitely not nil.

It works OK when I do it with a SQL query:

```
, err = db.Exec("UPDATE \"user\" SET email=?, password=?, metadata=? WHERE id=?", uu.Email, uu.Password, uu.Metadata, uu.ID)
```

Does go-pg modify empty maps in model instances to be null? Or is something else going on?

**Comment by vmihailenco** [comment]
Yes, go-pg treats zero values (such as empty string, 0, or empty map) as `NULL`. To revert that behavior you should add `sql:",notnull"` tag. It is also mentioned in the readme:

```
All struct fields are nullable by default and zero values (empty string, 0, zero time) are marshalled as SQL NULL. sql:",notnull" tag is used to reverse this behaviour.
```
