### ISSUE TITLE
Unable to use unnest(ARRAY[...])

### ISSUE THREAD

**Issue by mykolasmith** [go-pg/pg#736]
Hi, I've tried several combinations of the following. Per the "Array" example, I am doing the following:

```
uuids := []string{"fa546511-ab80-4b80-9c2b-3253e52d1037"}
var result []Result
stmt := `
SELECT * FROM t1
INNER JOIN unnest(?) as y
ON (t1.x = y::uuid)
`
_, err := db.Query(&result, stmt, pg.Array(uuids))
```

This assumes t1.x is a uuid column type.
Throws the following error:

`ERROR #42725 function unnest(unknown) is not unique`

**Comment by vmihailenco** [comment]
Looks like all you need is to add cast `unnest(?::uuid[])`.

To optimize code a bit you can use:

```
uuids := pg.Strings{"fa546511-ab80-4b80-9c2b-3253e52d1037"}
var result []Result
stmt := `
SELECT * FROM t1
INNER JOIN unnest(array[?]) as y
ON (t1.x = y::uuid)
`
_, err := db.Query(&result, stmt, uuids)
```

Query can be further simplified to:

```
SELECT * FROM t1, unnest(array[?]) as y
WHERE (t1.x = y::uuid)
```
