### ISSUE TITLE
Multiple HasOne relationships

### ISSUE THREAD

**Issue by Fyb3roptik** [go-pg/pg#737]
I have a struct that has multiple has one relationships. I would like to pull all of this data at once. Currently doing 
```
Column("user.*", "Account") 
```
works fine, but this does not 
```
Column("user.*", "Account", "Address") 
```

**Comment by Fyb3roptik** [comment]
Figured it out.

```
Column("user.*", "Account").Column("user.*", "Address")
````

**Comment by vmihailenco** [comment]
`Column("user.*", "Account").Column("user.*", "Address")` is the same as `Column("user.*", "Account", "Address")` so not sure what happens here.

**Comment by Fyb3roptik** [comment]
It was not working that way. I could only get it working by doing what I wrote above. Might be worth looking into!
