### ISSUE TITLE
Skipping fields in a model?

### ISSUE THREAD

**Issue by ivoras** [go-pg/pg#738]
Hello,

As it's possible to hide the "TableName struct{}" field from JSON by adding a `json:"-"` tag to it, is it also possible to hide a field from pg by adding a similar tag?

In other words, how to handle the case where there are "extra" fields in a struct that are not present in the table, but are e.g. calculated externally, and the same struct is being used for JSON and the DB model?

**Comment by vmihailenco** [comment]
You can use `tableName struct{}` which is unexported so it is hidden by default. `sql:"-"` can be used to skip other fields.

**Comment by ivoras** [comment]
Hi,

Thank you for your answer, I appreciate it! Let me clarify my question: the goal is to make the field VISIBLE TO JSON (so it must be exported) but INVISIBLE TO PG.

The other direction, as you've said, can be done by adding a json:"-" tag, but is there a pg:"-" tag or sql:"-" tag?
