### ISSUE TITLE
Cant fin colum

### ISSUE THREAD

**Issue by xperiafan13-rom** [go-pg/pg#741]
Hi, i use this query (this is a part of complete query) to get all rows
"SELECT commerce.all, address.all FROM commerce INNER JOIN address ON commerce.id_fiscal_address = address.id_address"

But i have the follow error pg: can't find column=id_address in model=Commerce

Can you help me with this?

**Comment by vmihailenco** [comment]
go-pg tries to load data into struct field `Commerce.IdAddress`, but can not find such field. You either have to create such field or use `sql:"id_address"` to manually specify field name. See https://github.com/go-pg/pg/wiki/Model-Definition on how to defined models.
