### ISSUE TITLE
Select Shortcut

### ISSUE THREAD

**Issue by Fyb3roptik** [go-pg/pg#742]
Let me start by saying this repo is a godsend!!!
I would like to make a feature request for a shortcut for Selects. Here is a before/after example

```golang
dbwrapper.DB().Model(&tiers).Select()
```
```golang
dbwrapper.DB().Select(&tiers)
```

Possibly the same for Insert/Update

```golang
dbwrapper.DB().Model(&tiers).Update()
```
```golang
dbwrapper.DB().Update(&tiers)
```

**Comment by vmihailenco** [comment]
There is already `db.Insert` and `db.Update`. There is no `dbwrapper.DB().Select(&tiers)`, because selecting all rows from the table is a bug in most cases - you need at least some order and limit.

**Comment by Fyb3roptik** [comment]
What I mean is assigning the model via &tiers. Instead of having to add Model(&tiers) it does the Select, Update, etc based on the interface put in.

**Comment by vmihailenco** [comment]
If you suggest something like this:

```
q := db.Model().Where("id = 1")
q.Select(&article) // selects from articles table
q.Select(&category) // selects froms categories
```

then it was considered at some point, but it is rarely useful and requires too many changes in the code and backwards incompatible API changes.

**Comment by Fyb3roptik** [comment]
Ok cool, no worries was just thinking it might be a nice to have. I love this ORM!
