### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by Fyb3roptik** [go-pg/pg#748]
Trying to use this a forked repo of this on Revel framework. I am getting these errors on build:

```
imports github.com/go-pg/pg/internal: use of internal package not allowed
imports github.com/go-pg/pg/internal/pool: use of internal package not allowed
```

**Comment by vmihailenco** [comment]
Do you use gopkg.in? If so it is not supported any more and you have to import `github.com/go-pg/pg`

**Comment by ekalinin** [comment]
If you use `dep` then you need to add a `source` option into `constraint` section of the `Gopkg.toml`.

Example:
```
[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.7.1"
  source = "https://github.com/your-fork/pg"
```

**Comment by Fyb3roptik** [comment]
No I am using none of these. I tried doing go get package. I am attempting to develop locally on my machine for go-pg and cannot even do that!

**Comment by vmihailenco** [comment]
`go get -u github.com/go-pg/pg` works - otherwise people would complain more actively. The problem with this issue is that it does not provide any details so the best thing we can do is to guess which is a waste of time for everyone

**Comment by Fyb3roptik** [comment]
I am attempting to update this repo locally with a feature I would like to add myself. I am unable to run this locally for development. How do you get it working locally!

**Comment by vmihailenco** [comment]
You have update imports like https://github.com/go-pg/pg/blob/master/db.go#L9-L11 to use your fork.
