### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by Fyb3roptik** [go-pg/pg#751]
Step 1: Fork repo
Step 2: Clone it locally. Rename main import of 
```
github.com/go-pg/pg
```
to
```
local_folder/pg
```
Step 3: Try to run it

You will get the error
```
imports github.com/go-pg/pg/internal: use of internal package not allowed
imports github.com/go-pg/pg/internal/pool: use of internal package not allowed
```

**Comment by vmihailenco** [comment]
That is how Go works. You can start with https://golang.org/doc/code.html#ImportPaths and https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit

The right solution is to clone repository into $GOPATH/src/github.com/go-pg/pg and do not rename anything.

**Comment by Fyb3roptik** [comment]
AH! Ok thanks!
