### ISSUE TITLE
Fetching Column data from within a Relation method

### ISSUE THREAD

**Issue by Fyb3roptik** [go-pg/pg#752]
Below is the sample code. When doing the Select, it selects and joins the TierSetting Data, but not Tier inside of TierSetting. How can I get it to also join the Tier data inside of TierSetting in the same query?

Currently I am doing a Select on a model for Contest which has TierSetting in it as a has many relationship

```golang
type Tier struct {
  BaseModel
  Name            string        `sql:"name" json:"name"`
}

type TierSetting struct {
  BaseModel
  ContestId             int64         `sql:"contest_id" json:"contest_id"`
  Rules                 string        `sql:"rules" json:"rules"`
  TierId                int64         `sql:"tier_id" json:"tier_id" pg:",fk:Tier"`
  Tier                  *Tier          `sql:"-" json:"tier,omitempty"`
  Parameters             string    `sql:"parameters" json:"parameters"`
}

if err :=DB().Model(&c).
	Column("contest.*", "App", "TierSettings").
  Relation("TierSettings", func(q *orm.Query) (*orm.Query, error) {
      return q, nil
  }).
	Where("\"contest\".id = ?", id).Select(); err != nil {
		log.Println("db read error, ", err.Error())
		return contest, errors.New("Record not found")
	}
```

**Comment by vmihailenco** [comment]
Your example is incomplete - `TierSettings` is not defined anywhere. Overall there is https://godoc.org/github.com/go-pg/pg#example-DB-Model-HasMany that shows how to use has many.

**Comment by Fyb3roptik** [comment]
Dude I explained it. Here is the contest model. Please dont just close the ticket without letting me respond! Here is the main Struct that references TierSetting. The issue is I have a HasOne that has a HasOne. The 2nd HasOne (Tier) is null, so it isnt grabbing that data

```golang
type Contest struct {
	BaseModel
	Name                   string    `sql:"name" json:"name"`
	StartDate              time.Time `sql:"start_date" json:"start_date"`
	EndDate                time.Time `sql:"end_date" json:"end_date"`TierSettings					 
        TierSettings		[]*TierSetting		`sql:"-" json:"tier_settings"`
```
