### ISSUE TITLE
HasMany not fetching HasOne data inside of the HasMany

### ISSUE THREAD

**Issue by Fyb3roptik** [go-pg/pg#756]
```golang
type Contest struct {
	BaseModel
	Name                   string    `sql:"name" json:"name"`
	StartDate              time.Time `sql:"start_date" json:"start_date"`
	EndDate                time.Time `sql:"end_date" json:"end_date"`
        TierSettings	      []*TierSetting		`sql:"-" json:"tier_settings"`
}

type Tier struct {
  BaseModel
  Name            string        `sql:"name" json:"name"`
}

type TierSetting struct {
  BaseModel
  ContestId             int64         `sql:"contest_id" json:"contest_id"`
  Rules                 string        `sql:"rules" json:"rules"`
  TierId                int64         `sql:"tier_id" json:"tier_id" pg:",fk:Tier"`
  Tier                  *Tier          `sql:"-" json:"tier,omitempty"`
  Parameters             string    `sql:"parameters" json:"parameters"`
}

contest := &Contest{}
contest, _ = contest.Read(contest.Id)
```

In this example, if I do a Read on Contest, it does fetch TierSettings with the HAsMany relationship, but inside of TierSetting, Tier is null. It is not also fetching the HasOne data inside of the HasMany. How can I resolve this without having to run loops?

**Comment by Fyb3roptik** [comment]
For now I have added the calls to retrieve that info inside of the AfterSelect hook. It is working fine, but would like to see if it is a bug or even possible to have it grab the data on initial select

**Comment by yiiTT** [comment]
@Fyb3roptik Looks like you can do .Column("contest.*", "TierSettings", "TierSettings.Tier")

**Comment by yiiTT** [comment]
@Fyb3roptik Looks like you can do .Column("contest.*", "TierSettings", "TierSettings.Tier") 
I found in issue from 2016 #280 which described and fixed this issue.

**Comment by Fyb3roptik** [comment]
Not all heroes wear capes! THANKS!!!

**Comment by Fyb3roptik** [comment]
@yiiTT This is now broken as of v6.8.1

**Comment by pluralism** [comment]
@Fyb3roptik I'm also experiencing this problem. Have you found a way to solve it without using raw SQL?

**Comment by Fyb3roptik** [comment]
For now using AfterSelect hook in the model seems to be working

**Comment by Fyb3roptik** [comment]
Why was this closed??? This is not fixed!

**Comment by macnibblet** [comment]
Uhm, I second that question still having this problem with the latest master

**Comment by macnibblet** [comment]
My bad it actually looks like it's working 👍
