### ISSUE TITLE
relation column naming

### ISSUE THREAD

**Issue by yiiTT** [go-pg/pg#763]
It's really restricting to have to follow the pre-defined PK/FK names when using relations and other relation fields. So it's possible to name my File struct as Files while still naming my FK FileId/file_id in other structs and does this also expand to the fields of a struct?

(Using a different defined FK field/column rather than the 'default' one or renaming the field to something totally different while still defining what the column should be IE: Post field FileId -> FilesId)
```
type File struct {
	tableName   struct{}        `sql:"files,alias:file"`
	Id          int             `sql:"file_id,pk"`
	Posts       []*Post  `sql:"-"`
}

type Post struct {
	tableName     struct{}  `sql:"posts,alias:post"`
	Id            int       `sql:"post_id,pk"`
	FileId        int       `sql:"file_id"`

	ExpectedMD5 string   `sql:"-"`
	File        *File    `sql:"-"`
}
```

**Comment by vmihailenco** [comment]
I am not able to understand what exactly you are trying to achieve. But you can specify foreign key name using fk tag, .e.g. Posts []*Post `pg:"fk:files_id"`. See https://godoc.org/github.com/go-pg/pg#example-DB-Model-HasManySelf for example.

**Comment by yiiTT** [comment]
Oh that makes sense, I wish the documentation would list that the field or column would be interchangeable among other things.
It's been great using the package so far, however sadly like most ORMs it lacks detailed documentation.
