### ISSUE TITLE
uint64 ID doesn't create proper pk and sequence

### ISSUE THREAD

**Issue by dalu** [go-pg/pg#765]
Man you're really making this hard for someone to like postgresql (for someone used to MongoDB and the excellent mgo driver).

I have a
```go
type Word struct {
	Id      uint64 `json:"id" sql:"id,pk"`
	Content string `json:"content"`
}
```
Yes uint64 because why would I have a negative number there?
And yes I also tried without any sql tags and with `sql:",notnull"`.

Even in MySQL you have various "ORM"s that get the autoincrement index right.

But postgresql and especially this one?

In another issue I can't find right now you say that `sql:"id,pk"` isn't necessary and that `Id int64` is enough.
Apparently not.

The frontend is an Angular (not .js) "app" that creates an instance of the `Word`.
```typescript
class Word {
id: number;
content: string;
}
let newWord = new Word();
//later
newWord.content = "test";
```
and submit that to Go, which de-serializes that JSON into a Go struct from above.
And then 
`Error #01: ERROR #23502 null value in column "id" violates not-null constraint (addr="[::1]:5432")`

I also explicitly try to set Id to 0.

What do I have to do in order to have the correct data type created and not have this error?
The answer is "change to int64". But that doesn't make sense. Why have a negative sequence number?

uint64 type should create the same bigint + sequence type

**Comment by vmihailenco** [comment]
>Why have a negative sequence number?

uint64 does not fit into bigint. There is no uint64 type in PostgreSQL.

As for the rest please create a Go program that
- reproduces the problem
- is reasonably small
