### ISSUE TITLE
ManyToMany Join FK issue

### ISSUE THREAD

**Issue by yiiTT** [go-pg/pg#766]
I'm having an issue where the fk and joinFK are using the incorrect column names. It just prepends whatever the fk value is. I have already checked a lot of different issues and the ManyToMany documentation (According to the docs I should be using "many2many:post_tag_mappings,fk:post,joinFK:tag", I have also tried to use Post and Tag).

What I would like it to do would be `JOIN post_tag_mappings AS post_tag_mappings ON (post_tag_mappings."post_id") IN ((1)) WHERE (tag."tag_id" = post_tag_mappings."tag_id")`
where it joins post_tag_mappings using "post_id" and "tag_id" 

If no fk or joinFK are used, it uses post_post_id and tag_tag_id. Where as a blank uses _post_id and _tag_id But no matter what I change the fk to it will always be fk+_post_id or joinfk+_tag_id. **I just want post_id and tag_id**.

```
type Post struct {
	tableName     struct{}  `sql:"posts,alias:post"`
	Id            int       `sql:"post_id,pk"`
	Tags          []*Tag  `pg:"many2many:post_tag_mappings"`

}

type Tag struct {
	tableName       struct{} `sql:"tags,alias:tag"`
	Id              int      `sql:"tag_id,pk"`
}

type PostTagMapping struct { // Attempted with and without this struct
	tableName struct{} `sql:"post_tag_mappings,alias:ptm"`
	PostId    int	`sql:"post_id"`
	TagId     int	`sql:"tag_id"`
}
```

```
SELECT "post".* FROM posts AS post WHERE (post_id = 1)
SELECT post_tag_mappings.*, tag."tag_id",FROM tags AS tag 
    JOIN post_tag_mappings AS post_tag_mappings ON (post_tag_mappings."post_post_id") IN ((1)) WHERE (tag."tag_id" = post_tag_mappings."tag_tag_id")

```

**Comment by vmihailenco** [comment]
The difference here from has one & has many is that go-pg does not have access to `PostTagMapping` model (it simply does not know that such model exists) and therefore can't check which columns really exist and use sql tags you define on `PostTagMapping`.

I've released v6.9.0 which should fix your code and also use `fk` and `joinFK` if the are specified:
- as field name if there is single primary key defined on the model
- as prefix if there are several primary keys
