### ISSUE TITLE
HasManySelf Issue

### ISSUE THREAD

**Issue by yiiTT** [go-pg/pg#768]
I'm trying to use the [HasManySelf](https://godoc.org/github.com/go-pg/pg#ex-DB-Model-HasManySelf), and every time it uses the post_id value instead of file_id. The goal is to get all posts that have the same FileId.
I have already tried to use the fk as File, file, FileId, file_, File_ and file_id with no success getting the IN to contain 977.

```
type Post struct {
	tableName     struct{}  `sql:"posts,alias:post"`
	Id            int       `sql:"post_id,pk"`
	FileId        int       `sql:"file_id"`
	SameFilePosts []Post    `pg:",fk:file_"`
}

DB.Model(post).Column("post.*","SameFilePosts").Where("post_id = ?", 55).Select()
SELECT post.*  FROM posts AS post WHERE (post_Id = 55)   (Id:55,FileId:977)
SELECT post."post_id", post."file_id", FROM posts AS post WHERE ((post."file_id") IN ((55)))
```

(Thank You and Sorry for the mass of issues I keep on submitting)

**Comment by vmihailenco** [comment]
This is not a has many any more. Just a query that selects some rows using some field. Try to replace `pg:",fk:file_"`  with `pg:"fk:file_id,fk_value:file_id"`.

**Comment by yiiTT** [comment]
Looks like it inputted the correct fk and fk_value, but "Failed to get post ID pg: relation="SameFilePosts" has no base model="Post" with id="5" (check join conditions)"

**Comment by yiiTT** [comment]
@vmihailenco Looks like it inputted the correct fk and fk_value, but "Failed to get post ID pg: relation="SameFilePosts" has no base model="Post" with id="5" (check join conditions)"

**Comment by vmihailenco** [comment]
Please try v6.9.2. If it still does not work please post a program that I can run to reproduce the issue.

**Comment by yiiTT** [comment]
Looks like v6.9.2 fixed the issue

**Comment by yiiTT** [comment]
Looks like v6.9.2 fixed the issue. 

(if you read this issue again) Is currently the best way to load sub-relations by using the AfterSelect hook like in #756 ?
