### ISSUE TITLE
Custom DB types

### ISSUE THREAD

**Issue by hummerd** [go-pg/pg#779]
Can we handle custom DB types?
```sql
CREATE TYPE book AS(
  title text,
  author varchar(300) 
);
CREATE TABLE user (
  id serial,
  books book[]
);
```
May be by writing custom appender, scanner?

**Comment by vmihailenco** [comment]
Yes, custom scanner and custom appender should definitely work. See https://github.com/go-pg/pg/blob/master/types/hstore.go#L43-L52

I don't have any experience with custom Postgres types. Can you please provide an example of insert query into user table?

**Comment by hummerd** [comment]
Hi!
It should look like this
INSERT INTO user(books)
VALUES(ARRAY[ROW(1, 'title1'),ROW(2, 'title2')]::book[]);

**Comment by vmihailenco** [comment]
Thanks. After inserting Postgres returns data in following format:

```
postgres=# select * from "user";
 id |            books            
----+-----------------------------
  1 | {"(1,title1)","(2,title2)"}
```

So it looks like go-pg would need appender and scanner that is able to produce `ARRAY[ROW(1, 'title1'), ROW(2, 'title2')]::book[]` and consume `{"(1,title1)","(2,title2)"}`. That is definitely possible, but if feels like re-inventing JSONB which is already supported. Are there any good reasons not to use JSONB here except supporting some legacy code?

**Comment by hummerd** [comment]
I think array must be more efficient than json (not sure how much) because DB do not need to parse json. And also array is strongly typed.
Actually I use jsonb for now)

**Comment by tpoxa** [comment]
I am not able to change the existing database structure. And I already using go-pg. And we do have custom types like above. Is there any idea how to solve that with pg?

**Comment by vmihailenco** [comment]
There is an example how to write custom scanner in https://github.com/go-pg/pg/blob/v10/example_custom_test.go . You will have to write a parser yourself though.

**Comment by tpoxa** [comment]
@vmihailenco Thank you. Is the 10th version is a must? I am still using the 9th.

**Comment by vmihailenco** [comment]
It is not, but only the last version receives updates / bug fixes.

**Comment by tpoxa** [comment]
@vmihailenco thank you, I will try it now. Should it also work as params for `QueryOne` or its only for ORM?
Why am I asking because  I need to call Postgres function with custom types as input parameters.

**Comment by vmihailenco** [comment]
It should work with QueryOne.

**Comment by tpoxa** [comment]
Yes, it is. @vmihailenco sorry to be annoying. But what is the best way to cook complex types which consist of simpler type?
Like if we have a book having an array of custom types of Articles.

For example. What should I call in AppendValue to cause sub type's AppendValue during insert?

Thanks in advance.

**Comment by vmihailenco** [comment]
It is hard without trying, but AFAIK Postgres array is always serialized as one big type. There are no subtypes. You can check how normal/standard arrays are serialized - https://github.com/go-pg/pg/blob/v10/types/array_append.go#L111-L137
