### ISSUE TITLE
Lib pq fallback

### ISSUE THREAD

**Issue by sanjaypsmc** [go-pg/pg#781]
Is there any way to fall back to the standard Go `sql` package using `pq`?

It appears that `go-pg` is making use of pq, but I don't see an obvious way to scan through instances of `sql.Row`. I have a use case that requires a generic `SELECT * ....` (no model) for a variable number of returned rows and unknown number/type of columns.

Is there any easy to to do this in `go-pg`? I'd rather avoid starting a separate connection with `pq`, which seems a little ridiculous. Alternatively, a way to achieve the equivalent with `go-pg` would be great.

**Comment by vmihailenco** [comment]
go-pg does not use lib/pq. It implements PostgreSQL protocol to avoid double copy between Postgres -> database/sql -> lib/pq -> go-pg.

`db.QueryOne(pg.Scan(&var1, &var2, &var3), `SELECT col1, col2, col3 FROM my_table LIMIT 1`)` can be used to scan known number of columns. If you want to scan unlimited number of columns you will have to implement custom scanner - see [example](https://github.com/go-pg/pg/blob/master/pg.go#L85-L108). It probably should be simpler, but so far you are the first person who needs this.

**Comment by mhadam** [comment]
I find myself needing the ability to scan an unknown amount of columns. I just need to print the response from a select statement, essentially. I'll attempt to make a custom scanner but I'm not too clear on how to do that.

**Comment by vmihailenco** [comment]
Can you show database/sql code you write in such case?

**Comment by mhadam** [comment]
The code is user created SQL files containing PL/pgSQL, so it's basically arbitrary.

**Comment by mhadam** [comment]
I copied the Strings scanner, and it seems to work:
```golang
type Results []string

var _ orm.HooklessModel = (*Results)(nil)
var _ types.ValueAppender = (*Results)(nil)

func (results *Results) Init() error {
	if s := *results; len(s) > 0 {
		*results = s[:0]
	}
	return nil
}

func (results *Results) NewModel() orm.ColumnScanner {
	return results
}

func (Results) AddModel(_ orm.ColumnScanner) error {
	return nil
}

func (results *Results) ScanColumn(colIdx int, _ string, b []byte) error {
	log.Println("result is", string(b))
	*results = append(*results, string(b))
	return nil
}

func (results Results) AppendValue(dst []byte, quote int) []byte {
	if len(results) <= 0 {
		return dst
	}

	for _, s := range results {
		dst = types.AppendString(dst, s, 1)
		dst = append(dst, ',')
	}
	dst = dst[:len(dst)-1]
	return dst
}
```

**Comment by mhadam** [comment]
@vmihailenco Another related question: is there any way to get column names from results? It'd be useful if there were something like this function from `database/sql`:
https://golang.org/pkg/database/sql/#Rows.Columns

**Comment by vmihailenco** [comment]
Name is available in `ScanColumn(colIdx int, colName string, b []byte)` as 2nd argument.
