### ISSUE TITLE
How to get joined table name or alias?

### ISSUE THREAD

**Issue by kpeu3i** [go-pg/pg#786]
I want to filter `user` table by the fields (`Relation.Field_1`, `Relation.Subrelation.Field_2`)  from joined tables, for example:

```
var users []User

err := db.Model(&users).
    Column("user.*", "Relation", "Relation.Subrelation").
    Where("Relation.Field_1 > 100")    
    Where("Relation.Subrelation.Field_2 > 200")
    Select()
```

Is it possible?

**Comment by vmihailenco** [comment]
You have to do it manually - there is no help from ORM. You will need to look at generated SQL to get joined table alias and use it in WHERE clause, e.g. `Where("relation_alias.field_1 > 100")`. For has many and many to many relations you will need to use `Relation` API to change has-many query, e.g.

```
var user User
err := db.Model(&user).
    Column("user.*", "Profiles").
    Relation("Profiles", func(q *orm.Query) (*orm.Query, error) {
        return q.Where("active IS TRUE"), nil
    }).
    First()
```

**Comment by kpeu3i** [comment]
It would be nice to have an ability to specify the table alias:

```
var users []User

err := db.Model(&users).
    Column("user.*", "Relation AS r1", "Relation.Subrelation AS r2").
    Where("r1.field_1 > 100")    
    Where("r2.field_2 > 200")
    Select()
```
Thanks for your response in any case!

**Comment by vmihailenco** [comment]
While this looks nice and simple in theory in reality it requires too many changes to be implemented. Closing.
