### ISSUE TITLE
Using query builder with Query/QueryOne

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#788]
Instead of writing plain SQL, is there a way to use the query builder (.Where(), .Columns()) with Query/QueryOne?

Now, I'm using select and have to check whether the result is empty or not.

**Comment by vmihailenco** [comment]
`Model(&Struct{})` uses `QueryOne`, `Model(&[]Struct{}{})` use `Query`. That works fine in most cases and you can `check whether the result is empty or not` in corner cases.
