### ISSUE TITLE
Struct Tags for Foreign Keys not working as expected

### ISSUE THREAD

**Issue by pixelskull** [go-pg/pg#792]
Have recently some trouble working with the pg-module related to the struct tags used for describing the foreign key. 

My situations is as follows, our database scheme is using the convention fk_<tablename> for foreignkeys. The default used in pg is  <tablename>_pk. While trying to modify this foreign key name I had a hard time finding the Tags needed. 

Following some example: 
- Without using any tags related to foreign keys the rowname in sql is "userprofile_pk_userprofile"
- using the "fk" tag (value is "foobar") the result is "foobar_pk_userprofile"
- using the "joinFK" tag (value is "barfoo") the result is "barfoo_pk_group" – related to an other column

In the end i found the "pg" tags that can be used to change the prefix and suffix (with "fk" and "joinFK"). From my understanding this tags should be named differently. When you can define "joinFk"  I would assume an override of the whole row name, not only some part. Also I would assume that you can change prefix and suffix independently - as is only the naming is misleading. 

Is this behaviour intended or am I missing something? What is the preferred way to change the foreign key name? Also is there any documentation related to this tag system? 

Greetings and Thanks for your effort.

**Comment by vmihailenco** [comment]
Hi,

I will try to write more docs on this topic, but https://github.com/go-pg/pg/wiki is open for editing so please participate.

Overall from v6.9 `fk` and `joinFK` try to accept whatever you feed them, e.g. for `fk:foo_bar` it tries `foo_bar` as fully qualified column name and as column prefix. It also supports "old" syntax `fk:Foo`. Can it be that you are using older version? If not provide a program that reproduces the problem.

Is there a better description of the convention you are using? If it is widespread I could try to support it in go-pg out of the box.

**Comment by vmihailenco** [comment]
PS https://github.com/go-pg/pg/pull/793 shows that `fk` allows specifying column name.

**Comment by pixelskull** [comment]
Thanks for the fast reply, was using 6.8 and 6.9 so updating dependencies... and it is working as you said and as expected. So sorry for that.

Concerning the convention, don't remember the name for this. This was what my professor told me in University (on Oracle based systems), it looks like it is also convention in MySQL [(Workbench->Foreign Key)](https://dev.mysql.com/doc/workbench/en/wb-relationship-tools.html). 

Nevertheless MySQL is using `<tablename>_id` as PK which is not the way we learned it at University. 

In the convention we are using, you mark your Primary Key with the prefix `PK_`  and your Foreign Key with `FK_` this is sometimes handy to see in which table you are working. Also you know exactly if the key you are working with  is primary or foreign. The problem I see with PK `id_<name>` and FK `<name>_id` is that it may can be misleading, but it is a valid convention too. 

But I don't think it is necessary to provide this Notation. The only downfall I had using this convention with pg was that I couldn't use the `.First()` function (no PK defined or something). But maybe the tag `sql:",pk"` can fix this issue to?!

**Comment by vmihailenco** [comment]
So the table looks like:

```
table groups (
  PK_id int,
  name varchar
)

table users (
  PK_id int,
  name varchar,
  FK_group_id int,
)
```

Does that look right?

>But maybe the tag sql:",pk" can fix this issue to?!

Yeah, it is worth a try.

**Comment by pixelskull** [comment]
The table would look like this: 
```
table groups (
    PK_groups int, 
    name varchar
)

table users (
    PK_users int ,
    name varchar, 
    FK_group
) 

```

So in this case the value of `FK_group` and `PK_group`. This way we defined the Relation in our model.

**Comment by pixelskull** [comment]
@vmihailenco Sorry for asking in this Issue, since it is not related to foreign keys... My query is now correct(ish). The only downside is, that my primary key reference (schema from above) is `userprofile_pk_userprofile`. 

My query is as follows: 
```
SELECT "userprofiles_groups".*, "group"."pk_group", "group"."name", "group"."description" 
    FROM "groups" AS "group" JOIN userprofiles_groups AS "userprofiles_groups" 
    ON ("userprofiles_groups"."userprofile_pk_userprofile") 
    IN ((1))
```

For the query to work properly, the name in the `ON` part has to be `pk_userprofile` so the prefix has to be disabled. 

Since I couldn't find a tag or something, I have to ask... Is there some tag-magic that can help me in this situation? Or should I write my own join statement?

**Comment by vmihailenco** [comment]
Please create a small program that reproduces the issue and post it here.

**Comment by pixelskull** [comment]
```go
package main

import("./KMDBHelper"
            "log"
            "github.com/go-pg/pg")

// specifies the userprofiles table
type Userprofile struct {
    TableName struct{} `sql:"userprofiles"`
    Pk_userprofile uint64 `sql:",pk"`
    Groups []*Group `pg:",many2many:userprofiles_groups,joinFK:fk_group"`
}

// specifies the group table 
type Group struct {
    TableName struct{} `sql:"groups"`
    Pk_group uint64 `sql:",pk:pk_group`
    Userprofiles []*Userprofile `pg:",many2many:userprofiles_groups,fk:fk_userprofile"`
}

// creates db connection from configuration files 
var db *pg.DB = KMDBHelper.OpenDBAdapter() 

func main() {

    var userprofiles Userprofile
    // using this resulted in sql statement posted earlier
    err := db.Model(&userprofiles).Column("Groups").First()

    if err != nil {
        log.Panicln(err.Error())
    }
}
```

The Scheme is for this case: 

```
table groups (
    pk_group int
)
```

```
table userprofiles (
    pk_userprofile int
) 
```

and the relation table (many to many) for both connections; users and groups. 

```
table userprofiles_groups (
    pk_userprofiles_groups int, 
    fk_userprofile int, 
    fk_group int
) 
```

Hope this is short enough by providing the information you need.

**Comment by vmihailenco** [comment]
Following schema seems to work as you want:

```
type Userprofile struct {
	tableName struct{} `sql:"userprofiles"`

	PKUserprofile uint64   `sql:",pk"`
	Groups        []*Group `pg:",many2many:userprofiles_groups,fk:fk_userprofile,joinFK:fk_group"`
}

type Group struct {
	tableName struct{} `sql:"groups"`

	PKGroup      uint64         `sql:",pk"`
	Userprofiles []*Userprofile `pg:"many2many:userprofiles_groups,fk:fk_group,joinFK:fk_userprofile"`
}

type UserprofileGroup struct {
	tableName struct{} `sql:"userprofiles_groups"`

	FKUserprofile uint64
	FKGroup       uint64
}
```

**Comment by vmihailenco** [comment]
Master branch also supports this:

```
func init() {
	orm.Tables.Register((*UserprofileGroup)(nil))
}

type Userprofile struct {
	PKUserprofile uint64
	Groups        []*Group `pg:"many2many:userprofiles_groups"`
}

type Group struct {
	PKGroup      uint64
	Userprofiles []*Userprofile `pg:"many2many:userprofiles_groups"`
}

type UserprofileGroup struct {
	tableName struct{} `sql:"userprofiles_groups"`

	FKUserprofile uint64
	FKGroup       uint64
}
```

Note that you must `orm.Tables.Register((*UserprofileGroup)(nil))` m2m table in init function to make it work.

**Comment by pixelskull** [comment]
Thanks man, it's working fine. Have had some try's using the third struct, but maybe there were some other bugs. 

Nevertheless thank you for your help.
