### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by threeaccents** [go-pg/pg#796]
What would be the idiomatic way of handling errors. For example handling a `unique_constraint` error? Parsing the error string seems wrong do you have any recommendations?

**Comment by threeaccents** [comment]
I checked out the code. Not sure how to still go about it. The errors returned from pg.sql don't seem to adhere to the pg Error interface since they don't have the `Field` and `IntegrityViolation` methods. So how could I go about checking it? For some errors you have helper errors which makes it great. Like the example below. But I've I'm trying to check for constraint error I'm still stuck

```go
if err := s.DB.Model(l).Where("id = ?", id).First(); err != nil {
  if err == pg.ErrNoRows {
    return nil, adioo.ErrNotFound
  }
  return nil, err
}
```

**Comment by vmihailenco** [comment]
There is no integrity violation in the code you posted so I am not sure what you are expecting.

See how ORM does it - https://github.com/go-pg/pg/blob/master/orm/query.go#L647-L659

**Comment by threeaccents** [comment]
Thanks that's exactly what I was looking for. And the code above was just an example of the helper err you have for when no rows are returned. I was asking if you had the same for constraint errors. But the code you linked me to is perfect. Thanks!

**Comment by threeaccents** [comment]
Is it possible to get the error code name? For example with the postgre sql driver package I can do something like
```go
if err, ok := err.(*pq.Error); ok {
    fmt.Println(err.Code.Name()) // unique_name_key
}
```
It is much more flexible since some tables have the same constraints for different columns.  I know I can do something like 

```go
if pgErr, ok := err.(pg.Error); ok {
    fmt.Println(pgErr.Field('M')) // duplicate key value violates unique constraint "unique_name_key"
}
```
However I would need to parse out the actual error code name. A helper function to get this info could be helpful. Maybe something like `pgErr.Field('N')` could return the error code name.
