### ISSUE TITLE
Implementing Scanner.Scan for int64 returns []uint8 (byte) instead of int64

### ISSUE THREAD

**Issue by azbshiri** [go-pg/pg#802]
I implemented Scanner for a struct called `PrepTime` in which embeds `time.Duration` and type of the related column is `bigint` (also tested with `integer`) but the returning `src` is []uint8 instead of int64 and I must first convert the []uint8 (byte) to string then convert it to `int64` using `strconv.ParseInt(string(src.([]uint8), 10, 64)`

Is this behavior done on purpose?

**Comment by vmihailenco** [comment]
Postgres returns `[]byte` - that is what you receive in `Scanner.Scan`.
