### ISSUE TITLE
Adding a pointer to an other struct (belongs to) creates an additional column

### ISSUE THREAD

**Issue by andreacab** [go-pg/pg#806]
Hey,
I am not sure I am doing everything correctly and i have tried various ways without success.
I have the two following models:
```golang
// models/parity.go
package models

// parity belongs to a location
type Parity struct {
    Id uuid.NullUUID `sql:",pk,type:uuid default gen_random_uuid()"`
    Incoterm string
    LocationId uuid.NullUUID `sql:",type:uuid"`
    Location *Location `sql:"-"`
    CreatedAt time.Time `sql:"default:now()"`
    UpdatedAt time.Time
}
```
```golang
// models/location.go
package models

type Location struct {
    Id uuid.NullUUID `sql:",pk,type:uuid default gen_random_uuid()"`
    Latitude float32
    Longitude float32
    Country string
    City string
    Type string
    CreatedAt time.Time `sql:"default:now()"`
    UpdatedAt time.Time
}
```
However this results in the following `parities` table being created:
![screen shot 2018-03-22 at 6 39 26 pm](https://user-images.githubusercontent.com/3372323/37807029-74987e16-2e00-11e8-8c80-58934e8d21ba.png)

I was expecting to see only `location_id` but `location` has also been added. I went around that problem by adding `sql:"-"`next to the line where the pointer to a `Location` is declared, in the `Parity` struct.

I also noticed that replacing `uuid.NullUUID` by `int` works and does not create this `location` column. 

What am I doing wrong?

Thanks for your help!

**Comment by andreacab** [comment]
I had to explicitly write ``sql:"-"``next to the line where a I declare a pointer to a location.

**Comment by vmihailenco** [comment]
It works for me on the master. Please create a program that reproduces the issue.

**Comment by andreacab** [comment]
Got a gist [here](https://gist.github.com/andreacab/4cd97fb8fc659793a85039ec35d3a2cd)

**Comment by vmihailenco** [comment]
This is what I get locally with program from the gist:

```sql
CREATE TABLE IF NOT EXISTS "locations" ("id" uuid, "latitude" real, "longitude" real, "country" text, "city" text, "type" text, "created_at" timestamptz DEFAULT now(), "updated_at" timestamptz, PRIMARY KEY ("id"))
CREATE TABLE IF NOT EXISTS "parities" ("id" uuid, "incoterm" text, "location_id" uuid, "created_at" timestamptz DEFAULT now(), "updated_at" timestamptz, PRIMARY KEY ("id"))
```

All seems to work properly - probably you need to update go-pg.

**Comment by andreacab** [comment]
Weird, not sure why it's not working on my end but thanks for your help.

**Comment by YassinOuider** [comment]
Weird same error for me @andreacab you have found a solution ?
