### ISSUE TITLE
Random select example ?

### ISSUE THREAD

**Issue by gmolveau** [go-pg/pg#811]
Hello !

I'd like to know, how would you implement a `random select` on a table, please ?

Something like : 

```
book := new(Book)
err := db.Select(book).Random()
```

Thank you for your help :)

**Comment by vmihailenco** [comment]
I would check what stackoverflow suggests and pick method that suits your needs. So far I was lucky enough to not need this functionality so don't have any experience to share.

**Comment by gmolveau** [comment]
Thank you for your answer !
I managed to do it with : 
```
r, err := config.Global.DB.Query(&item_id, "SELECT item.id from items as item offset random() * (select count(*) from items) limit 1 ;")
if err != nil {
	log.Error(err)
}
if r.RowsReturned() == 0 {
	item_id = 1
}
item := Item{Id : item_id}
```

but I clearly don't think that this is the best way to do it ...

**Comment by vmihailenco** [comment]
Large offset are slow so depending on number of rows it can be a problem.

If your ids are mostly sequential you can try `WHERE id = random(min_id, max_id)` and retry until you find a row. Postgresql SELECT ... TABLESAMPLE also looks interesting.

**Comment by gmolveau** [comment]
Thank you for your help, I'll try that !
