### ISSUE TITLE
Difference between Set and Column

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#816]
Sine the breaking API change, I was looking at latest commit and noticed that there is a Set() method.

_, err := db.Model(&book).Column("title").Returning("*").Update()
_, err := db.Model(&book).Set("title = ?title").Returning("*").Update()

What's the difference between these two?

**Comment by vmihailenco** [comment]
Column is more concise, but Set allows to use expressions like `Set("title = upper(?title)")`.
