### ISSUE TITLE
"Cursor" support

### ISSUE THREAD

**Issue by torarvid** [go-pg/pg#82]
Hi. Is there any support for queries of large datasets where you want to "stream" the results instead of loading them all up in memory? So in other words, I'd like memory consumption to not necessarily be proportional to the size of the result set.

In the standard library (the database/sql Rows struct) it seems to work like a cursor.

**Comment by vmihailenco** [comment]
I work with big datasets using this lib, but I do it in for loop selecting by 100-1000 rows in 1 step. AFAIK this is the best way to process millions of rows. I doubt you can do it using 1 query and database/sql Rows API.

But anyway to ask question currently you can do something like this:

```
package main

import (
	"fmt"

	"gopkg.in/pg.v3"
)

type Record struct {
	Name string
}

type Processor struct {
	row Record
}

func (p *Processor) NewRecord() interface{} {
	if p.row.Name != "" {
		fmt.Println(p.row.Name)
	}
	return &p.row
}

func main() {
	db := pg.Connect(&pg.Options{
		User: "postgres",
	})

	var processor Processor
	_, err := db.Query(&processor, `
		WITH data (name) AS (VALUES ('one'), ('two'), ('three'))
		SELECT * FROM data
	`)
	if err != nil {
		panic(err)
	}
	// Process last record.
	processor.NewRecord()
}
```

Briefly go-pg calls `Processor.NewRecord` each time it decodes new row and technically nothing prevents you from processing data there.

If you can convince me that your use case is popular go-pg can be improved to support something like this:

```
func main() {
	db := pg.Connect(&pg.Options{
		User: "postgres",
	})

	processor := func(rec *Record) error {
		fmt.Println(rec.Name)
		return nil
	}

	_, err := db.Query(processor, `
		WITH data (name) AS (VALUES ('one'), ('two'), ('three'))
		SELECT * FROM data
	`)
	if err != nil {
		panic(err)
	}
}
```

**Comment by flgr** [comment]
Is it impossible to make the default behavior only use a bounded amount of memory?

Given that the DB interface looks like it should support that (Scan() tends to return one row at a time), I think a lot of people are surprised when they start working with medium sized data sets and everything ends up loaded into main memory at the same time.

But this also required fiddling with the SQL libs of other languages (python...). Just wondering why we can't do the sensible thing by default.

Thanks a lot!

**Comment by vmihailenco** [comment]
@flgr but what is the sensible default? And which libs of other languages do you mean? Ideally with some examples.
