### ISSUE TITLE
SelectAndCount does not work for Temp table

### ISSUE THREAD

**Issue by rucas** [go-pg/pg#823]
I'm getting a weird error were if I set my the table to be `Temp: true` upon creation for a unit test SelectAndCount will error with:

```
Error on List, ERROR #42P01 relation "people" does not exist (addr="[::1]:5432")
```

Every other method from the orm works with `Temp: true` (list, insert, update, delete) it's just when I do `SelectAndCount`, `Select` works perfectly

If I set the table to `Temp: false`. Everything works.

Below is the code (not sure if this is any help...):

```go
type Postgres struct {
	Db        *pg.DB
	MaxLimit  int
	MaxOffset int
}

func (pg *Postgres) ListAndCount(q url.Values) ([]*Person, int, error) {
	var p []*Person
	pgr := orm.Pager{MaxLimit: pg.MaxLimit, MaxOffset: pg.MaxOffset}
	pgr.SetURLValues(q)
	c, err := pg.Db.Model(&p).
		Apply(orm.URLFilters(q)).
		Apply(pgr.Paginate).
		OrderExpr("id ASC").
		SelectAndCount()
	if err != nil {
		return nil, 0, err
	}
	return p, c, nil
}
```

**Comment by vmihailenco** [comment]
`SelectAndCount` uses 2 goroutines (and therefore 2 connections) to select and count rows. Temp tables exist only in current connection session and therefore can't be accessed from multiple goroutines/connections.
