### ISSUE TITLE
documentation needs heavy attention

### ISSUE THREAD

**Issue by burner-account** [go-pg/pg#825]
Hi! 
Let me start this with saying something nice: 
Thank you for the work you put into go-pg! I really enjoy using the working & accessible parts of this package.

But boy, your documentation creeps me out. That's what i meant with accessible - if the documentation is misleading or outdated you are denied access to an otherwise nice piece of work. Please do the next guys a favor and consider writing/reworking documentation sections on:

- struct member annotations : which does go-pg require, which are nice to have, what are the defaults if member annotations are unspecified

- notation in Column(): a what is what, what does what

- many to many: Please provide an example on how to integrate an existing TableA <->TableAB <-> TableB relation...but: Please tailor this example to violate every bit of your and postgres column/table/key-naming standards or conventions. This might be a nice software test as well.

The specific problem which brought me here is the following:
I have some tables, relations working. But how do i write a where clause in a case like this?
```go
var a []*A
count, err := db.Model(&a).Column("B", "B.C", "B.C.D").
Where("some member of C is LIKE something else").
Apply(pagination.Filter).
SelectAndCount()
```
I would appreciate a pointer in the right direction, thx!

**Comment by perajovic** [comment]
+1

**Comment by luxn** [comment]
+1

**Comment by vmihailenco** [comment]
I've added better m2m example and tweaked some docs. Existing documentation may be bad, but that is what we have and it will not become better until someone improves it.
