### ISSUE TITLE
uppercase characters in table names

### ISSUE THREAD

**Issue by bushjames** [go-pg/pg#827]
It does not appear to be possible to use uppercase characters in table names when using the `sql:"NAME"` struct annotation. This makes it difficult when using go-pg with schemas where one does not control the names of tables.

**Comment by vmihailenco** [comment]
Please a program that I can run and that reproduces the problem.

**Comment by bushjames** [comment]
My apologies, this is not the fault of go-pg. In an error postgres seems to return the table name in all lowercase even though the statement submitted (an insert in this case) had the correct case.
