### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gadelkareem** [go-pg/pg#830]
I am experiencing high memory leak `1.5GB` after a simple select statement. Calling the garbage collector manually did not help. Here is a screenshot from stack impact:
![screen shot 2018-04-27 at 17 43 31](https://user-images.githubusercontent.com/1441127/39372399-8a684aae-4a44-11e8-998a-389eed66a562.png)

Query:
```
tr.Model(&books)
  .Column("id", "updated_at")
  .Where("updated_at > ?", sinceLastUpdate)
  .Select()
```

**Comment by gadelkareem** [comment]
updated

**Comment by vmihailenco** [comment]
It does not reproduce the problem.
