### ISSUE TITLE
GO false value translates to PostgreSQL null

### ISSUE THREAD

**Issue by JonEustace** [go-pg/pg#835]
I have a boolean column `pending` in my database that has a constraint of `not-null`.
Whenever I attempt to insert `true` into the column I get no complaints. When I attempt to insert `false` into the column I get the following : `ERROR #23502 null value in column "pending" violates not-null constraint`

Is this is a bug with the PG driver?

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/wiki/Model-Definition about `sql:",notnull"`
