### ISSUE TITLE
How to order the many2many field.

### ISSUE THREAD

**Issue by wiiiky** [go-pg/pg#837]
I know how to query the many2many field. but don't know how to order them. Does go-pg support it?

I have a field like 

> Topics       []*Topic    `pg:"many2many:question_topic,fk:qid,joinFK:tid" json:"topics"

Can I order **Topics** with something like 

> Topics       []*Topic    `pg:"many2many:question_topic,fk:qid,joinFK:tid,order:"sort"" json:"topics"`

**Comment by vmihailenco** [comment]
Try

```
q.Relation("Topics", func(q *orm.Query) (*orm.Query, error) {
    q = q.Order("sort")
    return q, nil
})
```

**Comment by wiiiky** [comment]
@vmihailenco It works. thanks
