### ISSUE TITLE
ERROR #42601 Syntax error

### ISSUE THREAD

**Issue by mdere** [go-pg/pg#839]
Hello - For some reason I do not understand why this would not work:

```
func UpdateUserVerification(id int64, mobile int32, verificationCode int32) error {
	user := struct {
		TableName  struct{} `sql:"user"`
		Id         int64    `sql:"id,pk"`
		Mobile     int32    `sql:"mobile"`
		VerifyCode int32    `sql:"verify_code"`
	}{
		Id:         id,
		Mobile:     mobile,
		VerifyCode: verificationCode,
	}
	log.Log(user)
	return db.Update(&user)
}
```

And I get the following:
```
{
    "id": "api.user.SendVerifyCode",
    "code": 500,
    "detail": "ERROR #42601 syntax error at or near \"\"verify_code\"\" (addr=\"127.0.0.1:5432\")",
    "status": "Internal Server Error"
}
```

I take it Update could take any fields and update those fields if it exists in the struct as long I target the correct tableName and ID with pk set?

**Comment by mdere** [comment]
And I'm not certain why it is reporting additional double quotes around my field?....

**Comment by vmihailenco** [comment]
Check what SQL query is generated and what is wrong. Or write a program that reproduces the problem.

**Comment by mdere** [comment]
Vladimir:

Sorry its not clear to me how to output the query from calling the go pg
queries and etc.
