### ISSUE TITLE
How to use postgres built-in function like `NOW()`

### ISSUE THREAD

**Issue by Tommy-42** [go-pg/pg#842]
hey,

I came across a case where I need to update a field `last_updated`, without an ORM I usually do : `SET last_updated = NOW()`, thus using the build-in func that posgres gives us.

given an object for example : 

```
type foo struct {
   id int64
   name string
   last_update time.Time
}
```

Do you need to use `Exec` func to craft your own query to use postgres built-in function.

or you can use the ORM to update it while updating the others fields ?

( In the wiki the update documentation part only talk about updating a whole object or one field. Or did I miss understood ? )

Thanks for your time,

Tommy

**Comment by vmihailenco** [comment]
ORM gives following options:

```
q.Model(&foo).Set("last_update = now()").Update() // you must specify all you want to update

q.Model(&foo).Value("last_update", "now()").Update() // overwrites value for specific column
```

**Comment by Tommy-42** [comment]
nice works like a charm !
