### ISSUE TITLE
WhereGroup error if query unchanged

### ISSUE THREAD

**Issue by mwei0210** [go-pg/pg#843]
I have an if conditional statement inside wheregroup to only return a where condition only if requirements meet. Is it not possible to return back the original query?

**Comment by vmihailenco** [comment]
It is possible - just try.

**Comment by mwei0210** [comment]
Doesn't look like it. Keep getting ERROR #42601 syntax error at or near ")" with
`WhereGroup(func(q *orm.Query) (*orm.Query, error) {
			return q, nil
		})`

query executed seems to have this `WHERE ()` at the end

**Comment by vmihailenco** [comment]
Ooops, should be fixed in master.

**Comment by mwei0210** [comment]
Thanks @vmihailenco! Mind answering the other issues about calling polymorph parent from child? :)
