### ISSUE TITLE
multiple joinFKs and FKs

### ISSUE THREAD

**Issue by mwei0210** [go-pg/pg#845]
Hi, i have profile as a polymorphic child which is why it has trackableID and trackableType. hence the need to specify multiple joinFKs and FKs for `Locations` a many2many relation. just wanna confirm if multiple joinFKs and Fks work like this? Thanks!
```
type Profile struct {
	TrackableID         int64  `sql:",pk"` // Artist.ID or Promoter.ID
	TrackableType       string `sql:",pk"` // "Artist" or "Promoter"
        Locations           []*Location `pg:",many2many:location_profiles,joinFK:trackable_id,joinFK:trackable_type,fk:trackable_id,fk:trackable_type" json:"-"`
}

type LocationProfile struct {
	LocationID    int64  `sql:",pk"`
	TrackableID   int64  `sql:",pk"`
	TrackableType string `sql:",pk"`
}
```

**Comment by vmihailenco** [comment]
I have no idea what happens here - try to write a program that can be run.

**Comment by mwei0210** [comment]
hmm, i have `Profile` that can have multiple locations, and `Location` that can have multiple profiles so i am defining a m2m relationship between them through LocationProfile m2m table. But how do i join them if `Profile` has multiple primary keys `TrackableType` and `TrackableID`
