### ISSUE TITLE
new version break backward compatibility for UpdateNotNull without warning

### ISSUE THREAD

**Issue by badoet** [go-pg/pg#846]
Hi guys,
this commit: https://github.com/go-pg/pg/commit/343ed7f0009a97d10db80b69f641454f6838590a#diff-74bb320d7cac8ee8cac4a90881c86900
break backward compatibility without warning for `UpdateNotNull` function
now we need to add .WherePK().UpdateNotNull() to get it to work.
Can try to notify developers on breaking changes like this in release notes or something?
it breaks our production code when we thought we didnt change any logic for this.

**Comment by vmihailenco** [comment]
That change was released in new version, is documented in changelog and code returns a reasonably good error message and should be caught easily if you have tests. I don't see what else can be done.

**Comment by badoet** [comment]
hooo my bad. will be more careful next time.
thank you for clarification
Maybe we can use a **Breaking Changes** header on changelog to highlight something need to be done on this version update?
