### ISSUE TITLE
Deeper Relation

### ISSUE THREAD

**Issue by enchantner** [go-pg/pg#847]
I have relations that look kinda like this:
User - one2one - UserProfile - one2many - Actions

So, I'm trying to write a query, that does a deep join. I want to get top User names ordered by the count of Actions every of them did. Something like this:

```
var topActive []struct {
    FirstName  string
    LastName   string
    ActionCount int
}

err = conn.Model(&db.Action{}).
    Relation("UserProfile").
    Relation("User"). // <-- this fails, because Action doesn't have direct relation to User
    Column("users.first_name", "users.last_name").
    ColumnExpr("count(*) AS action_count").
    Group("user_profile_id").
    OrderExpr("action_count DESC").
    Limit(5).
    Select(&topActive)

```
So, how do I join all of them together in one query? Is there a way to write a "deeper" Relation?

**Comment by vmihailenco** [comment]
Did you try `User` -> `UserProfile.User`?
