### ISSUE TITLE
Relation isn't called in my query

### ISSUE THREAD

**Issue by jmheidly** [go-pg/pg#848]
I have the below function call which returns a list of titles, each with its Publisher and ranking. However I noticed that by splitting the queries (titlesResult), **Relation** query isn't executed and therefore no Issues are retrieved. What seems to be the problem?   

	titlesResult := tms.db.Model(&titles).
		Column("title.*", "Issues", "Publisher").
		Relation("Issues", func(q *orm.Query) (*orm.Query, error) {
			return q.Where("state = 'published'").
				Where(`"publishedDate" IS NOT NULL`).
				Where(`"publishedDate" <= now()`).
		}).
		Where(`title."bundles"::jsonb` + " > '{}'::jsonb").

	err := tms.db.Model().
		TableExpr("(?) as result", titlesResult).
		TableExpr(fmt.Sprintf("plainto_tsquery('%s') query ", store.Query)).
		ColumnExpr("*, ts_rank(tsv, query) as ranking").
		Where("tsv @@ query").
		Order("ranking DESC").
		Select(&titles)

**Comment by vmihailenco** [comment]
It is not supported and I doubt it should be. If it is possible - move `Relation` to the 2nd query.

**Comment by jmheidly** [comment]
Did but failed

**Comment by vmihailenco** [comment]
For relations to work you should specify model, i.e. instead of `Select(&titles)` -> `Model(&titles)`.
