### ISSUE TITLE
ManyToMany Model not inputting correct column name

### ISSUE THREAD

**Issue by mdere** [go-pg/pg#862]
So going through the many to many example, I am having difficulty trying to get this to work. So below shows this weird behavior where at the JOIN it tries to do blog_place."get_blog_blog_id"

![image](https://user-images.githubusercontent.com/9097501/40464800-5ba8875e-5eeb-11e8-8bfa-ae44b06d90c7.png)

I am not sure why this is happening - I tried looking at other similar issues, but couldn't solve my issue with those.

My query:
![image](https://user-images.githubusercontent.com/9097501/40464857-b5ad3236-5eeb-11e8-8d0a-edea01fa9c8b.png)

My `&blogs` is
![image](https://user-images.githubusercontent.com/9097501/40464871-c78d16ec-5eeb-11e8-8d33-cb38adfef8bf.png)

My Place Struct is the following:
![image](https://user-images.githubusercontent.com/9097501/40464900-ea1f63a4-5eeb-11e8-98ea-60d04861137c.png)

Sorry for the images - my bidrectional copy from my VM guest is not working atm.

**Comment by vmihailenco** [comment]
Please create a program that can be run and that demonstrates the problem. It is much easier to fix the code rather than explain how to fix in in English.

**Comment by mdere** [comment]
@vmihailenco so you have no idea why this would happen then?

blog_place."get_blog_blog_id"?

get_blog was defined apparently through the struct I passed in which I am trying to build a relationship against it.
