### ISSUE TITLE
Best practice on model inheritance

### ISSUE THREAD

**Issue by Alireza-Ta** [go-pg/pg#866]
Lets say i have these models

```golang
type BaseModel struct {
	Id        int       `json: "id"`
	CreatedAt time.Time `json:"created_at" sql:"type:timestamptz, default:now()"`
	UpdatedAt time.Time `json:"updated_at" sql:"type:timestamptz"`
}
```
```golang
type Post struct {
	BaseModel `pg:"override"`
	AuthorID  int    `json:"author_id"`
	Author    *User  `json:"author"`
	Vote      int    `json:"vote" sql:"default:0"`
	Body      string `json:"body" sql:"type:text"`
}
```
```golang
type Question struct {
	Post     `pg:"override"`
	Title    string    `json:"title"`
	Comments []Comment `json:"comments" pg:"many2many:comments_questions"`
}
```
```golang
type Comment struct {
	Post `pg:"override"`
}
```
Now for example if i want to find a question by id i should do something like following:
```golang
q := &Question{
		Post: Post{
			BaseModel: BaseModel{
				Id: 2,
			},
		},
	}
	err := db.Select(q)
...
```
But this initialization is somehow ugly to me!
I know i can ignore inheritance and everything goes fine but is there any way to improve it or any better idea?
Thanks

**Comment by vmihailenco** [comment]
I don't use `db.Select` and prefer more explicit version:

```
q := new(Question)
err := db.Model(q).Where("id = ?", 2).Select()
```

Other than that I don't have anything to add here - I don't use base models. Perhaps you should not too.

**Comment by Alireza-Ta** [comment]
Thanks.
``` I don't use base models. Perhaps you should not too.```
You mean that it's fine don't use only the base model or ignore all the inheritance for models and declare them on their own ?

**Comment by vmihailenco** [comment]
I mean to get rid of `BaseModel` from your example and copy/paste columns where you need them.
