### ISSUE TITLE
BeforeUpdate() not called with OnConflict 

### ISSUE THREAD

**Issue by trrodrigues** [go-pg/pg#867]
should BeforeUpdate hook be called with an OnConflict? 

BeforeInsert() is executed.

`	query := rep.db.Model(foo).
		Where("id = ?", foo.id).
		OnConflict("(id) DO UPDATE").
		Returning("id")`

**Comment by trrodrigues** [comment]
How go/client knows that postgresql is going to execute the insert? The BeforeInsert() is called.

I think the query can be built with the update statement, postgresql will only execute that if the on conflict match.

**Comment by vmihailenco** [comment]
>How go/client knows that postgresql is going to execute the insert? The BeforeInsert() is called.

It does not care - it always calls BeforeInsert when Insert is called.

**Comment by vmihailenco** [comment]
What do you mean?
