### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by RenatoSerra22** [go-pg/pg#872]
Hi,

When i try to do a bulk delete [https://godoc.org/github.com/go-pg/pg#example-DB-Delete-BulkDelete](BulkDelete) i get the following error if i try to use a slice of pointers like:

```db := modelDB()

var books []*Book

//**add some books to it**

res, err := db.Model(&books).Delete()
if err != nil {
    panic(err)
}
```

Fails with `panic: reflect: call of reflect.Value.Field on ptr Value [recovered]`

But works when doing this with

```db := modelDB()

var books []Book //<---- array of structs instead of pointers

//**add some books to it**

res, err := db.Model(&books).Delete()
if err != nil {
    panic(err)
}
```
Is this intended?

thanks!

**Comment by vmihailenco** [comment]
Thanks for the report - this should be fixed in master.

**Comment by RenatoSerra22** [comment]
thank you :)
