### ISSUE TITLE
Release v6.13.2 broke db.CreateTable function 

### ISSUE THREAD

**Issue by chichivica** [go-pg/pg#874]
Hi guys,
first of all many thanks for your amazing framework and we really appreciate your work on it.

Unfortunately we met sad issue regarding **CreateTable** function. 
Imagine the situation, here we have three simple entities, **human_aggregated**, **task** and **task_group**
![](https://i.imgur.com/yx85oT7.png)

**task_group** _--one-to-many--_ **task** _--one-to-many--_  **human_aggregated**

We use following approach to initiate our tables:
```
       models := []interface{}{
		(*TaskGroup)(nil),
		(*Task)(nil),
		(*HumanAggregated)(nil),
                 ...
	}

	for _, model := range models {
		err := db.CreateTable(model, &orm.CreateTableOptions{
			IfNotExists:   true,
			FKConstraints: true,
		})
		if err != nil {
			print(err)
			return err
		}
	}
```
And this code generates **SOMETIMES** (I mean literally, in 2 from 3 times) wrong foreign keys.
![](https://i.imgur.com/91CnJIY.jpg)
Wrong on the left, correct on the left. v6.13.1 works as expected.
Models is written in accordance with documentation.

**Comment by chichivica** [comment]
@vmihailenco 
I did. 6.13.5, 6.13.4 doesn't work either

**Comment by vmihailenco** [comment]
Okay, then I will need model definitions in order to reproduce this.
