### ISSUE TITLE
JSON field doesn't unmarshal back to struct, can't determine why

### ISSUE THREAD

**Issue by intel352** [go-pg/pg#878]
I'm using go-pg to store oauth2 tokens for reuse. Example model:
```
type UserProvider struct {
    Id uint64 `sql:",type:bigserial,pk"`
    Token *oauth2.Token `sql:",type:jsonb"` // I've also tried with type:json
}
```

Saving the model works fine, but every time I fetch the record from db, the Token property is nil, without any errors emitted.

Just to test JSON unmarshal to ensure there's no problems, I took the Token definition from oauth2 package and tested in Playground, works fine: https://play.golang.org/p/070QslSP4E6

To work around this issue, I've had to map the token field to a `map[string]interface{}`, and use before/after hooks to remap the oauth2.Token to the map. It works, but seems a quite unnecessary workaround.

**Comment by vmihailenco** [comment]
Please write small program that reproduces the issue, e.g. insert+select `UserProvider` struct.

**Comment by intel352** [comment]
@vmihailenco ugh, my mistake. I'm newer to Go, and made a rookie mistake of creating pointers to values originating from a for/range loop... https://tam7t.com/golang-range-and-pointers/

My apologies, and thanks!
