### ISSUE TITLE
Issue with Struct Names

### ISSUE THREAD

**Issue by yiiTT** [go-pg/pg#881]
I'm trying to rename some of my structs by adding a "prefix" like changing Item to StoreItem or Storeitem but when I do it thinks my Has One is a column. 

```
type Item struct {
	TableName   struct{} `sql:"items,alias:item"`
	Id          int      `sql:"item_id,pk"`

	Mapping           *ItemMapping `sql:"-"`
}
type RenamedItem struct {
	TableName   struct{} `sql:"items,alias:item"` // table name could be anything
	Id          int      `sql:"item_id,pk"`

	Mapping           *ItemMapping `sql:"-"`
}
type Renamed struct {
	TableName   struct{} `sql:"items,alias:item"`
	Id          int      `sql:"item_id,pk"`

	Mapping           *ItemMapping `sql:"-"`
}

type ItemMapping struct {
	TableName struct{}   `sql:"item_mapping,alias:im"`
	ItemId int            `sql:"item_id,fk:item_id"`
}
```
// Works
db.Model(&Item{}).Column("item.*", "Mapping").Select() 
`SELECT "item".*, "mapping"."item_id" AS "mapping__item_id" FROM items AS item LEFT JOIN item_mapping AS "mapping" ON "mapping"."item_id" = item."item_id"`

// Does not work
db.Model(&RenamedItem{}).Column("item.*", "Mapping").Select()
db.Model(&Renamed{}).Column("item.*", "Mapping").Select() 

`SELECT "item".*, "Mapping" FROM items AS item`
// Err: column "Mapping" does not exist

**Comment by vmihailenco** [comment]
Please create an issue with code that can be run and that reproduces the issue.
