### ISSUE TITLE
Order By random() Fails: wrapping ORDER clauses in quotes doesn't always work

### ISSUE THREAD

**Issue by kamranjon** [go-pg/pg#882]
this query runs fine:
`SELECT * FROM nodes ORDER BY random() limit 1;`
but the ORM here: [is wrapping the clause in quotes](https://github.com/go-pg/pg/blob/master/orm/select.go#L114)
which is breaking the usage of builtin postgres methods in order clauses, leading to the error:

> ERROR #42703 column "RANDOM()" does not exist (addr="127.0.0.1:5432")

**Comment by vmihailenco** [comment]
See `OrderExpr`
