### ISSUE TITLE
Specify key for many-to-many relationship

### ISSUE THREAD

**Issue by asyndrige** [go-pg/pg#884]
I have these 2 models with many-to-many relationship:

```
type Person struct {
    tableName    struct{}   `sql:"person"`
    UUID         string     `sql:"person_uuid,pk"`
    ContactDatas []ContactData `pg:",many2many:person_contact_data,joinFK:"`
}

type ContactData struct {
    tableName     struct{}   `sql:"contact_data"`
    UUID          string     `sql:"contact_data_uuid,pk"`
}
```

And model for person_contact_data table is:
```
type PersonContactData struct {
    tableName       struct{} `sql:"person_contact_data"`
    PersonUUID      string   `sql:"person_uuid"`
    ContactDataUUID string   `sql:"contact_data_uuid"`
}
```
If joinFK in ContactDatas struct tag is empty go-pg adds underscore under the hood, so generated SQL part looks like this: WHERE ("contact_data"."contact_data_uuid" = person_contact_data."_contact_data_uuid").

Is there a way to specify joining keys completely manual? (go-pg v5)

**Comment by vmihailenco** [comment]
I don't know about v5, but latest version support full sql names in `joinFK`

**Comment by asyndrige** [comment]
I see, thanks.
