### ISSUE TITLE
Single polymophic relationship

### ISSUE THREAD

**Issue by mwei0210** [go-pg/pg#885]
Is there support for single polymorphic relationship? Looks like only polymorphic on slice is working. Thanks

**Comment by vmihailenco** [comment]
There is no support for single polymorphic relationship in any way. It is hard to say more, because I can guess what exactly do you mean under "single polymorphic relationship".

**Comment by mwei0210** [comment]
Should have termed it better. I meant "has one polymorphic relation", like the example
https://github.com/go-pg/pg/blob/d00e81b902758dd8f54010b0248048e973838804/db_test.go#L797
but for single instance only

**Comment by mwei0210** [comment]
If i understand correctly, has one is use when a model belongs to another model while polymorphic is when a model belongs to multiple models. Currently i have something like
```
type Actor struct {
    Id int
    Profile Profile `pg:"polymorphic:trackable_"`
}
type Singer struct {
    Id int
    Profile Profile `pg:"polymorphic:trackable_"`
}
type Profile struct {
    TrackableId int
    TrackableType string
}
```

**Comment by vmihailenco** [comment]
Why not something like this:

```
type Actor struct {
    Id int
    Profile Profile
    ProfileId int
}

type Singer struct {
    Id int
    Profile Profile
    ProfileId int
}

type Profile struct {
    Id int
}
```

I.e. plain has-one relation.

**Comment by mwei0210** [comment]
yeah that would work too, but it would be great to have the convenience of applying morph here since it theoretically fulfill the requirements of polymorphism :)

here's how laravel does it:
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Relations/MorphOne.php

**Comment by vmihailenco** [comment]
Sorry, but since this is complex enough and same result can be achieved with much simpler has-one relation I don't see a point in adding this functionality.
