### ISSUE TITLE
How to define isolation level for transactions?

### ISSUE THREAD

**Issue by andrehp** [go-pg/pg#886]
Hi,

Is there a way to define the isolation level for transactions? I would be interested in starting transactions with specific isolation levels, such as repeatable read and serializable.

Reference: https://www.postgresql.org/docs/9.5/static/transaction-iso.html

**Comment by rcmgleite** [comment]
+1

**Comment by vmihailenco** [comment]
What about `tx.Exec("SET TRANSACTION transaction_mode")` as described in https://www.postgresql.org/docs/9.5/static/sql-set-transaction.html ?

**Comment by andrehp** [comment]
I guess this works, thanks for the help!
