### ISSUE TITLE
Compatibility with sql.DB

### ISSUE THREAD

**Issue by gadelkareem** [go-pg/pg#887]
I am not sure how to use `pg.DB` as `sql.DB` I had to import github.com/lib/pq and reconnect as a workaround to inject into other libraries.

```
func (db *PgDb) SqlDriver() (*sql.DB, error) {
	return sql.Open(
		"postgres",
		fmt.Sprintf(
			"postgres://%s:%s@%s/%s?sslmode=disable",
			dbUser, dbPass, dbAddress, dbName,
		),
	)
}
```

**Comment by vmihailenco** [comment]
go-pg is a separate lib, not a driver fro sql.DB.
