### ISSUE TITLE
Mapping struct fields on table columns

### ISSUE THREAD

**Issue by njspok** [go-pg/pg#888]
I not find a way describe mapping go struct field on columns in table db. Like this
```go
type Pepole struct {
    ID int
    Name string
    Addr Addr
}

type Addr struct {
    Street string
    City string
}
```
And map to table `Peoples`
```
Peoples
   id //  People.ID
   name // People.Name
   addr_city // People.Addr.City
   addr_street // People.Addr.Street
```
Use JSONB type column for Addr do not consider as a solution.

**Comment by njspok** [comment]
But how work insert on update?

**Comment by vmihailenco** [comment]
My advice is to create 1:1 mapping between Go and SQL ,e.g.

```
type People struct {
    ID int
    Name string
    AddrStreet string
    AddrCity string
}
```

Support for the use case you are asking for does not look worth the time & complexity.
