### ISSUE TITLE
bool field-false will be set as null

### ISSUE THREAD

**Issue by ali-arabshahi** [go-pg/pg#889]
i'm new to pg.when i use false in my code,in database it will be null.this is my code

```
type Sms struct {
	ID          int64
	Code        int
	PhoneNumber string
	Expire      bool
	Gendate     time.Time
}
sms := &Sms{
		Code:        44444,
		PhoneNumber: 888888,
		Expire:      false,
		Gendate:     time.Now(),
	}
	err = db.Insert(sms)
	if err != nil {
		panic(err)
	}
```
'Expire' field will be null in database.thank you in advance and sorry for my bad english.

**Comment by ClintonCollins** [comment]
You want to use the sql tag: 

> `sql:",notnull"`

So it would look like this:

> type Sms struct {
	ID          int64
	Code        int
	PhoneNumber string
	Expire      bool `sql:",notnull"`
	Gendate     time.Time
}

**Comment by vmihailenco** [comment]
What @ClintonCollins said.

**Comment by sgon00** [comment]
`` `sql:",notnull"` `` doesn't work to me with error msg `null value in column violates not-null constraint"`

I have to use `` `sql:",default:false,notnull"` `` which works.

**Comment by vmihailenco** [comment]
You need to use `pg:",use_zero"` in v9. `sql:",notnull"` now only controls `NOT NULL` SQL constraint.

**Comment by sgon00** [comment]
@vmihailenco  Dear sir, I tried `` `pg:",use_zero"` `` in v9, it still insert DEFAULT value to the table, i.e. NULL. This is the same without use_zero tag. Did I do anything wrong?
I tried `` Active bool `sql:",default:false"` `` which works.

The following is the code:

go.mod:

```
require (
	github.com/go-pg/pg/v9 v9.0.0-beta.1
)
```

main.go:

```go
import (
	"github.com/go-pg/pg/v9"
	"github.com/go-pg/pg/v9/orm"
)

// Foo ...
type Foo struct {
	ID     int64
	Lang   string
	Active bool `pg:",use_zero"`
}

func main() {
	db := pg.Connect(&pg.Options{
		User:     "user1",
		Password: "user1",
		Database: "testdb1",
		Addr:     "localhost:5432",
	})
	defer db.Close()

	err := db.DropTable((*Foo)(nil), &orm.DropTableOptions{
		IfExists: true,
	})
	if err != nil {
		panic(err)
	}

	err = db.CreateTable((*Foo)(nil), &orm.CreateTableOptions{
		IfNotExists: true,
	})
	if err != nil {
		panic(err)
	}

	foo := &Foo{
		Lang:   "en",
		Active: false,
	}
	err = db.Insert(foo)
	if err != nil {
		panic(err)
	}
}
```

**Comment by vmihailenco** [comment]
`v9.0.0-beta.1` is 11 days old. I've just pushed `v9.0.0-beta.2` but it will take some time before it is available in go mod. Meanwhile you can use

```
GOPROXY=direct go get -u github.com/go-pg/pg/v9@master
```
