### ISSUE TITLE
Output generated SQL to console

### ISSUE THREAD

**Issue by ernsheong** [go-pg/pg#893]
Following https://github.com/go-pg/pg/issues/45, it would be really helpful to be able to set a flag and output the generated SQL to console for quick and easy debugging purpose. Does doing `SetLogger` achieve this?

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/wiki/FAQ#how-can-i-viewlog-queries-this-library-generates

**Comment by ernsheong** [comment]
Thanks. Sorry about that
