### ISSUE TITLE
Interface satisfying DB and Tx

### ISSUE THREAD

**Issue by ribice** [go-pg/pg#897]
I want my methods to receive an interface, that both DB and TX satisfy.

For example:

```go
func (s *Service) Create(db *pg.SomeInterface, usr *User) error{
    return db.Create(usr)
}
```
both *pg.DB and *pg.Tx can be passed as param to Create. How can I achieve this?

**Comment by vmihailenco** [comment]
There is `orm.DB` interface.

**Comment by ribice** [comment]
Thanks!
