### ISSUE TITLE
Does go-pg support Postgresql 10.4 ?

### ISSUE THREAD

**Issue by ivansalacceo** [go-pg/pg#899]
I have a go-app which use elephantsql as database service (https://www.elephantsql.com/). I have no problem with that. However, when I change the database to local postgresql, the app gives different result which is not expected. Moreover, when I try to query manually with pgAdmin on local computer it gives expected result. Therefore, temporarily I assume that something is wrong with go-pg.
Elephantsql postgresql version:
`PostgreSQL 10.0 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit`

Local postgresql version (run on Windows OS):
`PostgreSQL 10.4, compiled by Visual C++ build 1800, 64-bit`

Here is the app code:
```
func GetCostRange(min_date string, max_date string) (*[]int32, error) {
	var costs = &[]int32{}
	_, err := db.Query(costs, `
        SELECT coalesce(res.sum, 0)
        FROM generate_series
            (
                ?::TIMESTAMPTZ AT TIME ZONE 'Asia/Tokyo',
                ?::TIMESTAMPTZ AT TIME ZONE 'Asia/Tokyo',
                INTERVAL '1 month'
            ) AS gen_month LEFT JOIN
            (
                SELECT date_trunc('month', transaction_date AT TIME ZONE 'Asia/Tokyo') AS mon_year, SUM(amount)
                FROM expenses
                GROUP BY mon_year
            ) AS res
            ON gen_month = res.mon_year;
    `, min_date, max_date)
	log.Printf("%s", costs)

	return costs, err
}
```  
Using the elephantsql yield the result, for example (using dummy data for testing):
[0,0,1000,200,300]

Manually query on local computer with pgAdmin yield the result, for example (with different data from the elephantsql data):
[0,0,1000000,200000,30000000]

Result of app (on local computer) with go-pg query yield the result, for example:
[0,0,0,0,0]
where it should be the same with manually query on local computer, which is
[0,0,1000000,200000,30000000]

Any help would be appreciated.

Edited:
I edited the example, since I used different dataset for elephantsql and local computer.

**Comment by vmihailenco** [comment]
I don't any ideas except that I highly doubt it is go-pg issue :) My suggesting would be to isolate the problem and write a program that reproduces the problem.

**Comment by ivansalacceo** [comment]
I just have a thought that when the query result type is bigint and the golang variable used to store the result is int32, it will give 0 result. I haven't checked it though, since it's on my client computer. I will post the result later here. Thanks for the reply @vmihailenco

**Comment by ivansalacceo** [comment]
Just found out that it was database timezone config problem. I had solved the issue. Thanks.
