### ISSUE TITLE
Updating Using Insert() Not Working

### ISSUE THREAD

**Issue by oscartbeaumont** [go-pg/pg#901]
Hello,
I Am Wonder Why The Code Below is Not Working. It aim is to Creating Or Update (If It Already Exists) An Entry In the Database. It Successfully Creates New Entries In The Database But It Does Not Update Existing Ones.
```
_, err := pgdb.Model(_device).
    OnConflict("(udid) DO UPDATE").
    Set("udid = ?", _device.UDID).
    Insert()
```
Thanks,
Oscar

**Comment by vmihailenco** [comment]
go-pg only generates SQL - let me know if there are any bugs in the generated query. Other than that it is not a go-pg problem.
