### ISSUE TITLE
When TableAlias is used in parenthesis, param is not evaluated

### ISSUE THREAD

**Issue by 23doors** [go-pg/pg#903]
`q.Where("?TableAlias = ?", "param")` => works fine. TableAlias is substituted and param converted to sql Value.

`q.Where("(?TableAlias) = ?", "param")` => TableAlias is substituted but `?` is not evaluated. Results in e.g. `(table) = ?`

This is troublesome when using pg functions e.g.:
`q.Where("some_pg_func(?TableAlias.field) > ?", param)`

**Comment by vmihailenco** [comment]
I can't reproduce this. Try to upgrade to latest version and then create a program that reproduces the problem.

**Comment by 23doors** [comment]
This is weird, I am now unsure where the issue lies and my diagnose may have been off but I seem to have more or less reproduced issue I was having:
https://gist.github.com/23doors/fa40d32921f60c5b1105fcc6cabdfd6d
Tested against 6.14.2.

**Comment by 23doors** [comment]
@vmihailenco did you have a chance too look at it?

**Comment by 23doors** [comment]
Didn't check if there are any other side-effects to it, but if you remove this:
https://github.com/go-pg/pg/blob/master/orm/format.go#L235
it works fine for structs as a param.
Even some weird stuff like:
	`printQuery("?TableAlias.T > ?TableAlias.?.?TableAlias", time.Now())`
works fine.
