### ISSUE TITLE
Handle enumeration with go-pg

### ISSUE THREAD

**Issue by jhayotte** [go-pg/pg#906]
Hello,

Do you have an `@inject_tag` that handle column referencing an enum? I am trying to link the property defined in my proto to this enumeration.

```sql
CREATE TYPE contact_type AS ENUM (
    'DIRECTION',
    'LEGAL',
    'SALES',
    'PROCUREMENT',
    'FACTURATION'
);

CREATE TABLE "contact" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "contact_type" contact_type NOT NULL,
);
```

I could not find it in the documentation.

By the way, it would be nice to have a place with all sort of `inject_tag`

**Comment by vmihailenco** [comment]
What is `inject_tag`? I also don't understand what go-pg should add to support enums.

**Comment by Tommy-42** [comment]
hello,

we have our proto that contains a message : 
```
enum ContactType {
    Main = 0;
    Secondary = 1;
}
ContactType contact_type = 7;
```

and in our `sql` init : 

```
CREATE TYPE contact_type AS ENUM (
    'MAIN',
    'SECONDARY'
);
```

but go-pg is not able to find that this is an enum :/ 

resulting in : `strconv.ParseInt: parsing "SECONDARY": invalid syntax`

**Comment by vmihailenco** [comment]
I guess you need to change Go struct field type from `int` to `string`.

**Comment by Tommy-42** [comment]
the protobuf looks like this :
 
```protobuf
message Contact {
    enum ContactType {
        Direction = 0;
        Legal = 1;
        Sales = 2;
        Procurement = 3;
        Billing = 4;
    }
    ContactType contact_type = 1;
}
```

**Comment by vmihailenco** [comment]
Postgres enum is string/varchar, but protobuf is int32/number. You need to do something about it, but it does not look like a go-pg issue.

**Comment by ratsirarar** [comment]
what's the right approach here? Shouldn't there be an @inject_tag

**Comment by smyrgl** [comment]
This works just fine for me.

```golang
func (s Bill_BillState) Value() (driver.Value, error) {
	return strings.ToLower(s.String()), nil
}

func (s *Bill_BillState) Scan(value interface{}) error {
	if value == nil {
		*s = Bill_UNKNOWN
		return nil
	}
	bs := string(value.([]uint8))
	*s = Bill_BillState(Bill_BillState_value[strings.ToUpper(bs)])
	return nil
```
