### ISSUE TITLE
OnConflict break id sequence

### ISSUE THREAD

**Issue by Alireza-Ta** [go-pg/pg#909]
Lets assume the following table:
```go
type Tag struct {
	Id        int       `json:"id"`
	Name      string    `json:"name" sql:",unique"`
	CreatedAt time.Time `json:"created_at" sql:"type:timestamptz, default:now()"`
	UpdatedAt time.Time `json:"updated_at" sql:"type:timestamptz"`
}
```
The Name field is unique so if i insert duplicate value it will give ```ERROR #23505 duplicate key value violates unique constraint "tags_name_key"```.
Now to get rid of that error use this code : 
```go
var tag Tag
tag.Name = "golang"
res, err := s.db.Model(&tag).OnConflict("(name) DO NOTHING").Insert()
```
But for new inserted data the id would not be sequential !
For example : 
id | name | created_at | updated_at
-- | ------ | ----------- | ------------ 
1   | javascript |2018-07-16 13:23:28 | 2018-07-16 13:23:28
5   | golang |2018-07-16 13:23:28 | 2018-07-16 13:23:28

Thanks.

**Comment by vmihailenco** [comment]
That is how Postgres works I guess. I don't think this is a go-pg problem (if there is a problem).

**Comment by Alireza-Ta** [comment]
Yes, thats true.
That was a misunderstanding that i thought PK increments after checking duplicates through insert command while it wasn't.
But for those who wants to handle it, the below SQL command before insert will help : 
``` go
SELECT setval('sometable_id_seq', MAX(id), true) FROM sometable;
```

I'll close it.
