### ISSUE TITLE
error in get row count -> Count ()

### ISSUE THREAD

**Issue by dfmabbas** [go-pg/pg#910]
Hello . I need to get the number of rows in a table based on one condition.

**my sample code :** 
```
var count int
_, errs := conn.Model(&DeviceStruct{}).QueryOne(
pg.Scan(&count),
"SELECT count(*) FROM device_structs where unique = ? ", unique)
```

**OR**
`	count, errs := conn.Model(&DeviceStruct{}).Where("unique = ?", unique).Count()`

**OR**
`	count, errs := conn.Model(&DeviceStruct{}).Where("unique = ?", unique).SelectAndCount()`

Unfortunately, these codes do not work.

**error :** 

> ERROR #42601 syntax error at or near "=" (addr="127.0.0.1:5432") 

**What should I do?**

**Comment by Alireza-Ta** [comment]
Hey
I guess this problem arose because of the ```unique``` word in your SQL command.
```unique``` is a PostgreSQL keyword so you can't use it without quoting it.
Just use backticks for whole SQL command  ``` `` ``` and wrap unique in quotes like so : 
```go
var count int
_, errs := conn.Model(&DeviceStruct{}).QueryOne(
pg.Scan(&count),
`SELECT count(*) FROM device_structs where "unique" = ? `, unique)
```

**Comment by dfmabbas** [comment]
@Alireza-Ta  I did not pay attention to this.
Thank you for helping me fix this problem

`count, errs :=  conn.Model(&device).Where(" \"unique\" = ?", unique).Count()`

This code works.
