### ISSUE TITLE
Insert and return?

### ISSUE THREAD

**Issue by ivoras** [go-pg/pg#911]
If I have a model defined which maps to an already existing table which has a serial PK and some fields with default values, is there a way to insert a record and fetch the resulting row which has the proper fields initialised with the defaults?

I.e. is there a way to accomplish this with models:

```
INSERT INTO mytable(field5, field8) VALUES ('abc', 123) RETURNING *;
```

**Comment by vmihailenco** [comment]
Try `q.Returning("*")`

**Comment by ivoras** [comment]
I'd like to do this with the ORM, since there are a lot of fields involved. Can you provide more detailed information? Here's what I tried:

```
o := DbObject{...something...}
o2 := DbObject{}
err := db.Insert(&o).Returning("*")
```

And I get an error message saying: `db.DB.Insert(&o).Returning undefined (type error has no field or method Returning)`
