### ISSUE TITLE
Schema naming

### ISSUE THREAD

**Issue by bonjefir** [go-pg/pg#915]
I need to put my tables in different schemas, so I used bellow example
```
type Applications struct {
    tableName struct{} `sql:"xxx.applications"`
}

```
but it seems `pg` automatically creates schema with package name**(or executable file name. in my case both of these have same name as created schema which is different with `xxx`).

Is there any idea about schema naming in `pg`? How can I force `pg` to use `xxx` as schema name?

** It create schema which is different with `xxx`, but it wants to create tables in `xxx` schema(i.e 1. it could not create tables since the schema `xxx` is not created, 2. if we look at postgres we found schema which its name is different with `xxx` and same as exec/package...).

**Comment by vmihailenco** [comment]
Please create a small program that reproduces the problem.

**Comment by bonjefir** [comment]
I do that and its result:
1. `pg` does not create db or schema automatically(I must do that manually).
2. In my original case I have no idea.

**Comment by vmihailenco** [comment]
go-pg does not create db or schema. I don't understand the 2nd point.

**Comment by bonjefir** [comment]
I see. It seems there is some issues with running postgres docker. it does not rebuild or something like this and `db`s are old and not clean!
Thanks
