### ISSUE TITLE
FTS and tsvector

### ISSUE THREAD

**Issue by dc0d** [go-pg/pg#917]
How to define a column of type `tsvector`?

I am following [this](https://www.opsdash.com/blog/postgres-full-text-search-golang.html) post to enable FTS for some tables.

**Comment by vmihailenco** [comment]
`type:tsvector` specifies column type, but I don't think that is what you want.

What I currently do is creating 2 models with and without tsvector:

```go
type Article struct {
    Id int
    Text string
}

type ArticleSearch struct {
    *Article `pg:",override"`
    Search types.ValueAppender // tsvector
}
```

Then when I need to select article I use `Article` and when I need to insert article I use `ArticleSearch`:

```go
m := &ArticleSearch{
	Article: article,
	Search:    pg.Q("to_tsvector('simple', ?)", article.Text),
}
db.Model(m).Insert()
```

Better solution might be following but it is not working at the moment:

```
db.Model(article).Value("search", "to_tsvector('simple', ?)", article.Text).Insert()
```

**Comment by dc0d** [comment]
Thanks! Looking forward to see this internalized. For now it seems proper to close this.

**Comment by ToferC** [comment]
I'm having similar issues trying to implement tsvector with go-pg. I was using the same article as a base.

I'm getting the following error on queries for the model after implementing `types.ValueAppender` as a struct value: "invalid character '\'' looking for beginning of value"

It seems to be related to issue #770 

I saw the suggestion above, but I'm not sure what type I should have for the tsvector in the regular model.

Any help would be greatly appreciated.

Code below.

Model is:
```
type CharacterModel struct {
	ID        int64
	Author    *User
	Random    bool
	Character *runequest.Character
	Open      bool
	Search    types.ValueAppender // tsValue
}
```

Save or update is basically the code below:

```
func SaveCharacterModel(db *pg.DB, cm *models.CharacterModel) error {

	cm.Character.UpdateCharacter()

	if cm.Slug == "" {
		cm.Slug = slug.Make(fmt.Sprintf("%s-%s", cm.Author.UserName, cm.Character.Name))
	}

	// Save character in Database
	_, err := db.Model(cm).
		OnConflict("(id) DO UPDATE").
		Set("character = ?character").
		Insert(cm)
	if err != nil {
		panic(err)
	}

	setTSVSearch := fmt.Sprintf(`
	UPDATE character_models SET search = 
	setweight(to_tsvector(coalesce(character ->> 'Name')), 'A') ||
	setweight(to_tsvector(coalesce(author ->> 'UserName')), 'B') ||
	setweight(to_tsvector(coalesce(character ->> 'Description')), 'C') ||

	setweight(to_tsvector(coalesce(character#> '{Homeland, Name}')), 'D') ||
	setweight(to_tsvector(coalesce(character#> '{Occupation, Name}')), 'D') ||
	setweight(to_tsvector(coalesce(character#> '{Cult, Name}')), 'D') ||

	WHERE
	id = %d;
	`, cm.ID)

	db.ExecOne(setTSVSearch)

	return err
}
```

Query is:

```
func PaginateCharacterModels(db *pg.DB, limit, offset int) ([]*models.CharacterModel, error) {

	var cms []*models.CharacterModel

	err := db.Model(&cms).
		Limit(limit).
		Offset(offset).
		Where("open = true").
		Order("created_at DESC").
		Select()

	if err != nil {
		log.Println(err)
	}

	return cms, nil
}
```
