### ISSUE TITLE
inverse of belongs to relation (has many) not working properly

### ISSUE THREAD

**Issue by mamal72** [go-pg/pg#926]
Hi. I've got 2 models in my application. Each `EmailAddress` is going to have many `EmailBounce`es.

In order to add a foreign key inside `EmailBounce` model, I had to explicitly define `EmailID` and `Email` in order to make it work. If I remove `EmailID` field, `Email` will be a `jsonb` type field. If I remove `Email` field, `EmailID` will be a normal `int` field. (Why?)

I'd like to define the inverse of this relationship in `EmailAddress` field so I could easily query related `EmailBounce`es by using `EmailAddress` model. The following code doesn't work for me and creates a `jsonb` field named `email_bounces` inside my `EmailAddress` model.

What's the problem? What should I do?

Here's my code:

```go

type EmailAddress struct {
	ID                 int64
	Address            string
	UnsubscribedTopics []string
	EmailBounces       []*EmailBounce // has many
	CreatedAt          time.Time      `sql:"default:now()"`
	UpdatedAt          time.Time
}

type EmailBounce struct {
	ID        int64
	EmailID   int64
	Email     *EmailAddress // belongs to
	CreatedAt time.Time     `sql:"default:now()"`
}

//
//

models := []interface{}{
	(*models.EmailAddress)(nil),
	(*models.EmailBounce)(nil),
}

for _, model := range models {
	err := db.CreateTable(model, &orm.CreateTableOptions{
		IfNotExists:   true,
		FKConstraints: true,
	})
	if err != nil {
		return err
	}
}


```

**Comment by mamal72** [comment]
OK. One of my friends helped me and it's fixed by changing struct field name of foreign key inside `EmailBounce` model. Here is the new model:

```go
type EmailBounce struct {
	ID        int64
	EmailAddressID   int64
	EmailAddress     *EmailAddress // belongs to
	CreatedAt time.Time     `sql:"default:now()"`
}
```

I've got another question. Is it really necessary to define `EmailAddressID` field here? I mean, isn't it better to generate `email_address_id` automatically when I've defined a foreign key to `EmailAddress` model?

**Comment by vmihailenco** [comment]
`EmailAddress` can be a foreign key relation or a plain struct mapped to a jsonb column.

**Comment by kopaygorodsky** [comment]
@vmihailenco isn't it better to add some tag that will mark relation instead of guessing? Adding two fields for this purpose doesn't look efficient.

**Comment by eddiewang** [comment]
@vmihailenco is there any way to explicitly define the relation mapping? With many2many you have the joinFK tag.
