### ISSUE TITLE
BulkUpdateSlice doesn't work

### ISSUE THREAD

**Issue by ali-arabshahi** [go-pg/pg#928]
hello
based on document and example i wrote this code

``` go
type SMS struct {
	ID          int64 `json:"-"`
	Code        int
	PhoneNumber string
	RequestDate time.Time
	ExpiryDate  time.Time
}

smsList := []SMS{}
err := db.Model(&smsList).Select()
	if err != nil {
		fmt.Println(err)
	}
for _, sms := range smsList {
	sms.ExpiryDate = time.Now()
	}
result, err := db.Model(&smsList).Column("expiry_date").Update()
	if err != nil {
		fmt.Println(err)
	}
fmt.Println(result.RowsAffected())


```

The `result.RowsAffected()` returns correct number of affected rows but when I check the database nothing changed.
sorry for my english and thank you in advanced

**Comment by vmihailenco** [comment]
See https://github.com/go-pg/pg/wiki/FAQ#how-can-i-viewlog-queries-this-library-generates how you can view generated queries. After you have actual queries it should be obvious what is wrong.

**Comment by ali-arabshahi** [comment]
thank's a lot.that was my mistake
