### ISSUE TITLE
ForEach doesn't accept interface?

### ISSUE THREAD

**Issue by mwei0210** [go-pg/pg#929]
Hi, 

i saw that it only accept struct but not interface here:
https://github.com/go-pg/pg/blob/27967a42754506e1378a1259c7f73475c571e465/orm/model_func.go#L65
is it on purpose to only accept struct?

**Comment by vmihailenco** [comment]
It is intentional, because I don't understand why you need interface{} there.

**Comment by mwei0210** [comment]
there would be cases where different structs are needed to be retrieved dynamically. if there are 10 of such cases, same logic will have to be duplicated 10 times with only the difference of struct name..

consider this:
```
type animal interface {
	run() error
}

type dog struct {
	id int64
}

type cat struct {
	id int64
}

sr.db.Model(animalInterface).ForEach(func(animalInterface animal) error {
		animalInterface.run()
})
```
**else:**
```
sr.db.Model((*dog)(nil)).ForEach(func(d *dog) error {
		d.run()
})

sr.db.Model((*cat)(nil)).ForEach(func(c *cat) error {
		c.run()
})
```

**Comment by vmihailenco** [comment]
Yeah, that is not supported.
