### ISSUE TITLE
Foreign key to a table in different schema

### ISSUE THREAD

**Issue by bonjefir** [go-pg/pg#930]
I need to create `fk` from a table to another table which is in different schema,

 but it seems `pg` does not do that.
A simple example attached [fk.txt](https://github.com/go-pg/pg/files/2228388/fk.txt).

Thanks

**Comment by vmihailenco** [comment]
go-pg does not create schemas if you mean that. Other than that your example seem to work as expected. Is there anything else?

**Comment by bonjefir** [comment]
There was an typo in `AccountID` definition(it was created as `bool` instead of `uint`).
