### ISSUE TITLE
Bool sent as null on update despite "notnull"

### ISSUE THREAD

**Issue by matthew-noken** [go-pg/pg#940]
Hi,

I don't have time to debug this issue as I found a workaround, but I thought I would file a ticket just so it's out there. I'm using version 6.14.3.

Given the following code (untested—my apologies), the `test_boolean` value is sent as `NULL` in the update statement:

```
type Example struct {
    ID int64
    TestBoolean bool `sql:",default:false,notnull"`
}

example := Example{
    TestBoolean: true,
}
if err := db.Insert(&example); err != nil {
    panic(err.Error())
}

example.TestBoolean = false

if err := db.Update(&example); err != nil {
    panic(err.Error()) // Constraint violation from NOT NULL
}
```

However, the following works as expected and sends the value as `false`:

```
type Example struct {
    ID int64
    TestBoolean bool `sql:",default:false,notnull"`
}

example := Example{
    TestBoolean: true,
}
if err := db.Insert(&example); err != nil {
    panic(err.Error())
}

var example2 Example
_, err := db.
    Model(&example2).
    Set("test_boolean = ?", false).
    Where("id = ?", 1).
    Update()
if err != nil {
    panic(err.Error())
}
```

Hopefully this is helpful. I prefer the former style, but whenever I have a not null boolean field I have to use the latter approach.

Thanks for making a great ORM!

**Comment by matthew-noken** [comment]
Thanks for fixing so quickly!

**Comment by rakils** [comment]
Is the fix available in 8.0.6? I tried updating the package to 8.0.6 and issue is still there.

**Comment by MrBadge** [comment]
Having exact same issue in the latest master now. Seems to be broken by recent changes, worked as expected before

**Comment by vmihailenco** [comment]
Check changelong - you shoul use `pg:",use_zero"` now.
