### ISSUE TITLE
Unable to add addition JoinOn conditions to Relations

### ISSUE THREAD

**Issue by Kay-Zee** [go-pg/pg#943]
Currently trying to add a preset condition for a `LEFT JOIN` using the ORM. Something similar to the following:

```go
db.Model(parent).
	Relation("HasOne", func(q *orm.Query) (*orm.Query, error) {
		return q.JoinOn("has_one.state = 'o'"), nil
	})
```
I'm using the Relation function so that the `HasOne` will be populated, since otherwise I could just use 

```go
db.Model(parent).
	Join("LEFT JOIN  has_one").
	JoinOn("parent.id = has_one.parent_id").
	JoinOn("has_one.state = 'o'")
```

I'd like it to result in something like

```sql
SELECT "parent"."id", "has_one"."parent_id" AS "has_one__parent_id", "has_one"."state" AS "has_one__state"
FROM "parent"
LEFT JOIN "has_one" ON "parent"."id" = "has_one"."parent_id" AND "has_one"."state" = 'o'
```

but currently on the latest release, the `JoinOn` is completely ignored and on the latest master, i get a `runtime error: index out of range`

Is the `Relation` function meant to only affect the columns that are returned? or should they also be able to handle things like the `JoinOn`?

**Comment by vmihailenco** [comment]
For now you can replace `q.JoinOn("has_one.state = 'o'")` with `q.Where("has_one.state = 'o'")`. I will see what can be done to make your example work.

**Comment by Kay-Zee** [comment]
I believe that will simply filter out all rows that do not have `state = 'o'` after the join has already happened, where I want to only join items from the `has_one` table if `state = 'o'`. Key point here is that I'm doing a `LEFT JOIN`. The where gives the desired result if it was an inner join, but I believe for a `LEFT JOIN` it gives a different than desired result.
