### ISSUE TITLE
In case no results are found

### ISSUE THREAD

**Issue by rogierlommers** [go-pg/pg#949]
I have the following code. When my memory serves well, this used to work. But now, for some reason, when the resultset is nil, I don't get a pg.ErrNowRows throwed. Is this changed or something? How do I determine if the query returned no rows? Simply by doing a `len(group)`?

	search := db.Model(&group).
		Where("reference = ?", reference).
		Where("object_type = ?", objectType)

	if err := search.Select(); err != nil {
		if err == pg.ErrNoRows {
			writeEmptyResponse(w)
			statResponseCodes(http.StatusNotFound)
			return
		}

**Comment by vmihailenco** [comment]
`pg.ErrNoRows` is returned only when `group` is a struct, not slice. If it is a slice you should use `len(groups)`.
