### ISSUE TITLE
How to exclude column in Update?

### ISSUE THREAD

**Issue by fi0** [go-pg/pg#950]
is there a method to exclude a single column when doing an Update, like ExcludeColumn in select

**Comment by fi0** [comment]
It seems that ExcludeColumn can be used with Update as well, is this correct?

**Comment by vmihailenco** [comment]
If you want to exclude the column that is a part of composite primary key you can use `Where` instead of `WherePK` and specify columns you need.

ExcludeColumn should work with Update - let me know it it does not.
