### ISSUE TITLE
Cannot fetch one to many

### ISSUE THREAD

**Issue by JonEustace** [go-pg/pg#954]
I have the following structs, an appointment can have several participants: 

```
type AppointmentsParticipants struct {
	AppointmentsID int `sql:",pk"`
	UserID int `sql:",pk"`
	Approved bool
	ReviewedAt time.Time
	ReviewedBy int
	Comment string
	Cancelled bool
}

type Appointments struct {
	ID int `sql:",pk"`
	Pending bool
	StartTime time.Time
	EndTime time.Time
	auditData
	InitialAppointmentID int
	SessionID string
	Type string
	AppointmentParticipants []*AppointmentsParticipants `json:"participants"`
}
```
I would like to run the following query: `SELECT * FROM "appointments" AS "appointments" JOIN appointments_participants ON appointments.id = appointments_participants.appointments_id WHERE (appointments_participants.user_id = 259);`

This snippet does just that, but it does not populate the AppointmentParticipants slice. 

```
err = database.DB().
		Model(&app).
		Column("*").
		Where("appointments_participants.user_id = ?", id).
		Join("JOIN appointments_participants ON appointments.id = appointments_participants.appointments_id").
		Select()
```

**Comment by vmihailenco** [comment]
Please create an example that can be run and that reproduces the problem.
