### ISSUE TITLE
How to make many to many without empty column in table schema?

### ISSUE THREAD

**Issue by kimihailv** [go-pg/pg#956]
When we define many to many relation, we should add an extra field to struct (example from docs):

```
type Order struct {
    Id    int
    Items []Item `pg:"many2many:order_to_items"`
}

type Item struct {
    Id int
}
```

Because of it, we should add an empy column "items" to schema to insert new instance of Order in db. But this column is useless. It will be NULL. So, how to make many to many without empy column?

**Comment by vmihailenco** [comment]
That is the column where you load the "many" part of a relation. When relation is detected properly it is automatically excluded from the SQL columns list and does not receive any values (including NULLs). I guess in your case relation was not detected properly.
