### ISSUE TITLE
scram-256 not supported: pg: unknown authentication message response: 10 - 

### ISSUE THREAD

**Issue by niski84** [go-pg/pg#960]
Postgres 10 [introduced scram-256 authentication](https://www.postgresql.org/docs/10/static/sasl-authentication.html#SASL-SCRAM-SHA-256)

steps to reproduce.:
1.  open postgresql.conf and change the setting as follows:
password_encryption = scram-sha-256		# md5 or scram-sha-256

2.  ALTER USER user_name WITH PASSWORD 'new_password';

3. ensure rolepassword is using SCRAM: 
SELECT * FROM pg_authid;

4. 
	```
db := pg.Connect(&pg.Options{
		User:     "user_name",
		Password: "a",
		Database: "<db here>",
		Addr: "localhost:5433",
	})

		
	var n int
	_, err := db.QueryOne(pg.Scan(&n), `SELECT 1`)
```

**Comment by vmihailenco** [comment]
Could you try master branch?

**Comment by niski84** [comment]
@vmihailenco I was previously using pq golang driver with sql select statements as strings.  Is there a way I can do the same without constructing a model/struct with the pg driver?
