### ISSUE TITLE
|Question] How to avoid go-pg  to use my relations fields as column in Insert

### ISSUE THREAD

**Issue by JulienTant** [go-pg/pg#962]
Hi,

I have the following entity :

```go
type Meal struct {
	ID uuid.UUID `sql:",pk,type:uuid default uuid_generate_v4()"`

	RecipeID uuid.UUID
	Recipe   *Recipe

	MealTypeID uuid.UUID
	MealType   *MealType `pg:"fk:meal_type_id"`

	Date time.Time

	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
```

And I try to do the following insert : 

```go
meal := models.Meal{
	RecipeID:   recipe.ID,
	MealTypeID: mealType.ID,
	Date:       when,
}
_, err := tx.Model(&meal).Insert()
```
I found in my query that go-pg tries to insert values into the columns `recipe` and `meal_type`. What do i do wrong here ? Sorry i couldn't find anything by looking at the doc or the examples

**Comment by vmihailenco** [comment]
That means that go-pg was not able to recognize relation. I guess you don't `Recipe.ID uuid.UUID` field. That is all I can say without a small program that reproduces the problem.
