### ISSUE TITLE
orm problem in conversion of time.Now() into timestamptz

### ISSUE THREAD

**Issue by Alireza-Ta** [go-pg/pg#963]
When I'm using time.Now() for time.Time fields orm round up the second time precision then insert it into database.
I've a model hook like this: 
```golang
func (q *Question) BeforeInsert(db orm.DB) error {
	q.UpdatedAt= time.Now()
	return nil
}
```
For example the time that time.Now() will return would be: 
```
"updated_at":"2018-08-24T21:57:23.0259197+04:30"
```
After inserting the fetched result is: 
```
updated_at":"2018-08-24T21:57:23.02592+04:30"
```
Notice the precision rounded up!

My actual problem isn't that time is rounding up but when I'm writing tests the difference between timestamps in responses is annoying hence must delete them from response then compare.
Thanks!

**Comment by vmihailenco** [comment]
It is rounded up by PostgreSQL not go-pg:

```
postgres=# select '2018-08-24T21:57:23.0259197+04:30'::timestamptz;
         timestamptz          
------------------------------
 2018-08-24 17:27:23.02592+00
```

And I have no ideas what go-pg could do to help with that.

**Comment by Alireza-Ta** [comment]
I've handled it with unix time representation:

```golang
func (q *Question) BeforeInsert(db orm.DB) error {
	q.UpdatedAt= time.Unix(time.Now().Unix(), 0)
	return nil
}
```
Thanks anyway!
