### ISSUE TITLE
How to dynamically construct queries.

### ISSUE THREAD

**Issue by latipovsharif** [go-pg/pg#965]
For example I'm getting parameters from http query and the are varying for filtering purposes, so I need to construct query dynamically. Is it possible to do this kind of stuff?

**Comment by frederikhors** [comment]
@latipovsharif why did you close it?

**Comment by latipovsharif** [comment]
@frederikhors because I found this snippet

```
	whereGroup := func(q *orm.Query) (*orm.Query, error) {
		if val, ok := c.Request.Form["q"]; ok {
			return q.WhereOr("u.first_name ilike ?0 or u.last_name ilike ?0", "%"+val[0]+"%"), nil
		}
		return q, nil
	}
```

so you can use it to construct your queries

**Comment by latipovsharif** [comment]
@frederikhors because I found this snippet

```
	whereGroup := func(q *orm.Query) (*orm.Query, error) {
		if val, ok := c.Request.Form["q"]; ok {
			return q.WhereOr("u.first_name ilike ?0 or u.last_name ilike ?0", "%"+val[0]+"%"), nil
		}
		return q, nil
	}
```

so you can use it to construct your queries
