### ISSUE TITLE
How to use Jsonb operators via go-pg

### ISSUE THREAD

**Issue by bonjefir** [go-pg/pg#966]
Hi all

Is it possible to use [JSONB operators](https://www.postgresql.org/docs/9.4/static/functions-json.html) via go-pg? I could not find any documentation about this.

As an example queries like these:
```
SELECT parameters->'param' FROM device.parameters;
```
```
SELECT parameters FROM device WHERE parameters @> '[{"param":"voltage"}]';
```
On data structures as follows:
```
type Parameters struct {
    Param string
    ...
}
type Device struct {
    TableName   struct{} `sql:"device"`
    Name string
    ...
    Parameters Parameters
}
```
**PS:**
Suppose due to problem requirements we must store `Parameters` as a `jsonb` column of table `Device`(so `Device` structure maps to a table in db and `Parameters` became one of its columns in jsonb format) and queries are as described above.

**Comment by vmihailenco** [comment]
You can pass anything to `SelectExpr` and `Where` including jsonb operators.

**Comment by bonjefir** [comment]
@vmihailenco  Thanks.
I could not find any example for `SelectExpr` in repository(Also no such method in whole `pg` project). Could you please explain more.

**Comment by vmihailenco** [comment]
`SelectExpr` -> `ColumnExpr`, for example, `ColumnExpr("parameters->'param'")`
