### ISSUE TITLE
Accessing PG error codes directly

### ISSUE THREAD

**Issue by khash** [go-pg/pg#968]
I'm trying to get the five letter PG error codes from the error returned by a DB operation.

I can see that in the code `internal.PGError` is defined to deal with the PG error wire protocol and concatenates the code, condition name and some other fields into a string in `Error()`. Obviously with `PGError` being defined as `internal` we cannot convert a normal returned `error` to it to fetch `Field('C')` so I was hoping if you have any suggestions to get around this. 

I tried implementing the `pg.Error` interface on a new class but since the entire library uses `internal.PGError` the resulting error cannot be converted to my new class (see below):

```Go
	a1 := &models.Account{Name: "aa"}
	a2 := &models.Account{Name: "aa"}
	err := db.Insert(a1)
	err = db.Insert(a2) // this will violate an FK but that's just an example
	pgErr := err.(utils.PGError) // <--- below error
```

`interface conversion: error is internal.PGError, not utils.PGError`

At this point I would like to have the code and condition name separately instead of it being in the string formatted way the library prefers which would be something like this:

```
ERROR #23505 duplicate key value violates unique constraint \"accounts_name_key\" (addr=\"[::1]:5432\")
```

**Comment by vmihailenco** [comment]
I think you are looking for `pgErr, ok := err.(pg.Error)` - https://godoc.org/github.com/go-pg/pg#Error

**Comment by khash** [comment]
Excellent! Thank you!

One note for others who find their way here: 

Apart from `ErrNoRows` and `ErrMultiRows` other `error` can be cast into `pg.Error` as @vmihailenco  mentioned.
