### ISSUE TITLE
No quote for table name?

### ISSUE THREAD

**Issue by wiiiky** [go-pg/pg#972]
I have a table named order. And I found pg generates SQL like
`
INSERT INTO order ("id", "price", "user_id", "status", "utime", "ctime") VALUES (DEFAULT, 800, '0da2335e-b1e1-11e8-a383-8b0b98aa2d89', DEFAULT, DEFAULT, DEFAULT) RETURNING "id", "status", "utime", "ctime"
`

Why not quote the table name?

**Comment by vmihailenco** [comment]
If that custom table name then it is up for you to quote the name. Also the long-term plan for go-pg is only quote names when needed.
