### ISSUE TITLE
Cant' set bool field to false on insertion if it's defined with "not null" and "default:true" 

### ISSUE THREAD

**Issue by zengxinzhy** [go-pg/pg#973]
When a boolean filed is defined with "not null" and "default:true", the insertion result may be incorrect.
```
type Image struct {
    Id    int
    Valid bool `sql:",notnull,default:true"`
}
db = pg.Connect()
db.CreateTable((*Image)(nil), &orm.CreateTableOptions{
    IfNotExists: true,
})
image := new(Image)
image.Valid = false
db.Model(image).Insert()
fmt.Println(image)
// will print &{1 true}, the data added to DB is also "true"
```

**Comment by vmihailenco** [comment]
This is already fixed in master branch - you need to update go-pg.

**Comment by vmihailenco** [comment]
I don't see what is so special about UPDATE vs INSERT.

For now I am inclined to say that `default:` option should be rejected on `bool` field and you should be using `sql.NullBool` instead.

**Comment by vmihailenco** [comment]
I don't see what can be done here.

**Comment by clwilliams** [comment]
I've got this issue now. Upon creating a new entity, any boolean values are set to the default value of that field, it ignores whatever I pass in. Updates work fine, it's only on creation that this is a problem. I've fixed the issue by removing the default value from the boolean fields I have - which isn't ideal but works.
