### ISSUE TITLE
Array slice in 'IN'?

### ISSUE THREAD

**Issue by betrok** [go-pg/pg#979]
I want to construct something like
`SELECT '{1, 2}'::int[] IN ('{1,2}','{3,4}')`
But
``` go
	src := [][]int{
		{1, 2},
		{3, 4},
	}

	var pgArr []*types.Array
	for i := range src {
		pgArr = append(pgArr, pg.Array(src[i]))
	}

	var ret bool
	_, err := db.QueryOne(&ret, "SELECT '{1, 2}'::int[] IN (?)", pg.In(pgArr))
	fmt.Println(ret, err)
```
results in
`SELECT '{1, 2}'::int[] IN ('{}','{}')`
Seems like *types.Array is interpreted as a common structure.

Whole solution does not look too good as well. Is there any better way?

**Comment by vmihailenco** [comment]
You are probably looking for https://godoc.org/github.com/go-pg/pg#InMulti

**Comment by betrok** [comment]
If i understood correctly, no.
I'm working with array fields.

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed in master
