### ISSUE TITLE
Soft delete does not work with many2many

### ISSUE THREAD

**Issue by matthew-noken** [go-pg/pg#981]
Hi Vladimir,

With regard to #952, the soft delete functionality has been working great (thanks for that!!), with one exception: selecting against many2many relationships.

Assume the following types:

```
type HotDog struct {
    ID int64
    DeletedAt time.Time `sql:",type:'timestamp without time zone'" pg:",soft_delete"`
    Condiments []*Condiment `pg:"many2many:hot_dog_condiments"`
    tableName struct{} `sql:"hot_dogs"`
}

type Condiment struct {
    ID int64
    DeletedAt time.Time `sql:",type:'timestamp without time zone'" pg:",soft_delete"`
    Name string `sql:",notnull"`
    tableName struct{} `sql:"condiments"`
}
```

If you use the following query, you will get back all Condiment members, deleted and non-deleted alike.

```
var hotDog HotDog
err := db.Model(&hotDog).Column("hot_dog.*", "Condiments").First()
if err != nil {
    return err
}
for _, c := range hotDog.Condiments {
    fmt.Printf("%+v\n", c)
}
```

The workaround is setting up relationships to the intermediate models instead (e.g., `HotDogCondiment`), but that's ehh, not great. Thoughts?

Thanks again for your great support of this library!

**Comment by vmihailenco** [comment]
Hi,

I can't reproduce this - generated query looks good to me

```sql
SELECT hot_dog_condiments.*, "condiment"."id", "condiment"."deleted_at", "condiment"."name" FROM condiments AS "condiment" JOIN hot_dog_condiments AS hot_dog_condiments ON (hot_dog_condiments."hot_dog_id") IN (1) WHERE ("condiment"."id" = hot_dog_condiments."condiment_id") AND "condiment".deleted_at IS NULL
```

Feel free to re-open this with a program that reproduces the problem.
