### ISSUE TITLE
Error reading database: EOF

### ISSUE THREAD

**Issue by badoet** [go-pg/pg#982]
Any idea what will cause this error?

it just suddenly happen on our Go applications
and when this happen, all the docker pods will similarly have the error printed when it try to fetch data from Postgres DB

`Error reading orders database: EOF`

**Comment by badoet** [comment]
sorry false alarm

**Comment by ardenn** [comment]
@badoet Did you figure out what caused this? I had the same issue recently. Reading/Writing from the DB returns an error `EOF`.
