### ISSUE TITLE
Insert many strings

### ISSUE THREAD

**Issue by kosta** [go-pg/pg#983]
Suppose I have this table:

```sql
CREATE TABLE "test" ("id" text NOT NULL primary key);
```

I want to insert a string slice with ids:

```go
var values []string
//...
db.Exec(`INSERT INTO test VALUES ?`, values)
```
This doesn't work as the values are not properly formatted for SQL. Neither do `pg.In()` or `pg.InMulti()`. I'm not aware how to make this work, except wrapping each string into a struct or another slice. (Please tell me if there's an existing way, I'll send a PR to document it).

Could we 
either a) In types/append.go: Add a case for []string to the type switch?
or b) Add a pg.MultiString() wrapper that returns a `ValueAppender` that does this?

Example code, please review (this is for option b), but I think option a) is better - but it's your decision)

Also, the name PgMultiString is very bad, I'll try to come up with something better if we want to go with option b)

```go
type PgMultiString struct {
	Values []string
}

// Make sure PgMultiString is a go-pg ValueAppender
var _ types.ValueAppender = PgMultiString{}

func (ms PgMultiString) AppendValue(b []byte, quote int) []byte {
	for i, s := range ms.Values {
		if i != 0 {
			b = append(b, ',', ' ')
		}
		b = append(b, '(')
		b = types.AppendString(b, s, quote)
		b = append(b, ')')
	}
	return b
}
```

Let me know what you think and I'll send a PR!

**Comment by kosta** [comment]
Note that the table could have other columns with auto-increment or default values. Here, I used it as a "dirty" table for other workers to process.

On the other hand, if you do this, you'd need to do the same for _all_ types that you support (for consistency) and I see how that is not a good idea :)

**Comment by vmihailenco** [comment]
Okay, closing until we have more data.

**Comment by kosta** [comment]
I found that I use this all the time in queries like this:

    ids := []string{"a", "b", "c"}
    db.Query(&rows, `SELECT * FROM sometable WHERE id = ANY(VALUES ?)`, PgMultiString{ids})

Maybe that a better use case that's currently not covered by go-pg?

**Comment by kosta** [comment]
Hm, I see your point.

I try to avoid `WHERE id IN ...` as it is much slower than `WHERE id = ANY(VALUES...`, however, here the passed argument should be small enough so that it does not matter.

If I find another good use case I'll let you know :)
