### ISSUE TITLE
Google AppEngine support broken with scram-256 change

### ISSUE THREAD

**Issue by rossmcdonald** [go-pg/pg#984]
With support for the scram-256 authentication mode in https://github.com/go-pg/pg/pull/969, clients running within Google AppEngine can no longer build properly due to the sasl libraries use of the `unsafe` package (which is disallowed in GAE). A workaround is to pin pg to a version prior to the scram support, but I just wanted to bring it up in case there was any way another sasl library could be used or the `unsafe` use could be removed from that one. Also note that this applies regardless of whether the client is actually using scram-256 or not.

Also I just wanted to say what a pleasure this project is to use, so keep up the amazing work.

**Comment by vmihailenco** [comment]
Please try update go-pg again - I think I've fixed this with https://github.com/vmihailenco/sasl/commit/2f13c189728a02f8cc31b3b9cc06047b383c21cc

**Comment by vmihailenco** [comment]
Please re-open if this is still a problem.
