### ISSUE TITLE
Panics when querying and unmarshaling to a slice of structs that has an embedded struct with the same name

### ISSUE THREAD

**Issue by sanggonlee** [go-pg/pg#985]
Here is an example of what I mean by `struct that has an embedded struct with the same name`:
```
import uuid "github.com/satori/go.uuid"

type UUID struct {
	UUID uuid.UUID
}
```

FYI, when it's simply a struct, there doesn't seem to be a problem:
```
var id UUID
```

But when unmarshaling to a slice of structs:
```
var ids []UUID

var db pg.DB
/* ...assume db is configured... */
if err := db.Query(&ids, `
    SELECT
        json_agg(dogs.id) AS dog_ids
    FROM dogs
    GROUP BY dogs.id
`)
```

It panics `panic: reflect: NumField of non-struct type`.

**Comment by vmihailenco** [comment]
Following works for me:

```
type UUID struct {
	UUID uuid.UUID
}

var ids []UUID
_, err := db.Query(&ids, "SELECT '123e4567-e89b-12d3-a456-426655440000' AS uuid")
if err != nil {
	panic(err)
}
log.Println(ids)
```

Make sure you are using latest go-pg version and re-open with program to reproduce this issue if it is still a problem.
