### ISSUE TITLE
Handle UNIQUE error

### ISSUE THREAD

**Issue by olegsobchuk** [go-pg/pg#990]
Is it possible to handle UNIQUE error?

for example model:
```

type User struct {
	ID                   int    `form:"id"`
	Email                string `sql:",unique:idx_users_on_email" form:"email" binding:"required,email"`
}
```

when I try to save `user` with same `email` I have error:

`ERROR #23505 duplicate key value violates unique constraint "idx_users_on_email"`

But is there any way to handle this error for specific field except parse string with error?

**Comment by vmihailenco** [comment]
Yes, see following example https://godoc.org/github.com/go-pg/pg#example-Error

**Comment by olegsobchuk** [comment]
@vmihailenco it's ok if Instance has one unique field, but if it has several fields?
`IntegrityViolation()`  return `true`/`false` it is less information than in error string message.

Is it possible fetch field name which is not valid (not uniq)? Or there is only needed parse error string message?

**Comment by vmihailenco** [comment]
Check Error.Field - https://godoc.org/github.com/go-pg/pg#Error. That is all information available from Postgres.

**Comment by olegsobchuk** [comment]
@vmihailenco thanks, I missed this information, my fault
