### ISSUE TITLE
How to write to the table without knowing the name of the table?

### ISSUE THREAD

**Issue by themrxcm** [go-pg/pg#992]
How do I write data into a table, the name of which I do not know in advance? The table is created on the server node js, after I transfer the name of the table to the server GO and there it is necessary to write the data into the already created table. How to do it? Why can not you simply transfer the name of the table and the necessary data for the record to here http://docs.sequelizejs.com/manual/tutorial/instances.html#working-in-bulk-creating-updating-and-destroying-multiple-rows-at-once-

**Comment by vmihailenco** [comment]
Did you try https://godoc.org/github.com/go-pg/pg/orm#Query.Table?

**Comment by themrxcm** [comment]
I tried this structure `db.Model().Table(tableName).Insert(layers)` and nothing happens, there is no error either.

**Comment by vmihailenco** [comment]
You will need to update go-pg and try https://godoc.org/github.com/go-pg/pg#example-DB-Insert-DynamicTableName

`DB.Exec` might work too, but you will have to manually construct batch insert query (if you want to use batch inserts).
