### ISSUE TITLE
Support SELECT DISTINCT clause

### ISSUE THREAD

**Issue by zenghur** [go-pg/pg#998]
I know ColumnExpr can achieve it. But I want a more elegant way .
Before,
`db.Model(...).ColumnExpr("DISTINCT foo, bar").Select()`
After,
`db.Model(...).Distinct("foo, bar").Select()` and
`db.Model(...).DistinctOn("foo, bar").Select()`

**Comment by vmihailenco** [comment]
What is the difference? `Distinct("foo, bar")` could call `ColumnExpr("DISTINCT foo, bar")` but I'd rather not expand API without a good reason.

**Comment by zenghur** [comment]
> without

when you do multiple distinct columns, it seems that ColumnExpr("DISTINCT ON(a, b, c) a") is not that  reasonable cuz I want to select all columns at the same time. In this situation, I want to use db.Model(...).DistinctOn("a, b, c").Select() to select all columns.

**Comment by zenghur** [comment]
> What is the difference? `Distinct("foo, bar")` could call `ColumnExpr("DISTINCT foo, bar")` but I'd rather not expand API without a good reason.

when you do multiple distinct columns, it seems that ColumnExpr("DISTINCT ON(a, b, c) a") is not that reasonable cuz I want to select all columns at the same time. In this situation, I want to use db.Model(...).DistinctOn("a, b, c").Select() to select all columns.

**Comment by vmihailenco** [comment]
Please explain how resulting query should look like - go-pg is responsible only for constructing the query and unmarshaling the result into Go structs.

**Comment by zenghur** [comment]
> Please explain how resulting query should look like - go-pg is responsible only for constructing the query and unmarshaling the result into Go structs.

Suppose table t have three columns a, b, c. if we do `db.Model(...).ColumnExpr("DISTINCT ON(a), a").Select()`, this would result in `select distinct on(a) a from t`, but I want to generate `select distinct on(a) a, b, c from t` by using `db.Model(...).DistinctOn("a").Select()`

**Comment by zenghur** [comment]
any updates?

**Comment by vmihailenco** [comment]
What you are asking for makes sense but I am hesitant to further grow [Query](https://github.com/go-pg/pg/blob/master/orm/query.go#L30-L55) without evidence this is widely useful. I will try to decide something this week.

**Comment by ahmadster** [comment]
I'd like to voice support for implementing this.

**Comment by Fyb3roptik** [comment]
I would +1 this as well!

**Comment by wavded** [comment]
I would like this as well, the current suggestion is awkward, in order for it to work I had to to make it the first ColumnExpr after `db.Model` and I needed to use a throwaway column to avoid it putting the comma in the wrong spot (causing a syntax error):

```
db.Model(...).ColumnExpr(`DISTINCT ON ("a", "b", "c") id`)
```

Would be nice to have a `DistinctOn` or similar to enable us to programmatically add that requirement when needed.

**Comment by vmihailenco** [comment]
Master branch should support for `db.Model().Distinct()` and `db.Model().DistinctOn("foo", "bar")`. Thanks for waiting :)

**Comment by MohitKS5** [comment]
This isn't on releases yet ?

**Comment by vmihailenco** [comment]
Should be in v9.

**Comment by MohitKS5** [comment]
@vmihailenco but for every version above 8 I get an error. Since dep works till v8 I don't know if its dep's issue or go-pg's. Any ideas? Atleast whats the difference between v9 and others?

` v9.0.0-beta: github.com/go-pg/pg imports github.com/go-pg/pg/v9/internal, which contains malformed code: unknown error for github.com/go-pg/pg/v9/internal, if you get this error see https://github.com/golang/dep/issues/351`
